### ISSUE TITLE
Switching Activities

### ISSUE THREAD

**Issue by deon-wentzel** [nicoduj/homebridge-harmony#10]
Hi, Thanks for the plugin.
I have a small issue, when switching from one activity to the another activity i.e TV to Movies, in the Home APP, the previous Activity remains ON, while the selected Activity is ON too..

Any advice?

**Comment by nicoduj** [comment]
Hi, If you close the home app and open it again is it ok then ?

**Comment by deon-wentzel** [comment]
Thanks that works...
