### ISSUE TITLE
How to Fast Forward and Rewind on the iOS remote

### ISSUE THREAD

**Issue by gitgayhub** [nicoduj/homebridge-harmony#100]
On the Harmony iOS App, I can press and hold the right/left arrow to fast forward or rewind, but on the iOS 12.2 remote, when I press and hold the array, nothing happens, the phone doesn't vibrate, no command sent to homebridge either. Don't know if Apple doesn't support this function yet or just that I didn't set it correctly

This is my keysmap:

{
	"2": "{\"command\":\"SkipForward\",\"type\":\"IRCommand\",\"deviceId\":\"42949922\"}",
	"3": "{\"command\":\"SkipBack\",\"type\":\"IRCommand\",\"deviceId\":\"42949922\"}",
	"4": "{\"command\":\"DirectionUp\",\"type\":\"IRCommand\",\"deviceId\":\"42949922\"}",
	"5": "{\"command\":\"DirectionDown\",\"type\":\"IRCommand\",\"deviceId\":\"42949922\"}",
	"6": "{\"command\":\"DirectionLeft\",\"type\":\"IRCommand\",\"deviceId\":\"42949922\"}",
	"7": "{\"command\":\"DirectionRight\",\"type\":\"IRCommand\",\"deviceId\":\"42949922\"}",
	"8": "{\"command\":\"Ok\",\"type\":\"IRCommand\",\"deviceId\":\"42949922\"}",
	"9": "{\"command\":\"Exit\",\"type\":\"IRCommand\",\"deviceId\":\"42949922\"}",
	"10": "{\"command\":\"Exit\",\"type\":\"IRCommand\",\"deviceId\":\"42949922\"}",
	"11": "{\"command\":\"Play\",\"type\":\"IRCommand\",\"deviceId\":\"42949922\"}",
	"15": "{\"command\":\"Menu\",\"type\":\"IRCommand\",\"deviceId\":\"42949922\"}"
}

**Comment by nicoduj** [comment]
#100 issue congratulations 🎖 . Concerning this I have no clue on how it can be sent, I did not found how but might be released in a future update . Remote for HomeKit device has less options than the one of Apple TV , but clearly they have exposed more commands than buttons for now through HomeKit (same for exit  command, and mute for example)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nicoduj** [comment]
Can't do anything on this as far as I know
