### ISSUE TITLE
[FEATURE] add “Menu” button to iOS remote widget

### ISSUE THREAD

**Issue by leoneleone** [nicoduj/homebridge-harmony#102]
Apparently other plugins have been able to add a button to the iOS Remote widget labelled “Menu” by adding the characteristic Characteristic.PowerModeSelection

This is an example from homebridge-webos-tv:
`    this.tvService
        .getCharacteristic(Characteristic.PowerModeSelection)
        .on('set', (newValue, callback) => {
            this.log.debug('webOS - requested tv settings (PowerModeSelection): ' + newValue);
            this.setRemoteControlButtonState(true, callback, 'MENU');
        });`

Can you please add this to your harmony plugin? Hopefully that iOS remote widget “Menu” button can be mapped to the MENU button on the Harmony Remote/Hub

**Comment by nicoduj** [comment]
Hi,

I made this available in 0.5.2. However it is not available in the remote widget, but in the properties of the TV accessory.

![IMG_EAA084711996-1](https://user-images.githubusercontent.com/19813688/54475067-5e835f80-47ed-11e9-99a8-0a7f240a953e.jpeg)
