### ISSUE TITLE
[FEATURE] Evers Single Remote availa

### ISSUE THREAD

**Issue by homohurre123** [nicoduj/homebridge-harmony#103]

**Comment by nicoduj** [comment]
?

**Comment by homohurre123** [comment]
Sorry pressed enter by accident 
---
Make it possible to make every single remote show up. Means that in apple remotes you can control every single devices singularly without action and that all of them show up at one.
I know this doesn't work yet because it doesn't work with only one homebridge server but In a long run it would make the Harmony hub even better.

**Comment by nicoduj** [comment]
like exposed in #53 you mean ?

**Comment by homohurre123** [comment]
Yes didnt See it before
