### ISSUE TITLE
Spell "skiped" correctly as "skipped"

### ISSUE THREAD

**Issue by DeutscheMark** [nicoduj/homebridge-harmony#105]
I know it might be something that needs changes in the people's configs but the correct spelling of "skiped" is "skipped" even though it's a small and unimportant change. Maybe this is something for the next major version where people have to change one or more fields anyway.

- skipedIfSameStateActivities -> skippedIfSameStateActivities
- addAllActivitiesToSkipedIfSameStateActivitiesList -> addAllActivitiesToSkippedIfSameStateActivitiesList

**Comment by nicoduj** [comment]
Will be done in 1.0 with a breeaking change
