### ISSUE TITLE
[BUG] showTurnOffActivity doesn’t work properly when inverterted

### ISSUE THREAD

**Issue by Sunoo** [nicoduj/homebridge-harmony#107]
When showTurnOffActivity is set to inverted, the power toggle in Home shows the expected state, but toggling it off doesn’t turn off the activities. It just immediately sets itself back on.

**Comment by nicoduj** [comment]
Hi, thanks for reporting. Could you post your whole config so that I can check ?

**Comment by Sunoo** [comment]
{
    "bridge": {
        "name": "Homebridge",
        "username": <removed>,
        "port": 51826,
        "pin": <removed>
    },

    "accessories": [
    ],

    "platforms": [
        {
            "platform": "ring-video-doorbell",
            "name": "Doorbell",
            "username": <removed>,
            "password": <removed>
        },
        {
            "platform": "WeatherPlus",
            "name": "WeatherPlus",
            "service": "darksky",
            "key": <removed>,
            "locationGeo": <removed>
        },
        {
            "platform": "HarmonyHubWebSocket",
            "name": "Living Room Harmony Hub",
            "hubIP": "10.0.1.14",
            "addAllActivitiesToSkipedIfSameStateActivitiesList": true,
            "publishActivitiesAsIndividualAccessories": false,
            "showTurnOffActivity": "inverted"
        },
        {
            "platform": "HarmonyHubWebSocket",
            "name": "Bedroom Harmony Hub",
            "hubIP": "10.0.1.86",
            "addAllActivitiesToSkipedIfSameStateActivitiesList": true,
            "publishActivitiesAsIndividualAccessories": false,
            "showTurnOffActivity": "inverted"
        },
        {
            "platform": "HarmonyHubWebSocket",
            "name": "Guest Room Harmony Hub",
            "hubIP": "10.0.1.85",
            "addAllActivitiesToSkipedIfSameStateActivitiesList": true,
            "publishActivitiesAsIndividualAccessories": false,
            "showTurnOffActivity": "inverted"
        },
        {
            "platform": "HarmonyHubWebSocket",
            "name": "Basement Harmony Hub",
            "hubIP": "10.0.1.87",
            "addAllActivitiesToSkipedIfSameStateActivitiesList": true,
            "publishActivitiesAsIndividualAccessories": false,
            "showTurnOffActivity": "inverted"
        }
    ]
}

**Comment by nicoduj** [comment]
Tried a quick blind fix, build is on its way, hope it will be ok

**Comment by Sunoo** [comment]
I can try installing it in a minute, but unless I’m misreading things, the only things changed are the change log and version number?

**Comment by nicoduj** [comment]
https://github.com/nicoduj/homebridge-harmony/commit/673f2f73b54687c1ac2d7a3113df1e392ed316f9#diff-f28ddcb4194d607d217cf1ba6e5aab18

(I made a pre push before releasing)

**Comment by Sunoo** [comment]
Ah, missed that one. 😁 

I just installed the updated version, and with limited testing it appears to be working as expected on all four of my hubs now. Thanks for the quick fix!
