### ISSUE TITLE
[BUG] Trigger TV mode OFF in a homekit scene causes double IR commands.

### ISSUE THREAD

**Issue by Midifreakz** [nicoduj/homebridge-harmony#109]
**Describe the bug**
I have a scene in homekit called 'goodnight' that turns every device in the house off.

When the TV device is already turned off in homekit, triggering this scene wil result in the harmony hub sending all the 'OFF' commands a second time (resulting in devices switching on)

**To Reproduce**
- Create a scene in homekit, add the TV device and let the scene trigger an 'off' state to the TvDevice. 
- Make sure no activities are running on the harmony hub and the Tv Device is off to begin with.
Run the scene.

**Expected behavior**
Triggering the off state a second time should not do anything if the tv device is already off.

**IOS (please complete the following information):**
- Version [12.2 public beta 6]
- Device: [iPhone XR]
- Plugin version 5.5 (Can't update via npm to 6.0 yet?)

**Logs**
[https://pastebin.com/TF4T4A4u]

**Config**
` {
   "platform": "HarmonyHubWebSocket",
    "name": "Woonkamer",
    "hubIP": "192.168.42.123",
    "TVPlatformMode" : true,
    "mainActivity" : "Apple Tv",
    "playPauseBehavior" : true,
    "showTurnOffActivity" : true,
    "publishActivitiesAsIndividualAccessories" : true
  }
   ]
 }
`
**Additional context**
I tried to overcome this problem by adding the "showTurnOffActivity" parameter but this seems to be broken for me, I can't get an all-off button to appear in homekit.. tried rebooting everything, re-adding homebridge to homekit etc. 
Does this only work when "TVPlatformMode"  is set to false?
[https://pastebin.com/KSL7e1Vt]

**Comment by nicoduj** [comment]
hi, thnak you for report and detailed informations . showTurnOffActivity is only available indeed when TVPlatformMode is off. 
0.6.0 is on its way, but still not finished.
Will try to include this fix as well .

**Comment by nicoduj** [comment]
ok, in fact it is allready possible and reported : 
https://github.com/nicoduj/homebridge-harmony/issues/104

you have to use the option describer in readme : 

- `skipedIfSameStateActivities` array of Activities name to trigger only if their state is different from the action sent. Can be usefull if your devices in the activity have the same on / off command and you want to automate them outside off the home app . For TV mode, and PowerOff feature, you can add "PowerOff" to this list if you want.
