### ISSUE TITLE
[FEATURE] list of activities as switches

### ISSUE THREAD

**Issue by BetoRn** [nicoduj/homebridge-harmony#116]
Not all activities are Tv related, I have a “Bluetooth Speaker” activity, which doesn’t fit into the Tv accessory 

A list of activities to be skipped by the Tv accessory and published as switches would be a nice add on

**Comment by nicoduj** [comment]
Hi,

You can unselect the input in properties of tv accessory to disable your Bluetooth input .

You can also add a second sub platform (1.0.0) or a second platorm (0.6.X) that behaves a switch . 

I will think of an option to hide some activities on switch mode however :)
