### ISSUE TITLE
[FEATURE] Revamp config to make it simple by default

### ISSUE THREAD

**Issue by nicoduj** [nicoduj/homebridge-harmony#117]
Revamp config, with default behavior , as simple as possible for basic usage.

- make subplatform optional if one platform (first platform always outside ?)
- rename subplatforms otherplatforms ?
- make tvmode the default
- make skippAllifsamestate the default
- do not publish anything else
- don’t make switch mode and tv mode separate ?
- revamp readme in a noob / power user approach
- add wiki for samples of config and faqs

**Comment by DoctorExitus** [comment]
Maybe support for the homebridge-configui-x plugin could also be a way to simplify the setup process. By that you could provide a UI for all the different config parameters. I just setup a different plugin that supported this and it was very easy and straight forward. I don't know how much work implementing support for that is though.

https://www.npmjs.com/package/homebridge-config-ui-x

**Comment by BetoRn** [comment]
Isn't _activitiesToPublishAsAccessoriesSwitch_   and _activitiesToPublishAsInputForTVMode_ essentially a whitelist of activities for each plugin mode? since those options cannot be used at the same time, maybe a single activitiesWhitelis would be simpler

**Comment by nicoduj** [comment]
Hi @BetoRn , in fact in the version I am working on, the same platform will be able to expose switches AND a TV accessory (by default only a TVaccessory). Having both options makes possible to have some activities as switch, and some on the TV accessory as inputs, but maybe not all (some asked for this since some activities are not "TV related").
