### ISSUE TITLE
[DEMO] TV-Mode

### ISSUE THREAD

**Issue by Phoenix-DH** [nicoduj/homebridge-harmony#120]
Hey, 

I really love this plugin, one of the most used for me.
I configured it perfectly for my need.

I want to give the TV mode a try, but I have no test scenario available and do not want to loose my actual config, because I used several action on hardware wall switches as example.

Can I see somewhere pircutes of the mode?
Is it also possible to use both in combination, like for example "devicesToPublishAsAccessoriesSwitch"

Thanks!

**Comment by nicoduj** [comment]
Hi, if you want to give it a try , are on 0.0.x version of this plugin(I guess so) and don’t have any other Roku or lg web tv plugin that exposes such device in homebridge, you can just add a second platform to your homebridge config with this mode enabled, a different name, and same hub ip. 

You have a video on my twitter account https://twitter.com/dujnic/status/1091094270814109696?s=21



<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Phoenix-DH** [comment]
Hey, if 2 platforms in parallel are working, great... I think I will give it a try.

**Comment by nicoduj** [comment]
What do you mean by such devices ?

**Comment by Phoenix-DH** [comment]
Yes, only that hub which is exposed via your plugin to home.

What does that then mean no support for the older versions? Only TV mode? ....

**Comment by nicoduj** [comment]
No, only 1.x version of my plugin which will involve configuration changes

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
