### ISSUE TITLE
error

### ISSUE THREAD

**Issue by roberkane212** [nicoduj/homebridge-harmony#123]
@nicoduj now i am getting this error

[2019-3-28 16:16:38] [28" Sanyo TV] INFO - Loading activities...
[2019-3-28 16:16:38] [28" Sanyo TV] Error - Error retrieving info from hub : Error: getaddrinfo ENOTFOUND undefined undefined:8088-(4/3)
Unhandled rejection Error - Harmony HUB at undefined is not available - can't start plugin

**Comment by roberkane212** [comment]
my config is

"platform": "HarmonyHubWebSocket",
"name": "TV",
"subPlatform": [{
"name": "Harmony Hub",
"hubIP": "192.168.0.5",
"TVPlatformMode": true,
"mainActivity": " The TV"
}]

**Comment by nicoduj** [comment]
Hi, are you in 1.0.0 beta ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by roberkane212** [comment]
yes i believe so

**Comment by roberkane212** [comment]
how can i check?

**Comment by nicoduj** [comment]
How did you install :) my guess is you are not from what I see

Nicolas

**Comment by roberkane212** [comment]
sudo npm install -g homebridge-harmony

**Comment by roberkane212** [comment]
config without sub platforms works fine, not sure what im doing wrong. is my config correct?

**Comment by roberkane212** [comment]
i have also tried sudo npm install -g homebridge-harmony@beta , but to this error

Loading 1 platforms...

/usr/local/lib/node_modules/homebridge/lib/api.js:108
  if (name.indexOf('.') == -1) {
           ^
TypeError: Cannot read property 'indexOf' of undefined
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:108:12)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:316:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:86:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:45:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)

**Comment by nicoduj** [comment]
You are not on beta but on 0.7.0 version (to install the beta, see [README](https://github.com/nicoduj/homebridge-harmony#work-in-progress-for-dynamic-plugin-mode) :)

However, in 0.4.7, you can make it work with the following config : 

```json
  {
    "platform": "HarmonyHubWebSocket",
    "name": "TV",
    "hubIP": "192.168.0.5",
    "TVPlatformMode" : true,
    "mainActivity" : "The TV"
  }
```

**Comment by roberkane212** [comment]
thats the config i currently have, but when i try to find another tv in add accessories there are none

**Comment by nicoduj** [comment]
Sorry, but I don't follow what version you are on, what config you are using .... and even if you have any other plugin installed . The last log from homebridge doesn't make sense and doesn 't seems to be possible in latest homebridge version

**Comment by roberkane212** [comment]
0.7.0

**Comment by roberkane212** [comment]
that error came with 
npm install -g homebridge-harmony@beta

**Comment by nicoduj** [comment]
ok, so. In 0.7.0, with the following config :   {
    "platform": "HarmonyHubWebSocket",
    "name": "TV",
    "hubIP": "192.168.0.5",
    "TVPlatformMode" : true,
    "mainActivity" : "The TV"
  }
, you have no device in home app, but no error ?
or is it just in control center remote app ?

**Comment by roberkane212** [comment]
it is just control center remote app

**Comment by nicoduj** [comment]
@roberkane212 I am sorry, but I really don't understand while reading this thread what is your problem at all. the error you report is talking about 1.0.0beta, but your log demonstrate that you are in 0.7.0. 
After that, you said that you are in 0.7.0, and I don't know if it works or not there. Can you calrify a bit in order me to help ? With full log and so on ? (the report template for bug reporting is there for that reason :) )

**Comment by nicoduj** [comment]
> it is just control center remote app

ok, and DO YOU have another plugin that exposes a TV to homekit ?

**Comment by roberkane212** [comment]
yes roku plugin

**Comment by nicoduj** [comment]
ok, so your roku is exposing from your homebridge, so you can't have both in 0.7.0 of my plugin. 

If you disable your roku, you will see your harmony.

You can try harmony beta by installing it this way : 
```bash
npm install -g homebridge-harmony@beta
```

Be sure to have update homebridge it self to ***0.4.47***.

Then modify your config like this :

```json
   "platforms": [
        {
            "platform": "HarmonyHubWebSocket",
            "name": "My Harmony Hub",
            "subPlatform": [{
                "hubIP": "192.168.0.5",
                "name": "TV",
                "TVPlatformMode": true,
                "mainActivity" : "The TV"
                }]
        }
    ]
```

**Comment by roberkane212** [comment]
Ok, how do i add my other tv's?

**Comment by roberkane212** [comment]
none show up when i go to add accessories like i saw in the video

**Comment by nicoduj** [comment]
I really don't understand man . How many TV do you have ? How many hubs ? 

Did you read carrefully the readme and especially options : 

'publishAsTVAsExternalAccessory' publish all TV accessory as external Accessories. This way, if another plugin on the same homebridge instance as one, the one on harmony will also be visible, but you will have to add them manually after the hub itself. Defaults to false (in that case, only second tv accessory or following will be published by this plugin as external accessories, first one will be linked to the hub).

**Comment by roberkane212** [comment]
i have 3 tv's 1 hub, just trying to do what i saw done in the video you posted from twitter

**Comment by nicoduj** [comment]
If you have only one hub you can’t currently , all tv are linked to the same hub . That is what I say in the beginning of the readme  : I expose one hub as a tv and each activity as an input . There is an evolution #53  for doing what I think you want but it is not implemented yet. 
If you want to expose your only hub with Roku, just add to the config I proposed to you the option publishAsTVAsExternalAccessory to true before the subplatform key

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nicoduj** [comment]
@roberkane212 did you make any progress on this ? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nicoduj** [comment]
@roberkane212 any news ? Can I close this or you still have problems ? Have a nice week end !

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by roberkane212** [comment]
I only have the one hub, so I figured it was a done deal

**Comment by nicoduj** [comment]
> I only have the one hub, so I figured it was a done deal

Ok, I though you were not seing your hub with roku. In fact, you can't see one remote per device for the mment, but will do this in the next futur.
