### ISSUE TITLE
Hubs linger after renaming.

### ISSUE THREAD

**Issue by jofotoo** [nicoduj/homebridge-harmony#124]
Homebridge Version 0.4.47
homebridge-harmony v1.0.0-beta10
macOS 10.14.4 (but i only upgraded to this yesterday)

I can successfully add hubs but can't seem to remove old versions after renaming them. In order to get the new version to appear, I have to delete homebridge from my Home config and re-add it. 

I tried removing all files highlighted here and restarting: <img width="882" alt="Screen Shot 2019-03-30 at 10 57 12 AM" src="https://user-images.githubusercontent.com/18692137/55277815-9e147600-52da-11e9-979a-08ff37e0f164.png">

my config looks like this (multiple cleanCaches because I can't seem to get it working):
 ```
   {
			"cleanCache": "true",
		   "platform": "HarmonyHubWebSocket",
		   "publishAsTVAsExternalAccessory": "true",
	       "name": "HubName",
	       "subPlatform": [{
   			"cleanCache":"true",
	         "name": "Living Room Harmony",
	         "hubIP": "10.0.1.xx",
	         "TVPlatformMode" : true,
			 "mainActivity" : "AppleTV"
		 	},
	         {
	         "name": "Bedroom Harmony",
	         "hubIP": "10.0.1.yy",
	         "TVPlatformMode" : true,
			 "mainActivity" : "Bedroom TV"
			 
	       }]
	     },
```

**Comment by nicoduj** [comment]
Since you are adding them as external accessories you have to remove them directly in home app in the settings .

Nicolas

**Comment by nicoduj** [comment]
@jofotoo can I close this one ? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jofotoo** [comment]
Yes thanks. That solved it
