### ISSUE TITLE
[FEATURE]Turn on Device when pressing any button on apple remote like on Apple TV

### ISSUE THREAD

**Issue by homohurre123** [nicoduj/homebridge-harmony#126]
I wondered if this would be possible since I think it would add a lot functionality to be able to turn on the TV  by simply pressing any button on the remote app without having to enter Home before.

**Comment by nicoduj** [comment]
Hi, nice suggestion . What behavior seems preferable : launch the main activity ? Last one ? Indeed keys on the remote are binded per activity so if there is no current activity I currently discards press on them . 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BetoRn** [comment]
My setup already does this

**Comment by nicoduj** [comment]
@BetoRn can I ask which version of the plugin you are using ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BetoRn** [comment]
> @BetoRn can I ask which version of the plugin you are using ?
> 
> Sent with [GitHawk](http://githawk.com)

v0.7.0

**Comment by nicoduj** [comment]
@homohurre123 and you ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nicoduj** [comment]
Can't reproduce in 1.0.0 and 0.7.0, in fact homekit set on on activecharacteristic so the default activity will be activated if everything is currently off. The command itself will be ignored however.
