### ISSUE TITLE
[BUG]publishActivitiesAsIndividualAccessories does not work on TV mode

### ISSUE THREAD

**Issue by reidrichardson** [nicoduj/homebridge-harmony#127]
First of all thank you so much for the hard work on this project.  My apologies if I misread and this is currently not supported in TV mode.

**Describe the bug**
publishActivitiesAsIndividualAccessories defaults as true; however, without it in my config, devices are not published as individual accessories.  if i hardcode it as true, the same behavior occurs.  If I hardcode it as false, behavior is same as if it is true

**To Reproduce**
{
 "hubIP": "192.168.x.x1",
 "TVPlatformMode": true,
 "publishActivitiesAsIndividualAccessories": true
}

**Expected behavior**
I would expect that each activity (Watch Apple TV, Play Xbox One, etc) would be individual accessories and icons I could press on the Home menu, and add to command center shortcuts

**Comment by nicoduj** [comment]
Hi,

This option is only for switch mode currently, and makes no sense currently since activities are inputs in tv mode.

I plan to had an option for tv mode to publish devices as tv accessories but it is not yet available . See https://github.com/nicoduj/homebridge-harmony/issues/53 .

**Comment by reidrichardson** [comment]
Thanks for the response and issue to the FR.

As to the why - I would enjoy being able to have a one click button available for friends/family, however I have found a work around by creating a scene for an input.

Thanks again for providing this plugin

**Comment by nicoduj** [comment]
> As to the why - I would enjoy being able to have a one click button available for friends/family, however I have found a work around by creating a scene for an input.

Why don’t you also publish a switch in this case ?
