### ISSUE TITLE
devicesToPublishAsAccessoriesSwitch not showing device, if PowerOn/PowerOff

### ISSUE THREAD

**Issue by JangoBritt** [nicoduj/homebridge-harmony#132]
**Describe the bug**

I'm trying to run two instances of the plugin, as separate platforms, as I'd like to set up a device separately to the TV Control.

However, the second one is only showing up the "Harmony Control" as a Not Supported device (with a house icon), but not the Savisto Candles.

I take note that the Candles don't have a PowerToggle command, only PowerOn and PowerOff, but I have tried using the specific ["Savisto Candles;PowerOn"] and this doesn't appear either.

When I add ["Humax DVR"] which does have PowerToggle, it shows up just fine as a device.

How can I get this device without a PowerToggle to show up? The Readme.md states that it should detect the availability of PowerOn/PowerOff as if PowerToggle

**To Reproduce**
Config.json configured as:

```
  {
    "platform": "HarmonyHubWebSocket",
    "name": "Harmony TV",
    "hubIP": "192.168.1.222",
    "TVPlatformMode" : true,
    "mainActivity" : "Play XBOX One"
  },
{
    "platform": "HarmonyHubWebSocket",
    "name": "Harmony Control",
    "hubIP": "192.168.1.222",
    "publishActivitiesAsIndividualAccessories" : false,
    "activitiesToPublishAsAccessoriesSwitch" : [],
    "publishDevicesAsIndividualAccessories" : true,
    "devicesToPublishAsAccessoriesSwitch" : ["Savisto Candles"],
    "TVPlatformMode" : false
  },

```

***Logs***
[2019-4-28 18:28:47] [Harmony Control] INFO - Command : PowerOff discovered for device : Savisto Candles
[2019-4-28 18:28:47] [Harmony Control] INFO - Command : PowerOn discovered for device : Savisto Candles
[2019-4-28 18:28:47] [Harmony Control] INFO - Command : Blue discovered for device : Savisto Candles
[2019-4-28 18:28:47] [Harmony Control] INFO - Command : Green discovered for device : Savisto Candles
[2019-4-28 18:28:47] [Harmony Control] INFO - Command : Light1 discovered for device : Savisto Candles
etc...

[2019-4-28 18:28:47] [Harmony Control] INFO - Loading devices...
[2019-4-28 18:28:47] [Harmony Control] INFO - Discovered Device : Savisto Candles
[2019-4-28 18:28:47] [Harmony Control] Error - No function found for Savisto Candles

***Details***
HomeBridge version 0.0.49
Harmony Hub version 4.15.250

**Comment by nicoduj** [comment]
Hi, I suspect those commands for this device are not in a controlgroup named power. In debug mode you will see the whole config of your hub could you send it to me ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by JangoBritt** [comment]
Forgive my ignorance... how do you set up a control group?

I set the device power options in the harmony app to use the two options... is that not it?

How do I set debug mode?

**Comment by nicoduj** [comment]
Hi, just launch homebridge with -D option for debug mode. 
Concerning control group, it is something defined by harmony while grouping commands, don’t think you have a way to control this by yourself. As far as I understand, you have set those commands manually ? So maybe they are not identified as power functions in the config and that might explain . 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nicoduj** [comment]
@JangoBritt any luck in getting your config ? I would like to be sure I correctly understood your issue before trying to fix .

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Kohle81** [comment]
@nicoduj

Hi, first thanks for your great plugin, it works fine!!

I have updated to version 1.03 and it is the first time I want to create toggles with devicesToPublishAsAccessoriesSwitch.

But when I (re)start homebridge I get now device command in the log.

When I used version 0.7 there were commands in the log.

Sorry for my bad english ;-)

Greetz, Manuel

**Comment by nicoduj** [comment]
Hi @Kohle81 , did you try option showCommandsAtStartup in your config ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Kohle81** [comment]
Hi,

oh I did not read the correct read.me 😬😬😬

No, I did not use the command showCommandsAtStartup in config. That‘s it.

"showCommandsAtStartup" : true

Is this the right command and format in config?

Thx for your fast answer!!

**Comment by nicoduj** [comment]
@Kohle81 that should do it 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Kohle81** [comment]
It works! Thx!
