### ISSUE TITLE
TV stops responding

### ISSUE THREAD

**Issue by sleepyarmistice** [nicoduj/homebridge-harmony#134]
**Describe the bug**
After running for ~12 hours, the TV accessory becomes nonresponsive. The only way to fix this appears to be to sign out/in of iCloud or to remove the TV from the Home app and then read the bridge. 

**To Reproduce**
Let it run, use normally. 

**Expected behavior**
The accessory stays accessible. 

**Screenshots**

**IOS (please complete the following information):**
- Version 12.2
- Device: iPhone 7, iPad Air 2, Apple TV 4

**Logs**
  I'm not sure when to include, since I don't see any errors. I'm pasted the logs here: https://pastebin.com/wUkqQrbn
  

**Config**
{
	"bridge": {
		"name": "Bedroom TV Bridge",
		"username": "CC:23:3D:E3:CE:32",
		"port": 51830,
		"pin": "987-65-432"
	},

	"platforms": [{
	    "platform": "HarmonyHubWebSocket",
	    "name": "Bedroom",
	    "hubIP": "10.0.1.34",
		"TVPlatformMode": true,
		"mainActivity": "Watch"
	  }
]
}

**Additional context**
This happens consistently across two bridges that I have set up for two hubs. I had to set it up this way because configuring this plugin on my main bridge made the rest of the configuration stop responding. I am running them on a mac running macOS 10.13.6 with Homebridge 0.4.46 and node 10.8.0. 

Other misc details:
- The accessory stops responding inconsistently across devices. IE: It will be available on my iPad, but not my phone. 
- After the device stops responding, it will still work as part of an automation. IE: The sounder is supposed to turn on in the morning and continues to do so consistently.
- Weirdly, on of my TVs just disappeared from the Home app overnight last night.

**Comment by nicoduj** [comment]
Hi. Do you have any other older device in your iCloud account that is on iOS 9 or 10 by any chance ? If so try disabling iCloud sync for home app on it ...

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nicoduj** [comment]
By the way I am interested into the stop responding issue with one bridge, could you tell me more about it ? Concerning the disappearing issue I checked your logs and definitely it seems like an home app problem, some users already had such problems with an older device on their iCloud account 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sleepyarmistice** [comment]
No, it’s not an iOS 9 problem. Everything in our house is running 12.2. I’m not really sure what other details to give, especially since I’m not really sure what causes this to happen. Oddly, I’ve had it running with our other TV for about 24 hours now without incident.

**Comment by nicoduj** [comment]
There is nothing on the side of the plugin / homebridge from what I see . It seems to be an home app problem / sync or maybe a conflict between your homebridge ? Are publishing different names just in case / don’t you have same if somewhere ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sleepyarmistice** [comment]
I’m starting to suspect the same thing. I’m not sure what you mean by you last two questions, though?

**Comment by nicoduj** [comment]
Hi, sorry, there was a lot of typo there :) 
I was wondering if your hubs had different names, and if your activities were also with different names ?

**Comment by nicoduj** [comment]
I am closing since there was no news on this, felle free to reopen if the problem persists.
