### ISSUE TITLE
Play/Pause Separate

### ISSUE THREAD

**Issue by FelixG28** [nicoduj/homebridge-harmony#138]
My TV has no Play/Pause Toggle like it is shown on the Apple TV Remote. There are separate Play and Pause Buttons. If I assign the Play/Pause button of the Apple TV remote to my TV, it is only possible to either do a Play or Pause Command.

**Comment by nicoduj** [comment]
Hi, did you give a try to playPauseBehavior option ?

**Comment by nicoduj** [comment]
Hi, any luck trying this option ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nicoduj** [comment]
I am closing since I have no news on my suggestion, feel free to reopen if it doesn't suits your needs.
