### ISSUE TITLE
Remove obsolete devices

### ISSUE THREAD

**Issue by twynne** [nicoduj/homebridge-harmony#139]
Since moving to to the new 'tv' version of this plugin, I've noticed I have a host of old individual harmony activities showing as devices.  I've tried deleting the cachedAccessories file, but it just regenerates with the same devices.  

Is there some simple way to clean this up?

**Comment by twynne** [comment]
Small update... I've tested further by renaming each of my hubs, and can see the obsolete devices are associated with the 'old' hub names.  Any idea which file/cache these are held in, as it must be something other than cachedAccessories.  Also I'm unable to delete them from the Home app.  I could remove the entire bridge and add it back, but still not sure that will get rid of these devices.

**Comment by nicoduj** [comment]
Hi, sorry I am ill and can’t really dig into your problem . If you are on 0.7 there is no cached accessory so it could be an iOS iCloud sync issue with old iOS version . Otherwise, on 1.0 you can try starting homebridge with the option to reset everything in my plugin (check the readme of 1.0)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by twynne** [comment]
Thanks for the reply, and sorry to hear you're unwell.  I suspect these devices are from a previous iteration of homebridge-harmony as noted above if I change the hub name in your plugin they remain associated with the old name.  Guessing the root issue here is that your plugin uses the same name as other harmony plugins ('homebridge-harmony') and homebridge itself is keeping these accessories around because that plugin is technically still installed.  The devices, by the way, appear in homebridge-config-ui so that tells me they exist in my homebridge installation, not just in the Homekit database.

I'm really not sure how to clean this up.  I suppose I could remove your plugin and reinstall it.  Do you know if I can leave the homebridge-harmony in the config file, or would I have to remove all of that as well?

**Comment by twynne** [comment]
Another quick update... I removed the homebridge-harmony lines from config, and uninstalled your plugin.  Restarted homebridge, and unfortunately these rogue devices are still there.  There isn't any longer any harmony plugins installed, so I've really no idea where it is getting these devices.

**Comment by twynne** [comment]
Further update... took a somewhat 'nuclear' option and managed to get there:

- Removed harmonyhub config
- Uninstalled harmonyhub plugin
- Deleted persist folder
- Deleted cachedAccessories files
- Restarted homebridge
(confirmed all rogue devices gone)
- Installed harmonyhub plugin
- Restored harmonyhub config lines
- Restarted homebridge
(confirmed all rogue devices still gone, correct devices are back)

Thanks for your help in any case.  :)

Get well soon!
