### ISSUE TITLE
[BUG] Multiple Hubs crashing homebridge

### ISSUE THREAD

**Issue by mensa84** [nicoduj/homebridge-harmony#140]
Hello,

when I add 2 hubs in version 1.0.0-rc.2 with TVmode the homebridge plugin is crashing at every restart with that messages:

```
Jun 16 16:13:54 Server homebridge[4186]: [6/16/2019, 4:13:54 PM] TypeError: Cannot read property 'name' of undefined
Jun 16 16:13:54 Server homebridge[4186]:     at HarmonyPlatform.configureAccessory (/usr/lib/node_modules/homebridge-harmony/harmonyPlatform.js:101:69)
Jun 16 16:13:54 Server homebridge[4186]:     at Server._configCachedPlatformAccessories (/usr/lib/node_modules/homebridge/lib/server.js:386:24)
Jun 16 16:13:54 Server homebridge[4186]:     at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:93:8)
Jun 16 16:13:54 Server homebridge[4186]:     at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:59:10)
Jun 16 16:13:54 Server homebridge[4186]:     at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
Jun 16 16:13:54 Server homebridge[4186]:     at Module._compile (internal/modules/cjs/loader.js:816:30)
Jun 16 16:13:54 Server homebridge[4186]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
Jun 16 16:13:54 Server homebridge[4186]:     at Module.load (internal/modules/cjs/loader.js:685:32)
Jun 16 16:13:54 Server homebridge[4186]:     at Function.Module._load (internal/modules/cjs/loader.js:620:12)
Jun 16 16:13:54 Server homebridge[4186]:     at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
Jun 16 16:13:54 Server homebridge[4186]:     at internal/main/run_main_module.js:21:11

```

Could you please fix this?

**Comment by nicoduj** [comment]
Can you post your config please ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mensa84** [comment]
This is the config:
(The names are not the same as the Harmony Hub itself is named in the Harmony App. Is that a problem?)

```

		{
			"platform": "HarmonyHubWebSocket",
			"name": "Wohnzimmer Fernseher",
			"hubIP": "192.168.1.20",
			"TVPlatformMode" : true,
			"mainActivity" : "Apple TV"
		},
		
		{
			"platform": "HarmonyHubWebSocket",
			"name": "Schlafzimmer Fernseher",
			"hubIP": "192.168.1.30",
			"TVPlatformMode" : true,
			"mainActivity" : "Apple TV"
		},
```

**Comment by nicoduj** [comment]
The config is not correct in 1.0 . You must use subplatform, please check readme

**Comment by mensa84** [comment]
Thank you, but I don't find anything with keyword "sub" in readme. What exactly do you mean?

**Comment by nicoduj** [comment]
otherplatforms sorry, but just read through the samples (ans the whole migration guide) :

https://github.com/nicoduj/homebridge-harmony/tree/Dynamic-Platform

Mutliple hubs

"platforms": [
  {
    "platform": "HarmonyHubWebSocket",
    "name": "HubName",
    "hubIP": "192.168.1.XX",
    "otherPlatforms": [{
      "name": "OtherHubName",
      "hubIP": "192.168.1.YY"
      }]
  }
]

**Comment by mensa84** [comment]
Thank you!
I did only read that readme: https://github.com/nicoduj/homebridge-harmony

How should I know about your link? I am not sure how one should find that, could you please explain why this is not in the "main" readme?

**Comment by nicoduj** [comment]
Readme on the main is for 0.7 version which is still the stable release for the moment . Readme on this branch is for the 1.x version ,which you have with it when you install this beta branch .

**Comment by mensa84** [comment]
Ok, thank you very much!
Do you have an idea, when a stable release with TVmode will come?

**Comment by mensa84** [comment]
Now I made that configuration, but now only the first entry "Wohnzimmer Fernseher" appears in HomeKit.
Why? What did I do now wrong?

```
		{
			"platform": "HarmonyHubWebSocket",
			"name": "Wohnzimmer Fernseher",
			"hubIP": "192.168.1.20",
			"otherPlatforms": [
				{
					"name": "Schlafzimmer Fernseher",
					"hubIP": "192.168.1.30"
				}
			]
		}
```

**Comment by nicoduj** [comment]
Once again please read carrefully the whole readme. Only one hub will be added by default, you have to had the other one manually since it will be exposed as an external accessories in order for the tv remote control to see it . 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mensa84** [comment]
I did read, but also when I use the option "publishAllTVAsExternalAccessory" : true it does not help.
It makes it even more bad, then don't see any TV. Could you please help me?

**Comment by mensa84** [comment]
I removed the previos mentioned option "publishAllTVAsExternalAccessory" and left it to default and found out, that I could add the second TV in HomeKit - but I am unable to do this, because I don't see the code anywhere and also not described in your readme, how to do this.

**Comment by nicoduj** [comment]
The code is in the log file at homebridge startup. If you don't use any other plugin on the same homebridge that expose a TV accessory, you are fine letting publishAllTVAsExternalAccessory in its default value (false)

**Comment by mensa84** [comment]
Thank you sooo much!! It worked now.
Maybe you should mention in the readme, that the code is the same as it is for homebridge itself?

**Comment by mensa84** [comment]
But now I have the problem, that for the first TV I can not select any input in the HomeKit app on the iPhone. For the second it is possible, but not for the first one.
Do you know why?

**Comment by nicoduj** [comment]
Not sure it is always the case (there is a separate log for each external accessory), but surely I will add a mention to it .

**Comment by mensa84** [comment]
The startup logfile shows that information now, I think that is not correct. Why is in the first line the name of the first TV and also the second TV mentioned?

```
Jun 16 19:57:23 Server homebridge[29374]: [6/16/2019, 7:57:23 PM] [Wohnzimmer Fernseher] (Wohnzimmer Fernseher)INFO - configuring Main TV Service
Jun 16 19:57:23 Server homebridge[29374]: [6/16/2019, 7:57:23 PM] [Wohnzimmer Fernseher] (Wohnzimmer Fernseher)INFO - Configuring Main Activity Apple TV
Jun 16 19:57:23 Server homebridge[29374]: [6/16/2019, 7:57:23 PM] [Wohnzimmer Fernseher] INFO - Adding Accessory : Schlafzimmer Fernseher-TV
Jun 16 19:57:23 Server homebridge[29374]: [6/16/2019, 7:57:23 PM] [Wohnzimmer Fernseher] (Schlafzimmer Fernseher)INFO - configuring Main TV Service
Jun 16 19:57:23 Server homebridge[29374]: [6/16/2019, 7:57:23 PM] [Wohnzimmer Fernseher] (Schlafzimmer Fernseher)INFO - Creating TV Service
Jun 16 19:57:23 Server homebridge[29374]: [6/16/2019, 7:57:23 PM] [Wohnzimmer Fernseher] (Schlafzimmer Fernseher)INFO - Creating Input Service - PlayStation
Jun 16 19:57:23 Server homebridge[29374]: [6/16/2019, 7:57:23 PM] [Wohnzimmer Fernseher] (Schlafzimmer Fernseher)INFO - Configuring Main Activity Apple TV
Jun 16 19:57:23 Server homebridge[29374]: [6/16/2019, 7:57:23 PM] [Wohnzimmer Fernseher] (Schlafzimmer Fernseher)INFO - Creating TV Speaker Service
Jun 16 19:57:23 Server homebridge[29374]: [6/16/2019, 7:57:23 PM] [Wohnzimmer Fernseher] (Schlafzimmer Fernseher)INFO - Creating Input Service - Apple TV
Jun 16 19:57:23 Server homebridge[29374]: [6/16/2019, 7:57:23 PM] [Wohnzimmer Fernseher] (Schlafzimmer Fernseher)INFO - Creating Input Service - AV-Receiver
Jun 16 19:57:23 Server homebridge[29374]: [6/16/2019, 7:57:23 PM] [Wohnzimmer Fernseher] (Schlafzimmer Fernseher)INFO - Creating Input Service - Einschlafmusik
Jun 16 19:57:23 Server homebridge[29374]: [6/16/2019, 7:57:23 PM] [Wohnzimmer Fernseher] (Schlafzimmer Fernseher)INFO - Creating Input Service - Radio
Jun 16 19:57:23 Server homebridge[29374]: [6/16/2019, 7:57:23 PM] [Wohnzimmer Fernseher] INFO - setupFoundAccessories - TV accessory added as external accessory
Jun 16 19:57:23 Server homebridge[29374]: [6/16/2019, 7:57:23 PM] Schlafzimmer Fernseher-TV is running on port 39595.
Jun 16 19:57:23 Server homebridge[29374]: [6/16/2019, 7:57:23 PM] Please add [Schlafzimmer Fernseher-TV] manually in Home app. Setup Code: 031-45-154

```

**Comment by nicoduj** [comment]
[Wohnzimmer Fernseher] is the name of the platform 
(Wohnzimmer Fernseher) is the name of the hub 

so it is indeed redundant for the first hub but It helped me seprate the logs of devices

**Comment by mensa84** [comment]
But did I configure it correct? Or should I change the naming?
