### ISSUE TITLE
[BUG] WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9

### ISSUE THREAD

**Issue by tooh** [nicoduj/homebridge-harmony#144]
**Describe the bug**
Warning about  Unsupported platform for fsevents@1.2.9

**To Reproduce**
```
sudo npm -g install homebridge-harmony
```

**Expected behavior**
Installation / upgrade without warning

**Screenshots**

**IOS (please complete the following information):**
- Device: [e.g. iPhone8]

**Logs**
Your log in debug mode (-D option)

```
$ sudo npm -g install homebridge-harmony

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/homebridge-harmony/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})

+ homebridge-harmony@0.7.0
updated 3 packages in 35.679s
```

**Config**
Your config section of platform. Please do not post your whole config and especially with logins / passwords !

**Additional context**

**Comment by nicoduj** [comment]
Hi, could you explain more please ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tooh** [comment]
when I run
sudo npm -g install homebridge-harmony

I get this warning

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/homebridge-harmony/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})

**Comment by nicoduj** [comment]
Hi, thx did you notice any unexpected behavior ? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jamesdh** [comment]
This can be safely ignored. It's caused because fsevents is a package used for handling file system  events in MacOS and is only used in MacOS. You're likely installing the package in some flavor of linux, and npm is correctly telling you that the package isn't needed/supported there. 

I'm guessing it's a transient dependency of one of the devDependencies (best guess is husky). This will not cause any unexpected behavior.

**Comment by rsonnens** [comment]
I see this too on raspberian "Buster" version. Latest OS that is needed for new pi4.


pi@raspberrypi:~ $ sudo npm -g install homebridge-harmony
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/homebridge-harmony/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})

+ homebridge-harmony@1.0.0
updated 1 package in 64.963s

**Comment by rsonnens** [comment]
I did not see this warning on earlier versions.
