### ISSUE TITLE
Siri Commands to Change Activity

### ISSUE THREAD

**Issue by itsgabraf** [nicoduj/homebridge-harmony#145]
What are the commands to change activity when using Tv Platform

**Comment by leoneleone** [comment]
Have you tried basics, like:
“Switch the tv to (input name)”?
“Change tv input to (input name)”?

**Comment by nicoduj** [comment]
Hi, didn’t find a way in French but still interested if you do in English !

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nicoduj** [comment]
Seems it is not possible at all :( Moreover, since IOS 12.4 (and it is the case alos in 13.1), you can't anymore activate on a dedicated input ...

**Comment by piejanssens** [comment]
Use Siri Shortcuts

**Comment by nicoduj** [comment]
Yes sir shortcuts does the trick indeed
