### ISSUE TITLE
Add a dummy switch when any activity is on/off

### ISSUE THREAD

**Issue by jasehigh** [nicoduj/homebridge-harmony#146]
A feature request not a bug...

I would like to be able to switch on the living room lamp at sunset if the TV (homebridge-harmony) is not on. From what I can see there is no method by which th is can currently be achieved in homekit.

Therefore I propose a an addition “dummy” switch is made available (configurable) which is set to On when any when homebridge-harmony is on, and set to Off when homebridge-harmony is off.

This way, it would be possible to create automations based upon the condition... is the TV on/off.

If we have decided to watch TV upstairs and left the living room in a darkness, a lamp can then be switched on if the TV is off.

Jason.

**Comment by nicoduj** [comment]
I, thanks for the suggestion. Can’t you use the off switch for that (option showTurnOffActivity). if you set to true, The "switch" will be "on" if and only if there is no current activity, and toggling it while "on" does nothing. You can invert its behavior if you want

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jasehigh** [comment]
The option showTurnOffActivity looks perfect. Should have read the documentation closer. Many thanks for your reply.
