### ISSUE TITLE
IOS 13 - Issues report thread

### ISSUE THREAD

**Issue by krazyflipj** [nicoduj/homebridge-harmony#147]
I think this might be a good place to post issues on IOS 13. One issue I’m having is that I can’t move the icon in the home app.

**Comment by nicoduj** [comment]
I, thx for opening the thread . For this one, I am not sure that it is plugin related but will check as soon as I will move to ios13 (probably in 1 or 2 betas ;) ) . What icon are you talking about however ? Activity for tv, device or other ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by krazyflipj** [comment]
![7FFFD2AE-BA5A-4259-8A27-06BB20B020AF](https://user-images.githubusercontent.com/10282165/62439644-7eb2ad00-b701-11e9-8e59-ff33a7cffa3d.jpeg)
When you try and move it, it doesn’t save and disappears. Closing app and relaunching will make it show again.

**Comment by nicoduj** [comment]
Ok, will check on my iPad tonight . It is the only device that does that ? Do you have any error un homebridge log ? Do you have multiple iOS device which are not all on iOS 13 ?

Nicolas

**Comment by nicoduj** [comment]
Hi again, I checked on my iPad yesterday evening which is on ios13 (my iPhone is not) and can not reproduce your issue in the room. Did not check on the home screen however , will do that also but can you check if moving in the room is ok ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by krazyflipj** [comment]
Weird. It does it in room too

**Comment by krazyflipj** [comment]
![F767EA3D-A843-4518-941A-978A024FA40D](https://user-images.githubusercontent.com/10282165/62511898-9ace5100-b7ca-11e9-8b82-3c7e99dc1c14.gif)

**Comment by nicoduj** [comment]
Weird indeed ! Which version of the plugin are you using ? I’ll check on iPhone as soon as I will be on ios13 on it , on iPad I don’t have the issue like I said (but I have one where one of my device name - a tplink outlet- is not correct and not the one displayed in properties .... 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nicoduj** [comment]
Just an idea : did you change the name of the accessory in HomeKit ? If not can you try I. The property tab ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by krazyflipj** [comment]
On .7  I just changed the name which it saved but still having same issues

**Comment by nicoduj** [comment]
Hi, since I am on 1.0 maybe it is working there . Will try in 0.7 as soon as I can .

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Krocko** [comment]
I don’t think it’s related to this plugin. 
I have the same problem with the homebridge-neato plugin.

**Comment by krazyflipj** [comment]
Upgraded to 1.0. Any way to default a certain input when turning on?

**Comment by nicoduj** [comment]
>Upgraded to 1.0. Any way to default a certain input when turning on?

@krazyflipj mainActivity option is still supported 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by krazyflipj** [comment]
I remember reading how we can only have 2 remotes at a time. Was this fixed on iOS 12? if so, it isn't working on iOS13. I have roku plugin, apple tv, and this plugin and only shows 2 of the 3

**Comment by nicoduj** [comment]
> I remember reading how we can only have 2 remotes at a time. Was this fixed on iOS 12? if so, it isn't working on iOS13. I have roku plugin, apple tv, and this plugin and only shows 2 of the 3

You have to publish as external accessories. I think Roku does not support that, my plugin does. please unsure your are publishing as external accessory and add it manually in home app (see README)

**Comment by nicoduj** [comment]
@krazyflipj is it ok, did you find the way to do it ? I remember to have a small video on a twitter post : https://twitter.com/dujnic/status/1110644949027041282?s=21

**Comment by nicoduj** [comment]
@krazyflipj do you still have the issue ?
