### ISSUE TITLE
[BUG]  activitiesToPublishAsAccessoriesSwitch isn't working in TVmode

### ISSUE THREAD

**Issue by mbhforum** [nicoduj/homebridge-harmony#148]
**Describe the bug**

I have a seperate activity called "Bedroom Fan" and it's not creating a switch for it. 

**To Reproduce**
Steps to reproduce the behavior

1: Edit config.json with the below code, and restart homebridge.  Seperate switch does not appear in Homekit, but TVmode device does. 

**Expected behavior**

A switch to appear called "Bedroom Fan". 

**Screenshots**

**IOS (please complete the following information):** 12.4
- Device: [e.g. iPhone6] iPhone XR/iPad 

**Logs**
Your log in debug mode (-D option)

Unfortunately, I am running Homebridge in a Docker container on my Synology and the logs aren't working properly. 

**Config**
Your config section of platform. Please do not post your whole config and especially with logins / passwords !

	{
			"platform": "HarmonyHubWebSocket",
			"name": "Master Bedroom",
			"hubIP": "192.168.1.36",
			"TVPlatformMode" : "true",
			"mainActivity" : "Watch Tivo-Master Bedroom",
			"showTurnOffActivity" : "true",
			"activitiesToPublishAsAccessoriesSwitch" : ["Bedroom Fan"]
	}

**Additional context**

**Comment by nicoduj** [comment]
Hi,

without the log it will be difficult to help. Can you confirm that the turnOff switch is shown ? Since you also add a problem with the mainActivity name if I correctly remmber, I suspect you might have an issue with your activities names. Did you try to use the option "switchAccessories" : true , and see what switches are added ?

Concerning your log, if you have configUI you can always see them there. You might also try to get them on your nas directly through the synology docker interface no ? (I have them and running also in a docker on my syno)

**Comment by mbhforum** [comment]
I don't have a problem with the activity name for this hub as it shows when I activate it. As you can see in my code, it's not my default main activity.   I do not see any turnOff switches either, which is fine, I actually don't want those and took that code out now. 

I tried, "switchAccessories" : "true" and that didn't work either.  I didn't see that variable in the ReadMe, so didn't know about it.  

The Synology Logs have been a little wonky for me this week as I am traveling, but they just did show up in the console and I don't see any errors relating to this. (These were info logs, I am having trouble seeing debug logs and will try when I get home this weekend).

**Comment by nicoduj** [comment]
Hi,

You are on 1.0.0 of the plugin right, not 0.7 ?

Nicolas

**Comment by mbhforum** [comment]
> Hi, You are on 1.0.0 of the plugin right, not 0.7 ? Nicolas
> […](#)
> Le 9 août 2019 à 14:36, mbhforum ***@***.***> a écrit : I don't have a problem with the activity name for this hub as it shows when I activate it. As you can see in my code, it's not my default main activity. I do not see any turnOff switches either, which is fine, I actually don't want those and took that code out now. I tried, "switchAccessories" : "true" and that didn't work either. I didn't see that variable in the ReadMe, so didn't know about it. The Synology Logs have been a little wonky for me this week as I am traveling, but they just did show up in the console and I don't see any errors relating to this. (These were info logs, I am having trouble seeing debug logs and will try when I get home this weekend). — You are receiving this because you were assigned. Reply to this email directly, view it on GitHub, or mute the thread.

How do I determine this?  In my install.sh, I run "npm install -g homebridge-harmony" upon startup, so I assume everytime I restart the container, it updates?

**Comment by nicoduj** [comment]
You are on the master branch so on 0.7. Version 1.0.0 is still in Beta testing (branch dynamic platform) . So in 0.7 you must add two instance of the plugin if you want both modes - see #97 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mbhforum** [comment]
That worked.  Thank you!
