### ISSUE TITLE
Add an option to expose devices on /off

### ISSUE THREAD

**Issue by nicoduj** [nicoduj/homebridge-harmony#15]
Expose devices (all  / some ?) with their on / off function (devices, not activities)

**Comment by sommo** [comment]
Need this too, it could be very usefull.
Power is good Also Expose other command could be nice

**Comment by carsten-h** [comment]
From the german Harmony forum I got the reply that this lib is using devices from the Harmony Hub. Maybe it is helpful: [https://github.com/Wolbolar/IPSymconHarmony](url)

**Comment by nicoduj** [comment]
Hi,

I will put this on a hold for now since I am working on #30 for now

**Comment by bverkron** [comment]
Very reasonable since it sounds like it would provide similar and maybe even better functionality in some ways, although it’s not entirely clear yet at this stage. Appreciate the update.

**Comment by sommo** [comment]
Thank you for the update!
Hope to succed in this way! Could be amazing!!

Inviato da iPhone

**Comment by nicoduj** [comment]
Since tv support is on its way I will close that

**Comment by nicoduj** [comment]
Reopen still it still make sense to have them aside , will think of it

**Comment by carsten-h** [comment]
Thank you very much!

**Comment by nicoduj** [comment]
@sommo @carsten-h  @bverkron  : Done in 0.4.0, let me know if it suits your needs !

I exposed devices as push button switch since there is no way to get their state (especially if they were put on / off by any other action than the switch itself).

If your device is configured with powertoggle button (on/off, same command), it will be exposed as one push switch in homekit. However, if there is only power on or/and power off defined, it will expose a switch for power on / power off.

**Comment by carsten-h** [comment]
I am getting this message for my shutters:
`[2/16/2019, 7:13:05 PM] [HarmonyHub] Discovered Device : Rollladen
[2/16/2019, 7:13:05 PM] [HarmonyHub] Error - No Power function found for Rollladen`

There is no switch for On/Off for them, only up/down is available. In my Harmony App these are visible around the OK button on the first page.
![img_6be1dcb8c35d-1](https://user-images.githubusercontent.com/44360828/52903574-9cf22280-321f-11e9-8e68-93f32dd5758b.jpeg)

**Comment by nicoduj** [comment]
I just mapped on / off as it is what make sense for me. I think you can try to map on / off function in harmony with up / down and it might work.

**Comment by carsten-h** [comment]
There is only Powertoggle available and what I need is DirectionUp and DirectionDown.
Maybe it is possible to specify the "correct" On/Off commandname via config.json?

**Comment by nicoduj** [comment]
It is a pleasure :) 

Did you try this : https://support.logitech.com/en_za/article/12732 ?

**Comment by Phoenix-DH** [comment]
Will also try this new feature because I have 2 light strips which are not part of an activity.

What about the syntax for config.joson?
„devicesToPublishAsAccessoriesSwitch„ : [„Stripe 1“, „Stripe 2“]

Thanks

**Comment by carsten-h** [comment]
Yes, I did this. I used DirectonUp for PowerOff and DirectionDown for PowerOn. But the error message is still the same. I will look into it this evening when I have more time.

**Comment by nicoduj** [comment]
> Will also try this new feature because I have 2 light strips which are not part of an activity.
> 
> What about the syntax for config.joson?
> „devicesToPublishAsAccessoriesSwitch„ : [„Stripe 1“, „Stripe 2“]
> 
> Thanks

You have to put the name of the devices in harmony app, as an array indeed .

**Comment by nicoduj** [comment]
> Yes, I did this. I used DirectonUp for PowerOff and DirectionDown for PowerOn. But the error message is still the same. I will look into it this evening when I have more time.

LEt me know, you will have to restart homebridge for this to take effect. If you could launch in debug mode and send me your config which will be displayed it might help.

**Comment by Phoenix-DH** [comment]
Okay, I tried ... restarted homebridge.
Accessories will not apear...

Did I miss something?

```
        {
            "platform": "HarmonyHubWebSocket",
            "name": "HarmonyHub",
            "hubIP": "XXX",
            "showTurnOffActivity": true,
            "turnOffActivityName": "All off",
            "devicesToPublishAsAccessoriesSwitch": [
                "Beleuchtung TV",
                "Beleuchtung Theke"
            ]
        }
```

I used exactly the names out of the Harmony App.

**Comment by carsten-h** [comment]
After I did the changes in Harmony app I restarted homebridge. Can you tell me how to start in debug mode?

**Comment by nicoduj** [comment]
Add a -D option in the command line

**Comment by carsten-h** [comment]
Ok, I will do it this evening as I have to leave now.

**Comment by Phoenix-DH** [comment]
Will Lso deliver data  with debug mode.
I hab a look to the app:
One device is powered on/off with the same button, the other with 2 buttons.

So I think whis will not be the problem as far as I understood, right?

**Comment by nicoduj** [comment]
Yes, right. I have a doubt if it works outside of tv mode (it should, but maybe Inmissed something) . Feel free to post debug log and I will check this evening

**Comment by maisun** [comment]
Hi Nicoduj, thanks for this nice feature! Would it be posible to expose a certain command on the device as toggle on/off button (it’s the same command for on and off). I have a light switch which is controlled by B&O sound system, and the switch works regardless the sound system is turned on/off. 
Thank you in advance!

**Comment by nicoduj** [comment]
Hi @maisun, will think of this use case originally I just wanted to handle power feature originally. Being able to map other commands involves begin able to list them all in a certain way and map them to each « switch » .  Definitely more work and config to do but why not :)

**Comment by maisun** [comment]
Hi @nicoduj, maybe a generic function to add a toggle switch (switch on send command and then set off) in HomeKit for DeviceName.CommandName - not sure if Harmony client sends command name or translated IR code to the hub though.
Thank you in advance!

**Comment by carsten-h** [comment]
Hi! I managed to start homebridge with -D.
The part from the logfile, that is interesting for this, should be the following (I extracted only the part for the shutter, if you need more I can send it):
[Rollladen.txt](https://github.com/nicoduj/homebridge-harmony/files/2873012/Rollladen.txt)

**Comment by nicoduj** [comment]
Great. Will take a look at it from what I see there is no power control group and that is why the plugin can’t find the command . Will see if I can base the search on something else or maybe another way to do this (would like the conf to be not too « difficult »)

**Comment by carsten-h** [comment]
The only thing that I am see is:
`"powerFeatures":{"PowerOffActions":[{"__type":"IRPressAction","IRCommandName":"DirectionUp","Order":0,"Duration":0,"ActionId":0}],"PowerOnActions":[{"__type":"IRPressAction","IRCommandName":"DirectionDown","Order":0,"Duration":0,"ActionId":0}]},`
These are the two commands I set.

For my Panasonic TV there can be the following found:
`"powerFeatures":{"PowerOffActions":[{"__type":"IRPressActi
Feb 17 15:05:36 HomePi homebridge[23019]: on","IRCommandName":"PowerOff","Order":0,"Duration":1000,"ActionId":0}],"PowerOnActions":[{"__type":"IRPressAction","IRCommandName":"PowerOn","Order":0,"Duration":1000,"ActionId":0}]},"isManualPower":"false","controlGroup":[{"name":"Power","function":[{"action":"{\"command\":\"PowerOff\",\"type\":\"IRCommand\",\"deviceId\":\"60257134\"}","name":"PowerOff","label":"Power Off"},{"action":"{\"command\":\"PowerOn\",\"type\":\"IRCommand\",\"deviceId\":\"60257134\"}","name":"PowerOn","label":"Power On"},{"action":"{\"command\":\"PowerToggle\",\"type\":\"IRCommand\",\"deviceId\":\"60257134\"}","name":"PowerToggle","label":"Power Toggle"}]},`

**Comment by nicoduj** [comment]
Yes, that is what I saw. For all my devices I have a power controlGroup and I based my search on this. Will think of using powerFeatures maybe instead .

**Comment by carsten-h** [comment]
Interestingly there is a powerFeatures group for my TV also, although I did not add anything here. Maybe it would be the best to search for powerFeatures only if there is no power controlGroup available.

**Comment by nicoduj** [comment]
I think powerFeatures is a link to the command itself since it doesn’t have the command . Don’t really know what the group stands for / if it si defined through the configuration. I might try to check the power features available and then parse the whole list of commands to find them .

**Comment by nicoduj** [comment]
OK guys I pushed a new version with a new optional behaviour where you can specify the command you want on the switch for the device. Please read README for syntax :) 
Let me know if it suits your needs !

**Comment by Phoenix-DH** [comment]
Will try tomorrow... thanks...

**Comment by maisun** [comment]
> OK guys I pushed a new version with a new optional behaviour where you can specify the command you want on the switch for the device. Please read README for syntax :)
> Let me know if it suits your needs !

Just tested the custom button with my setup and it works like charm! The only problem I noticed is when I press button too quickly it doesn't work sometimes, but I can live with that. Really good work, thanks for bringing my Harmony alive!

**Comment by nicoduj** [comment]
>The only problem I noticed is when I press button too quickly it doesn't work sometimes, but I can live with that. Really good work, thanks for bringing my Harmony alive!

Could you tell me more ? There is currently a delay for switching the switch back to off position (since it is a push button). The delay is about 1s, so I expect that if you hit twice it won't catch the second action. Is it in this time interval when you say quickly ?

**Comment by carsten-h** [comment]
Thank you for this solution!
Now I have two switches in Homekit for my shutters. If they work I can tell this evening as they are too loud to test them now where all others here are sleeping.

**Comment by Phoenix-DH** [comment]
Yes! Thanks for the great work.
I installed the latest version, but norhing changed until now.
THe devices are not visible. Before I start deeper cheecks I want to clarify if it should basicaly work with this settings:
This is my device, page 2, 2 buttons, one for power on one for power of, they are working inside harmony app
![img_3846](https://user-images.githubusercontent.com/44058592/52930513-028dfe00-3349-11e9-9c26-63d8c6174c91.PNG)
And these are the general power settings for the device:
![img_3847](https://user-images.githubusercontent.com/44058592/52930525-0de12980-3349-11e9-9e65-aa79ae8ca1ff.PNG)
Dies mean, power them off if not in use. But this device is not a part of any action ...
So in my opinion this value does not effect anything.

I did not change anything to this:
```
        {
            "platform": "HarmonyHubWebSocket",
            "name": "HarmonyHub",
            "hubIP": "XXX",
            "showTurnOffActivity": true,
            "turnOffActivityName": "All off",
            "devicesToPublishAsAccessoriesSwitch": [
                "Beleuchtung TV",
                "Beleuchtung Theke"
            ]
        }
```
The device is controlled via IR ... and as far as I saw I am not able to change the buttons that I for example use others for power off and on ...

**Comment by maisun** [comment]
> > The only problem I noticed is when I press button too quickly it doesn't work sometimes, but I can live with that. Really good work, thanks for bringing my Harmony alive!
> 
> Could you tell me more ? There is currently a delay for switching the switch back to off position (since it is a push button). The delay is about 1s, so I expect that if you hit twice it won't catch the second action. Is it in this time interval when you say quickly ?

That's most likely the problem - to be honest I pressed the button without looking at it.
Is it possible to configure the delay? 1s is ok for on/off but for volume it should be lower I think.

**Comment by nicoduj** [comment]
@maisun 

> That's most likely the problem - to be honest I pressed the button without looking at it.
> Is it possible to configure the delay? 1s is ok for on/off but for volume it should be lower I think.

This mode was not made for commands like Volume. I definitely prefer to focus on TV Mode with IOS 12.2 for such use case, since for this kind of commands a "remote" is much more reliable I think.


@Phoenix-DH  

I need your config (which is shown in debug mode) to investigate. From what I see at lest something like :  
-  **"devicesToPublishAsAccessoriesSwitch" : ["Beleuchtung TV;PowerOn","Beleuchtung TV;PowerOff"]** should work.

**Comment by Phoenix-DH** [comment]
@nicoduj:
Thank you, will try .. bad thing .. then I will have 2 switches, right?

**Comment by maisun** [comment]
Understood, thanks! Look forward to iOS 12.2

**Comment by carsten-h** [comment]
Hello!

@nicoduj, you are my hero!
The commands are recognized as I wrote this morning. And they are working without any problem, so now I can control my shutters depending on sunrise/sunset. That is really great!
Thank you!

**Comment by nicoduj** [comment]
> then I will have 2 switches, right?

**Comment by nicoduj** [comment]
>@nicoduj: ...

@Phoenix-DH yes you will have 2 switches. I can have a switch that knows the state of the device since it would not be able to react to external events. However if your device have a PowerToggle function then you can set only this one and you will have only one switch

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Phoenix-DH** [comment]
Great, thanks!
I get the one with Off/On seperat working ... with 2 switches!

But the one with one, the switch will not appear... extract from homebridge -d:
`{"label":"Beleuchtung Theke","deviceAddedDate":"/Date(1527532614833+0000)/","ControlPort":7,"contentProfileKey":XXX,"deviceProfileUri":"XXX=","manufacturer":"Paulmann","icon":"24","Capabilities":[],"deviceTypeDisplayName":"LightController","powerFeatures":[],"isManualPower":"false","controlGroup":[{"name":"Home","function":[{"action":"{\"command\":\"PowerToggle\",\"type\":\"IRCommand\",\"deviceId\":\"XXX\"}","name":"PowerToggle","label":"Power Toggle"}]},{"name":"Miscellaneous","function":[{"action":"{\"command\":\"Auto\",\"type\":\"IRCommand\",\"deviceId\":\"XXX\"}","name":"Auto","label":"Auto"},{"action":"{\"command\":\"B\",\"type\":\"IRCommand\",\"deviceId\":\"XXX\"}","name":"B","label":"B"},{"action":"{\"command\":\"BlueDown\",\"type\":\"IRCommand\",\"deviceId\":`

And the config:
`"Beleuchtung Theke;PowerToggle"`

Last step ;)

**Comment by nicoduj** [comment]
>Great, thanks! ...

@Phoenix-DH that is what I was about to say : you have the PowerToggle command ! Nice if it works as you want it to , enjoy !

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
