### ISSUE TITLE
[BUG] . Error: The requested platform 'HarmonyHubWebSocket' was not registered by any plugin.

### ISSUE THREAD

**Issue by mbhforum** [nicoduj/homebridge-harmony#153]
**Describe the bug**

Trying to run the harmony dynamic mode on a SEPARATE Homebridge Docker container on my Synology and I get the error below. Please note, I have not removed my existing non-Dynamic Harmony config from my primary Homebridge docker container yet.  I am able to successfully start the second HomeBridge container without the harmony configuration. 

**To Reproduce**
Steps to reproduce the behavior

Start HomeBridge docker container and observe logs

**Expected behavior**

I expect Homebridge to start up and see the Harmony Hub in Homekit. 

**Screenshots**

**IOS (please complete the following information):**
- Version [e.g. 22] 12.4
- Device: [e.g. iPhone6] iPhone Xr

**Logs**
Your log in debug mode (-D option)
[37m[8/11/2019, 3:39:06 PM][39m [1m[31mError: The requested platform 'HarmonyHubWebSocket' was not registered by any plugin.
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:134:13)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:327:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:90:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)[39m[22m

**Config**
Your config section of platform. Please do not post your whole config and especially with logins / passwords !

Config.json looks like below:

    "accessories": [
    ],

    "platforms": [
      {
    		"platform": "HarmonyHubWebSocket",
    		"name": "Master Bedroom Harmony Hub",
    		"hubIP": "192.168.1.36",
    		"activitiesToPublishAsAccessoriesSwitch" : ["Bedroom Fan"],
    		"mainActivity" : "Watch TiVo-Master Bedroom"
  	  }    
    ]
}

**Additional context**

Not sure which is the right command as your documentation has 2 seperate refences. I tried both, errors on both:

npm install -g homebridge-harmony@rc

OR

npm install -g homebridge-harmony@beta

**Comment by nicoduj** [comment]
Hi,

the correct command should be npm install -g homebridge-harmony@rc .
The plugin is not installed from homebridge point of view, did you have any error during installatin ? Check the node_modules directory to see if the plugin is there.

**Comment by mbhforum** [comment]
> Hi,
> 
> the correct command should be npm install -g homebridge-harmony@rc .
> The plugin is not installed from homebridge point of view, did you have any error during installatin ? Check the node_modules directory to see if the plugin is there.

Looks like that is the issue. This container doesn't have bash installed, so using install.sh doesn't work. When I drop to a terminal prompt, check out the error I get.  I am not able to see that log file in my file system though.  

/homebridge # npm install -g homebridge                                                                                                                                     
/usr/local/bin/homebridge -> /usr/local/lib/node_modules/homebridge/bin/homebridge                                                                                          
+ homebridge@0.4.50                                                                                                                                                         
updated 1 package in 3.335s                                                                                                                                                 
/homebridge # npm install -g homebridge-harmony@rc                                                                                                                          
npm ERR! code ETARGET                                                                                                                                                       
npm ERR! notarget No matching version found for homebridge-harmony@rc                                                                                                       
npm ERR! notarget In most cases you or one of your dependencies are requesting                                                                                              
npm ERR! notarget a package version that doesn't exist.                                                                                                                     
                                                                                                                                                                            
npm ERR! A complete log of this run can be found in:                                                                                                                        
npm ERR!     /root/.npm/_logs/2019-08-11T16_12_20_885Z-debug.log

**Comment by nicoduj** [comment]
My bad sorry, the command is : npm install -g homebridge-harmony@beta

**Comment by mbhforum** [comment]
> My bad sorry, the command is : npm install -g homebridge-harmony@beta

Thanks, that did it.  Does this support more than 2 hubs? Or do I need to run another container for my other 2 hubs? I have 4 in total. It seems to only accept one more.

**Comment by nicoduj** [comment]
Should support multiple hubs, with something like this : 

```json
"platforms": [
  {
    "platform": "HarmonyHubWebSocket",
    "name": "HubName",
    "hubIP": "192.168.1.XX",
    "otherPlatforms": [{
      "name": "OtherHubName",
      "hubIP": "192.168.1.YY"
      },
      {
      "name": "OtherHubName2",
      "hubIP": "192.168.1.ZZ"
      },
      {
      "name": "OtherHubNam3",
      "hubIP": "192.168.1.WW"
      }]
  }
]
```

**Comment by mbhforum** [comment]
Thanks! That fixed it.
