### ISSUE TITLE
Install warnings on raspberian "buster" OS

### ISSUE THREAD

**Issue by rsonnens** [nicoduj/homebridge-harmony#154]
**Describe the bug**
Install warnings that were not present in earlier releases. bug was opened and closed earlier but it is still happening even though it can be ignored. It is however disconcerting.

**To Reproduce**
pi@raspberrypi:~ $ sudo npm -g install homebridge-harmony
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/homebridge-harmony/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})

+ homebridge-harmony@1.0.0
updated 1 package in 64.963s

**Expected behavior**
no warnings

**Config**
Raspberian "Buster" release needed for pi4 support.

**Comment by nicoduj** [comment]
See #144 , it is linked to a dev dependencies no impact on run (optional means optional ;) )

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
