### ISSUE TITLE
[BUG] showTurnOffActivity switch still present when setting to false

### ISSUE THREAD

**Issue by Garywoo** [nicoduj/homebridge-harmony#155]
**Describe the bug**
The `showTurnOffActivity` switch accessory is still present after setting its config value to `false`.

**To Reproduce**
I upgraded to 1.0.0, and made the appropriate config migration changes. I was previously using the switches mode with `"showTurnOffActivity": true` , but accepted the new default to use the TV mode. I then realised I no longer needed this switch, so set the config value to `false` and restarted Homebridge. The switch was still present after the restart.

**Expected behavior**
I would expect the switch accessory to be removed from HomeKit.

**iOS**
- Version 12.4
- Device: iPhone 6s

**Config**
```
{
    "platform": "HarmonyHubWebSocket",
    "name": "Harmony Hub",
    "hubIP": "192.168.2.2",
    "showTurnOffActivity": false,
    "publishSwitchActivitiesAsIndividualAccessories": true,
    "publishDevicesAsIndividualAccessories": true,
    "publishHomeControlsAsIndividualAccessories": true,
    "mainActivity": "Watch Apple TV"
}
```

**Additional context**
Toggling the switch using the Home app does not do anything. No console output, and no Harmony actions are taken. The switch will remain in whatever state you leave it. It does not reset itself.

**Comment by nicoduj** [comment]
Did you try cleaning your cache (through the option or manually) ? Once added, since it is cached, it will remain in homekit.

**Comment by Garywoo** [comment]
I had not seen that option in the main readme. I found the documentation in the Dyanmic-Platfrom branch and set `cleanCache` to true. Restarting Homebridge then made the switch disappear from the Home app. 

Thanks for the help!

**Comment by nicoduj** [comment]
yes, master branch is not 1.0 (but 0.7) -> not a dynamic platform.
