### ISSUE TITLE
After update to version 1.0.1 no switch mode available anymore

### ISSUE THREAD

**Issue by Nastras** [nicoduj/homebridge-harmony#160]
Hello @nicoduj ,

i used switch mode so far after updating to version 1.0.1 it has completely disappeared. I assumed that I could use switch and tv mode after the update?

> If you want both modes, please add 2 platforms with different names (and same IP) or switch to 1.0.0 version of the plugin (Dynamic Branch)

I don't manage to show the switch mode again. Do you have an idea?

Here my Config:

"plugins": [
"homebridge-harmony"
],

"accessories": [
],

"platforms": [
{
"platform": "HarmonyHubWebSocket",
"name": "Multimediahub Wohnzimmer",
"hubIP": "192.168.178.77",
"showTurnOffActivity": true,
"publishActivitiesAsIndividualAccessories": false,
"addAllActivitiesToSkipedIfSameStateActivitiesList": true,
"devicesToPublishAsAccessoriesSwitch" : ["Apple TV;Reboot"]
},
{
"platform": "HarmonyHubWebSocket",
"name": "Multimediahub Schlafzimmer",
"hubIP": "192.168.178.78",
"showTurnOffActivity": true,
"publishActivitiesAsIndividualAccessories": false,
"addAllActivitiesToSkipedIfSameStateActivitiesList": true,
"devicesToPublishAsAccessoriesSwitch" : ["Apple TV;Reboot"]
}
] 
}

Thank you in advance for your help!

**Comment by nicoduj** [comment]
Hi,

I think you did not read the migration part of the readme :)

Something like this, if you don't want TV accessory mode : 

```json
"platforms": [
    {
      "platform": "HarmonyHubWebSocket",
      "name": "Multimediahub Wohnzimmer",
      "hubIP": "192.168.178.77",
      "showTurnOffActivity": true,
      "TVAccessory" : false,
      "switchAccessories" : true,      
      "publishActivitiesAsIndividualAccessories": false,
      "addAllActivitiesToSkippedIfSameStateActivitiesList": true,
      "devicesToPublishAsAccessoriesSwitch": [
          "Apple TV;Reboot"
      ],

      "otherPlatforms": [{
        "name": "Multimediahub Schlafzimmer",
        "hubIP": "192.168.178.78",
        "showTurnOffActivity": true,
        "TVAccessory" : false,
        "switchAccessories" : true,         
        "publishActivitiesAsIndividualAccessories": false,
        "addAllActivitiesToSkippedIfSameStateActivitiesList": true,
        "devicesToPublishAsAccessoriesSwitch": [
            "Apple TV;Reboot"
        ]
        }]
    }
  ]
```

In case of any trouble since you launched with a bad config eventually, set option cleanCache to true, launch homebrdge, set option to false and restart.

**Comment by Nastras** [comment]
Thanks for the quick answer.

It works almost as it should. All switches (harmony actions) are shown to me as their own device in the eve app. Previously these were listed as one device for each Harmony Hub.

I thought this option was responsible that it is not displayed as a separate switch?

"publishActivitiesAsIndividualAccessories": false,

**Comment by Nastras** [comment]
One more addition. I get this error when restarting the homebridge instance. Is it known to you?
<img width="1051" alt="Bildschirmfoto 2019-08-16 um 17 55 34" src="https://user-images.githubusercontent.com/27686185/63180745-34a9bf80-c04f-11e9-9727-06c9e0a52555.png">

**Comment by nicoduj** [comment]
Hi,

Ok, for the option I did a mistake and did not follow readme migration also : ) 
the option is now publish**SwitchActivities**AsIndividualAccessories and not publish**Activities**AsIndividualAccessories. I fear you need to clean cache since the accessories have been cached mostly.

Concerning the other error, it is due to a dependency breaking change I did not notice. Will publish an update asap.

**Comment by Nastras** [comment]
Super now everything works as it should. Can you explain these two options to me because I'm not sure what exactly they do? What exactly does home controls mean?

homeControlsToPublishAsAccessoriesSwitch array of home controls you want to publish as switches
publishHomeControlsAsIndividualAccessories option to publish home controls as individual accessories.

**Comment by nicoduj** [comment]
It is for harmony hubs which can expose devices like hue lamps (those orange icons on the remote) : 

https://assets.logitech.com/assets/64812/9/harmony-companion-whole-home-remote-hub-and-app.png

Not really convincing to my opinion but was asked from a user :)

**Comment by Nastras** [comment]
All right. Got it!

Would be cool if you could write an example like this in the readme behind the certain functions. Then one becomes also directly clear what is meant .-)

I thank you again for your help and wish you a nice weekend!
