### ISSUE TITLE
[BUG] - changing plarform name is not supported after first launch

### ISSUE THREAD

**Issue by rsonnens** [nicoduj/homebridge-harmony#162]
**Describe the bug**
I keep crashing at startup, even when I set "cleanCache"

**To Reproduce**
just start home bridge up. Was working I think before I changed the name parameter

*
**Logs**
Aug 16 14:19:10 raspberrypi systemd[1]: Started Node.js HomeKit Server.
Aug 16 14:19:12 raspberrypi homebridge[1450]: [8/16/2019, 2:19:12 PM] Loaded config.json with 0 accessories and 2 platforms.
Aug 16 14:19:12 raspberrypi homebridge[1450]: [8/16/2019, 2:19:12 PM] ---
Aug 16 14:19:13 raspberrypi homebridge[1450]: [8/16/2019, 2:19:13 PM] Loaded plugin: homebridge-harmony
Aug 16 14:19:13 raspberrypi homebridge[1450]: [8/16/2019, 2:19:13 PM] Registering platform 'homebridge-harmonyHub.HarmonyHubWebSocket'
Aug 16 14:19:13 raspberrypi homebridge[1450]: [8/16/2019, 2:19:13 PM] ---
Aug 16 14:19:14 raspberrypi homebridge[1450]: [8/16/2019, 2:19:14 PM] Loaded plugin: homebridge-nest
Aug 16 14:19:14 raspberrypi homebridge[1450]: [8/16/2019, 2:19:14 PM] Registering platform 'homebridge-nest.Nest'
Aug 16 14:19:14 raspberrypi homebridge[1450]: [8/16/2019, 2:19:14 PM] ---
Aug 16 14:19:15 raspberrypi homebridge[1450]: [8/16/2019, 2:19:15 PM] Loaded plugin: homebridge-weather-plus
Aug 16 14:19:15 raspberrypi homebridge[1450]: [8/16/2019, 2:19:15 PM] Registering platform 'homebridge-weather-plus.WeatherPlus'
Aug 16 14:19:15 raspberrypi homebridge[1450]: [8/16/2019, 2:19:15 PM] ---
Aug 16 14:19:15 raspberrypi homebridge[1450]: [8/16/2019, 2:19:15 PM] Loading 2 platforms...
Aug 16 14:19:15 raspberrypi homebridge[1450]: [8/16/2019, 2:19:15 PM] [TV] Initializing HarmonyHubWebSocket platform...
Aug 16 14:19:15 raspberrypi homebridge[1450]: [8/16/2019, 2:19:15 PM] [TV] HarmonyPlatform Init
Aug 16 14:19:15 raspberrypi homebridge[1450]: [8/16/2019, 2:19:15 PM] [Nest] Initializing Nest platform...
Aug 16 14:19:15 raspberrypi homebridge[1450]: [8/16/2019, 2:19:15 PM] [Nest] Fetching Nest devices.
Aug 16 14:19:15 raspberrypi homebridge[1450]: [8/16/2019, 2:19:15 PM] TypeError: Cannot read property 'name' of undefined
Aug 16 14:19:15 raspberrypi homebridge[1450]:     at HarmonyPlatform.configureAccessory (/usr/lib/node_modules/homebridge-harmony/harmonyPlatform.js:101:69)
Aug 16 14:19:15 raspberrypi homebridge[1450]:     at Server._configCachedPlatformAccessories (/usr/lib/node_modules/homebridge/lib/server.js:386:24)
Aug 16 14:19:15 raspberrypi homebridge[1450]:     at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:93:8)
Aug 16 14:19:15 raspberrypi homebridge[1450]:     at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:59:10)
Aug 16 14:19:15 raspberrypi homebridge[1450]:     at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
Aug 16 14:19:15 raspberrypi homebridge[1450]:     at Module._compile (internal/modules/cjs/loader.js:778:30)
Aug 16 14:19:15 raspberrypi homebridge[1450]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
Aug 16 14:19:15 raspberrypi homebridge[1450]:     at Module.load (internal/modules/cjs/loader.js:653:32)
Aug 16 14:19:15 raspberrypi homebridge[1450]:     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
Aug 16 14:19:15 raspberrypi homebridge[1450]:     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
Aug 16 14:19:15 raspberrypi homebridge[1450]:     at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
Aug 16 14:19:15 raspberrypi homebridge[1450]:     at startup (internal/bootstrap/node.js:283:19)
Aug 16 14:19:15 raspberrypi homebridge[1450]:     at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
Aug 16 14:19:15 raspberrypi homebridge[1450]: [8/16/2019, 2:19:15 PM] Got SIGTERM, shutting down Homebridge...
Aug 16 14:19:15 raspberrypi homebridge[1450]: [8/16/2019, 2:19:15 PM] [TV] INFO - shutdown
**Config**
        {
"cleanCache": true,
                "platform": "HarmonyHubWebSocket",
                "name": "TV",
                "hubIP": "192.168.87.20",
                "mainActivity": "Watch Apple TV"
        },

**Additional context**
Problem happen before I added the clean cache line. I think it worked before I changed the name of the "name" parameter. I can't remember the old name. :-(

**Comment by rsonnens** [comment]
Oh, running on raspberian BUster release on a pi 3+

**Comment by reidrichardson** [comment]
I was getting same error last night after updating, mine is basically the same config minus name and IP.  i uninstalled and went back to 0.7 and it is running perfectly again

**Comment by rsonnens** [comment]
OK, so I see a webscockets build error that I did not notice before if I uninstall and reinstall:

pi@raspberrypi:~ $ sudo npm -g install  homebridge-harmony      

> websocket@1.0.29 install /usr/lib/node_modules/homebridge-harmony/node_modules/harmony-websocket/node_modules/websocket
> (node-gyp rebuild 2> builderror.log) || (exit 0)

sh: 1: cannot create builderror.log: Permission denied

> websocket@1.0.29 install /usr/lib/node_modules/homebridge-harmony/node_modules/websocket
> (node-gyp rebuild 2> builderror.log) || (exit 0)

sh: 1: cannot create builderror.log: Permission denied
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/homebridge-harmony/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})

+ homebridge-harmony@1.0.2
added 818 packages from 993 contributors in 100.874s

**Comment by rsonnens** [comment]
So I put in a log debug and I saw my accessory name at the point of the crash was "NicoHarmonyHub2-TV" which seems odd! I think that prefix was my OLD name in the config.

**Comment by rsonnens** [comment]
Well well well, if I change the name back from "TV"  to "NicoHarmonyHub2" it now works again!

Something is being cached somewhere!

**Comment by nicoduj** [comment]
Hi,

Thank you for those test. I think clencache won’t work with a name change, will try to fix. You can always delete file (or entry in it if you are skilled with json) in homebridge persist folder . 1.0.0 is using homebridge cache of accessories, that is why this is happening when you change the naméof the platform
