### ISSUE TITLE
Update from 0.7.0 to 1.0.2 failure

### ISSUE THREAD

**Issue by niwre2019** [nicoduj/homebridge-harmony#163]
Hello,
unfortunately, my Homebridge does not start making the update anymore.  I do not seem to understand the changes to be adjusted.  Here is my new configuration, what am I doing wrong?
Thanks for your help

    {
      "showTurnOffActivity" : true,
      "sequencesToPublishAsAccessoriesSwitch" : [
        "Ton",
        "TV Ton"
      ],
      "platform" : "HarmonyHubWebSocket",
      "TVAccessory" : true,
      "mainActivity" : "My TV",
      "switchAccessories" : true,
      "publishSwitchActivitiesAsIndividualAccessories" : true,
      "hubIP" : "192.168.178.xxx",
      "skippedIfSameStateActivities" : [
        "PowerOff"
      ],
      "devicesToPublishAsAccessoriesSwitch" : [
        "Bose",
        "Fernseher",
        "Fernseher;InputHdmi1",
        "Fernseher;InputHdmi2",
        "PVR",
        "Apple TV;Reboot"
      ],
      "name" : "LogitechHub"
    }

**Comment by rsonnens** [comment]
Is the ip address correct? think the xxx needs a number there.

**Comment by niwre2019** [comment]
yes, the IP address is correct, I have only replaced the last digits with xxx.

**Comment by nicoduj** [comment]
Hi, what  error do you have ? Did you try with latest version released today just in cas it is related to platform renaming ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by niwre2019** [comment]
Hi, when starting the Homebridge with this configuration I get the error "There was a problem reading your config.json file." In the meantime, I've got it running by setting the two parameters "TVAccessory": true, and "switchAccessories"  : true, removed.  However, I miss so the activities.  Currently I have updated to version 1.0.3.

**Comment by nicoduj** [comment]
Ok, will check on a computer ASAP since I don’t see anything on my phone :) by the way you don’t need to set tvAccessory option to true since it is default . Only switchAccessories. I suggest you follow the order of the samples in your parameters and especially for mandatory parameters , it will be more readable even if not a problem .

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by niwre2019** [comment]
Many thanks.  I only have tvAccessory in the configuration to quickly test other configurations.  The order in the configuration was fine as it's so much clearer, but at one point it was suddenly different, I think the Homebridge app was the cause.

**Comment by nicoduj** [comment]
Ok, so do you still have a problem ? If so, post your full config, if not you can close the issue :) 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by niwre2019** [comment]
I'm slightly irritated now, you wanted to look at the problem, right?  My complete configuration contains too much personal information, so I do not want to post it.  A pity, then I close the issue. :(

**Comment by nicoduj** [comment]
Off course I want to look at your issue, otherwise I would not bear answering this thread at all. I think I do my best on this github to provide help to users and I don’t understand why you are irritated neither if you have a problem or not. It is fine it you don’t want to post your full config, but since you told the error was homebridge related on the whole config file, it might not be on the plugin section at all. If you have a real issue (did not understand with your last message), feel free to reopen and explain again the situation, following the bug report template .

Regards .

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by niwre2019** [comment]
Hi, Homebridge has just changed the order of configuration within the plugin, but the whole configuration is fine and the plugin works under version 0.7.0.  I know you're trying to help everyone and I do not want to swap myself with you.  But if the help means to me that I should post my entire configuration, then I do not want to do that.  Of course, I would be very grateful if I could use the plugin again as in version 0.7.0.
Regards

**Comment by nicoduj** [comment]
Can I have the log file then at startup ? Does the faulting config file validated through such service : https://jsonlint.com

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by niwre2019** [comment]
Yes I can do that.  I'm on the road for the rest of the day and will be in touch tomorrow.  Thank you for your message.

**Comment by nicoduj** [comment]
Just in case, the following config should work (only change ip) :
```json
{
    "platform": "HarmonyHubWebSocket",
    "name" : "LogitechHub",
    "hubIP": "192.168.1.XX",
    "switchAccessories" : true,
    "showTurnOffActivity" : true,
    "sequencesToPublishAsAccessoriesSwitch" : [
       "Ton",
       "TV Ton"
     ],
    "mainActivity" : "My TV",
    "publishSwitchActivitiesAsIndividualAccessories" : true,
    "skippedIfSameStateActivities" : [
       "PowerOff"
    ],
    "devicesToPublishAsAccessoriesSwitch" : [
       "Bose",
       "Fernseher",
       "Fernseher;InputHdmi1",
       "Fernseher;InputHdmi2",
       "PVR",
       "Apple TV;Reboot"
    ]
}
```

**Comment by niwre2019** [comment]
Hello, 
I renamed my Hub to LogitechHub, installed the latest version 1.04, and adopted your configuration.  What can I say, now it is running again, only PowerOff is now duplicated and can not be cleaned up with CleanCache, but I can live very well with it.  Thank you for your support.
Best Regards

**Comment by nicoduj** [comment]
Ok, do you see any difference in the properties of the duplicated PowerOff ? Is there any chance you have some old iOS device (iOS 10 or below) that sync your home with iCloud ? 

(The option is cleanCache and not CleanCache just in case :) )

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by niwre2019** [comment]
The old PowerOff does not work anymore, I renamed it PowerOff-Old so I do not accidentally use the old version. Unfortunately, I do not have an old iOS 10 device. 

(Sorry, for the wrong parameter, I used the correct spelling in the configuration. :))

**Comment by nicoduj** [comment]
Ok, i would really like to understand why it is still there, is it possible to check the properties of this switch, and send me the log in debug mode of the plugin at start ?  Is it still listed in the hub devices in home app ? the Jason file I. Homebridge persist folder could be interesting too if possible (or at least the section of it with the 2 switches)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by niwre2019** [comment]
I do not know if I understand everything correctly now, in Linux have unfortunately only rudimentary basic knowledge.  I just copied what I found.

[IdentifierCache.txt](https://github.com/nicoduj/homebridge-harmony/files/3516592/IdentifierCache.txt)
[Log.txt](https://github.com/nicoduj/homebridge-harmony/files/3516593/Log.txt)

**Comment by nicoduj** [comment]
#167 . 
You can still try to delet file in cachedAccessory, but Homebridge MUST be stopped while doing it.
