### ISSUE TITLE
Potential Phantom devices remained around when changing hub name

### ISSUE THREAD

**Issue by rsonnens** [nicoduj/homebridge-harmony#164]
**Describe the bug**
When I changed the name param, I noticed that phantom devices hung around that were associated with old settings using the other name!

**To Reproduce**
Create an instance not using the new TV remove settings where all devices get listed. Add devices in home app.

Then change the json name param to use a new name, and only use the simple TV mode settings.

When I re-add homebridge  in the home app  I see both new remote UI AND all the old devices that are associated with the old name.

Removing the persist file and cleanCache were not enough. I had to delete ALL the files in the homebridge directory that started with the names: harmonyPluginNames_* and use cleanCache for thing to get fixed up.

Not sure if easy to fix, but improved instructions are warnings about changing names might be advised.

**Comment by rsonnens** [comment]
[thanks for fixing the other related crash yesterday!]

I'm all fixed up but I wanted to get you this info.

**Comment by knuckleheadsmiff** [comment]
Sorry, above I said “old devices”, but I really was seeing old activities in the home app. Not sure if that matters.

**Comment by rsonnens** [comment]
Sorry, but I think I can better describe the phantom garbage I was seeing than I did above.

I saw a 'remote' UI with no inputs in the input drop down, and a seperate activity (with a home icon) for each activity that normally would have shown in the remote. These all listed the "model" in the UI using the old name. I had a total of 7 extra homebridge accessories in the home app.

I also correctly had one homebridge accessory,  the new remote, with all the activities in the input drop down, and the 'model' listed with the new name.

**Comment by nicoduj** [comment]
Hi, thank you for the extra info . I pushed a new release roadway that should fix issue when you rename the hub. Will do more test but should be ok I think 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by knuckleheadsmiff** [comment]
Was with the 1.0.3 release. (Sorry for my different git login name.) 

As noted I’m now good so I may not see the issue anymore.

**Comment by nicoduj** [comment]
Ok, thank you will try to reproduce to better understand ;) I am removing old accessories now in case of name change . What I don’t understand is the step where you readd homebridge, if you did that you probably have changed the homebridge is right ? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by knuckleheadsmiff** [comment]
Sorry, by readd, I just mean deleting the homebridge icon in the home app which deletes all the accessories, and then adding it back into the home app (used the same I’d code from the logs) which then in turn adds in the accessories again. I know my teminlogy is confusing here.
, sorry.

**Comment by nicoduj** [comment]
Ok, never did that this way , I never delete in home app relaunching homebridge with config change is enough for me .so the sequence to reproduce should be the following :
-launch homebridge with name1 and switch mode
-add bridge in home app (all switch are added)
-stop homebridge
-delete bridge in home app
-rename with name2 ans tvplatform mode this time
-launch homebridge (the log there should say for each accessory of platform name1 they are removed from cache since version1.0.3)
-add in home again . There you are seeing switch again AND the tv accessory

Right ? 


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by knuckleheadsmiff** [comment]
When I saw the problem that was the sequence except in the first step I now believe I was in tv platform mode in step one and not in switch mode—switch mode was a red-herring. 

Prior to 1.0.3 of course I would crash when starting up homebridge. 

I never had it just work in the home app by just relaunching homebridge when changing the name. When you do this is the “model” name in the tv accessories setting (in the home app) the new name or the old name?

**Comment by knuckleheadsmiff** [comment]
I need to let you know, that with my setup it is a pita to play with this a lot as I am using a Pi connected to my TV with a half ass wireless keyboard with trackpad. It is not the best setup for playing with this stuff. I have to sit like 8 feet away while making my edits..... so I was going best from memory of the steps. If you can’t reproduce then that’s OK. 

I just wanted you to know what I had to do to get things working again by manually removing files (harmonyPluginNames_* had 2 with both ‘names’)  in addition to what was in the persists directory.

**Comment by nicoduj** [comment]
thank you, will add a clean feature of this files also in case of name change just in case, but I don't really understand why it would have been the cause of this (I am more thinking about some icloud sync misalignement of devices).

**Comment by knuckleheadsmiff** [comment]
You may be right. I’m not sure how to force an iCloud resync of the devices—or how the syncing even works. But thanks for looking into it.

**Comment by nicoduj** [comment]
Will close since I have created a new issue for this cases #167
