### ISSUE TITLE
A general "Mute"-Switch

### ISSUE THREAD

**Issue by Kohle81** [nicoduj/homebridge-harmony#166]
Hi nicoduj,

I like your plugin, it works fine and you do a great work!!!

Would it be possible to create a general "Mute"-Switch? If this switch is toggled on or off, the harmony hub should be "mute" the actual activity.

Use case:

If my phone @home is ringing, I could activate the "Mute"-Switch and the devices in the activity are muted.

I hope you understand me and sorry for bad English.

Greetings,

Manuel

**Comment by nicoduj** [comment]
Hi, thank you ! In a way you can I think already do that with multiple switches grouped in home app for each device that handle sound in your setup (probably tv and av-receiver),but I agree handling it in the plugin would be easier and your use case definitely worth it ! Just a question : do you intend to use shortcut to make the trigger (phone ringing ?) or any other means ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Kohle81** [comment]
I want to use my phone at home with using fritzbox router.

But the option with shortcuts would be nice, too; if it is possible.
