### ISSUE TITLE
Multi Hubs Not Loading

### ISSUE THREAD

**Issue by cmb991** [nicoduj/homebridge-harmony#170]
Running iOS 13 PB 6, Homebridge with the latest version and the latest plugin version.  One of the devices names won't load correctly and the input selections don't load correctly.  Screenshots below.

Config:
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:FF:3D:AA",
        "port": 51826,
        "pin": "031-45-154"
    },
    "description": "Homebridge setup.",
    "platforms": [
        {
            "platform": "HarmonyHubWebSocket",
            "cleanCache": true,
            "name": "Vizio",
            "hubIP": "192.168.1.13",
            "showTurnOffActivity": true,
            "refreshTimer": 30,
            "otherPlatforms": [{
              "name": "Vizio 2",
              "hubIP": "192.168.1.16",
              "showTurnOffActivity": true,
              "refreshTimer": 30
              }]
        },
        {
            "platform": "Nest",
            "clientId": "asdf-123",
            "clientSecret": "asdf123",
            "code": "asdf123",
            "token": "asdf123"
        }
                 ]
}
![image0](https://user-images.githubusercontent.com/30929454/63477236-4970c380-c452-11e9-824a-ca01ad6d8eff.png)
![Vizio-TV I guess](https://user-images.githubusercontent.com/30929454/63477226-31993f80-c452-11e9-901d-829f3a267091.png)
![Vizio 2-TV](https://user-images.githubusercontent.com/30929454/63477227-31993f80-c452-11e9-9930-983c7b4c1c45.png)

**Comment by nicoduj** [comment]
Hello,

First you can remove refeshtimer option.
Then, I think it is because of your cleanCache option, this option is not intended to stay . I suggest you stop homebridge, remove this option, and start again. 

If that does not work, you can also delete harmony files that are at the root directory of your homebridge folder and then restart.

If it does not work, you can Clean your cachedaccessories folder while homebridge is stopped (important). 

i am working on better cache handling (#167) but will take time .


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by cmb991** [comment]
Attached is the new pic and config file.  Same issue.  Deleted the files in the root dir too.
![New](https://user-images.githubusercontent.com/30929454/63490348-7b9a1980-c482-11e9-9c60-a3fc8686d637.png)

`    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
    "description": "Homebridge setup.",
    "platforms": [
        {
            "platform": "HarmonyHubWebSocket",
            "name": "Vizio",
            "hubIP": "192.168.1.13",
            "showTurnOffActivity": true,
            "otherPlatforms": [{
              "name": "Vizio 2",
              "hubIP": "192.168.1.16",
              "showTurnOffActivity": true
              }]
        }
                 ]
}


`

**Comment by cmb991** [comment]
Okay a slight update, I rebooted my Pi and now (same config as above), its showing both TVs but not showing the input select type menu for 
![image0 (1)](https://user-images.githubusercontent.com/30929454/63492272-27ddff00-c487-11e9-9e5d-2bfefdeee1ce.png)
![image1](https://user-images.githubusercontent.com/30929454/63492273-27ddff00-c487-11e9-8ad1-8f08df6972cf.png)

**Comment by nicoduj** [comment]
Sorry don’t understand the problem you still have , your screen shows input selection 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by cmb991** [comment]
There is two TVs listed in my config file.  Only one is showing it’s activities. Not the other.  
![DB9205B2-2DD5-4605-A9D1-980C0C303C96](https://user-images.githubusercontent.com/30929454/63514051-b36e8480-c4b5-11e9-9ef0-10310b4c4e42.png)
![53AE90F8-007E-4E4B-B861-9FD32030B5B8](https://user-images.githubusercontent.com/30929454/63514052-b36e8480-c4b5-11e9-890e-4c784219cab4.png)

**Comment by nicoduj** [comment]
Ok, the second tv has to be added manually like the readme says . Only the first one is added automatically

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nicoduj** [comment]
https://twitter.com/dujnic/status/1110644949027041282?s=21

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by cmb991** [comment]
We are now back to the Ghost device showing up, "VizioMasterBedroom".  I have deleted the cacheAccessories file too when homebridge was shut down.  
Config:
```

{
    "bridge": {
        "name": "Homebridge",
        "username": "AB:84:28:E3:CE:20",
        "port": 51826,
        "pin": "043-73-454"
    },
    "description": "Homebridge setup.",
    "platforms": [
        {
            "platform": "HarmonyHubWebSocket",
            "cleanCache": true,
            "name": "Vizio LR",
            "hubIP": "192.168.1.13",
            "showTurnOffActivity": false,
            "otherPlatforms": [{
              "name": "Vizio MB",
              "hubIP": "192.168.1.16",
              "showTurnOffActivity": false
              }]
        }
                 ]
}
```


![IMG_1121](https://user-images.githubusercontent.com/30929454/63531587-d1001600-c4d6-11e9-9240-4cd012d1692f.PNG)
![IMG_1122](https://user-images.githubusercontent.com/30929454/63531592-d4939d00-c4d6-11e9-99d0-c56dd9739cb9.PNG)
<img width="347" alt="Screen Shot 2019-08-22 at 12 18 28 PM" src="https://user-images.githubusercontent.com/30929454/63531683-0e64a380-c4d7-11e9-8ad1-b7dd6c0abde6.png">
<img width="510" alt="Screen Shot 2019-08-22 at 12 18 11 PM" src="https://user-images.githubusercontent.com/30929454/63531685-0e64a380-c4d7-11e9-8643-839db4f1ae53.png">

**Comment by nicoduj** [comment]
Hum, just thinking of something, maybe spaces in the Name is not a good idea !

(and Try to avoid             "cleanCache": true, at first, especially after a manual cleanUp)

**Comment by nicoduj** [comment]
(from the flow I see that you played again with names vizio 1 / Vizio 2, then Vizio LR Vizio MB ... difficult to follow ! 
Try the following sequence : 
- Update to latest version of the plugin I just released
- Stop homebridge
- Delete file cachedAccessories in accessories folder
- Delete files harmonyPluginNames_* and harmonyPluginVisibility_*
- Add cleanCache to True in config and set "name" property to something without any spaces.
- Launch Homebridge
- Add your second hub manually through home app
- Stop Homebridge
- Remove cleanCache option
- Start Again

**Comment by cmb991** [comment]
0|homebridge  | [2019-8-22 15:01:51] [VizioLR] DidFinishLaunching
0|homebridge  | [2019-8-22 15:01:51] [VizioLR] INFO - Loading activities...
0|homebridge  | [2019-8-22 15:01:51] [VizioLR] INFO - Loading activities...
0|homebridge  | [2019-8-22 15:01:51] Homebridge is running on port 51826.
0|homebridge  | [2019-8-22 15:01:52] [VizioLR] INFO - Adding Accessory : VizioMB-TV
0|homebridge  | [2019-8-22 15:01:52] [VizioLR] (VizioMB)INFO - configuring Main TV Service
0|homebridge  | [2019-8-22 15:01:52] [VizioLR] (VizioMB)INFO - Creating TV Service
0|homebridge  | [2019-8-22 15:01:52] [VizioLR] (VizioMB)INFO - Creating Input Service - Master Bedroom Apple TV
0|homebridge  | [2019-8-22 15:01:52] [VizioLR] (VizioMB)INFO - Creating Input Service - Master Bedroom TV
0|homebridge  | [2019-8-22 15:01:52] [VizioLR] (VizioMB)WARNING - No main Activity that match config file found, default to first one
0|homebridge  | [2019-8-22 15:01:52] [VizioLR] (VizioMB)INFO - Configuring Main Activity Master Bedroom Apple TV
0|homebridge  | [2019-8-22 15:01:52] [VizioLR] (VizioMB)INFO - Creating TV Speaker Service
0|homebridge  | [2019-8-22 15:01:52] [VizioLR] WARNING - setupFoundAccessories - TV accessory added in your bridge, if another plugin is exposing a TV accessory this one might not be visible in your remote widget
0|homebridge  | You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
0|homebridge  | Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 6a100135-c71c-4670-a31a-3d6f30581458
0|homebridge  |     at Bridge.Accessory.addBridgedAccessory (/home/pi/.nvm/versions/node/v9.11.1/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:268:13)
0|homebridge  |     at Bridge.Accessory.addBridgedAccessories (/home/pi/.nvm/versions/node/v9.11.1/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:299:10)
0|homebridge  |     at Server._handleRegisterPlatformAccessories (/home/pi/.nvm/versions/node/v9.11.1/lib/node_modules/homebridge/lib/server.js:490:16)
0|homebridge  |     at Server.<anonymous> (/home/pi/.nvm/versions/node/v9.11.1/lib/node_modules/homebridge/lib/server.js:41:10)
0|homebridge  |     at API.emit (events.js:180:13)
0|homebridge  |     at API.registerPlatformAccessories (/home/pi/.nvm/versions/node/v9.11.1/lib/node_modules/homebridge/lib/api.js:171:8)
0|homebridge  |     at HarmonyBase.addAccessories (/home/pi/.nvm/versions/node/v9.11.1/lib/node_modules/homebridge-harmony/harmonyBase.js:803:25)
0|homebridge  |     at HarmonyBase.setupFoundAccessories (/home/pi/.nvm/versions/node/v9.11.1/lib/node_modules/homebridge-harmony/harmonyBase.js:195:14)
0|homebridge  |     at HarmonySubPlatform.readAccessories (/home/pi/.nvm/versions/node/v9.11.1/lib/node_modules/homebridge-harmony/harmonySubPlatform.js:145:22)
0|homebridge  |     at getHomeControlsAccessories.then.responseHome (/home/pi/.nvm/versions/node/v9.11.1/lib/node_modules/homebridge-harmony/harmonyBase.js:140:27)
0|homebridge  |     at <anonymous>
0|homebridge  | [2019-8-22 15:01:52] [VizioLR] INFO - Adding Accessory : VizioLR-TV
0|homebridge  | [2019-8-22 15:01:52] [VizioLR] (VizioLR)INFO - configuring Main TV Service
0|homebridge  | [2019-8-22 15:01:52] [VizioLR] (VizioLR)INFO - Creating TV Service
0|homebridge  | [2019-8-22 15:01:52] [VizioLR] (VizioLR)INFO - Creating Input Service - Living Room TV
0|homebridge  | [2019-8-22 15:01:52] [VizioLR] (VizioLR)INFO - Creating Input Service - Living Room Apple TV
0|homebridge  | [2019-8-22 15:01:52] [VizioLR] (VizioLR)WARNING - No main Activity that match config file found, default to first one
0|homebridge  | [2019-8-22 15:01:52] [VizioLR] (VizioLR)INFO - Configuring Main Activity Living Room TV
0|homebridge  | [2019-8-22 15:01:52] [VizioLR] (VizioLR)INFO - Creating TV Speaker Service
0|homebridge  | [2019-8-22 15:01:52] [VizioLR] INFO - setupFoundAccessories - TV accessory added as external accessory
0|homebridge  | [2019-8-22 15:01:52] VizioLR-TV is running on port 46279.
0|homebridge  | [2019-8-22 15:01:52] Please add [VizioLR-TV] manually in Home app. Setup Code:

**Comment by nicoduj** [comment]
I fear external accessory is a problem there, try to delete files also in persist folder (but you will have to readd everything) . If you manage to start, you can try to delete the device from home app.

**Comment by cmb991** [comment]
Same error after deleting everything in persist folder, deleting the harmony file in the root folder and deleting the accessorycache

`0|homebridge  | [2019-8-22 15:15:18] [VizioLR] DidFinishLaunching
0|homebridge  | [2019-8-22 15:15:18] [VizioLR] INFO - Loading activities...
0|homebridge  | [2019-8-22 15:15:18] [VizioLR] INFO - Loading activities...
0|homebridge  | [2019-8-22 15:15:19] Homebridge is running on port 51826.
0|homebridge  | [2019-8-22 15:15:20] [VizioLR] INFO - Adding Accessory : VizioMB-TV
0|homebridge  | [2019-8-22 15:15:20] [VizioLR] (VizioMB)INFO - configuring Main TV Service
0|homebridge  | [2019-8-22 15:15:20] [VizioLR] (VizioMB)INFO - Creating TV Service
0|homebridge  | [2019-8-22 15:15:20] [VizioLR] (VizioMB)INFO - Creating Input Service - Master Bedroom Apple TV
0|homebridge  | [2019-8-22 15:15:20] [VizioLR] (VizioMB)INFO - Creating Input Service - Master Bedroom TV
0|homebridge  | [2019-8-22 15:15:20] [VizioLR] (VizioMB)WARNING - No main Activity that match config file found, default to first one
0|homebridge  | [2019-8-22 15:15:20] [VizioLR] (VizioMB)INFO - Configuring Main Activity Master Bedroom Apple TV
0|homebridge  | [2019-8-22 15:15:20] [VizioLR] (VizioMB)INFO - Creating TV Speaker Service
0|homebridge  | [2019-8-22 15:15:20] [VizioLR] WARNING - setupFoundAccessories - TV accessory added in your bridge, if another plugin is exposing a TV accessory this one might not be visible in your remote widget
0|homebridge  | You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
0|homebridge  | Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 6a100135-c71c-4670-a31a-3d6f30581458
0|homebridge  |     at Bridge.Accessory.addBridgedAccessory (/home/pi/.nvm/versions/node/v9.11.1/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:268:13)
0|homebridge  |     at Bridge.Accessory.addBridgedAccessories (/home/pi/.nvm/versions/node/v9.11.1/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:299:10)
0|homebridge  |     at Server._handleRegisterPlatformAccessories (/home/pi/.nvm/versions/node/v9.11.1/lib/node_modules/homebridge/lib/server.js:490:16)
0|homebridge  |     at Server.<anonymous> (/home/pi/.nvm/versions/node/v9.11.1/lib/node_modules/homebridge/lib/server.js:41:10)
0|homebridge  |     at API.emit (events.js:180:13)
0|homebridge  |     at API.registerPlatformAccessories (/home/pi/.nvm/versions/node/v9.11.1/lib/node_modules/homebridge/lib/api.js:171:8)
0|homebridge  |     at HarmonyBase.addAccessories (/home/pi/.nvm/versions/node/v9.11.1/lib/node_modules/homebridge-harmony/harmonyBase.js:803:25)
0|homebridge  |     at HarmonyBase.setupFoundAccessories (/home/pi/.nvm/versions/node/v9.11.1/lib/node_modules/homebridge-harmony/harmonyBase.js:195:14)
0|homebridge  |     at HarmonySubPlatform.readAccessories (/home/pi/.nvm/versions/node/v9.11.1/lib/node_modules/homebridge-harmony/harmonySubPlatform.js:145:22)
0|homebridge  |     at getHomeControlsAccessories.then.responseHome (/home/pi/.nvm/versions/node/v9.11.1/lib/node_modules/homebridge-harmony/harmonyBase.js:140:27)
0|homebridge  |     at <anonymous>
0|homebridge  | [2019-8-22 15:15:20] [VizioLR] INFO - Adding Accessory : VizioLR-TV
0|homebridge  | [2019-8-22 15:15:20] [VizioLR] (VizioLR)INFO - configuring Main TV Service
0|homebridge  | [2019-8-22 15:15:20] [VizioLR] (VizioLR)INFO - Creating TV Service
0|homebridge  | [2019-8-22 15:15:20] [VizioLR] (VizioLR)INFO - Creating Input Service - Living Room TV
0|homebridge  | [2019-8-22 15:15:20] [VizioLR] (VizioLR)INFO - Creating Input Service - Living Room Apple TV
0|homebridge  | [2019-8-22 15:15:20] [VizioLR] (VizioLR)WARNING - No main Activity that match config file found, default to first one
0|homebridge  | [2019-8-22 15:15:20] [VizioLR] (VizioLR)INFO - Configuring Main Activity Living Room TV
0|homebridge  | [2019-8-22 15:15:20] [VizioLR] (VizioLR)INFO - Creating TV Speaker Service
0|homebridge  | [2019-8-22 15:15:20] [VizioLR] INFO - setupFoundAccessories - TV accessory added as external accessory
0|homebridge  | [2019-8-22 15:15:20] VizioLR-TV is running on port 40139.
0|homebridge  | [2019-8-22 15:15:20] Please add [VizioLR-TV] manually in Home app. Setup Code:`

**Comment by cmb991** [comment]
Heres from the update:
pi@homebridge:~/.homebridge $ npm install -g -unsafe-perm homebridge-harmony@latest -g
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/homebridge-harmony/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})

+ homebridge-harmony@1.0.6
updated 1 package in 71.761s

**Comment by nicoduj** [comment]
fsevents is not a problem at all .
You can try what worked for others : https://github.com/nicoduj/homebridge-harmony/issues/171#issuecomment-524040765

**Comment by cmb991** [comment]
Doing that worked one time.  Then I had to stop it and add nest back to my config to generate my 2fa pin for it.  The error came back as soon as I started it up again.  I tried deleting the same files and out of homebridge, but its just continuing to come up.

**Comment by nicoduj** [comment]
How is cleanCache option set up in your config ?

**Comment by cmb991** [comment]
{
            "platform": "HarmonyHubWebSocket",
            "cleanCache": true,
            "name": "VizioLR",
            "hubIP": "192.168.1.13",
            "showTurnOffActivity": false,
            "otherPlatforms": [{
              "name": "VizioMB",
              "hubIP": "192.168.1.16",
              "showTurnOffActivity": false
              }]
        },

**Comment by nicoduj** [comment]
Ther ewas a problem in 1.0.5 / 1.0.6 . Please try again in 1.0.7, from a fresh start . You can follow those steps I think :  https://github.com/nicoduj/homebridge-harmony/issues/171#issuecomment-524040765

**Comment by cmb991** [comment]
Works now, thanks!
