### ISSUE TITLE
[BUG] Error: Cannot add a bridged Accessory 

### ISSUE THREAD

**Issue by Phoenix-DH** [nicoduj/homebridge-harmony#171]
Hey and goog morning,

I now tried again to update to V 1.0.
The good thing is that the bridge is running, but not with all features, the switches are missing.
My config is:
```
        {
            "platform": "HarmonyHubWebSocket",
            "name": "Media",
            "hubIP": "192.168.XXX.XXX",
            "TVPlatformMode": true,
            "mainActivity": "Apple TV",
            "switchAccessories": true,
            "showTurnOffActivity": "inverted",
            "devicesToPublishAsAccessoriesSwitch": [
                "Beleuchtung TV;PowerOn",
                "Beleuchtung TV;PowerOff",
                "Yamaha AVR;VolumeUp",
                "Yamaha AVR;VolumeDown",
                "Beleuchtung Theke;PowerToggle"
            ],
            "numberOfCommandsSentForVolumeControl": 4,
            "cleancache": false
        },
```

In addition I saw those errors in the log:
```
[2019-8-22 07:52:46] [Media] INFO - Adding Accessory : Media-TV
[2019-8-22 07:52:46] [Media] (Media)INFO - configuring Main TV Service
[2019-8-22 07:52:46] [Media] (Media)INFO - Creating TV Service
[2019-8-22 07:52:46] [Media] (Media)INFO - Creating Input Service - TV
[2019-8-22 07:52:46] [Media] (Media)INFO - Creating Input Service - Radio
[2019-8-22 07:52:46] [Media] (Media)INFO - Creating Input Service - Fire TV
[2019-8-22 07:52:46] [Media] (Media)INFO - Creating Input Service - Airplay
[2019-8-22 07:52:46] [Media] (Media)INFO - Configuring Main Activity Apple TV
[2019-8-22 07:52:46] [Media] (Media)INFO - Creating TV Speaker Service
[2019-8-22 07:52:46] [Media] (Media)INFO - Creating Input Service - Apple TV
[2019-8-22 07:52:46] [Media] (Media)INFO - Creating Input Service - Webradio
[2019-8-22 07:52:46] [Media] INFO - Adding Accessory : Media-TV
[2019-8-22 07:52:46] [Media] (Media)INFO - Discovered Activity : TV
[2019-8-22 07:52:46] [Media] INFO - Creating Switch Service TV/TV
[2019-8-22 07:52:46] [Media] INFO - Adding Accessory : Media-PowerOff
[2019-8-22 07:52:46] [Media] (Media)INFO - Discovered Activity : PowerOff
[2019-8-22 07:52:46] [Media] INFO - Creating Switch Service PowerOff/PowerOff
[2019-8-22 07:52:46] [Media] INFO - Adding Accessory : Media-Radio
[2019-8-22 07:52:46] [Media] (Media)INFO - Discovered Activity : Radio
[2019-8-22 07:52:46] [Media] INFO - Creating Switch Service Radio/Radio
[2019-8-22 07:52:46] [Media] INFO - Adding Accessory : Media-Fire TV
[2019-8-22 07:52:46] [Media] (Media)INFO - Discovered Activity : Fire TV
[2019-8-22 07:52:46] [Media] INFO - Creating Switch Service Fire TV/Fire TV
[2019-8-22 07:52:46] [Media] INFO - Adding Accessory : Media-Airplay
[2019-8-22 07:52:46] [Media] (Media)INFO - Discovered Activity : Airplay
[2019-8-22 07:52:46] [Media] INFO - Creating Switch Service Airplay/Airplay
[2019-8-22 07:52:46] [Media] INFO - Adding Accessory : Media-Apple TV
[2019-8-22 07:52:46] [Media] (Media)INFO - Discovered Activity : Apple TV
[2019-8-22 07:52:46] [Media] INFO - Creating Switch Service Apple TV/Apple TV
[2019-8-22 07:52:46] [Media] INFO - Adding Accessory : Media-Webradio
[2019-8-22 07:52:46] [Media] (Media)INFO - Discovered Activity : Webradio
[2019-8-22 07:52:46] [Media] INFO - Creating Switch Service Webradio/Webradio
[2019-8-22 07:52:46] [Media] WARNING - setupFoundAccessories - TV accessory added in your bridge, if another plugin is exposing a TV accessory this one might not be visible in your remote widget
(node:32148) UnhandledPromiseRejectionWarning: Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 487d4f8b-5b8d-46d0-b579-9f76a783e239
    at Bridge.Accessory.addBridgedAccessory (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:268:13)
    at Bridge.Accessory.addBridgedAccessories (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:299:10)
    at Server._handleRegisterPlatformAccessories (/usr/lib/node_modules/homebridge/lib/server.js:490:16)
    at Server.<anonymous> (/usr/lib/node_modules/homebridge/lib/server.js:41:10)
    at API.emit (events.js:193:13)
    at API.registerPlatformAccessories (/usr/lib/node_modules/homebridge/lib/api.js:171:8)
    at HarmonyBase.addAccessories (/usr/lib/node_modules/homebridge-harmony/harmonyBase.js:803:25)
    at HarmonyBase.setupFoundAccessories (/usr/lib/node_modules/homebridge-harmony/harmonyBase.js:195:14)
    at HarmonySubPlatform.readAccessories (/usr/lib/node_modules/homebridge-harmony/harmonySubPlatform.js:145:22)
    at getHomeControlsAccessories.then.responseHome (/usr/lib/node_modules/homebridge-harmony/harmonyBase.js:140:27)
    at runNextTicks (internal/process/task_queues.js:52:5)
    at processImmediate (internal/timers.js:416:9)
(node:32148) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:32148) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I already stopped the bridge, cleaned up the cachedAccessories, restarted, but still the same ...

**Comment by Phoenix-DH** [comment]
Argh ... no luck again.... tried a reboot of my PI.... Homebridge won't come up again, exactly the same behaviour than last time....

I only saw in the "service homebridge status" the follwoing:
```
Aug 22 08:16:42 phoenixpi homebridge[8372]:     at Module._compile (internal/modules/cjs/loader.js:816:30)
Aug 22 08:16:42 phoenixpi homebridge[8372]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
Aug 22 08:16:42 phoenixpi homebridge[8372]:     at Module.load (internal/modules/cjs/loader.js:685:32)
Aug 22 08:16:42 phoenixpi homebridge[8372]:     at Function.Module._load (internal/modules/cjs/loader.js:620:12)
Aug 22 08:16:42 phoenixpi homebridge[8372]:     at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
Aug 22 08:16:42 phoenixpi homebridge[8372]:     at internal/main/run_main_module.js:21:11
```

How can I see the whole log?

**Comment by nicoduj** [comment]
Hi, did you launched multiple times after migration ? (Or with the old config) ? You can try cleanCache to true (with a C and not c , and don’t forget to put it back to false). Otherwise try step by step and first remove the devicesToPublishAsAccessoriesSwitch option 


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Phoenix-DH** [comment]
I first have to install backup again, then I can try.
I first changed the config to the latest version, but I think with a small c ...
Then I installed the update.
Then stopped the homebridge, started again, removed the cleanCache and stop/start again, all fine ... but no accessoeries.
Then I decided to reboot and then the bridge crashed.

Exactly like the last time.
Without the latest version of this plugin, all is fine, also reboot etc. ...

**Comment by nicoduj** [comment]
If your backup contains old cached / tries with beta version it might be a problem . 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Phoenix-DH** [comment]
I created the backup yesterday evening, because I got the fear that something would get wrong.
You mean I shopuld install the beta version of the plugin?

Or what do you mean with old data?

**Comment by nicoduj** [comment]
Did you try beta version before doing the backup ? What are you restoring at all ? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Phoenix-DH** [comment]
No, i never used the beta version.
Without having an update I used the following config:
```
        {
            "platform": "HarmonyHubWebSocket",
            "name": "HarmonyHub",
            "hubIP": "192.168.XXX.XXX",
            "showTurnOffActivity": "inverted",
            "devicesToPublishAsAccessoriesSwitch": [
                "Beleuchtung TV;PowerOn",
                "Beleuchtung TV;PowerOff",
                "Yamaha AVR;VolumeUp",
                "Yamaha AVR;VolumeDown",
                "Beleuchtung Theke;PowerToggle"
            ]
        },
        {
            "platform": "HarmonyHubWebSocket",
            "name": "Media",
            "hubIP": "192.168.XXX.XXX",
            "TVPlatformMode": true,
            "mainActivity": "Apple TV",
            "numberOfCommandsSentForVolumeControl": 4
        },
```

My backup includes the whole SD card, an image ...
I now restored it and removed the cachedAccessories in front... some of them reappeared now with other names.

Strange thing is, that all is working, okay, the accessoeries are missing, but homebridge will come up without problems.

**Comment by nicoduj** [comment]
Just to better understand : which switch are not there ? Activities or device ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Phoenix-DH** [comment]
The activieties are not there after the Update to 1.0.4 with this config, which replaces in the version 0.7 the other both:
```
        {
            "platform": "HarmonyHubWebSocket",
            "name": "Media",
            "hubIP": "192.168.XXX.XXX",
            "TVPlatformMode": true,
            "mainActivity": "Apple TV",
            "switchAccessories": true,
            "showTurnOffActivity": "inverted",
            "devicesToPublishAsAccessoriesSwitch": [
                "Beleuchtung TV;PowerOn",
                "Beleuchtung TV;PowerOff",
                "Yamaha AVR;VolumeUp",
                "Yamaha AVR;VolumeDown",
                "Beleuchtung Theke;PowerToggle"
            ],
            "numberOfCommandsSentForVolumeControl": 4,
            "cleancache": false
        },
```

What is missing is:
```
            "switchAccessories": true,
            "showTurnOffActivity": "inverted",
            "devicesToPublishAsAccessoriesSwitch": 
```

Means only the "TV" is shown ...

**Comment by nicoduj** [comment]
Don’t understand especially since your log shows the activities switch and turn off switch ... are you sure they are not in another room ? Can you check the hub devices in home app (or in eve app for example)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Phoenix-DH** [comment]
I haven't found them .... Will create a new backup with an additional test sd-card and try again ...

But my way on how to update is correct or?
Channge config ...
Update ...
Restart ...

**Comment by nicoduj** [comment]
As I said changing config after a first start might mess up things . Try while you do that to keep option cleanCache until it is ok.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Phoenix-DH** [comment]
I got no change at all ... after reboot I will always getting this error:
```
Aug 22 13:34:11 phoenixpi homebridge[23601]:     at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:93:8)
Aug 22 13:34:11 phoenixpi homebridge[23601]:     at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:59:10)
Aug 22 13:34:11 phoenixpi homebridge[23601]:     at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
Aug 22 13:34:11 phoenixpi homebridge[23601]:     at Module._compile (internal/modules/cjs/loader.js:816:30)
Aug 22 13:34:11 phoenixpi homebridge[23601]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
Aug 22 13:34:11 phoenixpi homebridge[23601]:     at Module.load (internal/modules/cjs/loader.js:685:32)
Aug 22 13:34:11 phoenixpi homebridge[23601]:     at Function.Module._load (internal/modules/cjs/loader.js:620:12)
Aug 22 13:34:11 phoenixpi homebridge[23601]:     at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
Aug 22 13:34:11 phoenixpi homebridge[23601]:     at internal/main/run_main_module.js:21:11
```

Without updating this package I will have no trouble ...

And I chage the config to the Version for V 1.0.4 before I did the update.
Update made, twice a rrestart, homebridge broken ...

Also removing the plugin and removing the config for it will not fix the bridge ....

**Comment by nicoduj** [comment]
Stay on 0.7 so, I really don’t know what to do since your log is incomplete and seems linked to the fact that 2 accessories have the same Id

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Phoenix-DH** [comment]
I will keep on fighting ...
You do a great job .... I love this plugin so much ....

Got different scenarios in my mind ...

**Comment by nicoduj** [comment]
Maybe check your node / npm / homebridge version ... and try maybe without other plugins (or tell me which you are using) there might be a conflict .... if you could recap a situation since I lost trail : config/ config of your hub / what is missing after a fresh install (don’t play with cleancache )

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Phoenix-DH** [comment]
Actually I updated all except the node version.
Here I am on 11.15.0

Do you know which is the latest supported one from homebridge?

**Comment by nicoduj** [comment]
No, I don’t check on homebridge github page :) your behavior is strange, I really think that there is something in your config that does a conflict. Having full config (without password) temp files and full log in debug might help 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Phoenix-DH** [comment]
Will first give it an additional try after updating everything ...
Then keep cleanCache out of the config.
And I know now how to see the homebridge logs during start when the crash will appear.
Then I hopefully can see the needed lines...

For today I am through ...

**Comment by nicoduj** [comment]
Hi have pushed an update that might help, by reviewing cleancache option behavior. Hope it will fix !

**Comment by Nastras** [comment]
Hello @nicoduj I have updated from version 1.0.4 to version 1.0.5 now I also have this bug.

[Untitled.txt](https://github.com/nicoduj/homebridge-harmony/files/3531468/Untitled.txt)

**Comment by Nastras** [comment]
i'm now back to 1.0.4 the bug is still present. I don't suspect anything good.
![49706AE2-8A67-496A-AC36-B094E897B430](https://user-images.githubusercontent.com/27686185/63541244-febc7d80-c51d-11e9-8e8e-b136045278d2.jpeg)

**Comment by Nastras** [comment]
I have now reinstalled v1.0.5 and deleted homebridge-harmony from homekit. Accessories and Persist deleted now it works again.

**Comment by nicoduj** [comment]
Hi @Nastras . Just for me to know, are you on ios13 ? Still some issues with cache i fear :(

**Comment by Phoenix-DH** [comment]
What have dou exactly made?
With the status of a crashed bridge deleted the accessories and persist folder?
Thst means you have to readd everything to home

**Comment by Nastras** [comment]
No I am still at iOS 12 with all devices.

**Comment by Phoenix-DH** [comment]
... and what did you mean with 

deleted homebridge-harmony from homekit

Deleted the config or the devices out of the home app?

**Comment by Nastras** [comment]
Step 1 - delete the harmony device from hk
Step 2 - stop hb and delete the folder accesories and persist 
Step 3 - restart hb
Step 4 - connect hb again

Attention if you don't use instances of hb all devices are deleted after that.

**Comment by Phoenix-DH** [comment]
Damn ... I don‘t use instances ... have all in one ...
But thank you.

**Comment by Nastras** [comment]
I have updated to V 1.0.6 and the error occurs again

![3C25CA5F-3197-4CDE-A715-C8915EE7DE52](https://user-images.githubusercontent.com/27686185/63562035-698ca980-c55c-11e9-914b-34c2df624077.jpeg)

**Comment by nicoduj** [comment]
Hi, is this issu ok for everyone in 1.0.7 ?

**Comment by Phoenix-DH** [comment]
Had no chance to try until now.

**Comment by Nastras** [comment]
Everything is fine again! Thank you!

**Comment by Phoenix-DH** [comment]
I tried it now again....
Still the same... from homebridge log:
```
[2019-9-9 19:29:58] [Media] WARNING - setupFoundAccessories - TV accessory added in your bridge, if another plugin is exposing a TV accessory this one might not be visible in your remote widget
(node:342) UnhandledPromiseRejectionWarning: Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 487d4f8b-5b8d-46d0-b579-9f76a783e239
    at Bridge.Accessory.addBridgedAccessory (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:268:13)
    at Bridge.Accessory.addBridgedAccessories (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:299:10)
    at Server._handleRegisterPlatformAccessories (/usr/lib/node_modules/homebridge/lib/server.js:490:16)
    at Server.<anonymous> (/usr/lib/node_modules/homebridge/lib/server.js:41:10)
    at API.emit (events.js:193:13)
    at API.registerPlatformAccessories (/usr/lib/node_modules/homebridge/lib/api.js:171:8)
    at HarmonyBase.addAccessories (/usr/lib/node_modules/homebridge-harmony/harmonyBase.js:942:25)
    at HarmonyBase.setupFoundAccessories (/usr/lib/node_modules/homebridge-harmony/harmonyBase.js:195:14)
    at HarmonySubPlatform.readAccessories (/usr/lib/node_modules/homebridge-harmony/harmonySubPlatform.js:152:22)
    at getHomeControlsAccessories.then.responseHome (/usr/lib/node_modules/homebridge-harmony/harmonyBase.js:140:27)
(node:342) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:342) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

What I now figured out, is that when I manually clean up the cachedAccessories file there are always generated 2 entries ... also after reboot etc....

For me it seems that my old config files are used ..... But the config.json is actual ...

Still no clue .... Damn, thought now to be able to use the latest version, will not loose any further upgrades ...

**Comment by nicoduj** [comment]
Hi , did you delete files while homebridge was stopped ? It recreates it at shutdown

**Comment by Phoenix-DH** [comment]
Hi, yes I copied the files to my desk, changed them and copied them back when bridge was stopped.

Can imagine than deleting the things in cachedAccessories manuallynis the same than using the cleanCache switch?

**Comment by nicoduj** [comment]
Are you sure you have deleted everything properly ? Can be tricky I think :( there are also references in persist folder that might be your issue. I fear that the safest way to do so is to remove everything

**Comment by Phoenix-DH** [comment]
I don‘t know ... I only know about the cachedAccessories file.... 
In the persist folder I only had a quick look and saw no real hint...

Removing everything is no possibility ...

I will try an additional instance instead.

**Comment by Phoenix-DH** [comment]
... and thisnis why I asked if this is the same like the cleanCache ... Because this really seems to be the problem in my case.

**Comment by nicoduj** [comment]
You Can try cleancache but I fear that since you tried a lot there is something messed up . Will check if I can do some modification in the code to better handle your problem, meanwhile you can also send me your cached / persist folder so that I can « check » .


Nicolas

**Comment by Phoenix-DH** [comment]
Tried a lot in the past ...

But I always restored last working version via backup.
But that would be great.
To which adress should I send the content?
Can took 1-2 days ...

**Comment by nicoduj** [comment]
Email on my github profile. The thing is I think you have something in your backup ... maybe in persist folder that was there, deleted on the new version is trying to add it again . The problème is to understand which one!

**Comment by Phoenix-DH** [comment]
Hey again,

I tried now the following:
Removed the config for harmony
Restarted the homebridge
Updated the plugin

But now in the logs I see:
[2019-9-26 11:07:46] [homebridge-harmonyHub.HarmonyHubWebSocket] WARNING - configureAccessory - The platform Media is not there anymore in your config (name property). It won't be loaded and will be removed from cache.

And the device is still visible in the home app.

**Comment by Phoenix-DH** [comment]
I saw that the last ID the device had was the following: 487d4f8b-5b8d-46d0-b579-9f76a783e239

If I check my IdentifierCache.CC223DE3CE30.json file, which is the one from homebridge, I can still find this ID inside, but I do not know how to edit this file ....

Can you maybe help me out if you know how? Thank you.

I sent you the file via mail!

Many thanks!
