### ISSUE TITLE
[BUG] Some activity switches are disappearing after restart 

### ISSUE THREAD

**Issue by genfersee** [nicoduj/homebridge-harmony#173]
Dear team,

I think I have a very common issue. After installing the plugin and have it configured successfully (it is working great!), after some reboots and update to the very latest version 1.0.6, I got some of my activity switches which disapeared.
When checking the homebridge startup logs, we can see the following error:
`[2019-8-22 21:41:34] [Bern] WARNING - setupFoundAccessories - TV accessory added in your bridge, if another plugin is exposing a TV accessory this one might not be visible in your remote widget
(node:903) UnhandledPromiseRejectionWarning: Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 0eb76f2e-af46-4b62-b171-3ab1db69bf09
    at Bridge.Accessory.addBridgedAccessory (/usr/lib/node_modules/hap-nodejs/lib/Accessory.js:268:13)
    at Bridge.Accessory.addBridgedAccessories (/usr/lib/node_modules/hap-nodejs/lib/Accessory.js:299:10)
    at Server._handleRegisterPlatformAccessories (/usr/lib/node_modules/homebridge/lib/server.js:490:16)
    at Server.<anonymous> (/usr/lib/node_modules/homebridge/lib/server.js:41:10)
    at emitOne (events.js:116:13)
    at API.emit (events.js:211:7)
    at API.registerPlatformAccessories (/usr/lib/node_modules/homebridge/lib/api.js:171:8)
    at HarmonyBase.addAccessories (/home/pi/.npm-global/lib/node_modules/homebridge-harmony/harmonyBase.js:803:25)
    at HarmonyBase.setupFoundAccessories (/home/pi/.npm-global/lib/node_modules/homebridge-harmony/harmonyBase.js:195:14)
    at HarmonySubPlatform.readAccessories (/home/pi/.npm-global/lib/node_modules/homebridge-harmony/harmonySubPlatform.js:145:22)
    at getHomeControlsAccessories.then.responseHome (/home/pi/.npm-global/lib/node_modules/homebridge-harmony/harmonyBase.js:140:27)
    at <anonymous>
(node:903) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:903) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

If I delete the cachedAccessories file within homebridge accessories folder, and restart homebridge, situation gets cleaned... until next time I reboot or relaunch homebridge.

Is there some cache or something I should clean more?

Many thanks in advance!
Genfersee

My config is:
`		{
		"platform": "HarmonyHubWebSocket",
		"name": "Bern",
		"hubIP": "192.168.xx.yy",
		"switchAccessories" : true
		},`

**Comment by genfersee** [comment]
Some more info...
I have 2 hubs in my Harmony account, but only 1 is declared in homebridge config.json
I have installed plugin version 1.0.6

**Comment by pponce** [comment]
I'm also seeing this behavior.
Some activities are disappearing. I had 3 activities missing.
Restarted homebridge  and two of them came back. Restarted again and one of the ones that came back disappeared again.
At the moment i'm missing 2 of my 5 activities as switches.  
The activities do appear in the settings list for the tv platform though.
I'm running 1.0.6 and only have one harmony hub.

**Comment by genfersee** [comment]
I unsintalled the plugin 1.0.6, reinstalled the version 1.0.4
Removed Homebridge bridge from Home app, deleted persist and accessories folders, emptied the trash, launched Homebridge with cleanCache option set to true in the plugin, killed homebridge, rebooted the PI, readded the Homebridge bridge in Home app, and now it looks ok again.

**Comment by pponce** [comment]
Here was my process to get back to a working config. I didn't have to remove homebridge from the home app or mess with the persist and accessories folders.

While on 1.0.6 i ran it with the "cleanCache": true, option.
Ran homebridge a couple of times for good measure (stopped and started homebridge a couple of times). 
I then uninstalled 1.0.6 and the installed 1.0.4.

npm uninstall -g homebridge-harmony
npm install -g homebridge-harmony@1.0.4

I ran homebridge one time with the cleanCache option set to true under 1.0.4 (probably overkill).
Then I stopped homebridge and set the cleanCache option to false in the config.
Restarted homebridge.

All my activities were back as switches.

**Comment by vzlgdu** [comment]
Hi all. Only to recap:
I'm with version 1.0.4 and I would upgrade to 1.0.7.
1 -  can I upgrade directly from config ui-x?
2 - should I use before the "cleancache" parameter?
3 - should I uninstall and after install the new version to avoid all errors?
Following my config:

        {
            "platform": "HarmonyHubWebSocket",
            "name": "HarmonyHub",
            "hubIP": "x.x.x.x",
            "TVAccessory": true,
            "switchAccessories": true
        },

Thanks

PS: I would absolutely avoid to delete persist/accessory folder!!!!

**Comment by nicoduj** [comment]
@sherazan hi, if you don’t have any problem with 1.0.4 you can just update through config ui-x . 1.0.7 seems fine from user feedback I have 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by vzlgdu** [comment]
Done! No problem after restart! Thanks!
