### ISSUE TITLE
[BUG] TV Mode not working with latest update 

### ISSUE THREAD

**Issue by guysbrown** [nicoduj/homebridge-harmony#174]
Hey,

The latest update broke the TV Accessory for me. It now shows without any Inputs and each activity (input) is show as a separate tile in the home app. None of them do anything when tapped. 

See attached image. 

![3589849F-6DDC-40AD-88D7-84564543D9AB](https://user-images.githubusercontent.com/46329244/63548003-42ff4c00-c525-11e9-8478-0541840369fb.jpeg)

I tried the clean cache option but it didn’t do anything. 

Here my config

{
            "platform": "HarmonyHubWebSocket",
            "name": "TV",
            "hubIP": "192.168.1.xx",
            "TVAccessory": true,
            "mainActivity": "Apple TV"
        }

Best Regards 

Guy

**Comment by Krocko** [comment]
Same for me.
All was working with v.1.0.4
Updated to v.1.0.5 and the error occurred.

Edit: Updated to v.1.0.6 --> Problem solved

Edit2: With v.1.0.6 I have the problem from #175. I am back to v.1.0.4 for now.
