### ISSUE TITLE
[BUG] TV mode: inputs button not showing when TV accessory is off

### ISSUE THREAD

**Issue by genfersee** [nicoduj/homebridge-harmony#177]
Hello!

I have just configured by TV accessory by enabling "TVPlatformMode" option.
When the TV accessory is ON, I can indeed select an input via the inputs button which is shown on screen.

But when the TV accessory is OFF, the inputs button does not show like on this example:
[https://9to5mac.com/wp-content/uploads/sites/6/2019/01/HomeKit-TV-4.png](url)

Is it a bug, misconfiguration on my side, or simply not yet implemented in the plugin?

Kind regards,
Genfersee

**Comment by nicoduj** [comment]
Hi,

It was changed in iOS 12.3 or 12.4 as far as I remember, maybe back In iOS 13 . Not on the plugin side , however automations can still power on a specified input .

Nicolas

**Comment by genfersee** [comment]
Many thanks Nicolas,

Waiting for the option to get back in next iOS release then.

Kind regards,
Genfersee
