### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by vzlgdu** [nicoduj/homebridge-harmony#179]
Hi, after a restart, I've the following errors.
Homebridge 0.4.50
Homebridge Harmony 1.0.6

ago 23 15:32:03 homebridgea homebridge[16617]: [2019-8-23 3:32:03 PM] [HarmonyHub] WARNING - setupFoundAccessories - TV accessory added in your bridge, if another plugin is exposing a TV accessory this one might not be visible in your remote widget
ago 23 15:32:03 homebridgea homebridge[16617]: (node:16617) UnhandledPromiseRejectionWarning: Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 51121c49-184f-45eb-b5c1-7a0d878e7b2f
ago 23 15:32:03 homebridgea homebridge[16617]:     at Bridge.Accessory.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:268:13)
ago 23 15:32:03 homebridgea homebridge[16617]:     at Bridge.Accessory.addBridgedAccessories (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:299:10)
ago 23 15:32:03 homebridgea homebridge[16617]:     at Server._handleRegisterPlatformAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:490:16)
ago 23 15:32:03 homebridgea homebridge[16617]:     at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:41:10)
ago 23 15:32:03 homebridgea homebridge[16617]:     at API.emit (events.js:198:13)
ago 23 15:32:03 homebridgea homebridge[16617]:     at API.registerPlatformAccessories (/usr/local/lib/node_modules/homebridge/lib/api.js:171:8)
ago 23 15:32:03 homebridgea homebridge[16617]:     at HarmonyBase.addAccessories (/usr/local/lib/node_modules/homebridge-harmony/harmonyBase.js:803:25)
ago 23 15:32:03 homebridgea homebridge[16617]:     at HarmonyBase.setupFoundAccessories (/usr/local/lib/node_modules/homebridge-harmony/harmonyBase.js:195:14)
ago 23 15:32:03 homebridgea homebridge[16617]:     at HarmonySubPlatform.readAccessories (/usr/local/lib/node_modules/homebridge-harmony/harmonySubPlatform.js:145:22)
ago 23 15:32:03 homebridgea homebridge[16617]:     at getHomeControlsAccessories.then.responseHome (/usr/local/lib/node_modules/homebridge-harmony/harmonyBase.js:140:27)
ago 23 15:32:03 homebridgea homebridge[16617]: (node:16617) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
ago 23 15:32:03 homebridgea homebridge[16617]: (node:16617) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Do you have suggest?
Thanks
Guido

**Comment by nicoduj** [comment]
Known bug, please stay on 1.0.4

Nicolas

**Comment by vzlgdu** [comment]
Ok, thanks for your feedback. How can I download previous version?

Thanks




> Il giorno 23 ago 2019, alle ore 16:45, Nicolas Dujardin <notifications@github.com> ha scritto:
> 
> Known bug, please stay on 1.0.4
> 
> Nicolas
>

**Comment by nicoduj** [comment]
I have published a 1.0.7 that should work as 1.0.4

**Comment by Acemach1ne** [comment]
Same to me after updating to 1.0.7. I cleaned the accessories cache but it doesnt help.

**Comment by nicoduj** [comment]
follow those steps, https://github.com/nicoduj/homebridge-harmony/issues/171#issuecomment-524040765
or 
https://github.com/nicoduj/homebridge-harmony/issues/173#issuecomment-524360232

**Comment by Acemach1ne** [comment]
> follow those steps, [#171 (comment)](https://github.com/nicoduj/homebridge-harmony/issues/171#issuecomment-524040765)
> or
> [#173 (comment)](https://github.com/nicoduj/homebridge-harmony/issues/173#issuecomment-524360232)

My problem is solved.
I had a accessory named "TV" and it only happens with "TV". In older versions that wasn't necessary.

**Comment by nicoduj** [comment]
Thanks for feedback . Indeed there was no cache mechanism in older version. Introducing cache prevents loosing accessories if homebridge starts with a hub that is not reachable but it is a bit more complicated to handle config changes
