### ISSUE TITLE
Multiple Hubs

### ISSUE THREAD

**Issue by adavison007** [nicoduj/homebridge-harmony#180]
**Describe the bug**
Multiple hubs does not work using this template...

"platforms": [
  {
    "platform": "HarmonyHubWebSocket",
    "name": "HubName",
    "hubIP": "192.168.1.XX",
    "otherPlatforms": [{
      "name": "OtherHubName",
      "hubIP": "192.168.1.YY"
      }]
  }
]

**To Reproduce**
Use the template

**Expected behavior**
Two hubs in homekit... you see two hubs in the Homebridge UI, but not in home kit....

**Screenshots**
None

**IOS (please complete the following information):**
Latest

**Logs**
None

**Config**

**Additional context**
Using this config in the JSON works...

        {
            "platform": "HarmonyHubWebSocket",
            "name": "Harmony-Lounge",
            "hubIP": "10.173.45.XX",
            "mainActivity": "Lounge Sky TV"
        },
        {
            "platform": "HarmonyHubWebSocket",
            "name": "Harmony-Kitchen",
            "hubIP": "10.173.45.XX",
            "mainActivity": "Kitchen SKy TV"
        },

**Comment by nicoduj** [comment]
Hi,

you have to add the second one manuallay in home app, as explained in the log and README, since second one will be necessary exposed as an external accessory . (It is in order to make both available in remote app in control center)
https://twitter.com/dujnic/status/1110644949027041282?s=21.

**Comment by adavison007** [comment]
> Hi,
> 
> you have to add the second one manuallay in home app, as explained in the log and README, since second one will be necessary exposed as an external accessory . (It is in order to make both available in remote app in control center)
> https://twitter.com/dujnic/status/1110644949027041282?s=21.

@nicoduj Thanks, OK, so I deleted the plugin in and code, cleaned the cache, reinstalled the plugin and then entered the below config... the first HUB and TV appear fine.... when I go to "Add Accessory" nothing appears to add (I'm trying to add a 2nd Harmony Hub and TV), can you let me know what I have done wrong?

        {
            "platform": "HarmonyHubWebSocket",
            "name": "Harmony-Kitchen",
            "hubIP": "10.173.45.17",
            "mainActivity": "Kitchen Sky TV",
            "TVAccessory": true,
            "publishAllTVAsExternalAccessory": true
        },

I'm confused by the fact you show code for two hubs, but you say don't use that code?

**Comment by adavison007** [comment]
OK, worked it out... so you do use the two hub code, then add manually.. simple.... the instructions were a little confusing.... but thanks for the support, love the app.

Code I used 

        {
            "platform": "HarmonyHubWebSocket",
            "name": "Harmony-Kitchen",
            "hubIP": "10.173.XX.XX",
            "mainActivity": "Kitchen Sky TV",
            "otherPlatforms": [
                {
                    "name": "Harmony-Lounge",
                    "hubIP": "10.173.XX.XX",
                    "mainActivity": "Lounge Sky TV"
                }
            ]
        },

**Comment by nicoduj** [comment]
Feel free to make a pull request on the readme if you think you can describe better how to do it :) 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by adavison007** [comment]
> Feel free to make a pull request on the readme if you think you can describe better how to do it :)
> 
> Sent with [GitHawk](http://githawk.com)

No idea how to do that... some wording

INSTALLATION FOR MULTIPLE HUBS

Firstly use the following code, ensuring that you have fixed IP address applied to your hubs. Then once you have the config in the JSON, restart homebridge.. NOTE - Only the TV for the first hub will appear in Homebridge, the 2nd one, 3rd etc will need you to click ADD ACCESSORY in homekit and add them manually.  (the manual addition is done after the jason and homebridge restart within the homekit app.
