### ISSUE TITLE
[BUG] showTurnOffActivity = False non work

### ISSUE THREAD

**Issue by drako86** [nicoduj/homebridge-harmony#183]
in configuration, if the string is set to "false" ... the button does not disappear in Homekit

**Comment by nicoduj** [comment]
If you have set it to true then to false, you need to clean your cache in current versions (auto cleaning not supported on accessory level)

**Comment by drako86** [comment]
Would you be so kind as to tell me how to do it?
Or a link to where to read?
Thank you

**Comment by nicoduj** [comment]
You can try option cleanCache as mentioned in the readme on this github (branch dynamic platform) first :
- Set cleanCache to true in your plugin config
- Restart homebridge
- Stop homebridge
- set cleanCache to false (or remove property)
- Start Homebridge

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
