### ISSUE TITLE
ERROR - refreshCurrentActivity TimeoutError: Can't open WebSocket within allowed timeout: 10000 ms

### ISSUE THREAD

**Issue by bubez81** [nicoduj/homebridge-harmony#184]
hello, it's days that often i see the harmony activity "not responding"
 the homebridge log says:
ERROR - refreshCurrentActivity TimeoutError: Can't open WebSocket within allowed timeout: 10000 ms
it's a bug or a problem of my Harmony Hub?

Best regards,
Michele.

**Comment by nicoduj** [comment]
It seems your hub is not reachable in time on your network . Check the les of your hub (red / green) and your network, try rebooting your hub maybe 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by bubez81** [comment]
yes, often the led become red and then green again in 1 minute.
Maybe my hub conflicts witch my router? (Orbi netgear mesh)

**Comment by nicoduj** [comment]
I have an orbi RB40 myself and doesn't have those issues. Can you share your config ?

**Comment by bubez81** [comment]
sure, but I'm thinking this is not the real problem...now I have tested the same configuration on a raspberry...no problems at all....before I used a macmini as a server...
