### ISSUE TITLE
[BUG] TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by AdmiralMichael** [nicoduj/homebridge-harmony#186]
I run a dedicated docker container for each Homebridge platform I use. Currently I have my harmony platform setup for three hubs. I added individual platforms in the config file for each hub and it works, that is until I restart the container. 

I can fix it by deleting the accessories and persist folders but that resets all my harmony accessories in HomeKit (One reason I run one container per platform so this just affects just the harmony stuff). 

I get the following error:

> [9/3/2019, 10:35:23 PM] Registering accessory 'homebridge-dummy.DummySwitch',
> [9/3/2019, 10:35:23 PM] ---,
> [9/3/2019, 10:35:23 PM] Loaded config.json with 0 accessories and 3 platforms.,
> [9/3/2019, 10:35:23 PM] Loaded plugin: homebridge-dummy,
> [9/3/2019, 10:35:24 PM] Loaded plugin: homebridge-harmony,
> [9/3/2019, 10:35:24 PM] Registering platform 'homebridge-harmonyHub.HarmonyHubWebSocket',
> [9/3/2019, 10:35:24 PM] ---,
> [9/3/2019, 10:35:24 PM] Loaded plugin: homebridge-config-ui-x,
> [9/3/2019, 10:35:24 PM] Registering platform 'homebridge-config-ui-x.config',
> [9/3/2019, 10:35:24 PM] Loading 3 platforms...,
> [9/3/2019, 10:35:24 PM] [Living Room] Initializing HarmonyHubWebSocket platform...,
> [9/3/2019, 10:35:24 PM] [Living Room] HarmonyPlatform Init,
> [9/3/2019, 10:35:24 PM] [Bedroom] Initializing HarmonyHubWebSocket platform...,
> [9/3/2019, 10:35:24 PM] [Bedroom] HarmonyPlatform Init,
> [9/3/2019, 10:35:24 PM] [Basement] Initializing HarmonyHubWebSocket platform...,
> [9/3/2019, 10:35:24 PM] [Basement] HarmonyPlatform Init,
> [9/3/2019, 10:35:24 PM] Loading 0 accessories...,
> [9/3/2019, 10:35:24 PM] TypeError: Cannot read property 'name' of undefined,
>     at HarmonyPlatform.configureAccessory (/homebridge/node_modules/homebridge-harmony/harmonyPlatform.js:101:69),
>     at Server._configCachedPlatformAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:386:24),
>     at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:93:8),
>     at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10),
>     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22),
>     at Module._compile (internal/modules/cjs/loader.js:778:30),
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10),
>     at Module.load (internal/modules/cjs/loader.js:653:32),
>     at tryModuleLoad (internal/modules/cjs/loader.js:593:12),
>     at Function.Module._load (internal/modules/cjs/loader.js:585:3),
>     at Function.Module.runMain (internal/modules/cjs/loader.js:831:12),
>     at startup (internal/bootstrap/node.js:283:19),
>     at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3),
> [9/3/2019, 10:35:24 PM] Got SIGTERM, shutting down Homebridge...,
> [9/3/2019, 10:35:24 PM] [Living Room] INFO - shutdown,
> [9/3/2019, 10:35:24 PM] TypeError: platform.harmonyBase.harmony.end is not a function,
>     at HarmonyPlatform.<anonymous> (/homebridge/node_modules/homebridge-harmony/harmonyPlatform.js:60:42),
>     at API.emit (events.js:203:15),
>     at process.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/cli.js:48:19),
>     at process.emit (events.js:198:13),
> Got SIGTERM, quitting.

This is my config file:

```
{
    "bridge": {
        "name": "Homebridge Harmony",
        "username": "CC:22:3D:E3:CE:32",
        "port": 51828,
        "pin": "031-45-156"
    },

    "accessories": [
    ],

    "platforms": [
    {
      "platform": "HarmonyHubWebSocket",
      "name": "Living Room",
      "cleanCache": false,
      "hubIP": "192.168.50.70",
      "TVPlatformMode": true,
      "mainActivity": "Watch TV",
      "switchAccessories": true,
      "publishAllTVAsExternalAccessory": true,
      "devicesToPublishAsAccessoriesSwitch": ["Denon AV Receiver|Mute;Mute"]
    },
    {
      "platform": "HarmonyHubWebSocket",
      "name": "Bedroom",
      "cleanCache": false,
      "hubIP" : "192.168.50.71",
      "TVPlatformMode": true,
      "mainActivity": "Watch TV",
      "switchAccessories": true,
      "publishAllTVAsExternalAccessory": true,
      "devicesToPublishAsAccessoriesSwitch": ["Vizio Soundbar|Mute;Mute"]
    },
    {
      "platform": "HarmonyHubWebSocket",
      "name": "Basement",
      "cleanCache": false,
      "hubIP": "192.168.50.72",
      "TVPlatformMode": true,
      "mainActivity": "Watch TV",
      "switchAccessories": true,
      "publishAllTVAsExternalAccessory": true,
      "devicesToPublishAsAccessoriesSwitch": ["Denon AVR-1909|Mute;Mute"]
    }
]
}
```

**Comment by nicoduj** [comment]
Hi, your config is not good , you can’t have 3 platforms on the same homebridge, you must use otherplatforms syntax / see readme / migration guide from 0.7 to 1.x

**Comment by AdmiralMichael** [comment]
Oh. Well it works on the first load so I figured it was ok to have three.

**Comment by AdmiralMichael** [comment]
OK I tried what you suggested and it works great now. I now see the bolded paragraph about using the otherplatforms option.
