### ISSUE TITLE
[BUG] Hub no longer appears in Home app Add Accessory list after deleting accessory and entering setup code

### ISSUE THREAD

**Issue by bonebox** [nicoduj/homebridge-harmony#187]
**Describe the bug**
If you add the hub to HomeKit as an external accessory via the provided setup code, then delete it from HomeKit and attempt to add it back, it no longer appears in the list after entering the setup code.

**To Reproduce**
1. In the Home app, add Harmony hub as TV-Mode accessory via the setup code provided by homebridge-harmony. 
2. In the Home app, delete the accessory.
3. Repeat step 1. The hub no longer appears in the list after entering the setup code.
4. Tried a. restarting homebridge, b. removing homebridge-harmony cache via config, c. restarting the Home app, and d. restarting the Harmony hub, but it still does not appear in the "Add Accessory" list.

**Expected behavior**
The hub still appears in the "Add Accessory" list after deleting the TV-Mode accessory and typing in the setup code again.

**Screenshots**

**IOS (please complete the following information):**
- Version [e.g. 13.1]
- Device: [e.g. iPhone X]

**Logs**
Your log in debug mode (-D option)

**Config**
```
{
      "platform": "HarmonyHubWebSocket",
      "publishAllTVAsExternalAccessory": true,
      "name": "Living Room",
      "hubIP": "192.168.1.141",
      "mainActivity" : "Watch Apple TV",
      "switchAccessories" : true,
      "showTurnOffActivity" : "inverted",
      "otherPlatforms": [
        {
          "platform": "HarmonyHubWebSocket",
          "name": "Master Bedroom",
          "hubIP": "192.168.1.139",
          "mainActivity" : "Watch Apple TV",
          "switchAccessories" : true,
          "showTurnOffActivity" : "inverted"
        }
      ]
    },
```

**Additional context**

**Comment by nicoduj** [comment]
Hi, did you try with publishalltvasexternalaccessories to off ? (Maybe you have another tv accessory in the same hub ?) . When you say remove the hub, you removed the hub OR the accessory ? The first tv is still there or both are missing ?





<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by bonebox** [comment]
Initial config was without `publishAllTVAsExternalAccessory` (so false) but I had two entries under “otherPlatforms” because I was still a little confused on how to migrate my old config. No TV accessories showed up automatically when I ran it like this the first time. So I used the code in the log, and both of my hubs showed up under “add accessories”. I only added one, but then deleted it once I realized my config wasn’t correct. In hindsite I probably shouldn’t have deleted it. Anyway, I fixed the config and restarted homebridge, then put in the code again to try and add back the one I deleted, but this time only the one that I hadn’t added yet showed up in the list. I went ahead and added it, then deleted it as well just to test, and sure enough, now neither one with show up when I put in the code. 

I then played around with different settings, including setting `publishAllTVAsExternalAccessory` to true, but nothing fixed it. It almost makes me think that by deleting the accessories they are now somehow “blacklisted” by HomeKit or homebridge. I noticed that the code provided by homebridge-harmony is always the same for both hubs. I wonder if generating a new code may possibly help. Is that possible?

**Comment by nicoduj** [comment]
I see you are in ios13, didi you try deleting the hub itself (not the accessory, hub is now in ios13 in home properties) ? 
If your homebridge is dedicated / you are not worried about having to reconfigure scenes in homekit with other accessories exposed, you can try also deleting persist folder in homebridge, and add again through homekit. 
I will try to reproduce as soon as I can

**Comment by bonebox** [comment]
Thanks, I deleted the homebridge hub from properties but it wouldn't allow me to add it back until I deleted the persist folder as well. This did allow both harmony hubs to show up again under "add accessories". However, after I add the first one, the second one no longer shows up when I go back to add it, so apparently I'm only able to add one of them.

**Comment by bonebox** [comment]
Nevermind, it took a couple minutes, but the second one finally showed up in the list. Odd since it showed up almost immediately the first time along with the other one. I had actually sat my phone down and when I came back it was showing in the list, but when I tried to add it it failed. So I tried it again, and again it took a few minutes to show up, but finally did. This time it added successfully.

**Comment by bonebox** [comment]
Back to the original issue, I noticed in the persist folder that there are files that correspond to each accessory. I'm wondering if you can just delete the individual file associated with the TV accessory rather than deleting the entire homebridge hub.

**Comment by nicoduj** [comment]
Hi, did you try by entering the code manually without waiting ?

**Comment by bonebox** [comment]
Yes, I entered the code each time. Before either of my Harmony hubs were added as a TV accessory, they showed up immediately when I entered the code. After adding the first hub then returning and entering the code again, it takes a while for the second to show up for some reason.
