### ISSUE TITLE
[BUG] Home shows GeneralMuteSwitch while disabled in config

### ISSUE THREAD

**Issue by carlovd1991** [nicoduj/homebridge-harmony#188]
**Describe the bug**
My Home app displays the General Mute Switch accessory while I have this field disabled

**To Reproduce**
Restarted Homebridge, docker, rebooted Raspberry Pi. Still no luck.

**Expected behavior**
Home app not showing this accessory while field disabled in config.

**IOS (please complete the following information):**
- Version 12.4.1
- Device: iPhone 6s and iPad Air 1

**Logs**
There are no errors or weird things in my logs

**Config**
        {
            "platform": "HarmonyHubWebSocket",
            "name": "OBFUSCATED",
            "hubIP": "OBFUSCATED",
            "mainActivity": "Television",
            "showTurnOffActivity": "inverted",
            "publishGeneralMuteSwitch": "false"
        }

**Comment by nicoduj** [comment]
Hi, did you activate it before ?

**Comment by carlovd1991** [comment]
Yes, I activated it to see what it was but I don’t need it. Now I can’t get rid of it.

**Comment by nicoduj** [comment]
I quickly checked the code and it should be removed at next start . Will try to reproduce ASAP , but do you see logs like WARNING - Accessory will be Removed ? If you launch in debug , what do you have in confirmed service log ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by carlovd1991** [comment]
After reboot, Homebridge restart and Docker container restart I keep getting this in the log:

//

[9/11/2019, 9:34:10 PM] [CarloHarmonyHub] DidFinishLaunching
[9/11/2019, 9:34:10 PM] [CarloHarmonyHub] INFO - Loading activities...

----- Some other plugins -----

[9/11/2019, 9:34:12 PM] [CarloHarmonyHub] (CarloHarmonyHub)INFO - configuring Main TV Service
[9/11/2019, 9:34:12 PM] [CarloHarmonyHub] (CarloHarmonyHub)INFO - Configuring Main Activity Televisie
[9/11/2019, 9:34:12 PM] [CarloHarmonyHub] (CarloHarmonyHub)INFO - Discovered Activity : PowerOff
[9/11/2019, 9:34:12 PM] [CarloHarmonyHub] INFO - Loading geeneral mute Switch...

//

Would restarting the hub do anything?

Edit: I noticed that the same goes for "showTurnOffActivity": "false", it's still showing up in the Home app. "inverted" seems to work, "true" seems to work but "false" doesn't?

**Comment by nicoduj** [comment]
"publishGeneralMuteSwitch": false 
and not 
"publishGeneralMuteSwitch": "false"

-> will try to handle this better but currently it is a boolean sorry . Or remove the option it should also work !
