### ISSUE TITLE
Integration of harmony-websocket for better state update in the background.

### ISSUE THREAD

**Issue by nicoduj** [nicoduj/homebridge-harmony#19]
Hi @nicoduj,

Maybe this Websocket implementation could help to achieve a faster and more convenient status update: https://github.com/lopelex/harmony-websocket

Cheers!

_Originally posted by @iharosi in https://github.com/nicoduj/homebridge-harmony/issues/11#issuecomment-450600764_

**Comment by pponce** [comment]
Also might be worth looking at this project and comment here: AirBorne04/harmonyhub#20 (comment)

**Comment by pponce** [comment]
I took a quick look at @AirBorne04 websocket implementation and there does appear to be an event sent from the hub itself that provides state information. You probably already noticed this too but just in case I wanted to post it here.  @AirBorne04 leveraged the @lopelex websocket work and it also uses this hub notification state change data.. 

`_onMessage(message) {
        if (message.type === 'connect.stateDigest?notify') {
            this.onStateDigest(message.data);
        }
    }
    /**
     * The state digest is caused by the hub to let clients know about remote updates
     * @param {message} stateDigest
     */
    onStateDigest(stateDigest) {
        debug(`received state digest ${JSON.stringify(stateDigest)}`);
        this.emit(HarmonyClient_1.Events.STATE_DIGEST, stateDigest);
    }
    /**
     * Returns the latest turned on activity from a hub.
     *
     * @returns Promise<string>
     */`

**Comment by nicoduj** [comment]
Thanks for the update.

What i fear with that is that we need to let the socket connected . By the past, with the old plugin, a lot of people (including me) were having errors (max client connected). I think the hub doesn’t allow too many simultaneous connection. But i will try that when i will have some time, currently the background update does the job (not a perfect one !) and i am focused on implementing the tv device mode  with ios 12.2

**Comment by pponce** [comment]
Looking forward to the tv device mode.
I’ll try out one of the plugins that uses the state digest functionality and report back.
I also had the the max client issue for the longest time. I resorted to using HA bridge and homebridge-hue to get around the issues. The issue did end up getting resolved in the xmpp homebridge harmonyhub plugin implementation. Just needed to use a version that relied on the latest harmonyhubjs client with included fixes for it. Airborne04 xmpp client also fixed that issue. 
I’ll report back on any Max client issues with using one of the websocket plugins that is using state digest functions. I want to make the move to a websockets version and I like all the features you are adding to your plugin but would like optimized state updates.

**Comment by pponce** [comment]
Have been running the airborne04 websocket implementation and have had no issues. No max client errors and home bridge crashing like the original harmony plugin did. It used to happen at least once a day if not more. Been running for 3+ days and no problem.  State change syncs are quick.  Great because my wife likes using the real remote. 
The airborne04 xmpp implementation also has no Max client error issues.  Just FYI Incase we ever have to go back to xmpp.

**Comment by nicoduj** [comment]
Thanks, i will try to test this asap ! Tv platform seems reliable for now I can switch to another subject

**Comment by nicoduj** [comment]
will be done in #48
