### ISSUE TITLE
Hubs disappeared and can't get them back

### ISSUE THREAD

**Issue by mikesalz** [nicoduj/homebridge-harmony#191]
I am hoping you can help! I have 3 Harmony hubs, and all were working perfectly.  Yesterday, my Homebridge crashed.  I couldn't figure out what was wrong, so I restored a backup from a couple of weeks ago.  Since then, 2 of the 3 hubs no longer show up in HomeKit.  I do see them in the Homebridge log, however.

I know that additional hubs need to be added manually through the Home app, but they are not showing up when I go to add a device.  My config is below.  Only the LoftHarmonyHub shows up.  Interestingly, the MasterBedroomHarmonyHub does not show up but its homeControlsToPublishAsAccessoriesSwitch switches do.

Please tell me I am doing something dumb and I can fix it easily!  Thanks in advance!

 ```
       {
            "platform": "HarmonyHubWebSocket",
            "name": "FamilyRoomHarmonyHub",
            "hubIP": "192.168.1.229",
            "mainActivity": "Watch Apple TV",
            "otherPlatforms": [
                {
                    "name": "LoftHarmonyHub",
                    "hubIP": "192.168.1.227",
                    "mainActivity": "Watch Loft Apple TV"
                },
                {
                    "name": "MasterBedroomHarmonyHub",
                    "hubIP": "192.168.1.228",
                    "mainActivity": "Watch Master Bedroom Apple TV",
                    "homeControlsToPublishAsAccessoriesSwitch": [
                        "hue-switch.harmony_master_bedroom_fan_switch",
                        "hue-switch.harmony_master_bedroom_fan_light_switch"
                    ]
                }
            ]
        },
```

**Comment by nicoduj** [comment]
Hi, did you try to enter manually the code while adding a device in home ? ![GitHawk Upload by nicoduj](https://i.imgur.com/4Oze8Va.jpg)![GitHawk Upload by nicoduj](https://i.imgur.com/9qwryHx.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mikesalz** [comment]
I did... In the Homebridge log it says:
Please add [MasterBedroomHarmonyHub-TV] manually in Home app. Setup Code:
031-xxx-xxx

That is the same setup code as the Homebridge installation.  So when I
enter that code, it tells me the device has already been added.  Am I doing
something wrong?

**Comment by nicoduj** [comment]
I think you have files in your persist folders for those accessories , maybe they need to be removed . 
Maybe I a doing something wrong in this particular case, will check ...

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mikesalz** [comment]
I tried removing from the persist folder the AccessoryInfo files that referenced the Harmony hubs.  But that blew up Homebridge.  I also removed references to the hubs from the accessories\cachedAccessories file, but that did not help either.  Any other ideas?

**Comment by mikesalz** [comment]
I figured it out!  Stupid me... I needed to remove the "Not Responding" hubs from the Home app.  I did that and removed them from the cachedAccessories file and then I was able to add them back to HomeKit.

**Comment by nicoduj** [comment]
👍 I thought they were not there anymore :) 

Nicolas

**Comment by mikesalz** [comment]
Yeah, I don't know what I was thinking.  I guess I assumed I could not manually remove them from the Home app if they were part of Homebridge.  Anyway, I am good now.  Thanks for your help!  And thanks again for creating an awesome plugin!
