### ISSUE TITLE
IOS 13 shows extra (Not Supported) accessory?

### ISSUE THREAD

**Issue by dewoert** [nicoduj/homebridge-harmony#192]
I updated one of my iPhones to IOS 13, and having some issues getting the Harmony to show up correctly.
On my IOS 12 iPhone, I have a perfect working icon Harmony. I can select directly witch input i want.
Same HomeKit on IOS 13 gives now the Hamony tile, but "behind" that is an extra accessory called TV.
When i look into HomeBridge Config UI X, is can see an "Not Supported" accessory, in the properties the name is "Harmony-TV"
Also some info there about Speaker, Mute and Volume.
IOS 12 doesn't seem to do antthing with is, but can it be that IOS 13 is seeing that accessory, and linking it to the Harmony tile ?

**Comment by nicoduj** [comment]
Hi, Tvaccessory includes different services (speaker, inputs ..)
I have no problem on iOS13, did you try restarting homebridge / home app ? Can you share screenshots ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dewoert** [comment]
![20190920_114228000_iOS](https://user-images.githubusercontent.com/18567064/65324542-cf487180-dbac-11e9-8c4f-6ce51f27afc2.jpg)
![20190920_114255000_iOS](https://user-images.githubusercontent.com/18567064/65324547-d3748f00-dbac-11e9-83ff-1a7bc2e026d3.png)
![20190920_114313000_iOS](https://user-images.githubusercontent.com/18567064/65324553-d8394300-dbac-11e9-953b-e5627d733cf0.jpg)
![20190920_114334000_iOS](https://user-images.githubusercontent.com/18567064/65324556-db343380-dbac-11e9-8c72-8f4d378e7c58.jpg)

**Comment by dewoert** [comment]
my current config:
```
            "platform": "HarmonyHubWebSocket",
            "name": "Harmony",
            "hubIP": "192.168.x.xx",
            "showCommandsAtStartup": false,
            "cleanCache": false,
            "publishAllTVAsExternalAccessory": true,
            "showTurnOffActivity": "stateless",
            "switchAccessories": true,
            "mainActivity": "Radio",
            "devicesToPublishAsAccessoriesSwitch": [
                "AV-ontvanger Harman Kardon;VolumeUp|100;VolumeUp|100;VolumeUp|100;VolumeUp|100;VolumeUp",
                "AV-ontvanger Harman Kardon;VolumeDown|100;VolumeDown|100;VolumeDown|100;VolumeDown|100;VolumeDown",
                "Tower Ventilator;PowerToggle",
                "Tower Ventilator;Speed",
                "Tower Ventilator;Osc"
            ]

```

**Comment by dewoert** [comment]
Screenshots from HomeBridge Config UI X:
![screenshot_7](https://user-images.githubusercontent.com/18567064/65325555-75957680-dbaf-11e9-9a4f-c9c8c4967712.png)
![screenshot_6](https://user-images.githubusercontent.com/18567064/65325557-77f7d080-dbaf-11e9-915e-1c641734006c.png)

**Comment by nicoduj** [comment]
Ok, maybe it is because it is published as an external device and iOS 13 messed  with it . Try deleting in home app and readd

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dewoert** [comment]
**Problem solved !**
It turns out that I had an activity with the name "TV".
Also an device named TV.
IOS 12 doesn't seem to mind, but in IOS 13 things have changed. 
So I renamed the activity, and now things are working like it should be.

**Comment by nicoduj** [comment]
Interesting ... iOS 13 is buggy however so might be a bug there :) 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
