### ISSUE TITLE
[BUG] Duplicate Dead TV Remote still showing

### ISSUE THREAD

**Issue by slunat** [nicoduj/homebridge-harmony#193]
I have just reinstalled windows and started my homebridge setup again. THe only thing I carried across was my config file. In the TV remote, I am still getting my old TV show up. I have removed the old bridge from my homekit stup and the old tv device is no longer there but I can still see the old TV remote. When I start homebridge, my config shows the following error:
TV accessory added in your bridge, if another plugin is exposing a TV accessory this one might not be visible in your remote widget
and I see two tvs in the remote app named the exact same, though one of them doesn't work (the old remote). How do I clear the old remote from showing on my device? I have tried deleting the accessories and homebridge-harmony folder and reinstalling homebridge-harmony but it is still the same. I am on the newest version of the plugin (only installed a couple of hours ago) as I had to reinstall all my plugins due to a new server.

Thanks

**Comment by nicoduj** [comment]
Hi, Did you check in ios13 if you have removed the old hub ? (and not only the device) . Hubs are now in home properties

**Comment by slunat** [comment]
Yes, Before I reinstalled Homebridge and reset it up, I deleted the old homebridge. None of my old homebridge devices show up in the home app, not even the TV. The only location I see a reference of the old TV is in the remote widget, as I now have two tv's to select from, both called "Suly's TV".
In my homebridge log, I can see the following message:
[Sulys TV] WARNING - configureAccessory - TV accessory added in your bridge from cache, if another plugin is exposing a TV accessory this one might not be visible in your remote widget

**Comment by nicoduj** [comment]
the warning is just in case you have other plugins exposing a TV accessory. The one there is not exposed as an external one since you have only one from what I understand.
Did you simply try to restart your phone ? It is a cache problem on IOS side I think, if the TV is not in home app.

**Comment by slunat** [comment]
I've not tried that yet, I will give it a go when I am at home later. I also want to see if any of my other devices are showing mutiple TV's.

**Comment by nicoduj** [comment]
Ok, let's do that and come back to me !

**Comment by slunat** [comment]
I had a look when i got home and the duplicate remote had disappeared, without me even restarting anything. Looks like you are right and iOS was just caching it and got rid of it. All is showing ok now :)

Thanks!
