### ISSUE TITLE
ERROR - activityCommand : could not SET status, no data

### ISSUE THREAD

**Issue by wissamoh** [nicoduj/homebridge-harmony#194]
I activated the Homebridge-harmony plugin and then added the "Simple Config (only TV Accessory)" gson code to the json file and I got the harmony hub showing on HomeKit and all the harmony activities showing as inputs. But surprisingly only one activity is showing the following error in the Homebridge logs each time I select this activity input. An I couldn't get it to work while all the other activities are working perfectly
<img width="679" alt="Screen Shot 2019-09-29 at 11 07 55 PM" src="https://user-images.githubusercontent.com/33606709/65838656-fff77c00-e30d-11e9-8da1-2f18f3954cf0.png">
.
ERROR - activityCommand : could not SET status, no data
Any hints?

**Comment by nicoduj** [comment]
Hi, could you try in debug mode to see what activity is retrieved and the code sent while changing to this one ? It would be usefull to have your hub config as well, what kind of activity is it ? The error is because when we send the activity to the hub, it returns no error but also no data at all. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nicoduj** [comment]
@wissamoh any news on this ?

**Comment by wissamoh** [comment]
Hi Nicoduj,
II tried debug mode and here is what I get when I clic on the activity that its having the issue. ( by the way this activity is just having the same devices (TV + sound system) as the working ones....but this one has a satellite receiver while the others are just Apple TV and Fire TV...
the non working activity works perfectly in harmony...I have the issue only in the Homebridge/Homekit.
Thanks for your support.


  EventedHTTPServer [192.168.55.44] HTTP request: /characteristics?id=21.23,21.31,21.39,21.47 +14s
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: GET /characteristics?id=21.23,21.31,21.39,21.47 +1ms
  Accessory [Homebridge] Getting value for Characteristic "Target Visibility State" +3ms
[10/6/2019, 10:29:40 PM] [Harmony] (Harmony)INFO - GET Characteristic.TargetVisibilityState : DEFAULT - 0
  Accessory [Homebridge] Got Characteristic "Target Visibility State" value: 0 +4ms
  Accessory [Homebridge] Getting value for Characteristic "Target Visibility State" +1ms
[10/6/2019, 10:29:40 PM] [Harmony] (Harmony)INFO - GET Characteristic.TargetVisibilityState : 1
  Accessory [Homebridge] Got Characteristic "Target Visibility State" value: 1 +3ms
  EventedHTTPServer [192.168.55.38] Sending HTTP event '21.31' with data: {"characteristics":[{"aid":21,"iid":31,"value":1}]} +1ms
  EventedHTTPServer [192.168.55.44] Muting event '21.31' notification for this connection since it originated here. +3ms
  Accessory [Homebridge] Getting value for Characteristic "Target Visibility State" +1ms
[10/6/2019, 10:29:40 PM] [Harmony] (Harmony)INFO - GET Characteristic.TargetVisibilityState : DEFAULT - 0
  Accessory [Homebridge] Got Characteristic "Target Visibility State" value: 0 +3ms
  Accessory [Homebridge] Getting value for Characteristic "Target Visibility State" +1ms
[10/6/2019, 10:29:40 PM] [Harmony] (Harmony)INFO - GET Characteristic.TargetVisibilityState : DEFAULT - 0
  Accessory [Homebridge] Got Characteristic "Target Visibility State" value: 0 +2ms
  EventedHTTPServer [192.168.55.44] HTTP Response is finished +3ms
  EventedHTTPServer [192.168.55.44] HTTP request: /characteristics +2s
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: PUT /characteristics +1ms
  Accessory [Homebridge] Processing characteristic set: [{"aid":21,"iid":11,"value":15924589}] +2ms
  Accessory [Homebridge] Setting Characteristic "Active Identifier" to value 15924589 +1ms
[10/6/2019, 10:29:41 PM] [Harmony] (Harmony)INFO - SET Characteristic.ActiveIdentifier 15924589
[10/6/2019, 10:29:41 PM] [Harmony] (Harmony)INFO - sendInputCommand : Activty OSN will be activated 
  EventedHTTPServer [192.168.55.38] Sending HTTP event '21.11' with data: {"characteristics":[{"aid":21,"iid":11,"value":15924589}]} +31ms
  EventedHTTPServer [192.168.55.44] Muting event '21.11' notification for this connection since it originated here. +3ms
  EventedHTTPServer [192.168.55.44] HTTP Response is finished +2ms
[10/6/2019, 10:29:42 PM] [Harmony] (Harmony)INFO - activityCommand : Returned from hub {"cmd":"harmony.activityengine?runactivity","code":401.2,"id":"0.8625857504460019","msg":"Unauthorized policy write haDevice denied"}
[10/6/2019, 10:29:42 PM] [Harmony] (Harmony)ERROR - activityCommand : could not SET status, no data

**Comment by nicoduj** [comment]
Hi, is the activity name OSN ? Could you post the full log since homebridge start and your config ? The error is quite strange

**Comment by wissamoh** [comment]
Hi @nicoduj, yes actually the activity name is OSN. And I attached the log from the beginning of the hub launching...I tried to remove all the logs related to other platforms than Harmony...
at the end of the log I tried to initiate the Apple TV activity which work well, and then at the end I laughed the OSN activity which failed to start.
Thanks in advance for your time and support, Appreciated.
Wissam
[Homebridge Logs.log](https://github.com/nicoduj/homebridge-harmony/files/3709128/Homebridge.Logs.log)

**Comment by nicoduj** [comment]
Ok, so I checked your log an this "OSN" activity seems a bit different :  
- type is  "VirtualTelevisionN" and not "VirtualGeneric"
- it has rules  [ "start","end" ]

However, I don't really know what it means yet, and don't have such activities by my side. Does it means something to you ?

**Comment by nicoduj** [comment]
for rules, maybe you set that : https://support.myharmony.com/en-us/schedule-activity ? Could you try without if it is the case ?

**Comment by wissamoh** [comment]
Hi nicoduj, Well that's very odd, I really don't know why I'm getting the "VirtualTelevisionN" as type and not "VirtualGeneric".
I don't have any rules configured for this activity.

But finally I created a new activity called "testOSN" that has the same inputs and  configuration as OSN activity and it's working perfectly without any issues, and the type is "VirtualGeneric" for it. thanks a lot for your support. ( I attached logs of the working setup if you are interested to have a look at).
However I still have a small question regarding the iPhone remote, I there a way to configure and show more buttons like forward and backward for example to control the OSN activity just straight from the iPhone remote?

Thanks again.
Wissam
[Homebridge Logs.log](https://github.com/nicoduj/homebridge-harmony/files/3714101/Homebridge.Logs.log)

**Comment by wissamoh** [comment]
by the way I still have the OSN activity configured if you ever want to further troubleshoot that for any reason.

**Comment by nicoduj** [comment]
Hi, I will add an issue for this but don’t really no yet if I will be able to fix it and where this type comes from ! 

Concerning your question, there is no way to show more buttons. However you can override their default behavior per input through your plugin config : see remoteOverrideCommandsList option 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
