### ISSUE TITLE
[BUG] - activities with type VirtualTelevisionN

### ISSUE THREAD

**Issue by nicoduj** [nicoduj/homebridge-harmony#196]
**Describe the bug**
Activities with type "VirtualTelevisionN" can't be activated

**To Reproduce**
Don't know

**Expected behavior**
Activity should be launched like others

**Logs**
[10/6/2019, 10:29:42 PM] [Harmony] (Harmony)INFO - activityCommand : Returned from hub {"cmd":"harmony.activityengine?runactivity","code":401.2,"id":"0.8625857504460019","msg":"Unauthorized policy write haDevice denied"}
[10/6/2019, 10:29:42 PM] [Harmony] (Harmony)ERROR - activityCommand : could not SET status, no data

**Config**
basic config with TV only

**Additional context**
originally reported in https://github.com/nicoduj/homebridge-harmony/issues/194 
Doing the activity config again did not produce this type of activity.

**Comment by nicoduj** [comment]
If anyone knows how to produce such kind of activity, please fill in since I won't be able to fix or try to if I can't reproduce with my own hub

**Comment by nicoduj** [comment]
needs  to be confirmed since error code means autorisation is not ok, maybe there was some other thing in the ocnfig in the original report I did not see.

**Comment by mwkchan** [comment]
I got the same after changed my Harmony configs (removing and creating activities in Harmony App). I tried to clear cache and made sure the "MainActivitiy" is correctly set but still can't fix it. The plugin works fine before I made the changes.

It still works fine if I go into the TV setting and choose my input. Just simple click to turn on TV doesn't work.

[3/7/2020, 11:06:11 PM] [Master Room Hub] (Master Room Hub)ERROR - activityCommand : could not SET status, no data

My config:

      {
            "name": "Master Room Hub",
            "hubIP": "192.168.1.245",
            "cleanCache": false,
            "publishAllTVAsExternalAccessory": true,
            "TVAccessory": true,
            "mainActivity": "Live TV",
            "activitiesToPublishAsInputForTVMode": [
                "Apple TV",
                "BBC",
                "Bluetooth Music",
                "Live TV",
                "my TV Super",
                "Netflix"
            ],
            "playPauseBehavior": true,
            "remoteOverrideCommandsList": [
                {
                    "ActivityName": "my TV Super",
                    "CommandsList": [
                        {
                            "CommandName": "INFORMATION",
                            "NewCommand": "TVB STB;TV/VOD"
                        },
                        {
                            "CommandName": "ARROW_UP",
                            "NewCommand": "TVB STB;DirectionUp"
                        },
                        {
                            "CommandName": "ARROW_DOWN",
                            "NewCommand": "TVB STB;DirectionDown"
                        },
                        {
                            "CommandName": "ARROW_LEFT",
                            "NewCommand": "TVB STB;DirectionLeft"
                        },
                        {
                            "CommandName": "ARROW_RIGHT",
                            "NewCommand": "TVB STB;DirectionRight"
                        },
                        {
                            "CommandName": "SELECT",
                            "NewCommand": "TVB STB;Select"
                        },
                        {
                            "CommandName": "PLAY",
                            "NewCommand": "TVB STB;Red"
                        },
                        {
                            "CommandName": "PAUSE",
                            "NewCommand": "TVB STB;Red"
                        },
                        {
                            "CommandName": "FAST_FORWARD",
                            "NewCommand": "TVB STB;Blue"
                        },
                        {
                            "CommandName": "REWIND",
                            "NewCommand": "TVB STB;Yellow"
                        },
                        {
                            "CommandName": "BACK",
                            "NewCommand": "TVB STB;Back"
                        }
                    ]
                }
            ],
            "switchAccessories": true,
            "showTurnOffActivity": "inverted",
            "publishGeneralMuteSwitch": true,
            "showCommandsAtStartup": false,
            "otherPlatforms": [
                {
                    "name": "Living Room Hub",
                    "hubIP": "192.168.1.225",
                    "TVAccessory": true,
                    "mainActivity": "Live TV",
                    "playPauseBehavior": true,
                    "switchAccessories": false,
                    "showTurnOffActivity": "false",
                    "publishGeneralMuteSwitch": false,
                    "showCommandsAtStartup": false
                }
            ],
            "platform": "HarmonyHubWebSocket"
        }

**Comment by nicoduj** [comment]
Hi, Living Room Hub is ok ? Only the master hub produce the error ? You still have the permission error right before ? Did you try another mainActivity ?

**Comment by mwkchan** [comment]
Living Room Hub is fine. Master Room Hub still got the error. I went so far as to clear the cache, uninstall the plugin and reinstall it and still got the same error. Tried another mainActivity "Apple TV" and "BBC", got the same result. But it was all fine before I change the Harmony activities. Very strange.

Have I successful clear all files by uninstalling the plugin or there would be residual somewhere?

**Comment by mwkchan** [comment]
By the way, I don't have permission error. I was not the owner of the original bug. I just found this open issue and I have the same error.

**Comment by nicoduj** [comment]
Hi, there can be some files on the root directory of homebridge  (harmonyPlugin*) , you can try to remove them (they handle renamming of your activities, so maybe the name is not the one you think)
Be aware it is fully case sensitive ..

**Comment by mwkchan** [comment]
Ok, deleted the files, cleared cache, killed all HomeKit apps, restart homebridge, now it works!

**Comment by nicoduj** [comment]
nice, Noted, maybe there was so confusion in the plugin with old names/ new names and the file cache. I will let this bug open to dig into it when I will have some time, thanks for reporting.

**Comment by nicoduj** [comment]
Can't reproduce, closing since there was no other report
