### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by mensa84** [nicoduj/homebridge-harmony#198]
Hello I am running homebridge-harmony@1.1.1 with homebridge@0.4.50.

I currently have 3 Harmony Hubs in my LAN but as it seems homebridge-harmony can only handle max. 2.

Could you please check?

My config is the following:
```
		{
			"platform": "HarmonyHubWebSocket",
			"name": "Wohnzimmer Fernseher",
			"hubIP": "192.168.1.20",
			"mainActivity" : "Apple TV",
			"otherPlatforms": [
				{
					"name": "Schlafzimmer Fernseher",
					"hubIP": "192.168.1.30",
					"mainActivity" : "Apple TV"
				},
				{
					"name": "Badezimmer Fernseher",
					"hubIP": "192.168.1.40",
					"mainActivity" : "Apple TV"
				}
			]
		}
```

Then Only 2 television do appear, the third one does not appear.

Config with only 2 hubs works welle:
```
		{
			"platform": "HarmonyHubWebSocket",
			"name": "Wohnzimmer Fernseher",
			"hubIP": "192.168.1.20",
			"mainActivity" : "Apple TV",
			"otherPlatforms": [
				{
					"name": "Schlafzimmer Fernseher",
					"hubIP": "192.168.1.30",
					"mainActivity" : "Apple TV"
				}
			]
		}
```

**Comment by nicoduj** [comment]
Hi,

The config seems fine, can you share your logs please ? Did you add manually the 2 other ones in home app ?

**Comment by mensa84** [comment]
Sorry, I just forgot that I have to add TVs manually. It worked now :)
