### ISSUE TITLE
Trigger activity switching only if current state changed

### ISSUE THREAD

**Issue by Nastras** [nicoduj/homebridge-harmony#20]
Hello and thank you for the new Harmony plugin and your work.

I have the problem, if I incorporate an activity or the off switch in a scene that when running the scene, the devices are turned on if they have been previously turned off. The problem is that many devices only have one IR command for on and off. HomeKit does not check the real status of the device. Each command is sent when the scene is executed.

I used this pull request in the old homebridge-harmonyhub plugin to solve the problem.
https://github.com/KraigM/homebridge-harmonyhub/pull/88

I hope that you also have the possibility for your plugin to install an option to solve the problem?

Thank you, I am looking forward to your answer.

Greeting Nastra

**Comment by nicoduj** [comment]
Hi,

thank you for the feedback. It is indeed a problem :) I will take a look at it.

**Comment by Nastras** [comment]
Perfect, if you need support then tell me.
Thx❗️

**Comment by nicoduj** [comment]
I think we have 3 options there : 

- either adding a global option like that was made - not very "fan" of that, since you might want different behaviors depending on the scene (especially for the "turn off TV" one while using siri if you are on another scene,
- either setting an option per activity (some parameter with a list of scene to have this behavior)
- or maybe we could decide of the beahivour automatically if the scene has at least one device that doesn't have 2 IR command for on / off. 

What do you think ?

**Comment by Nastras** [comment]
I think point 2 would not be bad. Point 3 sounds good too. But I can not really judge what is technically best implemented. 😕

**Comment by Nastras** [comment]
Hello @nicoduj, thanks for fixing it. I have tested it quickly and so far everything works fine. I'll call you tomorrow after a long test again .-)

Greeting Nastra

**Comment by det-box** [comment]
Hi,
After updating to version 0. , the hombridge reboots when activating an action
error:
`Jan  7 18:32:12 hbridge3 homebridge[21296]: /usr/local/lib/node_modules/homebridge-harmony/index.js:460
Jan  7 18:32:12 hbridge3 homebridge[21296]:           this.skipedIfSameStateActivities.includes(
Jan  7 18:32:12 hbridge3 homebridge[21296]:                                            ^
Jan  7 18:32:12 hbridge3 homebridge[21296]: TypeError: Cannot read property 'includes' of undefined
Jan  7 18:32:12 hbridge3 homebridge[21296]:     at HarmonyPlatform.<anonymous> (/usr/local/lib/node_modules/homebridge-harmony/index.js:460:44)
Jan  7 18:32:12 hbridge3 homebridge[21296]:     at Characteristic.On.emit (events.js:188:13)
Jan  7 18:32:12 hbridge3 homebridge[21296]:     at Characteristic.On.Characteristic.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:320:10)
Jan  7 18:32:12 hbridge3 homebridge[21296]:     at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:871:22)
Jan  7 18:32:12 hbridge3 homebridge[21296]:     at Array.forEach (<anonymous>)
Jan  7 18:32:12 hbridge3 homebridge[21296]:     at Bridge.Accessory._handleSetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:811:8)
Jan  7 18:32:12 hbridge3 homebridge[21296]:     at HAPServer.emit (events.js:188:13)
Jan  7 18:32:12 hbridge3 homebridge[21296]:     at HAPServer._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:972:10)
Jan  7 18:32:12 hbridge3 homebridge[21296]:     at HAPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
Jan  7 18:32:12 hbridge3 homebridge[21296]:     at IncomingMessage.emit (events.js:188:13)
Jan  7 18:32:12 hbridge3 systemd[1]: homebridge-harmony.service: Main process exited, code=exited, status=1/FAILURE
Jan  7 18:32:12 hbridge3 systemd[1]: homebridge-harmony.service: Unit entered failed state.
Jan  7 18:32:12 hbridge3 systemd[1]: homebridge-harmony.service: Failed with result 'exit-code'.
Jan  7 18:32:22 hbridge3 systemd[1]: homebridge-harmony.service: Service hold-off time over, scheduling restart.
Jan  7 18:32:22 hbridge3 systemd[1]: Stopped Node.js HomeKit homebridge-harmony.
Jan  7 18:32:22 hbridge3 systemd[1]: Started Node.js HomeKit homebridge-harmony.
`

**Comment by Sunoo** [comment]
Being able to have a setting to include everything in skippedIfSameState would be nice, since that is how I would use it.

**Comment by det-box** [comment]
Sorry, the error was due to wrong configuration

**Comment by nicoduj** [comment]
hi,
@carsten-h 
@det-box 

In 0.0.8 you MUST add a config key like this even if you don't want to use the option :
"skipedIfSameStateActivities" : []

I will fix this in the next version (in order to make it optionnal), as well as being able to include all activites by default. - see #21

**Comment by carsten-h** [comment]
Yes, this is correct, adding the option "skipedIfSameStateActivities" is working fine!

Thank you!

**Comment by nicoduj** [comment]
@Sunoo : check latest version, I have added the option you were asking for.

**Comment by Nastras** [comment]
It works for me 👍
