### ISSUE TITLE
Second Hub - wants setup code

### ISSUE THREAD

**Issue by reffr** [nicoduj/homebridge-harmony#200]
I'm trying to add my second hub. If I manually go to add the second hub (from the Home app on iOS) it sees the second hub. I try to add it but it wants a setup code.  What is the code or what am I doing wrong?

Thanks,
Rob
   {
            "platform": "HarmonyHubWebSocket",
            "name": "Greatroom",
            "hubIP": "192.168.1.118",
            "otherPlatforms": [
                {
                    "name": "Theater Room",
                    "hubIP": "192.168.1.145"
                }
            ]
        }
    ]
}

**Comment by nicoduj** [comment]
Hi,

the code is written in homebridge log, at startup.

**Comment by reffr** [comment]
Thank you so much for the quick response and the help. Sorry I missed that detail!!!!

Take care great plug in!
Rob

**Comment by nicoduj** [comment]
you're welcome, thank you for the support :)
