### ISSUE TITLE
[FEATURE] Possibility to control other HomeKit device by Harmony remote?

### ISSUE THREAD

**Issue by mensa84** [nicoduj/homebridge-harmony#201]
Hello,

is it possible to control another HomeKit device by a button on the Harmony remote?

For example when I am in activity "TV" and press the button 0 on my Harmony remote my Nuki door lock should unlock the door.

Maybe this i currently already possible?

Or would it be possible in the future for example with a fake device/switch which activates when I press for example button 0 on my remote? If one have that fake switch for a device it will be easy to create an automation in HomeKit which would do the rest (unlock door).

Is that possible?
Or is that absolutely impossible and why?

**Comment by jimsmt** [comment]
You should use a hue light emulator to create several fake hue lights, connect them to harmony hub, then you will be able to control these fake switches using the home automation buttons on your harmony remote

**Comment by mensa84** [comment]
Thank you, I know about that "workaround". But the big problem is, if I would do that, that then I can not connect my Harmony directly to my real hue bridge. And if I would connect my real hue bridge to the fake bridge, then I would have to maintain everything in two systems, that is not really helpful.

So I am looking for another solution. But thanks again for your help.

**Comment by nicoduj** [comment]
Hi.

The main problem to achieve what you want is the fact that the hub does not give any feedback on device / commands pressed on the physical remote. We are only notified as far as I know with activities changes. Thus, it is not possible to respond to a button press in the plugin, except for thoses buttons which are linked to a home device in harmony app, only on some remotes and on dedicated buttons. The "trick" that was given by @gitgayhub is so the best way to achieve what you want I think.

**Comment by mensa84** [comment]
Ok, understand, thank you!
Are you also not informed if a device is truned on or off? Only activity change gets you informed?

**Comment by nicoduj** [comment]
Yep, only activity changes, that is also why I have not implemented the "device" mode as a TV accessory I was thinking about :(

**Comment by mensa84** [comment]
Thanks for your quick replies :)
Maybe anyone else will have a good idea, then please post here :)
But currently it seems impossible, how sad.
