### ISSUE TITLE
[BUG]"showTurnOffActivity" wrong config via UI X

### ISSUE THREAD

**Issue by JacVid** [nicoduj/homebridge-harmony#203]
**Describe the bug**
No matter the choice in the Show TurnOff activity, the Power Off is still available in Home App when the "Publishswitch activities as indivdual accessories" is set to ON.

**To Reproduce**
When UI X is used for Config "..." is added in the "showTurnOffActivity" => "false",

**Expected behavior**
When set to None or Flase, the Power Off switch should not be visible.

**Screenshots**

**IOS (please complete the following information):**
- Version 13.2.2
- Device: iPhone SE

**Logs**
Your log in debug mode (-D option)

**Config**
        {
            "name": "Harmony",
            "hubIP": "10.0.1.123",
            "cleanCache": true,
            "TVAccessory": false,
            "switchAccessories": true,
            "activitiesToPublishAsAccessoriesSwitch": [
                "Regarder CanalSat",
                "Utiliser l'Apple TV"
            ],
            "showTurnOffActivity": "false",
            "publishSwitchActivitiesAsIndividualAccessories": true,
            "platform": "HarmonyHubWebSocket"
        },

**Additional context**
 A bug in the UI X config. When it is done directly in the config file, everthing works well.

**Comment by nicoduj** [comment]
Thanks for reporting, should be fixed in 1.2.1 . I did not changed the config for configUI, I add some logic to better handle this hybrid option (bool / enum).
