### ISSUE TITLE
Multiple Hubs (3 Hubs)[BUG]

### ISSUE THREAD

**Issue by QcVictor** [nicoduj/homebridge-harmony#206]
**Describe the bug**
3 hubs  does not work using this template...

**To Reproduce**
Add 3 hubs doesn't work with config below, if I remove the third hub in the config file everything is ok !
**Expected behavior**
See third hub appear !
**Screenshots**

**IOS (please complete the following information):**
Latest

**Logs**
Your log in debug mode (-D option)

**Config**
{
    "bridge": {
        "name": "BridgeTestHarmony",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51827,
        "pin": "012-34-567"
    },
    "description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",
    "ports": {
        "start": 52100,
        "end": 52150,
        "comment": "This section is used to control the range of ports that separate accessory (like camera or television) should be bind to."
    },
    "accessories": [],
    "platforms": [
        {
            "platform": "HarmonyHubWebSocket",
            "name": "Cuisine",
            "hubIP": "10.0.0.20",
            "mainActivity": "Regarder La TV",
            "otherPlatforms": [
                {
                    "name": "Salon",
                    "hubIP": "10.0.0.21",
                    "mainActivity": "Watch TV Salon",
                    "otherPlatforms": [
                        {
                            "name": "Sous-Sol",
                            "hubIP": "10.0.0.24",
                            "mainActivity": "Projecteur-Ampli"
                        }
                    ]
                }
            ]
        }
    ]
}

**Additional context**

**Comment by nicoduj** [comment]
Hi,

otherPlatforms is not an inception :) Here is the cofnig that should work :  

```json
{  
   "platforms":[  
      {  
         "platform":"HarmonyHubWebSocket",
         "name":"Cuisine",
         "hubIP":"10.0.0.20",
         "mainActivity":"Regarder La TV",
         "otherPlatforms":[  
            {  
               "name":"Salon",
               "hubIP":"10.0.0.21",
               "mainActivity":"Watch TV Salon"
            },
            {  
               "name":"Sous-Sol",
               "hubIP":"10.0.0.24",
               "mainActivity":"Projecteur-Ampli"
            }
         ]
      }
   ]
}

```

**Comment by QcVictor** [comment]
Awesome thanks for the quick reply and this great plugin, someday I will learn to code ;-)
