### ISSUE TITLE
How/Why did this happen?

### ISSUE THREAD

**Issue by costispavlou** [nicoduj/homebridge-harmony#208]
Don’t really know how this occurred but heres a screenshot 

![1779AB70-707A-4C30-ACA2-7E0D942FA7F0](https://user-images.githubusercontent.com/57916603/70467753-74992480-1ace-11ea-9039-5cb5985e9d17.png)

**Comment by nicoduj** [comment]
Hi, could you at least share your config ? Your logs? Is it on an external device or main one ? Was there an homebridge reboot ? Hub config change ? Mostly it happened because input services were not published in the right way ... but giving so few context, I can’t help you !

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by costispavlou** [comment]
name": "HarmonyHub",
            "hubIP": "192.168.0.28",
            "TVAccessory": true,
            "switchAccessories": true,
            "publishGeneralMuteSwitch": true,
            "devicesToPublishAsAccessoriesSwitch": [
                "LG Climate;PowerOn",
                "LG Climate;PowerOff",
                "Philips TV",
                "PS4",
                "Cablenet",
                "infomir DVR",
                "Pioneer"
            ],
            "publishDevicesAsIndividualAccessories": true,
            "showCommandsAtStartup": true,
            "platform": "HarmonyHubWebSocket"
        }

**Comment by costispavlou** [comment]
![DC085514-49C0-49F2-BF3B-412E808DD4FA](https://user-images.githubusercontent.com/57916603/70469924-ac09d000-1ad2-11ea-9d16-c3c9277e6693.png)

**Comment by costispavlou** [comment]
Ip changed to 16. That fixed it, but same issue with the harmony button though

**Comment by costispavlou** [comment]
Fixed by removing the switch accessories from true to false
