### ISSUE TITLE
Nothing Appearing in Homekit

### ISSUE THREAD

**Issue by mattangelofdeth** [nicoduj/homebridge-harmony#209]
Hello, thanks so much for the great plugin.
I appear to be having an issue where home doesn't appear to be showing any harmony devices / activities.

My config is as follows:

  {
    "platform": "HarmonyHubWebSocket",
    "name": "Rumpus",
    "hubIP": "192.168.1.55",
    "publishAllTVAsExternalAccessory" : true,
    "otherPlatforms": [{
      "name": "Main Bedroom",
      "hubIP": "192.168.1.56",
      "publishAllTVAsExternalAccessory" : true
      }]

Any advice would be greatly appreciated!

Thanks and Merry Christmas

**Comment by nicoduj** [comment]
Hi, since you set publishAllTVAsExternalAccessory to true, you need to add them manually in home app.

I made a video on twitter : https://twitter.com/dujnic/status/1110644949027041282?s=21

**Comment by mattangelofdeth** [comment]
Thanks for the reply.
I’m a little lost though. How do I add them manually? Do you mean add an accessory in HomeKit or specify them manually in the json ?
Is there an easier way to publish all the activities automatically?

________________________________

**Comment by nicoduj** [comment]
Hi, did you watch the video on Twitter ? With your config, launch homebridge. You will see in the log a setup code for your device . In home app, add a new device, choose enter setup code, your deivce will be listed, add it by entering the code. Repeat for each device (same code) .

Please notice that the option "publishAllTVAsExternalAccessory" in subplatform is not necessary.

**Comment by mattangelofdeth** [comment]
Thanks again 
When entering the homebridge accessory setup code, none of the harmony devices show up.  The code I’m entering is the standard code that’s used when I initially setup homebridge and linked it to HomeKit.
I must be doing something wrong.

**Comment by nicoduj** [comment]
Ok, so first of all, do you have any other homebridge device exposed on the same hub that is a tv accessory ? If not, remove option publishAllTVAsExternalAccessory (in both platform and subplatform).

This way, your first harmony hub will be added automatically, but you will still need to add second one manually. the setup code is the same indeed, it is expected behavior.

Please share your logs if you still have troubles.

**Comment by mattangelofdeth** [comment]
Thanks Nicholas
No joy unfortunately. I’m running sysmd so logs haven’t really been setup correctly as of yet. I’ll have to sort that and post.

**Comment by nicoduj** [comment]
Maybe you should try with only one hub at first. Be sure to have static ip set on your hubs.
Let me know once you have your logs.

**Comment by mattangelofdeth** [comment]
Yep. Removed 2nd hub. Have static’s. Still no joy.
I’ll try and fix logs and post again.

Thanks for your speedy help!

**Comment by nicoduj** [comment]
Do you have any other plugin that works on this homebridge instance ? Did you try with switch mode ? 

```json
  {
    "platform": "HarmonyHubWebSocket",
    "name": "HubName",
    "hubIP": "192.168.1.XX",
    "TVAccessory" : false,
    "switchAccessories" : true
  }
```

**Comment by mattangelofdeth** [comment]
Thanks so much! I resolved this. For some reason, my homebridge systemd config didn't save and so homebridge wasn't operating in insecure mode!

Once I added the -I argument, it all kicked into gear. Thanks again for your help
