### ISSUE TITLE
ECONNREFUSED

### ISSUE THREAD

**Issue by jahnkenneth** [nicoduj/homebridge-harmony#210]
Hello,

after the latest update I'm getting ECONNREFUSED.
I have three Harmony-hubs, and the plugin was working prior to this update.

My set up is as follows:
 "platforms": [
        {
            "name": "Stue",
            "hubIP": "192.168.68.113",
            "otherPlatforms": [
                {
                    "name": "loftstue",
                    "hubIP": "192.168.68.104"
                },
                {
                    "name": "hovedsoverom",
                    "hubIP": "192.168.68.112"
                }
            ],
            "platform": "HarmonyHubWebSocket"
        },

Log:
[List Rooms] connect ECONNREFUSED 127.0.0.1:51826
[List Accessories] connect ECONNREFUSED 127.0.0.1:51826

I have double checked the IP´s, and they are correct. They have a fixed IP on my router.

**Comment by jahnkenneth** [comment]
Problem with HOOBS

**Comment by nicoduj** [comment]
Hi, thanks for reporting,  what was the hoobs problem ? Just for others just in case ;)

**Comment by jahnkenneth** [comment]
An old platform in the config... I had uninstalled the plugin, but not removed it from the config. :-)
