### ISSUE TITLE
[BUG] 2nd & 3rd Hub in Homebridge Not Converting to Switch Accessory

### ISSUE THREAD

**Issue by TejasAntani** [nicoduj/homebridge-harmony#212]
**Describe the bug**
Installed 2nd and 3rd hub as TV accessories.  Looking to convert them to switch accessories to get each input as it's own icon.  When I switch the setting from TV to switch accessory in the config UI and save, the accessory in homekit doesn't change for the 2nd and 3rd hubs.  They did change in the first hub.  I ran a clear cache and it still did not help.

**To Reproduce**
See above

**Expected behavior**
All inpouts on all hubs change to switches.

**IOS (please complete the following information):**
- Version [13.3]
- Device: [iPhone 11 Pro]

**Config**
        {
            "name": "Media Room",
            "hubIP": "192.168.1.2xx",
            "cleanCache": false,
            "switchAccessories": true,
            "showTurnOffActivity": "stateless",
            "publishSwitchActivitiesAsIndividualAccessories": true,
            "otherPlatforms": [
                {
                    "name": "Living Room Hub",
                    "hubIP": "192.168.1.1xx"
                },
                {
                    "name": "Master Bedroom",
                    "hubIP": "192.168.1.2xx"
                }
            ],
            "platform": "HarmonyHubWebSocket"
        }

**Comment by TejasAntani** [comment]
UPDATE: I found that I have to select the settings individually for each hub under the "other hubs" section.  Now I see all the accessory switches.  Sorry!

However, even with clean cache turned on I still see the old TV accessories.  Thanks for the help!

**Comment by nicoduj** [comment]
Hi,

Indeed you do need to specify option for each hub, so they can behave differently.

Concerning your remaining TV accessories, since they were added externally you have to remove them manually in home app (long press them and just remove them).

Enjoy the plugin :) 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by TejasAntani** [comment]
Fantastic thank you. Question - how does the notion of volume control work when your activities are set up as accessories? Is volume still an option?

**Comment by nicoduj** [comment]
Volume only works in the remote widget through tv accessory. With switch accessory you can still publish a command switch fort the device you want to control (one for up command, one for down, and maybe one for mute) .

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
