### ISSUE TITLE
Eposed TV not shown on all devices

### ISSUE THREAD

**Issue by Phoenix-DH** [nicoduj/homebridge-harmony#215]
Hey,

since a few days I am experiencing that the exposed TV remote on my devices is not shown on all....

On my iPhone it is missing... on the other 2 additional devices, an iPhone and an iPad it is vissible.

All is working on all devices except the remote is not vissible.

I have no clue to track this issue ...
All are on the same ip range ... same than all devices.

Does anybody else had the same?

**Comment by nicoduj** [comment]
Hi, did you just try to reboot your faulty iOS device ? Seems to be a bug on iOS I think.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Phoenix-DH** [comment]
Sure ... multiple times ...
Sure there must be an iOS issue.

Only want to know if somebody has an idea what I can do or had the same.

**Comment by nicoduj** [comment]
Are you on the same WiFi network ? (Multiple access points maybe ?) as far as I know it uses bonjour protocol so maybe your iOS device does not discover it . 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Phoenix-DH** [comment]
Yes ... Strange .... Actually visible now 😂

**Comment by Phoenix-DH** [comment]
Seems that I got it right now...
By ubiquiti needs a downgrade because there was a bug in the fw.
Since then no problems anymore.
