### ISSUE TITLE
Mutiple Hub showing extra TV

### ISSUE THREAD

**Issue by sdorilas** [nicoduj/homebridge-harmony#216]
**Describe the bug**
Using multiple hubs. One TV is showing twice in Homekit but cannot actually control device

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**
Homekit should only display two televisions, not 3. Should also be able to control device.

**Screenshots**
![D315EBF3-7122-41CC-9326-AB510D2ADBC8_1_105_c](https://user-images.githubusercontent.com/19697514/72580614-b629a600-38aa-11ea-8f39-97e801a842d1.jpeg)

![B822F81C-5902-4B49-83AC-1458C6DCDE57_1_105_c](https://user-images.githubusercontent.com/19697514/72580638-c17cd180-38aa-11ea-8536-f4e7244e3d9b.jpeg)

**IOS (please complete the following information):**
- Version [13.3]
- Device: [iPhoneXR]

**Logs**
Your log in debug mode (-D option)

**Config**
{
            "platform": "HarmonyHubWebSocket",
            "name": "Living_Room",
            "hubIP": "192.168.1.xxx",
            "otherPlatforms": [
                {
                    "name": "Master_Bedroom",
                    "hubIP": "192.168.1.xxx",
                    "mainActivity": "Watch TV"
                }
            ],
            "publishAllTVAsExternalAccessory": true,
            "mainActivity": "Watch TV",
            "plugin_map": {
                "plugin_name": "homebridge-harmony"
            }

**Additional context**

**Comment by nicoduj** [comment]
Hi, you are publishing everything as external device, I think you might have publish this tv once with a different name . Did you simply try to remove the faulty one on home app manually (long press / settings / delete ) ? External devices not published anymore needs to be removed manually .

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sdorilas** [comment]
Yes, publishing all as external. Both TVs had a different name prior. I added the underscore to both names in order to remove the space between characters. I cannot manually remote from home app. No delete option under settings for the device in question.

**Comment by nicoduj** [comment]
Check in hub section in home app maybe, don’t remember where it is in ios13 but should be somewhere (see #124 ) .

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nicoduj** [comment]
And if you changed the option publish allas external in the same time while renaming, maybe this broken tv device is the first one that you were adding before , and this maybe still in the cache of homebridge. If this is the case, check your homebridge logs to see if it publish it, and if so try first a simple reboot of homebridge . You can also confirm that hypothesis by going to the hub section in home app and see if this ghost device is listed attached to your homebridge hub. 
If nothing works you can still try to stop homebridge, add option cleancache, restart , put it back to off, and restart again . 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sdorilas** [comment]
﻿
﻿Unfortunately I can’t remove any individual device from the homebridge. I can view the device when navigating to the hub but no option to remove.  I did the cleancache true then false a couple times, while stopping and running service in between...nothing. I did notice my working Television is on Living_Room, whereas the one not working is on the older name of Living Room.

**Comment by nicoduj** [comment]
Can you post a screenshot of the properties pane of this tv device , at the very bottom after force touching it, just below the information pane with manufacturer and so on ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sdorilas** [comment]
Non Working Tv:


Working TV:

**Comment by sdorilas** [comment]
![82DCF6D3-743F-484A-A093-7CEBDAAC81C8](https://user-images.githubusercontent.com/19697514/72588101-33faab00-38c5-11ea-81cc-38920662b33a.png)
![4889AD9C-D8F2-4BAC-990A-EBB1B30B166E](https://user-images.githubusercontent.com/19697514/72588102-34934180-38c5-11ea-8e5e-48eae113cd2f.png)

**Comment by sdorilas** [comment]
![1AA21899-0679-4121-8782-42CC7BE80CDB](https://user-images.githubusercontent.com/19697514/72588166-6dcbb180-38c5-11ea-921e-f8166d7bbdcf.png)

**Comment by nicoduj** [comment]
Thank you. Is it listed in hub devices list in the global home options ? (Go to details of homebridge hub in hub section) I would also need homebridge startup log in debug please

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sdorilas** [comment]
It is listed there. And how do I go about getting the log files?

![042A207B-4BBC-4CAA-B170-6EDA881D5D89](https://user-images.githubusercontent.com/19697514/72588708-247c6180-38c7-11ea-8dfd-dd15aeedbb08.png)

**Comment by jmbwell** [comment]
I just added a second hub, and I’m seeing this behavior too. My original hub started showing up with each activity appearing as a separate device/tile. The new hub worked, however. But then I updated node and homebridge and the plugin (from HEAD), and now both are exhibiting the behavior. 

![FA4E15F6-2352-46F4-AE3A-4238B5933FA8](https://user-images.githubusercontent.com/32799077/72657641-5398de80-396c-11ea-9f8a-309c30e34fd7.png)
![F65E9F47-D7A0-42E4-B8B7-B31AEB503871](https://user-images.githubusercontent.com/32799077/72657642-5398de80-396c-11ea-9b78-9b2144e4a56a.png)
![C852CD43-6128-403D-BEFA-41B84728CA8D](https://user-images.githubusercontent.com/32799077/72657643-54317500-396c-11ea-89b1-6e2db8d851b4.png)
![89F84F7B-F8E2-4CEF-B85C-9CC622E61B35](https://user-images.githubusercontent.com/32799077/72657644-54317500-396c-11ea-8002-669c28ca1d56.png)

[screen is terminating]
root@c0eae8d1-8ec1-e5f5-bdf6-b8a98ec08bd7:~# cat log.log 
[1/18/2020, 2:56:55 AM] Loaded config.json with 0 accessories and 2 platforms.
[1/18/2020, 2:56:55 AM] ---
[1/18/2020, 2:56:55 AM] Loaded plugin: homebridge-harmony
[1/18/2020, 2:56:55 AM] Registering platform 'homebridge-harmonyHub.HarmonyHubWebSocket'
[1/18/2020, 2:56:55 AM] ---
[1/18/2020, 2:56:55 AM] Loading 2 platforms...
[1/18/2020, 2:56:55 AM] [Living Room] Initializing HarmonyHubWebSocket platform...
[1/18/2020, 2:56:55 AM] [Living Room] HarmonyPlatform Init
[1/18/2020, 2:56:55 AM] [Living Room] undefined
[1/18/2020, 2:56:55 AM] [Bedroom] Initializing HarmonyHubWebSocket platform...
[1/18/2020, 2:56:55 AM] [Bedroom] HarmonyPlatform Init
[1/18/2020, 2:56:55 AM] [Bedroom] undefined
[1/18/2020, 2:56:55 AM] Loading 0 accessories...
[1/18/2020, 2:56:55 AM] [Bedroom] WARNING - configureAccessory - TV accessory added in your bridge from cache, if another plugin is exposing a TV accessory this one might not be visible in your remote widget
[1/18/2020, 2:56:55 AM] [Bedroom] WARNING - configureAccessory - The platform Living Room is not there anymore in your config (name property). It won't be loaded and will be removed from cache.
Setup Payload:
X-HM://0023ISYWPHKMH
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
                                                      
Or enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-145 │     
    └────────────┘     
                       
[1/18/2020, 2:56:55 AM] [Living Room] DidFinishLaunching
[1/18/2020, 2:56:55 AM] [Living Room] INFO - Loading activities...
[1/18/2020, 2:56:55 AM] [Bedroom] DidFinishLaunching
[1/18/2020, 2:56:55 AM] [Bedroom] INFO - Loading activities...
[1/18/2020, 2:56:55 AM] Homebridge is running on port 51826.
[1/18/2020, 2:56:57 AM] [Living Room] INFO - Adding Accessory : Living Room-TV
[1/18/2020, 2:56:57 AM] [Living Room] (Living Room)INFO - configuring Main TV Service
[1/18/2020, 2:56:57 AM] [Living Room] (Living Room)INFO - Creating TV Service
[1/18/2020, 2:56:57 AM] [Living Room] (Living Room)INFO - Creating Input Service - ROKU
[1/18/2020, 2:56:57 AM] [Living Room] (Living Room)INFO - Configuring Main Activity AppleTV
[1/18/2020, 2:56:57 AM] [Living Room] (Living Room)INFO - Creating TV Speaker Service
[1/18/2020, 2:56:57 AM] [Living Room] (Living Room)INFO - Creating Input Service - AppleTV
[1/18/2020, 2:56:57 AM] [Living Room] (Living Room)INFO - Creating Input Service - PS3
[1/18/2020, 2:56:57 AM] [Living Room] WARNING - setupFoundAccessories - TV accessory added in your bridge, if another plugin is exposing a TV accessory this one might not be visible in your remote widget
[1/18/2020, 2:56:57 AM] [Bedroom] (Bedroom)INFO - configuring Main TV Service
[1/18/2020, 2:56:57 AM] [Bedroom] (Bedroom)INFO - Configuring Main Activity AppleTV
[1/18/2020, 2:57:02 AM] Got SIGINT, shutting down Homebridge...
[1/18/2020, 2:57:02 AM] [Living Room] INFO - shutdown
root@c0eae8d1-8ec1-e5f5-bdf6-b8a98ec08bd7:~#

**Comment by sdorilas** [comment]
Welcome. Sorry to hear that but glad I’m not alone. It will get sorted.

**Comment by sdorilas** [comment]
So I just checked and it’s fixed!! I’ve done nothing and it resolved itself. Best of luck.

**Comment by jmbwell** [comment]
Mine is correct now too. Of course, I’ve been fiddling with it, so I don’t know what would have changed.

**Comment by nicoduj** [comment]
Hi, as I thought it is some HomeKit sync issue . Since ios13 I have seen such strange behaviors, glad to know everything is back to normal !

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
