### ISSUE TITLE
npm ERR! missing: websocket@latest, required by harmony-websocket@1.5.0

### ISSUE THREAD

**Issue by mensa84** [nicoduj/homebridge-harmony#220]
Hello,

after upgrading to latest 1.2.4 version I get following error, do you know why and how to solve this?

```
root@Server:~# npm list -g --depth=0
/usr/lib
├── homebridge@0.4.50
├── homebridge-automation-switches@3.2.1
├── homebridge-cmdtrigger@0.3.2
├── homebridge-harmony@1.2.4
├── homebridge-http-webhooks@0.0.57
├── homebridge-mi-outlet@0.3.0
├── homebridge-people@0.6.2
├── homebridge-soundtouch@5.3.1
├── homebridge-tplink-smarthome@4.0.1
├── miio@0.15.6
└── npm@6.13.6

npm ERR! missing: websocket@latest, required by harmony-websocket@1.5.0
npm ERR! missing: websocket-as-promised@latest, required by harmony-websocket@1.5.0
```

**Comment by nicoduj** [comment]
Why do you do —depth =0 ? My plugin rely only on harmony-websocket which depends on other libs . The plugin does not work ? I had previously the dep in my package.json but since that might cause some deep problems and I don’t use them directly I removed it 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mensa84** [comment]
First of all: The plugin is working and I am very thankful that it exists!

I found this "--depth=0" anywhere in the internet and I liked it, because then I only see the installed homebridge plugins.

Now I did uninstall homebridge-harmony and reinstalled and that errors are gone! Perfect.

I only saw that permission errors, do you know why? I ran it as root and withouth any sudo:

```
root@Server:~# npm -g install homebridge-harmony

> websocket@1.0.31 install /usr/lib/node_modules/homebridge-harmony/node_modules/websocket
> (node-gyp rebuild 2> builderror.log) || (exit 0)

**sh: 1: cannot create builderror.log: Permission denied**
+ homebridge-harmony@1.2.4
added 519 packages from 876 contributors in 33.006s

root@Server:~# npm list -g --depth=0
/usr/lib
├── homebridge@0.4.50
├── homebridge-automation-switches@3.2.1
├── homebridge-cmdtrigger@0.3.2
├── homebridge-harmony@1.2.4
├── homebridge-http-webhooks@0.0.57
├── homebridge-mi-outlet@0.3.0
├── homebridge-people@0.6.2
├── homebridge-soundtouch@5.3.1
├── homebridge-tplink-smarthome@4.0.1
├── miio@0.15.6
└── npm@6.13.6
```

**Comment by nicoduj** [comment]
The build log could not be wirtten, maybe you did not have the rights while building the dependency.
npmcache behaves strangely sometimes, I think it might have cahced previous dependency .

**Comment by Nastras** [comment]
I had not seen that it had already been reported. Sorry. I reinstalled it and now the bug is gone.

Thank you!
