### ISSUE TITLE
missing: websocket@latest and missing: websocket-as-promised

### ISSUE THREAD

**Issue by Nastras** [nicoduj/homebridge-harmony#221]
Hello @nicoduj 

FYI: I just noticed after the update on v1.2.4 is set when calling sudo npm list -g --depth=0

<img width="1058" alt="Bildschirmfoto 2020-01-25 um 14 13 44" src="https://user-images.githubusercontent.com/27686185/73122547-805d7f00-3f86-11ea-9ec2-105c9628cd2e.png">

these missing packages are displayed at the end.

I'm not sure if it will affect your plugin?

Greetings Nastras

**Comment by nicoduj** [comment]
Hi,

see #220 , I removed unnecessary dependencies but seems that npm cache is messing up at some point. you can try reinstall again , but it should not be a problem if the dep is correctly there for harmony-websocket (which you don't see since you added a --depth=0 parameter)
