### ISSUE TITLE
“An Accessory is Controlled” automation triggers are not being triggered

### ISSUE THREAD

**Issue by jqnatividad** [nicoduj/homebridge-harmony#222]
**Describe the bug**
I’m trying to trigger my shades to close when the Harmony TV device or any of the activity switches are turned on, but the triggers are not being fired.

**To Reproduce**
Create “An Accessory is Controlled” trigger on the Harmony TV service or any activity switches.

**Expected behavior**
The On/Off trigger will fire accordingly.

**IOS (please complete the following information):**
- Version 13.3
- Device: iPhone 8s plus, iPad Pro

**Config**
```
     {
            "platform": "HarmonyHubWebSocket",
            "plugin_map": {
                "plugin_name": "homebridge-harmony"
            },
            "hubIP": "192.168.1.29",
            "name": "Harmony",
            "TVAccessory": true,
            "mainActivity": "AppleTV",
            "switchAccessories": true,
            "activitiesToPublishAsAccessoriesSwitch": [
                "AppleTV",
                "Karaoke",
                "Chromecast",
                "Wii U",
                "Broadcast TV"
            ],
            "publishAllTVAsExternalAccessory": false,
            "cleanCache": false,
            "publishGeneralMuteSwitch": true
        }

```
**Additional context**
Using v1.2.4 of this plugin, running on Hoobs 3.1.20

**Comment by nicoduj** [comment]
Hi,

as far as I understand, you are trying to do an automation in Home app that reacts to a switch / input change correct ? 

Are you seing the same behavior if you trigger the activity through harmony remote and through home app ? 

Are you sure at all automations are working (there are known problems with automations on ios 13.3 dependending on hubs / versions / beta enrollment ...)

**Comment by jqnatividad** [comment]
Hi,
Thanks for the quick response and all your work!  And yes, I’m trying the automation from the Home app to react to the on/off state of the switches.

I originally did the shade automation by leveraging the Home Control features of Harmony when defining an Activity, but I found that once I do that for an Activity, I’d get this error on the HOOBS log if I try to invoke it from HomeKit.

`[Harmony] (Harmony)ERROR - activityCommand : could not SET status, no data`

If I remove the shade automation on Harmony, it would work again on Homebridge.

That’s why I’m trying to set the automation on the Home app.

As for my HomeKit setup, I have 2 Apple TV 4Ks and 2 paired homepods which are serving as HomeKit hubs.  The Apple TV 4Ks are setup to accept Beta software.  The Homepods are running on GA 13.3, and the Apple TV’s are running 13.3.1 (17K5795a), with one of the paired Homepods often taking on the Master hub role, and the rest on standby.

HOOBs is running on a Raspberry Pi 3 CanaKit (Model B Quad-Core 1.2 GHz 1gb RAM)

**Comment by nicoduj** [comment]
On my experience all automations stopped working when I had hub (Apple TV) on 13.3 and my iPad on 13.3.1 beta . I had to remove my iPad from HomeKit hubs to have them work again. Can you try other automations to see if they work ,like triggering a light when another is set on or something like that ? Concerning your try with harmony, I am interested in more details if you want in order to see if I can do something !

**Comment by jqnatividad** [comment]
I just removed myself from the TVos beta based on your recommendation...  Hopefully, some of these problems will disappear once my Apple TVs are on GA.

As for Harmony/Homekit automation in general, I can confirm that none of the Harmony switches trip the On/Off automation triggers in the Home app even if the Harmony Activity is successfully invoked...

What details can I provide to help you troubleshoot why the automation triggers are not being invoked?

**Comment by nicoduj** [comment]
Hi, did you try any automation that does not involve harmony ? Just to be sure . And moreover getting out of beta won’t make your Apple TV back on non beta . You must remove it as HomeKit hub and let only hubs in your home that are on non beta to check if it is the cause of your problem.

Unfortunately if the switch is working well I have no way to debug the automation since it is in HomeKit not on homebridge / my plugin

**Comment by jqnatividad** [comment]
Hi, I have a fairly complicated setup with about 60 accessories and a similar number of automations in the Home app and Eve.  Several of those automations are trigger automations that work without a problem, and right now, its only the Harmony trigger automations that do not fire.

Let me see if I can eliminate some possible causes and I’ll report my findings here.

**Comment by nicoduj** [comment]
Ok, let’s try maybe with other actions than your shades also . I have some here that works in home app (with smart plugs or hue lights as target, made in home not as a shortcut)

**Comment by jqnatividad** [comment]
Hi @nicoduj , just wanted to let you know that the issue has been resolved!

I don't know the exact root cause, but it must have been a symptom of one of my other accessories not working...
