### ISSUE TITLE
[Questions]Control Light buttons with the plugin?

### ISSUE THREAD

**Issue by QcVictor** [nicoduj/homebridge-harmony#223]
Can I control Light buttons on my harmony companion with the plugin?
**Describe the solution you'd like**
Being able to send http call, with light button "long and short press" with the remote

**Comment by nicoduj** [comment]
High, not really sure to understand what you mean. If you are talking about home controls on harmony remote there is an option to bind them to a switch in home app through the plugin (see readme). No long / short press however , and it won’t make any http call, only send the command to the hub that is linked to that button in harmony configuration . 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by QcVictor** [comment]
Thanks for the reply, need http call for control my stuff...
