### ISSUE TITLE
Homekit remote buttons

### ISSUE THREAD

**Issue by maisun** [nicoduj/homebridge-harmony#224]
Hi,
I have a question regarding the button list in HomeKit remote:
REWIND
FAST_FORWARD
NEXT_TRACK
PREVIOUS_TRACK
ARROW_UP
ARROW_DOWN
ARROW_LEFT
ARROW_RIGHT
SELECT
BACK
EXIT
INFORMATION
PLAY
PAUSE
VOLUME_UP
VOLUME_DOWN
MUTE
SETUP

I can only see few of them in my remote. I can't find things like next/previous track, mute, rewind/ff etc. Is it possible to define the layout of the remote or do I miss something in my configuration? Thanks
<img width="253" alt="Screenshot 2020-02-10 at 21 39 56" src="https://user-images.githubusercontent.com/5745785/74188293-6f7f5f80-4c4e-11ea-94e0-2ab540996edf.png">

**Comment by nicoduj** [comment]
Hi, the remote is fixed, sorry ! I have exposed every command available at api level but only some are there . Volume are bond to physical buttons when the remote is on the screen . I think some gestures are there for some commands but I am not sure , not using it very often myself !



<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
