### ISSUE TITLE
playPauseBehavior vs Play/Pause

### ISSUE THREAD

**Issue by maisun** [nicoduj/homebridge-harmony#225]
Hi, sorry I have another question.
I use Kodi which support play, pause and play/pause command. Should I override the Play/Pause button to use play/pause command from Kodi or it's better to use playPauseBehavior?
If I use playPauseBehavior what if the play state is changed from other channels (Harmony remote for example)?
Thank you in advance!

**Comment by nicoduj** [comment]
Hi again. If you have separate commands use them . If the plugin handle play pause behavior it won’t be aware of external changes and will send play and pause in sequence no matter what happened somewhere outside its world ;)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by maisun** [comment]
> Hi again. If you have separate commands use them . If the plugin handle play pause behavior it won’t be aware of external changes and will send play and pause in sequence no matter what happened somewhere outside its world ;)
> 
> Sent with [GitHawk](http://githawk.com)

Hi Nicoduj,
Thank you! So you recommend to use play/pause command instead of playPauseBehavior, right?

**Comment by nicoduj** [comment]
Hi, sorry for my late reply. If you have separate play pause command , yes .

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
