### ISSUE TITLE
Control Center Remote 

### ISSUE THREAD

**Issue by GRClark** [nicoduj/homebridge-harmony#228]
Trying to take advantage of control center remote for Harmony connected television.  So far I can’t get past the searching phase.  Is there something I need to set?  I’ve got three settings that are blank that I don’t know if they should be set and what to set them as.  

-Activities to Publish As Input for Tv Mode
-Remote Override Commands List
-Activities to Publish As Accessories Switch

![54964F75-94B5-4DD2-BF0C-7BCF69D8E73B](https://user-images.githubusercontent.com/5118059/75389837-3cc3a100-58b5-11ea-8ed5-649153b684fa.png)

**Comment by nicoduj** [comment]
Hi, can you post your config please ? Do you see your tv accessory in home app ?

**Comment by GRClark** [comment]
I do not see tv accessory in Home app.  

{
  "activitiesToPublishAsAccessoriesSwitch" : [

  ],
  "activitiesToPublishAsInputForTVMode" : [

  ],
  "addAllActivitiesToSkippedIfSameStateActivitiesList" : true,
  "cleanCache" : false,
  "devicesToPublishAsAccessoriesSwitch" : [

  ],
  "homeControlsToPublishAsAccessoriesSwitch" : [

  ],
  "hubIP" : "10.0.0.23",
  "mainActivity" : "Watch TV",
  "name" : "Harmony Hub",
  "numberOfCommandsSentForVolumeControl" : 5,
  "otherPlatforms" : [

  ],
  "platform" : "HarmonyHubWebSocket",
  "playPauseBehavior" : true,
  "plugin_map" : {
    "plugin_name" : "homebridge-harmony"
  },
  "publishAllTVAsExternalAccessory" : true,
  "publishDevicesAsIndividualAccessories" : true,
  "publishGeneralMuteSwitch" : true,
  "publishHomeControlsAsIndividualAccessories" : true,
  "publishSequencesAsIndividualAccessories" : true,
  "publishSwitchActivitiesAsIndividualAccessories" : true,
  "remoteOverrideCommandsList" : [

  ],
  "sequencesToPublishAsAccessoriesSwitch" : [

  ],
  "showCommandsAtStartup" : true,
  "skippedIfSameStateActivities" : [

  ],
  "switchAccessories" : true,
  "TVAccessory" : true
}

**Comment by nicoduj** [comment]
Since you set "publishAllTVAsExternalAccessory" : true, you have to add it manually through home app. Please read readme carrefully to see if you need to set this option to true

**Comment by GRClark** [comment]
So if I set this option to false will that correct the issue?

**Comment by GRClark** [comment]
Ok I guess I’ve got to read the readme because I changed that setting and all fixed.  Thanks.
