### ISSUE TITLE
Activities change bug with two harmonyhubs

### ISSUE THREAD

**Issue by Nastras** [nicoduj/homebridge-harmony#23]
Hello nicoduj,

i have two harmonyhubs. One is in the living room and one in the bedroom. I created a scene in HomeKit called TV change. In this scene, the PowerOff switch is turned off by the Harmony hub in the living room and the harmonyhub bedroom starts an activity at the same time in this scene.

When running the scene, the TV is turned off in the living room, unfortunately, the TV is not turned on in the bedroom. The Homebridge Log displays both activities as completed.

I also tried without problems to start or stop all activities individually in a HomeKit scene.

From my experience with the old homebridge-harmonyhub plugin I know that the homekit scene described above worked earlier. Therefore, I could imagine that it is the plugin. What do you think?

Greeting Nastra

**Comment by nicoduj** [comment]
Ok, I gave it a look quickly, I am definitely interested into your logs in debug mode, while starting homebridge and while launching your scene !

**Comment by Nastras** [comment]
No problem, I restarted the homebridge in debugg mode and ran the scene. I hope this helps you further?

![89bad51e-d73f-45a1-aa54-ba5071f3d1eb](https://user-images.githubusercontent.com/27686185/51203253-e984ce00-1900-11e9-8b2c-6198c821ba9f.jpeg)
![e31d7718-20df-4e96-bb91-4d19ebc2cfc7](https://user-images.githubusercontent.com/27686185/51203255-e984ce00-1900-11e9-8c69-1b16f2a4e88e.jpeg)

**Comment by Nastras** [comment]
![50cfa0e0-e532-44b3-8834-6028a8a46bcf](https://user-images.githubusercontent.com/27686185/51203333-16d17c00-1901-11e9-8128-afe2624cc474.jpeg)

**Comment by nicoduj** [comment]
did you put the -D switch ? can't see the plugin logs.

**Comment by Nastras** [comment]
Look here is my homebridge config for the instance with which I started your plugin in debug mode.

![78c553a3-4bb7-4cf4-92ed-89c23413ab97](https://user-images.githubusercontent.com/27686185/51204714-86953600-1904-11e9-9317-bcb46e81511f.jpeg)

**Comment by nicoduj** [comment]
strange I was expecting far more logs ! (and I don't see the startup activities discovery logs).

However, If I correctly understand, you try to activate Apple Tv scene on your schlafzimmer and power off i your wohnzimmer, and the power off goes "right" but the scene activatio ndoesn't fire  ?Are you doing this through home app ? If yes, whatr are the state of the switches in it ? (immedialtely and after exiting and relaunching the app)  Can I see your config file ?

**Comment by Nastras** [comment]
![665fd710-c571-45c8-846d-705a5ff90f76](https://user-images.githubusercontent.com/27686185/51206804-4f755380-1909-11e9-8796-50d330356188.jpeg)

**Comment by Nastras** [comment]
Yes, exactly. I started the scene to try out the Home app and Siri. The switches of activities are off after firing in the living room. As it should be. And in the bedroom too. Here, however, an activity should be started. The activity is also started in the log. I observed the HarmonyHub in the bedroom when I triggered the scene and I did not realize that there were any IR commands sent.

**Comment by Nastras** [comment]
At these points in the log can be seen that the activities have started?

![Uploading D9D4DE0D-642E-424F-9F05-C6F5B8FD6E9F.jpeg…]()

**Comment by nicoduj** [comment]
This log is indeed put when we have a status 200 after sending the command to the hub. What seems strange to me is that I can't see a lot of other logs you should have on debug . Are you in 0.0.9 version ? In previous I might had a problem with background refresh with multiple platforms.

**Comment by nicoduj** [comment]
by the way, you can try to narrow the issue to : 
- disable refreshtimer on both platforms (set it to 0). 
- disable the turnoffactivity on the hub you want to turn on with this scene (bedroom).


Sorry, but I only have one hub so I must figure it out by reading the code and it is not obvious right now :)

**Comment by nicoduj** [comment]
hi @Nastras , do you have any update on that issue ?

**Comment by Nastras** [comment]
Hello @nicoduj,
sorry for the late reply. At the moment I have a lot to do that unfortunately I have not got around yet. I wanted to start trying the tips of you now. For this I have updated to V1.2.0.

Unfortunately, after the update my instance for your plugin does not start anymore. I did not make any changes.

I get this error:
<img width="1068" alt="bildschirmfoto 2019-01-27 um 06 47 09" src="https://user-images.githubusercontent.com/27686185/51797273-8fd5ab00-2200-11e9-9eb6-b4d77dc40d10.png">

I read that you want to show each activity individually and no longer grouped under one device. Or is this optional? Could not see an option in the config for it.

https://github.com/nicoduj/homebridge-harmony/issues/26

It's good for the Apple Home users.
Not so nice for the third party apps user.


I suspect that he has a problem since V1.2.0 when using two hubs that use the same name in the activity.

What do you think?

**Comment by Nastras** [comment]
I have just tested all versions. From version 1.0.0 the error occurs. I also deleted the accessories folder.

**Comment by Nastras** [comment]
I have now tested your tips in version 0.0.9.

refreshtimer deactivated = no improvement
Turnoffactivity deactivated and scenes adjusted in homekit = no improvement

The problem is still there. I think with an additional instance for the second harmonyhub it should definitely go. I have not tested it yet. Would be nice of course if it goes with one instance if you still have an idea? 😊

**Comment by MikeDeltaHH** [comment]
Hi @nicoduj , 
have the same problem... homebridge crashed after update to a version later then 0.0.9 - have also two hubs in my environment!

**Comment by nicoduj** [comment]
Hi , indeed I broke something for users with 2 hubs. Will fix asap bur until then stay on below 1.0.0.

I will try to make the behavior optionnal also.

Sorry for the bugs, i have only one hub ;)

**Comment by nicoduj** [comment]
> I have now tested your tips in version 0.0.9.
> 
> refreshtimer deactivated = no improvement
> Turnoffactivity deactivated and scenes adjusted in homekit = no improvement
> 
> The problem is still there. I think with an additional instance for the second harmonyhub it should definitely go. I have not tested it yet. Would be nice of course if it goes with one instance if you still have an idea? 😊

Definitely I still have ideas for your problem ( id of services since you have similar names on 2 hubs might be related !) , but as I cannot test them I might need your help :) will let you know

**Comment by nicoduj** [comment]
You can try updating manually to see if it solves at least the crash issue and maybe your other one (I will work on an option for #29 afterwards) thanks for the help !

**Comment by Nastras** [comment]
What do you mean to update manually? I have just the 1.2.0 Installed error still available...

![bcbc932a-96c1-47ae-93d8-1e5bf8c3be83](https://user-images.githubusercontent.com/27686185/51806173-ed0c4380-2276-11e9-97ab-868c30c98543.jpeg)

**Comment by Nastras** [comment]
ok I understand. Should I replace the index file in the 0.0.9 version?

I have previously installed version 1.2.0 as written above. Since the new index file was already online and the error has occurred.

**Comment by nicoduj** [comment]
You should replace ypur currét file. I haven’t publish my attempt to fix through npm

**Comment by Nastras** [comment]
Ok, so 1.2.0 install and manually replace index file 😁

**Comment by Nastras** [comment]
Good news, V1.2.0 works with the new index file!

**Comment by nicoduj** [comment]
I am curious : do you still have your issue on activity change ?

**Comment by nicoduj** [comment]
Hi, what do you mean by power switch not working properly anymore ? 

I am working on an option for the separate device mode, will keep you updated but will post an official version before that integrate the fix for #28

**Comment by Nastras** [comment]
The power off switch works. I tested it again. Sorry!

Only the change between the tv's is not possible. I think you can do the update for the index file.

**Comment by nicoduj** [comment]
ok thx. Option is on its way for getting only one accessory for all activities, hope to post this evening. I released howerver an update with the fix before as I said.

**Comment by nicoduj** [comment]
#29 is up (version 0.1.4) . Let me know if it is ok. 

Concerning your original issue, does addAllActivitiesToSkipedIfSameStateActivitiesList have an effect on it ?

**Comment by Nastras** [comment]
I do not think so, but I'm not sure because I set up the scene later.

**Comment by nicoduj** [comment]
Ok, still need to check some things but I really don’t know why especially if commands are working individually.

By the way I pushed a version but I am not 100% certain it will work with multiple hubs, any feedback would be much appreciated !

**Comment by Nastras** [comment]
Hello ,

wanted to briefly give you a current state of affairs because of the problem.

I have just updated to the current version and tried again. Now works the switch between two scenes without a problem. I think the issue can be closed.

Thanks again for your help and the great plugin!

**Comment by nicoduj** [comment]
WOW ;) Great news ! Can I ask which version exactly you were on, and if in latest it is still ok (I assume your are not using tv mode).

**Comment by Nastras** [comment]
With latest I meant the version 0.2.7 yesterday. No, I do not use the tv mode because I have no ios 12 beta installed. But I have it planned 😉

**Comment by nicoduj** [comment]
ok, I close, feel free to reopen especially since latest version od not use anymore polling for background refresh and had a lot of refactoring, I hope it still works since I didnt narrow this one :)
