### ISSUE TITLE
Siri Help for newbie

### ISSUE THREAD

**Issue by Robert91112** [nicoduj/homebridge-harmony#230]
How can I use Siri for volume and play pause commands. I.e “hey Siri, pause the tv” or “hey Siri, turn up the TV volume? ”

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nicoduj** [comment]
Hi, I don’t know the Siri commands at all, should be like other tv accessories but never found them, sorry. Only turn on / off are working here .
