### ISSUE TITLE
User error!

### ISSUE THREAD

**Issue by hstriepe** [nicoduj/homebridge-harmony#231]
**Describe the bug**
Adding a second Harmony Hub as another platform fails. Only the last platform entry is advertised.

**To Reproduce**
Add a second "platform."

**Expected behavior**
See a second device advertised.

** Actual behavior**
Only the last entry is seen.

**IOS (please complete the following information):**
- Version [13.3]
- Device: [iPhone 11]
 - bit also replicates on macOS

**Config**
Server is Mac mini mid 2011 running Sierra Server.

**Comment by nicoduj** [comment]
Hi, please read the readme you should not use 2 platform but use the property otherplatform instead

**Comment by hstriepe** [comment]
Yup. I was just editing this!

**Comment by nicoduj** [comment]
Ok :) so you are all good ? If yes i will close the issue :)
