### ISSUE TITLE
[BUG] Refresh Warning keep coming up

### ISSUE THREAD

**Issue by mwkchan** [nicoduj/homebridge-harmony#232]
I receive this warning every few seconds apart:

[3/8/2020, 2:08:24 AM] [Master Room Hub] WARNING - refreshCurrentActivity : Cancelling refresh since a refresh is allready in progress 43642481
[3/8/2020, 2:08:42 AM] [Master Room Hub] WARNING - refreshCurrentActivity : Cancelling refresh since a refresh is allready in progress 43642481
[3/8/2020, 2:09:57 AM] [Master Room Hub] WARNING - refreshCurrentActivity : Cancelling refresh since a refresh is allready in progress 43642481
[3/8/2020, 2:10:16 AM] [Master Room Hub] WARNING - refreshCurrentActivity : Cancelling refresh since a refresh is allready in progress 43642481
[3/8/2020, 2:11:52 AM] [Master Room Hub] WARNING - refreshCurrentActivity : Cancelling refresh since a refresh is allready in progress 43642481
[3/8/2020, 2:12:01 AM] [Master Room Hub] WARNING - refreshCurrentActivity : Cancelling refresh since a refresh is allready in progress 43642481

Config:

        {
            "name": "Master Room Hub",
            "hubIP": "192.168.1.245",
            "cleanCache": false,
            "publishAllTVAsExternalAccessory": true,
            "TVAccessory": true,
            "mainActivity": "Live TV",
            "playPauseBehavior": true,
            "remoteOverrideCommandsList": [
                {
                    "ActivityName": "my TV Super",
                    "CommandsList": [
                        {
                            "CommandName": "INFORMATION",
                            "NewCommand": "TVB STB;TV/VOD"
                        },
                        {
                            "CommandName": "ARROW_UP",
                            "NewCommand": "TVB STB;DirectionUp"
                        },
                        {
                            "CommandName": "ARROW_DOWN",
                            "NewCommand": "TVB STB;DirectionDown"
                        },
                        {
                            "CommandName": "ARROW_LEFT",
                            "NewCommand": "TVB STB;DirectionLeft"
                        },
                        {
                            "CommandName": "ARROW_RIGHT",
                            "NewCommand": "TVB STB;DirectionRight"
                        },
                        {
                            "CommandName": "SELECT",
                            "NewCommand": "TVB STB;Select"
                        },
                        {
                            "CommandName": "PLAY",
                            "NewCommand": "TVB STB;Red"
                        },
                        {
                            "CommandName": "PAUSE",
                            "NewCommand": "TVB STB;Red"
                        },
                        {
                            "CommandName": "FAST_FORWARD",
                            "NewCommand": "TVB STB;Blue"
                        },
                        {
                            "CommandName": "REWIND",
                            "NewCommand": "TVB STB;Yellow"
                        },
                        {
                            "CommandName": "BACK",
                            "NewCommand": "TVB STB;Back"
                        }
                    ]
                }
            ],
            "switchAccessories": true,
            "showTurnOffActivity": "inverted",
            "publishGeneralMuteSwitch": true,
            "showCommandsAtStartup": false,
            "otherPlatforms": [
                {
                    "name": "Living Room Hub",
                    "hubIP": "192.168.1.225",
                    "TVAccessory": true,
                    "mainActivity": "Live TV",
                    "playPauseBehavior": true,
                    "switchAccessories": false,
                    "showTurnOffActivity": "false",
                    "publishGeneralMuteSwitch": false,
                    "showCommandsAtStartup": false
                }
            ],
            "platform": "HarmonyHubWebSocket"
        }

**Comment by nicoduj** [comment]
Hi, As I said in #217 , this is a temprorary log until I am sure the issue is solved.
