### ISSUE TITLE
Multiple Hubs and TV Accessory will not work

### ISSUE THREAD

**Issue by clipse2004** [nicoduj/homebridge-harmony#233]
Hi Dude, 

i have a question, is it not possible to show more than 1 TV Accessory in Homekit?
Because i have two Hubs.
When i add the first Hub with TV Accessory it works fine, but after i add the second hub with TV Accessory, it shows me only the last one.
Log says i should add it manually, but there is nothing in homekit.

big thanks for your help

**Comment by nicoduj** [comment]
Hi,

As said in the log and readme, you have to add it manually . It is done via home app, add device, and enter the code . Demo here : https://twitter.com/dujnic/status/1110644949027041282?s=21

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by clipse2004** [comment]
Yeah now it works, only reinstall plugin has worked :) 
Thx

**Comment by m4d-maNu** [comment]
Hi sorry for Opening this Thread, but i have the same problem. 

This stand in my Log
```
 Ess- I Wohnzimmer Harmony-TV is running on port 62978.
 Please add [Ess- I Wohnzimmer Harmony-TV] manually in Home app. Setup Code: 130-81-537
```

But I can't add this Hub manually in the Home.app. The Code found nothing.


my config:
```
{
	"bridge": {
		"name": "Harmony Hub",
		"username": "C4:22:3D:E3:CE:93",
		"port": "51893",
		"pin": "130-81-537"
	},
	"plugins": [
		"homebridge-harmony"
	],

	"accessories": [],

	"platforms": [{
		"platform": "HarmonyHubWebSocket",
		"name": "Ess- I Wohnzimmer Harmony",
		"hubIP": "192.168.1.24",
		"mainActivity": "Television",
		"publishGeneralVolumeSlider": true,
		"publishGeneralMuteSwitch": true,
		"showTurnOffActivity": true,
		"switchAccessories": true,
		"publishSwitchActivitiesAsIndividualAccessories": true,
		"addAllActivitiesToSkippedIfSameStateActivitiesList": true,
		"devicesToPublishAsAccessoriesSwitch": [
			"LED Candle Light RGB",
			"LED Candle Light RGB|6H;6H",
			"LED Candle Light RGB|Mode;Mode",
			"LED Candle Light RGB|RGB;RGB",
			"LED Candle Light RGB|White;White",
			"LED Candle Light RGB|Orange;Orange",
			"LED Candle Light RGB|Purple;Purple",
			"LED Candle Light RGB|Red;Red",
			"LED Candle Light RGB|Blue;Blue",
			"LED Candle Light RGB|Green;Green",
			"LED Candle Light RGB|Yellow;Yellow"
		],
		"otherPlatforms": [{
			"name": "Schlafzimmer Harmony",
			"hubIP": "192.168.1.25",
			"mainActivity": "Television",
			"publishGeneralVolumeSlider": true,
			"publishGeneralMuteSwitch": true,
			"showTurnOffActivity": true,
			"switchAccessories": true,
			"publishSwitchActivitiesAsIndividualAccessories": true,
			"addAllActivitiesToSkippedIfSameStateActivitiesList": true
		}, {
			"name": "Büro Harmony",
			"hubIP": "192.168.1.23",
			"mainActivity": "Television",
			"publishGeneralVolumeSlider": true,
			"publishGeneralMuteSwitch": true,
			"showTurnOffActivity": true,
			"switchAccessories": true,
			"publishSwitchActivitiesAsIndividualAccessories": true,
			"addAllActivitiesToSkippedIfSameStateActivitiesList": true
		}]
	}]
}
```


The Hubs from otherPlattforms are in my Home.app.

**Comment by nicoduj** [comment]
IF they are in your home app, you are facing a bug that affects some users since Homebridge 1.0 -> only one is visible in remote control center. 

Can't figure out x-why for now, works for me, must be network related / bonjour problem. I know Hap-node js are working on a more reliable implementation.

Are you on hoobs ? Might be a port problem also, dont really know

**Comment by m4d-maNu** [comment]
> Are you on hoobs ? Might be a port problem also, dont really know

No, I use homebridge native.




> IF they are in your home app, you are facing a bug that affects some users since Homebridge 1.0 -> only one is visible in remote control center.
> 
> Can't figure out x-why for now, works for me, must be network related / bonjour problem. I know Hap-node js are working on a more reliable implementation.

Okay, than must I be wait and hope.



It worked yesterday, but I was just trying out the device mode you implemented. Now I would have finished trying it out, but the remote no longer appears.

**Comment by nicoduj** [comment]
interesting ... try to close the remote widget, or even launch it from home app if you have an apple tv, sometimes the behaviour of discovery is really strange. you could also try reverting to your old conf ? let me know, I am interested into info on this since it is not really "narrowed"

**Comment by m4d-maNu** [comment]
Yes, I have an Apple TV as an control center. I'm not using the remote widget, but the Harmony Touches with my hubs. What is important to me are the separate switches for my Harmony actions, with which I can control my lights automatically. The TV mode is only nice for my rooms in Home.app, then they are also cleaner. The separate switches are located in an additional room.


Now it works again, I stopped my homebridge, remove the plugin from Home.app and rename the hubs in the config from "Ess-I Living Area Harmony", "Schlafzimmer Harmony" and "Büro Harmony" to "Ess-I Wohnbereich HarmonyHub", "Schlafzimmer HarmonyHub" and "Büro HarmonyHub". Then I delete the file in "Accessories" and "Persist" and restart my homebridge. After adding in Home, I could add two more with the same PIN.
