### ISSUE TITLE
[FEATURE] Add capacity to send multiple commands at once with remoteOverrideCommandsList

### ISSUE THREAD

**Issue by claywd** [nicoduj/homebridge-harmony#236]
**Is your feature request related to a problem? Please describe.**
Its really annoying to have to press the volume key on my homekit remote 50 times depending upon the app/audio stream currently streaming. 

**Describe the solution you'd like**
Enable remoteOverrideCommandsList to contain commands which reference sequences... such as "Volume Up 5" which I created to change the volume must faster. 

```json
                        {
                            "CommandName": "INFORMATION",
                            "NewCommand": "Xbox One S;Xbox"
                        },
```

**Describe alternatives you've considered**
There aren't alternatives for this particular problem because telling siri to activate a switch to change the volume triggering a sequence is problematic with other sounds in the room. 

**Additional context**
An example command list might be something like this. 

```json
                "remoteOverrideCommandsList": [
                {
                    "ActivityName": "Xbox",
                    "CommandsList": [
                        {
                            "CommandName": "VOLUME_DOWN",
                            "NewSequence: "Volume Down 5"
                        }
                        {
                            "CommandName": "VOLUME_UP",
                            "NewSequence: "Volume Up 5"
                        }
                    ]
                }
```

If someone can point me to the code that needs to change, I wouldn't mind contributing

**Comment by nicoduj** [comment]
Hi, did you try the option «numberOfCommandsSentForVolumeControl » ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nicoduj** [comment]
Work in progress. 

Something like this will be possible, so that you can optionally specify the number of commands to send :

```json
 "remoteOverrideCommandsList": [
      {
        "ActivityName": "La TV",
        "CommandsList": [
          {
            "CommandName": "REWIND",
            "NewCommand": "Ampli;Number0;5"
          },
          {
            "CommandName": "BACK",
            "NewCommand": "TV;Back"
          }
        ]
      }
]
```
