### ISSUE TITLE
[FEATURE]General volume control as a slider

### ISSUE THREAD

**Issue by joobas** [nicoduj/homebridge-harmony#239]
Hello, Thank you so much for this Git.  I am new to all of this and have been working on programming my raspberry Pi with this.  I am learning through trial and error.  One thing I am uncertain, is it possible to add volume control to Homekit with this Git?

I would like to have a volume up and a volume down control.  I have implemented the general mute.

Thank you again.

**Comment by joobas** [comment]
I tried this in other accessories.  I am using Homebridge config ui.

"devicesToPublishAsAccessoriesSwitch" : ["Pioneer AV Receiver;VolumeDown","Pioneer AV Receiver;VolumeUp"]

But nothing shows up in my Homekit for volume.

**Comment by jimsmt** [comment]
this feature is already included, just use the physical volume button on your iPhone's side while the itv remote is on

**Comment by joobas** [comment]
What do you mean the itv remote?  I open Apple Home.  I have different switches included in there.  I can now turn on or off my receiver and TV.  But I do not see any volume controls.  I tried using the physical side buttons on my phone when in Home.  But they do not turn down my receiver volume.

**Comment by jimsmt** [comment]
> What do you mean the itv remote?

if you configure the plugin to work in tv mode, you can use your iPhone's built-in tv remote to control your harmony devices.

if using switch mode, you can also make custom buttons yourself in the home app, by using the `devicesToPublishAsAccessoriesSwitch` command

**Comment by joobas** [comment]
I tried the devices to publish. But nothin showed up in Apple Home. This was what I put in

"devicesToPublishAsAccessoriesSwitch" : ["Pioneer AV Receiver;VolumeDown","Pioneer AV Receiver;VolumeUp"]

**Comment by nicoduj** [comment]
H @joobas ,your syntax seems ok at first, can you post your logs ? Be very careful on names, it is case sensitive, did you check with the information listed when you set showCommandsAtStartup to true ? You could alse try to put a name to those switch (and check in default room also if they are not there).

Will think of n option like publishGeneralMuteSwitch for volumeUp / Down ,si I will keep this feature request open .

**Comment by joobas** [comment]
What logs do I post?  I am unsure how to do that.

In the information from startup I do see this.

[3/28/2020, 11:39:42] [Remote] INFO - Command : VolumeDown discovered for device : Pioneer AV Receiver
[3/28/2020, 11:39:42] [Remote] INFO - Command : VolumeUp discovered for device : Pioneer AV Receiver

In Homebridge config ui - settings. I wrote this in Other Accessories

Pioneer AV Receiver;VolumeDown","Pioneer AV Receiver;VolumeUp"

In the Config editor it showed up as this

{
            "name": "Remote",
            "hubIP": "xx.x.xx",
            "TVAccessory": false,
            "mainActivity": "Watch TV",
            "switchAccessories": true,
            "showTurnOffActivity": "stateless",
            "publishGeneralMuteSwitch": true,
            "publishSwitchActivitiesAsIndividualAccessories": true,
            "devicesToPublishAsAccessoriesSwitch": [
                "Pioneer AV Receiver;VolumeDown\",\"Pioneer AV Receiver;VolumeUp\""
            ],
            "showCommandsAtStartup": true,
            "platform": "HarmonyHubWebSocket"
        }

Is there anything else you need me to send?

**Comment by nicoduj** [comment]
"devicesToPublishAsAccessoriesSwitch": [
"Pioneer AV Receiver;VolumeDown","Pioneer AV Receiver;VolumeUp""
],

Is the the last " a mistake ? 

You can try to remove it, or to add a name alike this : 

"devicesToPublishAsAccessoriesSwitch": [
"Pioneer AV Receiver|AmpDown;VolumeDown","Pioneer AV Receiver|AmpUp;VolumeUp"
],

**Comment by joobas** [comment]
Oh wow. Thanks.  The extra " was part of the problem.

Then this
"Pioneer AV Receiver;VolumeDown","Pioneer AV Receiver;VolumeUp"

had to be separated. So I typed in
"Pioneer AV Receiver;VolumeDown".    Then clicked Add device and typed in
"Pioneer AV Receiver;VolumeUp"

So now the config editor shows
"name": "Remote",
            "hubIP": "xxxxxxxxxxx",
            "TVAccessory": false,
            "mainActivity": "Watch TV",
            "switchAccessories": true,
            "showTurnOffActivity": "inverted",
            "publishGeneralMuteSwitch": true,
            "publishSwitchActivitiesAsIndividualAccessories": true,
            "devicesToPublishAsAccessoriesSwitch": [
                "Pioneer AV Receiver;VolumeDown",
                "Pioneer AV Receiver;VolumeUp"
            ],
            "showCommandsAtStartup": true,
            "platform": "HarmonyHubWebSocket"
        }

Thank you so much @nicoduj 
I am able to have a volume up and a volume down switch.  It is not perfect as I have to rapidly tap the switches in order for the volume to increase or decrease significantly.  But it is better than nothing.  This is an amazing program.   

Thanks again.

**Comment by nicoduj** [comment]
You can add multiple commands in sequence if you want to send 2 or more up / down on each press

**Comment by joobas** [comment]
Awesome.  And thank you again.  This works great.

I would still request a feature to have this included, similar to a general mute function.  
I am also not sure if there is a way to actually have a volume up and down where we can hold the button and it will keep inputting until you let go?

**Comment by nicoduj** [comment]
Hi, great. I am thinking about it yes ;p Will try to do something !

**Comment by nicoduj** [comment]
Work in progress.

New option will be available : publishGeneralVolumeSlider. It will publish a volume slider as a light (no other way), stateless (defaults to 50 if an activity is on), that will send a volume command to current activity. Approximativley, it will send an Up / Down Volume command each 5%. It can be combined with `numberOfCommandsSentForVolumeControl` option to multiply the number of up / down commands sent each time.

**Comment by madcat-nl** [comment]
Super cool, thank you.

Is there a way to have the volume control as a linked service to the TV accessory?
So the volume/light is included into the same component as the tv within homekit?

**Comment by nicoduj** [comment]
> Super cool, thank you.
> 
> 
> 
> Is there a way to have the volume control as a linked service to the TV accessory?
> 
> So the volume/light is included into the same component as the tv within homekit?

Hi, nice Idea, will try to do so !


https://github.com/nicoduj/homebridge-harmony/issues/244

**Comment by madcat-nl** [comment]
Cool it works, thanks for the quick patch!
When i set the volume to for example 25%, it looks like it's only sending 1 time a volume down. Should it not al least send 5 times volume down, or in the configuration below 25 times a volume down? 
    {
            "name": "Harmony",
            "hubIP": "IP",
            "cleanCache": true,
            "TVAccessory": true,
            "mainActivity": "Music",
            "activitiesToPublishAsInputForTVMode": [
                "Music",
                "Movie",
                "Game"
            ],
            "playPauseBehavior": true,
            "numberOfCommandsSentForVolumeControl": 5,
            "switchAccessories": false,
            "publishGeneralMuteSwitch": false,
            "publishGeneralVolumeSlider": true,
            "linkVolumeControlToTV": true,
            "publishSwitchActivitiesAsIndividualAccessories": false,
            "showCommandsAtStartup": false,
            "platform": "HarmonyHubWebSocket"
        }

One other thing i also see a "Switch" and a "TV" accessory in my homekit, i guess it's to support the real harmony control, but is there a way to hide it or also include it into the real accessory?

One other question: does anybody know what is the Siri command to change input for the tv is?

**Comment by nicoduj** [comment]
Hi,

first of all, you have to remove cleanCache Option, otherwise everything will be recreated at each startup and you will loose automations, room assignment and so on.

Concerning the number of commands sent, it should indeed send 5 * 5 volume down command if you slide until 25 % . Will check again, maybe there is some bug, can you activate debug mode and see how much commands it really try to send (will be displayed in debug mode).

Concerning Siri, no, I d'ont known and as far as I know there is no command for that directly. Only way is to use shortcut app, where you can do so and where siri will ba handled.

Finally, I d'ont really understand your question about the switch.Your config should only publish a light bulb for volume inside your TV accessory, any screenshot maybe ?

**Comment by nicoduj** [comment]
Can confirm there is a bug, working on it.

**Comment by nicoduj** [comment]
Will be fixed in 1.3.3

**Comment by madcat-nl** [comment]
> first of all, you have to remove cleanCache Option, otherwise everything will be recreated at each startup and you will loose automations, room assignment and so on.

Thanks i can comfirm that the bug is solved.

I did the clean cache, because there was some "garbage accessories".
I see a switch and another "empty" TV, i kinda hoped it would be gone then.

Do you also see these two unusable accessories.
