### ISSUE TITLE
connect ECONNREFUSED

### ISSUE THREAD

**Issue by waxlabo** [nicoduj/homebridge-harmony#24]
I am not sure what I am doing wrong.  Could anyone help?

[1/16/2019, 6:09:41 PM] Loaded config.json with 0 accessories and 1 platforms.
[1/16/2019, 6:09:41 PM] ---
[1/16/2019, 6:09:43 PM] Loaded plugin: homebridge-harmony
[1/16/2019, 6:09:43 PM] Registering platform 'homebridge-harmonyHub.HarmonyHubWebSocket'
[1/16/2019, 6:09:43 PM] ---
[1/16/2019, 6:09:43 PM] Loading 1 platforms...
[1/16/2019, 6:09:43 PM] [Harmony Hub] Initializing HarmonyHubWebSocket platform...
[1/16/2019, 6:09:43 PM] [Harmony Hub] Loading activities...
[1/16/2019, 6:09:43 PM] [Harmony Hub] Error retrieving info from hub : connect ECONNREFUSED 192.168.1.62:8088

**Comment by nicoduj** [comment]
Hi, are you sure of the ip of you hub ? Is it static ? Could you post your config file ?

**Comment by waxlabo** [comment]
The ip should be correct. I got it from the Harmony app.

{
        "bridge": {
                "name": "Harmonybridge",
                "username": "XX:00:YY:00:ZZ:00",
                "port": 51930,
                "pin": "031-45-154"
        },

        "platforms": [{
                "platform": "HarmonyHubWebSocket",
                "name": "Harmony Hub",
		"hubIP": "192.168.1.68",
		"showTurnOffActivity" : true,
		"refreshTimer" : 30,
		"addAllActivitiesToSkipedIfSameStateActivitiesList" : true
        }]
}

**Comment by nicoduj** [comment]
Hi,

It says .62 in your lonand .68 in your config.
Moreover you have to set it static through your router so that it never changes

**Comment by waxlabo** [comment]
> 
> 
> Hi,
> 
> It says .62 in your logs and .68 in your config.
> Moreover you have to set it static through your router so that it never changes.

Thanks, great catch.  I do have static ip set for the hub.  However I do have two hubs, one ends in .68 and one ends in .62.  I am not sure why the error shows the other hub's ip when I specifically only added the other one in my config.  I'm not sure what's going on but I'll try and add both to the config and see what happens.

**Comment by nicoduj** [comment]
You could try to empty your cache and accessories directory in homekit and restart to see if it helps, I don’t see any reason why it tries to connect to the wrong ip since it is directly extracted from your config file. Did you try to change it to something completely different ? Maybe th econfig file is not the good one .

**Comment by nicoduj** [comment]
@waxlabo  Do you have any update on this ?

**Comment by lukasodhner** [comment]
I have this issue also and it seems to be a problem with the Hub itself.  I had it configured and working but something broke and it just can't connect to it while I can connect to my other hub just fine, both are set to Static IPs.  Might have to do a factory reset on the Harmony Hub?
