### ISSUE TITLE
[BUG] refreshCurrentActivity Error: WebSocket closed

### ISSUE THREAD

**Issue by barneyonline** [nicoduj/homebridge-harmony#240]
**Describe the bug**
Reoccurring web socket closed error preventing control from HomeKit, Harmony Hub configuration and controlling other services via the Hub (e.g. controlling Hue lights via the remote). Harmony Hub light turns red (offline).

**To Reproduce**
Unsure

**Expected behavior**
None of the above

**Logs**
[3/29/2020, 12:31:37 PM] [Harmony Hub] ERROR (1)- refreshCurrentActivity Error: WebSocket closed with reason: Socket Error: read ECONNRESET (1006). - Stack : Error: WebSocket closed with reason: Socket Error: read ECONNRESET (1006).
    at WebSocketAsPromised._handleClose (/usr/local/lib/node_modules/homebridge-harmony/node_modules/websocket-as-promised/src/index.js:351:19)
    at W3CWebSocket.listener (/usr/local/lib/node_modules/homebridge-harmony/node_modules/websocket-as-promised/src/index.js:309:63)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/usr/local/lib/node_modules/homebridge-harmony/node_modules/yaeti/lib/EventTarget.js:115:12)
    at W3CWebSocket.onClose (/usr/local/lib/node_modules/homebridge-harmony/node_modules/websocket/lib/W3CWebSocket.js:228:10)
    at WebSocketConnection.<anonymous> (/usr/local/lib/node_modules/homebridge-harmony/node_modules/websocket/lib/W3CWebSocket.js:201:17)
    at WebSocketConnection.emit (events.js:219:5)
    at WebSocketConnection.handleSocketClose (/usr/local/lib/node_modules/homebridge-harmony/node_modules/websocket/lib/WebSocketConnection.js:389:14)
    at Socket.emit (events.js:219:5)
    at TCP.<anonymous> (net.js:666:12)
[3/29/2020, 12:31:37 PM] [Harmony Hub] WARNING - socket closed

**Config**
        {
            "name": "Harmony Hub",
            "hubIP": "192.168.1.7",
            "cleanCache": false,
            "TVAccessory": true,
            "mainActivity": "Apple TV",
            "switchAccessories": true,
            "platform": "HarmonyHubWebSocket"
        },

**Versions**
Harmony Hub | fw4.15.264
Node.js | v13.3.0
Npm | v6.14.3
Homebridge | v0.4.53
homebridge-harmony | v1.2.7

**Comment by nicoduj** [comment]
Hi, does your hub have a static ip assigned by your routeur ? How often does it happen ? Is there any other client on hub websocket ? Is there any network loss problem between homebridge and your hub network ?

**Comment by barneyonline** [comment]
Hub has a static IP. Occurs about every 5min when an activity is active/on, otherwise every so often. No network issue between the homebridge and LAN network, other homebridge services (homebridge-arlo) are working fine.

How do I check for other clients on the hub websocket?

**Comment by nicoduj** [comment]
Does harmony app works when it happens ? You said the hub light is red, so it means it is disconnected from network I think. 
Are you using hoobs by the way did you try with Lts version of node ? Mainly it is a network error but don’t understand why you are experiencing it .

**Comment by barneyonline** [comment]
When it happens the app is unable to connect to the Hub or make any configuration changes. I'm not using hoobs. I don't believe it is an issue with my network as no other devices drop out, but I'll dig into that a bit more.

**Comment by nicoduj** [comment]
You can launch in debug mode and send me the full log when it happens , will try to see might be some timeout problem . Do you have a big setup (lots of devices / activities ?)

**Comment by barneyonline** [comment]
Here is the debug log, not too many devices or activities.
[Untitled.txt](https://github.com/nicoduj/homebridge-harmony/files/4400089/Untitled.txt)

**Comment by nicoduj** [comment]
I don’t see anything specula in your log at first, only you are using some plugin names automationsswitches : since it seems it uses timers, could you try without it and tell me if the problem still occurs  ?

**Comment by barneyonline** [comment]
Thanks. Removed the plugin (homebridge-automation-switches v3.2.1) but still get the timeout errors. I'm wondering if this is due to a general connectivity issue with the Hub and my Wi-Fi network. I'm going to try a few different configurations on my end and will report back.

**Comment by barneyonline** [comment]
Played around with my LAN but unfortunately the issue still remains.

**Comment by nicoduj** [comment]
Hi, sorry to hear that. Did you try with a lower version of node ?12.x ?

**Comment by barneyonline** [comment]
Downgraded to node 12.16.1 and npm 6.13.4 - seems to have reduced the frequency of errors (from ~20 to 7) but still occurs.

**Comment by nicoduj** [comment]
It is really strange, I am thinking about something : is there any chance your time is not the same between your hub zone and homebridge zone ?

**Comment by nicoduj** [comment]
Can you paste a full log ? there shouldbe multiple attemps and some wait between a series, want to check if everything is ok on the error handling side. I Thnik, from my understanding, that the socket is closed while retrieving data, which can be because hub is crashing , or timeout is too "thin".

the values of timeout are the following 👍 
HUB_CONNECT_TIMEOUT = 10000;
HUB_SEND_TIMEOUT = 30000;
MAX_SOCKET_ERROR = 5;
DELAY_BEFORE_RETRY_AFTER_NETWORK_LOSS = 20000;

Giving me a full timestamped log with a serie of error could help.

**Comment by barneyonline** [comment]
Thanks.

Have checked Hub timezone, changed from manual of "+10 GMT Sydney" to automatic "Australia, Melbourne" which is also +10 GMT. Timezone on Homebridge (MacOS) is already set to automatic "Australia, Melbourne".

Attached is the log since downgrading to node 12.16.1.
[Log.txt](https://github.com/nicoduj/homebridge-harmony/files/4432803/Log.txt)

**Comment by nicoduj** [comment]
I see you are on Mac, maybe with WiFi and Ethernet connection? Is there any chance one of the interface drops sometime ? If this is the case, could you try only with Ethernet ? Maybe powernap is enabled  ? The socket connection is dropped, I really think something is wrong on the network side with the websocket that needs to remain connected in order to receive update events if you use physical harmony or harmony app. 

From the log you sent, the "retry" behavior is seems ok, and I think it works between attemps no ? Or it never works ?

**Comment by barneyonline** [comment]
Correct. Mac is connected via Ethernet only with Wi-Fi switched off. Connection shouldn't drop as it is direct to the modem. PowerNap is turned off. The retry behaviour does seem to work, status does get updated in the Home app. Might just be my Wi-Fi connection to the Harmony Hub, or the Hub itself.

**Comment by nicoduj** [comment]
Are you on same subnet ? Or WiFi a bit overloaded those days ? The socket is dropped, can be on both side ...

**Comment by barneyonline** [comment]
Yes same subset, both with fixed IPs. I do have 11 devices on Wi-Fi, but that shouldn't be an issue for the Netgear Orbi modem.

**Comment by nicoduj** [comment]
I have an orbi also (RBR40 - RBS 40) with a lot more :). Can I ask what firmware you are on / what settings you have ? Especially advanced settings on wifi like Fast roaming / beam forming / mu-mimmo and Wifi multimedia ?

**Comment by barneyonline** [comment]
I've got the RBR50 and RBS50 with ethernet backhaul and the latest firmware (V2.5.1.8). Wi-Fi settings are pretty much the default, I have turned on any of those additional functions.

I've also done a factory reset of the Harmony Hub but that hasn't had any effect.

![Screen Shot 2020-04-07 at 11 15 08 am](https://user-images.githubusercontent.com/38914183/78619601-108e3d80-78c1-11ea-88a6-8c6ae03be2ea.png)

**Comment by nicoduj** [comment]
Hi, could you check with an a clean install ? Some changes were made to dependcy declaration in one of the dependency I use, hope it will help.

In my conf, I have enabled beamforming, mu-mimo and fast roaming, but disabled 20/40 mhs coexistence, you can also check that ?

**Comment by barneyonline** [comment]
[FIXED] Disabling 20/40 Mhz Coexistence did the trick, haven't had any errors since making that change. Also enabled Implicit Beamforming, MU-MIMO and Fast Foaming but they won't impact the Hub connection. Thanks for all your help mate
![Screen Shot 2020-04-18 at 2 41 23 pm](https://user-images.githubusercontent.com/38914183/79628250-b2940c80-8182-11ea-8264-593bcf5d24dd.png)
