### ISSUE TITLE
Unable to Display 2 TV Accessories

### ISSUE THREAD

**Issue by weekendplaya** [nicoduj/homebridge-harmony#241]
**Describe the bug**
I have 2 Harmony Hubs and am trying to set them both up so they both show as TV Accessories.  Currently, I can get one to show as TV and the other to show as a Switch.

**Expected behavior**
Each Hub will show as a TV Accessory

**IOS (please complete the following information):**

**Logs**

[Homebridge] [3/29/2020, 22:38:37] [Living Room Hub] INFO - Adding Accessory : Living Room Hub-TV
[Homebridge] [3/29/2020, 22:38:37] [Living Room Hub] (Living Room Hub)INFO - configuring Main TV Service
[Homebridge] [3/29/2020, 22:38:37] [Living Room Hub] (Living Room Hub)INFO - Creating TV Service
[Homebridge] [3/29/2020, 22:38:37] [Living Room Hub] (Living Room Hub)INFO - Creating Input Service - Watch Living Room Blu Ray
[Homebridge] [3/29/2020, 22:38:37] [Living Room Hub] (Living Room Hub)INFO - Configuring Main Activity Watch Living Room TV
[Homebridge] [3/29/2020, 22:38:37] [Living Room Hub] (Living Room Hub)INFO - Creating TV Speaker Service
[Homebridge] [3/29/2020, 22:38:37] [Living Room Hub] (Living Room Hub)INFO - Creating Input Service - Watch Living Room TV
[Homebridge] [3/29/2020, 22:38:37] [Living Room Hub] (Living Room Hub)INFO - Creating Input Service - Watch Living Room Netflix
[Homebridge] [3/29/2020, 22:38:37] [Living Room Hub] (Living Room Hub)INFO - Discovered Activity : Watch Living Room Blu Ray
[Homebridge] [3/29/2020, 22:38:37] [Living Room Hub] (Living Room Hub)INFO - Discovered Activity : Watch Living Room TV
[Homebridge] [3/29/2020, 22:38:37] [Living Room Hub] (Living Room Hub)INFO - Discovered Activity : Watch Living Room Netflix
[Homebridge] [3/29/2020, 22:38:37] [Living Room Hub] INFO - setupFoundAccessories - TV accessory added as external accessory
[Homebridge] [3/29/2020, 22:38:37] [Living Room Hub-TV] is running on port 46007.

**Config**

        {
            "platform": "HarmonyHubWebSocket",
            "plugin_map": {
                "plugin_name": "homebridge-harmony"
            },
            "name": "Living Room Hub",
            "hubIP": "192.168.0.XXX",
            "playPauseBehavior": true,
            "numberOfCommandsSentForVolumeControl": 2,
            "TVAccessory": true,
            "switchAccessories": true,
            "publishAllTVAsExternalAccessory": false,
            "publishGeneralMuteSwitch": false,
            "publishSwitchActivitiesAsIndividualAccessories": false,
            "publishDevicesAsIndividualAccessories": false,
            "publishSequencesAsIndividualAccessories": false,
            "publishHomeControlsAsIndividualAccessories": false,
            "otherPlatforms": [
                {
                    "name": "Bedroom Hub",
                    "hubIP": "192.168.0.XXX",
                    "playPauseBehavior": true,
                    "numberOfCommandsSentForVolumeControl": 2,
                    "TVAccessory": true,
                    "switchAccessories": true,
                    "publishAllTVAsExternalAccessory": true,
                    "publishGeneralMuteSwitch": false,
                    "publishSwitchActivitiesAsIndividualAccessories": false,
                    "publishDevicesAsIndividualAccessories": false,
                    "publishSequencesAsIndividualAccessories": false,
                    "publishHomeControlsAsIndividualAccessories": false
                }
            ],
            "cleanCache": false,
            "addAllActivitiesToSkippedIfSameStateActivitiesList": false,
            "mainActivity": "Watch Living Room TV"
        }
    ]
}

**Comment by nicoduj** [comment]
Hi, did you add it manually as mentionned in the readme ? It is publish as an external accessory so you must add it manually from home app

**Comment by weekendplaya** [comment]
Thanks a lot. I figured it out. Your directions are right once I figured out what you meant. Great piece of code!!
