### ISSUE TITLE
EHOSTUNREACH

### ISSUE THREAD

**Issue by dswee999** [nicoduj/homebridge-harmony#242]
My harmony plugin quit working for some reason. No changes have been made to my set up that I'm aware of but now the plugin does not work and the log shows the below message over and over again.

[Living Room] INFO - Loading activities...
[Living Room] Error - Error retrieving info from hub : Error: connect EHOSTUNREACH 192.XXX.X.XX:8088-(4904)

I'm on homebridge version 0.4.53, Node 12.16.1, and NPM 6.14.2 running on a raspberry pi with ozno docker image. All my other plugins seem to be working fine.

Please help! Thank you!

**Comment by nicoduj** [comment]
It seems your hub does not have the same IP address anymore, is it fixed ?

**Comment by dswee999** [comment]
Yes it is fixed and I’ve double check the IP address the hub is assigned to in the router and it matches the IP address in the error message.



On Mar 31, 2020, at 1:43 AM, Nicolas Dujardin <notifications@github.com> wrote:

﻿

It seems your hub does not have the same IP address anymore, is it fixed ?

**Comment by nicoduj** [comment]
did you update the plugin ? Does harmony app on a phone works and show the same IP ? The error is happening at the start of homebridge, so you must have restart for any reason, was there any config file change maybe that were not in action before restart ?

**Comment by dswee999** [comment]
It was updated from the release a week or two ago. Harmony app on phone works fine and shows same IP address. I’ve not made any config changes and the error repeats it self over and over not just at start up in the logs.



On Mar 31, 2020, at 7:49 AM, Nicolas Dujardin <notifications@github.com> wrote:

﻿

did you update the plugin ? Does harmony app on a phone works and show the same IP ? The error is happening at the start of homebridge, so you must have restart for any reason, was there any config file change maybe that were not in action before restart ?

**Comment by nicoduj** [comment]
did you try to ping the ip inside docker ? is the port open ? It is clearly a network connection error. The error is trigered at launch and the plugin can't work without retrieving info from hub so it tries again and again. I think you tired to restart without any success ?

**Comment by dswee999** [comment]
Yes I have restarted everything several times including router and hub with no luck.



On Mar 31, 2020, at 7:55 AM, Nicolas Dujardin <notifications@github.com> wrote:

﻿

did you try to ping the ip inside docker ? is the port open ? It is clearly a network connection error. The error is trigered at launch and the plugin can't work without retrieving info from hub so it tries again and again. I think you tired to restart without any success ?

**Comment by dswee999** [comment]
I just factory restored my hub and set the static ip to different address and it’s still giving the same error but with the new IP.



On Mar 31, 2020, at 7:55 AM, Nicolas Dujardin <notifications@github.com> wrote:

﻿

did you try to ping the ip inside docker ? is the port open ? It is clearly a network connection error. The error is trigered at launch and the plugin can't work without retrieving info from hub so it tries again and again. I think you tired to restart without any success ?

**Comment by nicoduj** [comment]
Hi, sorry to hear that . I don’t really know what is happening, i have quite the same config (oznu image on Synology, only my npm version is 6.13.4) . Would also be interested into the version of npm packages dependencies , especially websocket / websocket as promised .

**Comment by nicoduj** [comment]
Can you post a log with multiple attemps of connections, timestamped so that I can see the delay between each try ? Is there any chance it happened after daytime change and your py is not on the same time it should not be an issue, just an idea !)

**Comment by dswee999** [comment]
I ended up wiping my Pi and redoing everything and that fixed. Still do not know what caused it but it is working good now. Thanks for the help!

On Apr 4, 2020, at 12:01 PM, Nicolas Dujardin <notifications@github.com<mailto:notifications@github.com>> wrote:



Can you post a log with multiple attemps of connections, timestamped so that I can see the delay between each try ? Is there any chance it happened after daytime change and your py is not on the same time it should not be an issue, just an idea !)

**Comment by nicoduj** [comment]
Hi, thx for the update. I discussed with the dev of one dependency, and made an update to it to fix the request and websocket dep to a version because npm is not really good at handling dependencies from my experience when they are not fixed,  especially if you install globally.

Maybe it works now because before there was some conflict in those dependencies because of previous installs.
