### ISSUE TITLE
Feature : link volume switch/ mute  to tv accessory

### ISSUE THREAD

**Issue by nicoduj** [nicoduj/homebridge-harmony#244]
Check if it is possible to link those services to tv accessory if it exists in order to have them on the same screen in home app .

**Comment by nicoduj** [comment]
Will look like this (on iPhone), unfortunately home app is not really good at this and does not show names of services when grouped !


![image](https://user-images.githubusercontent.com/19813688/78469172-ef8de700-771e-11ea-97c8-542d86c89fea.png)
![image](https://user-images.githubusercontent.com/19813688/78469179-07fe0180-771f-11ea-8faf-7068e8902dda.png)

**Comment by Phoenix-DH** [comment]
Hey.... again great work!
I implemented the mute and volume slider but not able to group all.

Is this actually possible or are you still working on ... did not really get it.

**Comment by nicoduj** [comment]
> Hey.... again great work!
> I implemented the mute and volume slider but not able to group all.
> 
> Is this actually possible or are you still working on ... did not really get it.

Hi, thx :) It is in latest 1.3.2 only, you have to set a new option : linkVolumeControlToTV to true !

**Comment by Phoenix-DH** [comment]
Okay will try with this:
            "publishGeneralVolumeSlider": true,
            "publishGeneralMuteSwitch": true,
            "linkVolumeControlToTV": true,

**Comment by nicoduj** [comment]
Should do it (only if you have published a tv accessory off course)
