### ISSUE TITLE
npm ERR! missing: request@latest, required by harmony-websocket@1.5.0

### ISSUE THREAD

**Issue by mensa84** [nicoduj/homebridge-harmony#246]
Hello,

I am getting that 2 errors in the last lines. Why? And how to fix this?

```
root@Server:~# npm list -g --depth=0
/usr/lib
├── homebridge@0.4.53
├── homebridge-automation-switches@3.2.1
├── homebridge-cmdswitch2@0.2.10
├── homebridge-cmdtrigger@0.3.2
├── homebridge-harmony@1.3.3
├── homebridge-http-webhooks@0.0.57
├── homebridge-mi-outlet@0.3.0
├── homebridge-people@0.6.2
├── homebridge-soundtouch@5.3.1
├── homebridge-tplink-smarthome@4.0.1
├── miio@0.15.6
├── npm@6.14.4
└── ps4-waker@1.9.0

npm ERR! invalid: request@2.88.2 /usr/lib/node_modules/homebridge-harmony/node_modules/request
npm ERR! missing: request@latest, required by harmony-websocket@1.5.0

```

**Comment by nicoduj** [comment]
Hi, interesting ... doe it work, or do you have this only when listing dependencies ?

**Comment by mensa84** [comment]
It does work yes and the errors I see only when listing by npm list -g --depth=0

**Comment by nicoduj** [comment]
strange, might be a problem with npm . It is also not a good way I think to install globaly plugin packages. 
My setup gives the following : 

/homebridge # npm list -g --depth=0
/usr/local/lib
+-- homebridge@0.4.53
+-- homebridge-config-ui-x@4.13.3
`-- npm@6.13.4

Config UI does not do that, and I think it is better this way.

If you do this command inside your harmony plugin, without -g , I think it won't be listed (the plugin would not work at all if request was not there somewhere)

**Comment by nicoduj** [comment]
I also have some errors by the way, seems that it depends on the order of dependencies installation and npm strucure tree.

I would say : if it works: don't bother :) 

otherwise you can try but not sure if it will help : https://docs.npmjs.com/cli/dedupe.html

**Comment by nicoduj** [comment]
Some changes were made to the dependency that could cause such issue, let me know if it is better after a clean install

**Comment by nicoduj** [comment]
will reopen if needed
