### ISSUE TITLE
[FEATURE] Bridge TV Support

### ISSUE THREAD

**Issue by donavanbecker** [nicoduj/homebridge-harmony#248]
**Is your feature request related to a problem? Please describe.**
No Problem, Just a request.

**Describe the solution you'd like**
Once Homebridge v1.0.0 comes out with Bridge TV/Camera support. It would be nice to have that implemented so that any "TVs"/Hubs added would connect automatically to the Bridge

**Describe alternatives you've considered**
none

**Additional context**
[Bridged TV/Cameras](https://github.com/homebridge/HAP-NodeJS/commit/3add725d95ec0f71ec94b3a1cc1eec34b3230dc9)

**Comment by nicoduj** [comment]
Thanks for the suggestion, will check. Just to confirm, it will allow to expose multiple "external accessories" without adding them manually , correct ?

**Comment by donavanbecker** [comment]
Never mind closing...
