### ISSUE TITLE
Device switches see to not work

### ISSUE THREAD

**Issue by rsonnens** [nicoduj/homebridge-harmony#25]
I see all my Logitech devices listed as switches (in addition to activities) in homekit but using the switches does not toggle devices on and of. Is this a work in progress and can the list of devices be filtered out?

(The older harmony-hub npm did not so a list of devices, only activities.)

**Comment by nicoduj** [comment]
Hi, there is no such feature currently, The plugin only lists the activities. Could you post your config and log ?

**Comment by rsonnens** [comment]
[npmlog.txt](https://github.com/nicoduj/homebridge-harmony/files/2774537/npmlog.txt)

[config.txt](https://github.com/nicoduj/homebridge-harmony/files/2774539/config.txt)

The device switches are definitely showing in ios home app from homebridge.  Very odd.

**Comment by rsonnens** [comment]
note: In my log you'll see an activity "System Off: that is an activity I created on my Harmony remote back when I was using the harmony-hub NPM.

**Comment by rsonnens** [comment]
OK, Homebridge had something stale in it. i cleared caches and then removed and added  back homebridge to the home app and all is OK. looks like your awesome NPM had nothing to do with the issue.

**Comment by nicoduj** [comment]
Nice if your issue is solved ! I definitely plan to add such option, just need to find some time to do it :) Enjoy the plugin meanwhile.

**Comment by nicoduj** [comment]
(By the way I deleted your comment with your config since you posted it with a key of one of your service, I suggest your renew it just in case)
