### ISSUE TITLE
npm WARNINGS during upgrade

### ISSUE THREAD

**Issue by mensa84** [nicoduj/homebridge-harmony#250]
Hello,

I got that warnings during upgrade to 1.3.6

Should I canre about?

```
root@Server:~# npm -g update homebridge-harmony
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request                                      /request/issues/3142
npm WARN notsup Unsupported engine for homebridge-harmony@1.3.6: wanted: {"homebridge":"^0.4.50                                      ","node":"^12.16.0"} (current: {"node":"11.15.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: homebridge-harmony@1.3.6

```

**Comment by donavanbecker** [comment]
This is just a warning of a dependency, you can ignore. Also you must update your homebridge and node.

**Comment by nicoduj** [comment]
I have bump dependencies for next version of homebridge, it should work but like @donavanbecker said you should update homebridge and node .
Request was deprecated by its maintainer you can’t do anything about this, but it is still widely used :)

**Comment by mensa84** [comment]
How can I update homebridge, if it's already installed in most current version?

**Comment by nicoduj** [comment]
If homebridge is fine, just node ( your version of homebridge was not mentioned). Updating method might depend on what kind of install you are using.

**Comment by mensa84** [comment]
My node version is the following and looks up to date. OK to stay with it?
```
root@Server:~# node -v
v11.15.0
```

**Comment by donavanbecker** [comment]
[12.6.0](https://github.com/nicoduj/homebridge-harmony/blob/7c02a2b83968d6d1b750d7ca9ad8d59b3c4d880c/package.json#L17) is what homebridge-harmony is expecting.

**Comment by donavanbecker** [comment]
> My node version is the following and looks up to date. OK to stay with it?
> 
> ```
> root@Server:~# node -v
> v11.15.0
> ```
[12.6.0](https://github.com/nicoduj/homebridge-harmony/blob/7c02a2b83968d6d1b750d7ca9ad8d59b3c4d880c/package.json#L17) is what homebridge-harmony is expecting.

**Comment by mensa84** [comment]
I have upgraded to nodejs v12.16.2 by these commands:

```
curl -sL https://deb.nodesource.com/setup_12.x | bash -
apt-get install -y nodejs
```

But now my complete homebridge crashes at startup:
```
Apr 18 01:22:09 Server homebridge[5088]: [4/18/2020, 1:22:09 AM] Loading 3 accessories...
Apr 18 01:22:09 Server homebridge[5088]: [4/18/2020, 1:22:09 AM] Error: The requested accessory 'SoundTouch' was not registered by any plugin.
Apr 18 01:22:09 Server homebridge[5088]:     at API.accessory (/usr/lib/node_modules/homebridge/lib/api.js:64:13)
Apr 18 01:22:09 Server homebridge[5088]:     at Server._loadAccessories (/usr/lib/node_modules/homebridge/lib/server.js:297:42)
Apr 18 01:22:09 Server homebridge[5088]:     at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:91:38)
Apr 18 01:22:09 Server homebridge[5088]:     at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:59:10)
Apr 18 01:22:09 Server homebridge[5088]:     at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
Apr 18 01:22:09 Server homebridge[5088]:     at Module._compile (internal/modules/cjs/loader.js:1156:30)
Apr 18 01:22:09 Server homebridge[5088]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
Apr 18 01:22:09 Server homebridge[5088]:     at Module.load (internal/modules/cjs/loader.js:1000:32)
Apr 18 01:22:09 Server homebridge[5088]:     at Function.Module._load (internal/modules/cjs/loader.js:899:14)
Apr 18 01:22:09 Server homebridge[5088]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
Apr 18 01:22:09 Server homebridge[5088]:     at internal/main/run_main_module.js:18:47
Apr 18 01:22:09 Server homebridge[5088]: [4/18/2020, 1:22:09 AM] Got SIGTERM, shutting down Homebridge...
```

**Comment by mensa84** [comment]
I reinstall homebridge-soundtouch now and it worked.
Should I reinstall every (homebridge)npm package after my upgrade from node 11 to 12? Or houw should one know, when this is possible?

**Comment by donavanbecker** [comment]
@mensa84 how did you install homebridge?

**Comment by mensa84** [comment]
> @mensa84 how did you install homebridge?

Like the homebridge website says. Is this not the way to install it correctly?

`npm -g install homebridge`

**Comment by nicoduj** [comment]
I am using a docker image, so that is is more "isolated" and easy to update (I update the whole image). Npm can be messy from my experience especially whith global packegs and deps.

By the way, thanks for pointing me on this since I was a bit aggressive with node dependency to V1é, issed the fact that v10 is still in LTS support, so I have lower the dep to >= 10.20.0 .

Sorry for all the trouble so .

**Comment by mensa84** [comment]
> > @mensa84 how did you install homebridge?
> 
> Like the homebridge website says. Is this not the way to install it correctly?
> 
> `npm -g install homebridge`

I did run that command as user root on a small Debain 10.3 x64 VM.
Did I install it corrextly?
