### ISSUE TITLE
Clarification on volume and mute

### ISSUE THREAD

**Issue by twynne** [nicoduj/homebridge-harmony#251]
Adding this as a feature request as it's not really a 'bug', but would be great if you could clarify the use of the mute/volume options.  What I'd like to achieve is that when viewing the iOS 'remote', the volume up/down links to iPhone volume up/down and controls whichever activity is active on the Harmony being controlled (as opposed to just the TV). 

How should the options be set to achieve that?

**Comment by nicoduj** [comment]
Hi, this should be the case , volume and remote are linked to the current input of tv (so current activity on harmony) . Can you share your config and log in debug while pressing the up/ down volume ?

**Comment by twynne** [comment]
Testing further, but I think it’s now mostly working.  Suspect I had a mis-configuration on the Harmony side which I hadn’t realised until looking deeper (meaning Harmony wasn’t controlling Sonos on certain activities).  I’ll continue testing activities and report back if I find any issues.
