### ISSUE TITLE
Expose HomeKit devices to Harmony?

### ISSUE THREAD

**Issue by Vortec4800** [nicoduj/homebridge-harmony#255]
Does this plugin allow me to control HomeKit devices from the smart accessory (yellow) buttons on the Harmony remote? It seems like most of the documentation is focused on going in the opposite direction, controlling Harmony devices from HomeKit.

If this doesn't do that, does anyone know of a plugin that does? Is it even possible?

**Comment by Vortec4800** [comment]
I did some more reading and found `publishHomeControlButtons` and the limitations it has. Looks like I'll need to do something like emulate Hue bulbs and attach to those.

**Comment by nicoduj** [comment]
exactly :)
