### ISSUE TITLE
[BUG] UUID conflict crashloop with homebridge 1.0.0 

### ISSUE THREAD

**Issue by machineglow** [nicoduj/homebridge-harmony#256]
**Describe the bug**
Upgraded to Homebridge 1.0.0 and ran into a crash loop.  

**To Reproduce**
1. upgrade to homebridge 1.0.0
2. running homebridge-harmony 1.3.7

**Expected behavior**
Expected homebridge to start up.  

**IOS (please complete the following information):**
- Version 13.4.1
- Device: ipad pro 9.7 and iphone SE

**Logs**
```
Apr 27 03:14:20 homiebee homebridge[85639]: [4/27/2020, 3:14:20 AM] Failed to find plugin to handle accessory HarmonyHub-Panasonic TV-PowerToggle
Apr 27 03:14:20 homiebee homebridge[85639]: [4/27/2020, 3:14:20 AM] Failed to find plugin to handle accessory HarmonyHub-Pioneer AV Receiver-VolumeUpVolumeUpVolumeUpVolumeUpVolumeUp
Apr 27 03:14:20 homiebee homebridge[85639]: [4/27/2020, 3:14:20 AM] Failed to find plugin to handle accessory HarmonyHub-Pioneer AV Receiver-VolumeDownVolumeDownVolumeDownVolumeDownVolumeDownVolumeDownVolumeDownVolumeDownVolumeDownVolume
Apr 27 03:14:20 homiebee homebridge[85639]: [4/27/2020, 3:14:20 AM] Failed to find plugin to handle accessory HarmonyHub-Pioneer AV Receiver-Mute
Apr 27 03:14:20 homiebee homebridge[85639]: [4/27/2020, 3:14:20 AM] Failed to find plugin to handle accessory HarmonyHub-Pioneer AV Receiver-ExtendedStereo
Apr 27 03:14:20 homiebee homebridge[85639]: [4/27/2020, 3:14:20 AM] Failed to find plugin to handle accessory HarmonyHub-Pioneer AV Receiver-ModeStandard
Apr 27 03:14:20 homiebee homebridge[85639]: [4/27/2020, 3:14:20 AM] Failed to find plugin to handle accessory HarmonyHub-TV
Apr 27 03:14:20 homiebee homebridge[85639]: [4/27/2020, 3:14:20 AM] Failed to find plugin to handle accessory HarmonyHub-Pioneer AV Receiver-PowerToggle
Apr 27 03:14:20 homiebee homebridge[85639]: [4/27/2020, 3:14:20 AM] Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: efba48cc-0514-40d8-9b3c-b8e24a1daad5
Apr 27 03:14:20 homiebee homebridge[85639]:     at Bridge.Accessory._this.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:413:15)
Apr 27 03:14:20 homiebee homebridge[85639]:     at /usr/local/lib/node_modules/homebridge/src/server.ts:287:19
Apr 27 03:14:20 homiebee homebridge[85639]:     at Array.filter (<anonymous>)
Apr 27 03:14:20 homiebee homebridge[85639]:     at Server.restoreCachedPlatformAccessories (/usr/local/lib/node_modules/homebridge/src/server.ts:268:69)
Apr 27 03:14:20 homiebee homebridge[85639]:     at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:156:10)
Apr 27 03:14:20 homiebee homebridge[85639]:     at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:74:10)
Apr 27 03:14:20 homiebee homebridge[85639]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
Apr 27 03:14:20 homiebee homebridge[85639]:     at Module._compile (internal/modules/cjs/loader.js:1147:30)
Apr 27 03:14:20 homiebee homebridge[85639]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
Apr 27 03:14:20 homiebee homebridge[85639]:     at Module.load (internal/modules/cjs/loader.js:996:32)
Apr 27 03:14:20 homiebee homebridge[85639]:     at Function.Module._load (internal/modules/cjs/loader.js:896:14)
Apr 27 03:14:20 homiebee homebridge[85639]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
Apr 27 03:14:20 homiebee homebridge[85639]:     at internal/main/run_main_module.js:17:47
Apr 27 03:14:20 homiebee homebridge[85639]: [4/27/2020, 3:14:20 AM] Got SIGTERM, shutting down Homebridge...
Apr 27 03:14:20 homiebee homebridge[85639]: [4/27/2020, 3:14:20 AM] [HarmonyHub] INFO - shutdown

```

**Config**
```
{
                        "platform": "HarmonyHubWebSocket",
                        "name": "HarmonyHub",
                        "hubIP": "192.168.1.196",
                        "showTurnOffActivity" : false,
                        "mainActivity": "Watch Apple TV",
                        "publishSwitchActivitiesAsIndividualAccessories" : true,
                        "publishGeneralMuteSwitch": true,
                        "publishGeneralVolumeSlider": true,
                        "devicesToPublishAsAccessoriesSwitch" : ["Pioneer AV Receiver"
                                ,"Panasonic TV"
                                ,"Pioneer AV Receiver|Volume Up;VolumeUp;VolumeUp;VolumeUp;VolumeUp;VolumeUp"
                                ,"Pioneer AV Receiver|Volume Down;VolumeDown;VolumeDown;VolumeDown;VolumeDown;VolumeDown;VolumeDown;VolumeDown;VolumeDown;VolumeDown;VolumeDown"
                                ,"Pioneer AV Receiver|Mute;Mute"
                                ,"Pioneer AV Receiver|Extended Stereo;ExtendedStereo"
                                ,"Pioneer AV Receiver|Standard Audio Mode;ModeStandard"
                                ]
                },
```

**Comment by nicoduj** [comment]
did you try 1.0.1 ? there is a problem on homebridge side

**Comment by nicoduj** [comment]
https://github.com/homebridge/homebridge/pull/2522

**Comment by machineglow** [comment]
I have not yet.  that was a fast =).  Will try later though I'm a bit gun shy cause I had to downgrade twice before the config would work again.  Not sure why. maybe something to do with the cached/persist files....

**Comment by nicoduj** [comment]
yes, it is because cache is rewrite at homebridge stop. It has to be deleted while homebridge stopped, or at startup . 
like all 1.0.0, there are some things to fix :p

**Comment by tooh** [comment]
I experience  the same on v1.0.1

**Comment by nicoduj** [comment]
@tooh can you post your logs and config please ? It seems that cached accessories / external accessories might be an issue with the upgrade but can’t reproduce for now , might be on homebriddge side or plugin side .
Clean cache seems to make it ok

**Comment by TheEngineerGuy** [comment]
updated to 1.0.1, getting the same error:

```
(node:18222) UnhandledPromiseRejectionWarning: Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 0feddaa8-b425-40aa-88cd-76ff503afe3b
    at Bridge.Accessory._this.addBridgedAccessory (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:413:15)
    at Bridge.Accessory._this.addBridgedAccessories (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:447:12)
    at Server.handleRegisterPlatformAccessories (/usr/lib/node_modules/homebridge/src/server.ts:480:17)
    at HomebridgeAPI.emit (events.js:310:20)
    at HomebridgeAPI.registerPlatformAccessories (/usr/lib/node_modules/homebridge/src/api.ts:296:10)
    at HarmonyBase.addAccessories (/usr/lib/node_modules/homebridge-harmony/harmonyBase.js:1236:25)
    at HarmonyBase.setupFoundAccessories (/usr/lib/node_modules/homebridge-harmony/harmonyBase.js:333:14)
    at HarmonySubPlatform.readAccessories (/usr/lib/node_modules/homebridge-harmony/harmonySubPlatform.js:161:22)
    at /usr/lib/node_modules/homebridge-harmony/harmonyBase.js:93:27
(node:18222) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:18222) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by tooh** [comment]
I cleared cache no solution
My logs are the same as @TheEngineerGuy

**Comment by nicoduj** [comment]
I need full logs and config to help, sorry guys. Only the error does not help. 

@tooh : how did you clean the cache ? Did you do it while homebridge was stopped ?

**Comment by TheEngineerGuy** [comment]
I cleared cache and accessories, and seems to have resolved itself.

EDIT: But, I do wish to bring your attention to this last part here, we are using a deprecated approach. Should it be updated?

`(node:18222) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:18222) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by nicoduj** [comment]
@TheEngineerGuy : thanks for the update. Yeah i could definitely do a try / catch around that on the plugin side,  but would not solve the problem at all .

**Comment by TheEngineerGuy** [comment]
100% agreed. 2 mutually exclusive items.

**Comment by tooh** [comment]
Here my log
``
Failed to find plugin to handle accessory Harmony-TV
[4/27/2020, 7:55:37 PM] Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 251fd294-4705-48fd-9645-2661664c61f4
    at Bridge.Accessory._this.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:413:15)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:287:19
    at Array.filter (<anonymous>)
    at Server.restoreCachedPlatformAccessories (/usr/local/lib/node_modules/homebridge/src/server.ts:268:69)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:156:10)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:74:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
``

I cleared cache using the advanced option in config-ui-x

**Comment by machineglow** [comment]
can someone post the manual steps for clearing the cache?  I'd like to try this before upgrading to 1.0.1.  

Thanks,

**Comment by TheEngineerGuy** [comment]
> can someone post the manual steps for clearing the cache? I'd like to try this before upgrading to 1.0.1.
> 
> Thanks,

Refresh Homebridge accessories:
```
sudo hb-service stop
ls /var/lib/homebridge/
rm -dR /var/lib/homebridge/accessories
rm -dR /var/lib/homebridge/persist
ls /var/lib/homebridge/
sudo hb-service start
```

**Comment by nicoduj** [comment]
For the moment, I don't see any other way to solve than to clear cache / persist and uninstall / reinstall plugin (breaking all automation and so). It seems for some reason that this change had no effect before 1.0.0 of homebridge (I made it on purpose seeing the logs reported in beta, like @donavanbecker pointed me, since I was registering before with a plugin name that was not correct), but with 1.0 it is a problem it seems both for cached accessories and external accessories retrieval (I think it now retrieves them from the plugin name, before it was more "tolerant" and retrived the way it was registered). Trying to find a better way with homebridge people but not really confident, sorry guys.

**Comment by pponce** [comment]
I followed the advice by ebaauw here:
https://github.com/homebridge/homebridge/issues/2428

If you delete the persist directory you lose everything. It's like a complete reset of homebridge.  If you have a lot of rooms, devices, plugins then it's pain to get everything back the way you had it.
Try first uninstalling the harmony plugin then run homebridge with the -R option to remove only the harmony now stale cached accessories.  
Then re-instal the harmony plugin and reconfigure just the harmony devices/accessories.  You will have to add them back into scenes and rooms. But it's better than configuring everything from scratch across all plugins.

---edit---
Looks like in homebridge 1.0.2,  Removing orphaned cached accessories is now the default behavior. So if you uninstall the plugin and remove it from the config and restart homebridge cached accessories should be removed.

**Comment by nicoduj** [comment]
https://github.com/nicoduj/homebridge-harmony/issues/257#issuecomment-620410122
