### ISSUE TITLE
[BUG] Update to homebridge 1.0.1 "Cannot add a bridged Accessory with the same UUID as another bridged Accessory"

### ISSUE THREAD

**Issue by pponce** [nicoduj/homebridge-harmony#257]
**Describe the bug**
Error on Homebridge start after update to hombridge 1.0.1.

[4/27/2020, 9:37:52 AM] [myHarmonyHub] (myHarmonyHub)WARNING - setupFoundAccessories - TV accessory added in your bridge, if another plugin is exposing a TV accessory this one might not be visible in your remote widget
(node:22092) UnhandledPromiseRejectionWarning: Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: (UUID here)
    at Bridge.Accessory._this.addBridgedAccessory (/home/pi/.nvm/versions/node/v12.16.2/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:413:15)
    at Bridge.Accessory._this.addBridgedAccessories (/home/pi/.nvm/versions/node/v12.16.2/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:447:12)
    at Server.handleRegisterPlatformAccessories (/home/pi/.nvm/versions/node/v12.16.2/lib/node_modules/homebridge/src/server.ts:480:17)
    at HomebridgeAPI.emit (events.js:310:20)
    at HomebridgeAPI.registerPlatformAccessories (/home/pi/.nvm/versions/node/v12.16.2/lib/node_modules/homebridge/src/api.ts:296:10)
    at HarmonyBase.addAccessories (/home/pi/.nvm/versions/node/v12.16.2/lib/node_modules/homebridge-harmony/harmonyBase.js:1236:25)
    at HarmonyBase.setupFoundAccessories (/home/pi/.nvm/versions/node/v12.16.2/lib/node_modules/homebridge-harmony/harmonyBase.js:333:14)
    at HarmonySubPlatform.readAccessories (/home/pi/.nvm/versions/node/v12.16.2/lib/node_modules/homebridge-harmony/harmonySubPlatform.js:161:22)
    at /home/pi/.nvm/versions/node/v12.16.2/lib/node_modules/homebridge-harmony/harmonyBase.js:93:27
(node:22092) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:22092) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

There is a new line in my cachedAccessories file that uses the same UUID that was already present before I upgraded.

Previously Existing line from cachedAccessories:
{"plugin":"homebridge-harmonyHub","platform":"HarmonyHubWebSocket","context":{"subPlatformName":"myHarmonyHub"},"displayName":"myHarmonyHub-TV","UUID":........

New line added to cachedAccessories after restarting homebridge that is causing the error:
{"plugin":"homebridge-harmony","platform":"HarmonyHubWebSocket","context":{"subPlatformName":"myHarmonyHub"},"displayName":"myHarmonyHub-TV","UUID":.......

**Comment by nicoduj** [comment]
@pponce thank you for the difference ! It finally gives me a clue on what is happening

**Comment by pponce** [comment]
If you need the full lines to see the differences let me know.
I was not sure if any of the UUID values should not be shared on the open internet.  So only pasted the start of the lines. Can DM the full lines to you if that would help.

**Comment by nicoduj** [comment]
Don't need, thank you. The problem is there if you have declared everything before release 1.3.5 of the plugin, where I changed the platform registration name to handle a warning in upcoming homebridge 1.0
You have to clean cache and delete persist files for extrernal accessories, and reinstall I think

**Comment by nicoduj** [comment]
For the moment, I don't see any other way to solve than to clear cache / persist and uninstall / reinstall plugin (breaking all automation and so). It seems for some reason that this change had no effect before 1.0.0 of homebridge (I made it on purpose seeing the logs reported in beta, like @donavanbecker pointed me, since I was registering before with a plugin name that was not correct), but with 1.0 it is a problem it seems both for cached accessories and external accessories retrieval (I think it now retrieves them from the plugin name, before it was more "tolerant" and retrived the way it was registered). Trying to find a better way with homebridge people but not really confident, sorry guys.

**Comment by pponce** [comment]
I've in the past done surgical edits of the cachedAccessories file.
Do you think it would be enough to edit that file. remove all HarmonyHub references.
Uninstall and re-install the harmony plugin?

I'm afraid to delete the persist directory contents.  If i do that do you know if I will have to completely re-configure all my homekit setting across all my plugins etc..?
See this comment:  Would like to avoid this. 
https://github.com/homebridge/homebridge/issues/2428

I'm going to roll back homebridge install to latest before the 1.0 change as I am now also reading about potential issues with users added to my home and the suggestion to remove users from the homekit home before updating.  I'll get back to my original state before the update.

Then i'll remove the harmony plugin and make sure there are no references to it in my cachedAccessories.  I'll remove all users from homekit home (as is suggested).  I'll then update homebridge again and then re-install the harmony plug in.

I'll see how that goes and report back later today.

**Comment by nicoduj** [comment]
I fear so yes. You might try just changing the plugin name you pointed into cached accessory file and see if it works. should if you have only one hub

**Comment by nicoduj** [comment]
- stop homebridge
- change "plugin":"homebridge-harmonyHub" -> "plugin":"homebridge-harmony" in old line
- delete the new line added.
- restart

**Comment by pponce** [comment]
Ok Good news:  I was able to keep all my homekit settings. Didn't have to do an entire reset.
Not sure if all the steps were required. Probably just surgically removing the old harmony entries in cachedAccessories would have done the trick. That and uninstalling then re-installing homebridge-harmony.
But i wanted to revert as i wanted to do the suggested steps of removing all users from homekit before updating.

Here were my steps: 

- stopped homebridge service
- Reverted back to old homebridge version.
npm install -g  homebridge@0.4.53
- edited cachedAccessories to remove the newly added line that the homebridge-harmony plugin added
- restarted homebridge to make sure there were no errors and that the harmony plugin worked.
All worked as expected with no errors.
- stopped homebridge service again.
- edited cachedAccessories to remove all the lines that existed for the homebridge-harmony plugin
- uninstalled homebridge-harmony:  npm uninstall -g  homebridge-harmony
- removed homebridge-harmony config settings from the config.conf file
- started homebridge with the -R option to remove the stale cached accessories. Don't think i needed to do this step as i had already manually edited cachedAccessories file but did it for good measure. (This -R option might help me in the future avoid having to manually edit the file)
- stopped homebridge service again.
- updated homebridge to 1.0.1
- installed homebridge-harmony again
- added the config parameters for homebridge-harmony to config.conf
- restarted homebridge service.

The above steps fixed the errors i was seeing.
All i had to do was move the harmony accessories into the correct room and add the commands to existing scenes again.
So no need to delete persist folder and its contents as that is the nuclear option.

Thanks again for all your work on this plugin. Hope my the steps i took will help others.

**Comment by nicoduj** [comment]
Hi @pponce , the way you did it seems ok ,thank you for sharing.
Meanwhile, a new homebridge version was released that should handle all this automatically :
- default will be to remove orphaned accessories (thus old one retrieved won't collide with the one)
- improved plugin resolution for cached accessories by searching a best match without conflicts
  
[homebridge v1.0.2](https://github.com/homebridge/homebridge/releases/tag/1.0.2) .
