### ISSUE TITLE
[BUG] Can't publish TV Acccessory as external device, need Homebridge 0.0.47 at least

### ISSUE THREAD

**Issue by julien94800** [nicoduj/homebridge-harmony#258]
**Describe the bug**
I get this message while running homebridge with this plugin since last homebridge version.
Any idea about the rootcause? Thanks in advance

[4/27/2020, 9:25:03 PM] [Harmony Salon] (Harmony Salon)ERROR - readAccessories - Can't publish TV Acccessory as external device, need Homebridge 0.0.47 at least : Error: EISDIR: illegal operation on a directory, read | stdout
-- | --

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**

**Screenshots**

**IOS (please complete the following information):**
- Version 13
- Device: iPhone 11

**Logs**

**Config**
{
    	"platform": "HarmonyHubWebSocket",
    	"name": "Harmony Salon",
    	"hubIP": "192.168.0.53",
    	"publishAllTVAsExternalAccessory" : true,
    	"mainActivity" : "Regarder la TV",
    	"cleanCache": false,
    	"showCommandsAtStartup" : false,
    	"remoteOverrideCommandsList":
    			{"Regarder la TV":
    				{
        		 	"SETUP": "BBox;Home",
        		 	"INFORMATION": "BBox;Home"
    				}
    			}
    },
**Additional context**

**Comment by nicoduj** [comment]
You will need 1.0.1 https://github.com/homebridge/homebridge/pull/2522

But be aware there are issues and you will need probably to clean or modify you cache . See other bug reports

**Comment by julien94800** [comment]
Thanks for your quick feedback. I was already in 1.0.1 and I manually cleaned all persists/accessory folders and still get this message.
So I modified publishAllTVAsExternalAccessory to False and now seems to be ok. It was essentially for  your information
