### ISSUE TITLE
Different activities in different rooms 

### ISSUE THREAD

**Issue by Krocko** [nicoduj/homebridge-harmony#26]
Is it possible for you to make an option, to sort the avtivities in different rooms?

**Comment by nicoduj** [comment]
Hi, I will think of it but since all activities are linked to one accessory, it is not possible right now. You have only one hub am I correct ?

**Comment by Krocko** [comment]
Yes i have only one hub. At the moment i am using the harmonyhub plugin @0.1.1 because of this.

**Comment by Krocko** [comment]
Thank you. This works.

**Comment by nicoduj** [comment]
@Krocko : thanks for the update, but I fear there is a bug in latest version that will crash your homebridge instance. Trying t fix it, hope it will be good for tomorrow.

**Comment by Krocko** [comment]
Tested the Switches. Noticed no crash until now.

**Comment by nicoduj** [comment]
ok, depends on your settings. however 0.1.2 should fix everything ! enjoy ;)

**Comment by NoTrace-Kai** [comment]
Ups ... i already did a "pull request" a few minutes ago ..
sorry, i saw this posts here to late ... is it now possible to use different activities in different rooms?
