### ISSUE TITLE
[BUG] Hubs do not always appear as HomeKit TVs in the Apple TV Remote app

### ISSUE THREAD

**Issue by mikesalz** [nicoduj/homebridge-harmony#262]
**Describe the bug**
I have 3 Harmony hubs connected.  They all display in HomeKit and work perfectly.  But in the Apple TV Remote in Control Center, they are very inconsistent.  Sometimes one shows up.  Sometimes they all show up.  Sometimes none of them are there. 

**To Reproduce**
Hard to reproduce as there does not seem to be any common scenarios that produce it.  But I suspect it only happens when you have multiple Harmony hubs.

**Expected behavior**
All connected Harmony hubs should show up in the Apple TV Remote in Control Center.

**Screenshots**
In the screenshot, you can see that only one Harmony hub (Loft TV) is being picked up.

![image](https://user-images.githubusercontent.com/46855061/80930294-b332c280-8d80-11ea-931c-cc268d009c99.png)

**IOS (please complete the following information):**
- Version: 13.4.1
- Device: iPhone 11 Pro Max

**Logs**
No errors appear in logs

**Config**
 ```
       {
            "platform": "HarmonyHubWebSocket",
            "name": "FamilyRoomHarmonyHub",
            "hubIP": "xxx.xxx.x.xxx",
            "mainActivity": "Watch Apple TV",
            "otherPlatforms": [
                {
                    "name": "LoftHarmonyHub",
                    "hubIP": "xxx.xxx.x.xxx",
                    "mainActivity": "Watch Loft Apple TV"
                },
                {
                    "name": "MasterBedroomHarmonyHub",
                    "hubIP": "xxx.xxx.x.xxx",
                    "mainActivity": "Watch Master Bedroom Apple TV",
                    "homeControlsToPublishAsAccessoriesSwitch": [
                        "hue-switch.harmony_master_bedroom_fan_switch",
                        "hue-switch.harmony_master_bedroom_fan_light_switch"
                    ]
                }
            ]
        },
```

**Additional context**

**Comment by nicoduj** [comment]
Hi, I think it was introduced in latest homebridge but not sure, still checking this. logs in full (DEBUG=*) while this is happening could help . Referenced also in #261 I think.

**Comment by mikesalz** [comment]
Here is the log.  Please let me know if this is useful.  Thanks!
[Log.txt](https://github.com/nicoduj/homebridge-harmony/files/4576529/Log.txt)

**Comment by nicoduj** [comment]
Did not find any usefull info in there. Was the problem occuring in this log ? it seems only to be a startup log

**Comment by mikesalz** [comment]
Only one of the 3 hubs was showing up at the time that I grabbed the logs.  In fact, I think I have only seen the Loft hub exclusively for quite some time now.  Is there a limitation that only allows one hub into the remote app?

**Comment by nicoduj** [comment]
The fact to  publish them as external accessories was for that purpose . I think it is homebridge / hap related but not sure ... could you try removing one and adding again ?

**Comment by nicoduj** [comment]
Can you try with homebridge 1.0.4 ? Other users seems to say it is working again (see #261)

**Comment by mikesalz** [comment]
I am actually on 1.0.4.  One more thought, based on your comment regarding external accessories.  Do I need to include:
    "publishAllTVAsExternalAccessory" : true

I am not currently doing that in my config.  Maybe that was added after I created it, or maybe I missed it?

**Comment by mikesalz** [comment]
OK, so it is not publishAllTVAsExternalAccessory. I tried that and it did nothing.  So then I tried removing all TVs, and then adding back only the main one I need in the remote widget (Family Room TV).  It did show up then.  Then I added back the other two hubs.  Still, only the Family Room TV shows up in the remote widget.  So I am back to my original issue - Only one TV is showing in the remote widget.  I did notice this in the logs:

> TV accessory added in your bridge, if another plugin is exposing a TV accessory this one might not be visible in your remote widget

I don't have another plugin exposing them to HomeKit through Homebridge.  But it does sort of sound like this might be close to the issue.  Thoughts?

**Comment by nicoduj** [comment]
> Then I added back the other two hubs.

Did you remove the whole hub ? From your config, the frist TV was linked to the hub, only second and third had to be removed individually (force touch on the accessory in home app)

> Then I added back the other two hubs.

Are they visible inside home app ? Did you add the 2nd and 3rd manually ? The log you are seeing is a reminder for external accessories : they are not linked directly to the hub exposed by homekit, and have to be added like any other device in home app (with the same code / by autodiscovery)

**Comment by mikesalz** [comment]
Sorry, I should have given more detail.  First I completely removed HarmonyHubWebSocket from my config and then restarted Homebridge.  This of course removed it from HomeKit.  I also verified that there were no remaining references in cachedAccessories.

I then added HarmonyHubWebSocket back, with only one hub (Family Room).  I restarted, and this hub showed up in HomeKit and in the remote widget.

I then added back the other two hubs.  I restarted, and added them in to HomeKit.  All 3 now show up and work in HomeKit.  But only the Family Room hub shows up in the remote widget.

**Comment by nicoduj** [comment]
I think your external accessories are messed up i you did not have to re add them one by one in home app.
They are not cached, only referenced in persists folder, and Is suspect you have to delete them and R-eadd them from home app

**Comment by mikesalz** [comment]
That sounds plausible.  Do you have a recommendation how to fix it?

Worst case, the primary TV that I want to be able to control in the remote widget IS there now.  So it is not the end of the world if I can't get the other two TVs to show up.  But it would be nice to have them there.

**Comment by nicoduj** [comment]
I discussed with @supereg about this on discord, and here is what he is saying : 

> would you mind just reinstalling 1.0.4 to ensure you got the latest version and that all the latest depedencies are pulled in (some dependencies got updated after the release of 1.0.4 with minor changes which get pulled in automatically with reinstalling).
Would` be great if you could report back on this, if the issue still persists when running the current, latest versions of everything. There were some changes over the last few versions regarding the underlying dns-sd implementation." 

And

> the latest 1.0.4 should replicate behavior like it was at 0.4.x
We currently are also in the process of creating a new dns-sd aka bonjour implementation. It improves heavily on bonjour-hap and we hope we can squash a lot of issues users are currently having. But that will still take some time to release.


So let me know if possible !

**Comment by mikesalz** [comment]
Thanks for the info.  I downloaded the latest docker image today, but unfortunately it is still the same result.  Like I said, it is not the end of the world.  I have the main TV that I want in the remote widget.  The others are just nice to have.

**Comment by mikesalz** [comment]
Check out this HomeAssistant thread.  It looks like this might actually be a limitation in HomeKit.

https://community.home-assistant.io/t/homekit-new-options-tv-source/98912/84

**Comment by nicoduj** [comment]
> Check out this HomeAssistant thread. It looks like this might actually be a limitation in HomeKit.
> 
> https://community.home-assistant.io/t/homekit-new-options-tv-source/98912/84

Hi, this is why the second one or all can be exposed as external accessories . It was working fine but it seems that latest homebridge has some problems with that .

**Comment by nicoduj** [comment]
@donavanbecker could you help us on this and especially what to check with homebridge team ?

**Comment by joerexlo** [comment]
i am having simila issue but for me the second hub is not coming as a remote but in homekit everything is working fine

**Comment by nicoduj** [comment]
@joerexlo : did you publish as external accessories all of your remotes ? IT seems more reliable this way.

**Comment by joerexlo** [comment]
Thanks @nicoduj  I tried this and it worked. published as external and then added them manually.
