### ISSUE TITLE
[BUG] numberOfCommandsSentForVolumeControl still working

### ISSUE THREAD

**Issue by Phoenix-DH** [nicoduj/homebridge-harmony#263]
Hey,

I got the following config, and the amount of volume changes is not working anymore. 
It is always 1. I have sll plugin up to dste.

`"platform": "HarmonyHubWebSocket",
            "name": "Entertain",
            "hubIP": "192.168.xxx.xxx",
            "TVPlatformMode": true,
            "mainActivity": "TV",
            "switchAccessories": true,
            "devicesToPublishAsAccessoriesSwitch": [
                "Beleuchtung TV;PowerOn",
                "Beleuchtung TV;PowerOff",
                "Beleuchtung Theke;PowerToggle"
            ],
            "publishGeneralVolumeSlider": true,
            "publishGeneralMuteSwitch": true,
            "linkVolumeControlToTV": true,
            "remoteOverrideCommandsList": [
                {
                    "ActivityName": "TV",
                    "CommandsList": [
                        {
                            "CommandName": "INFORMATION",
                            "NewCommand": "Samsung Q60R;Home"
                        }
                    ]
                },
                {
                    "ActivityName": "Apple TV",
                    "CommandsList": [
                        {
                            "CommandName": "INFORMATION",
                            "NewCommand": "Samsung Q60R;Home"
                        }
                    ]
                }
            ],
            "numberOfCommandsSentForVolumeControl": 4,
            "cleanCache": false `

Is this still working?

Do I maybe habe the wrong order?

**Comment by nicoduj** [comment]
It is a known bug yes, a fix will be released soon I was waiting for another logs for another bug to do a release, sorry

**Comment by Phoenix-DH** [comment]
Ah okay, haven‘t found anything related 🤷🏼‍♂️
Thanks.

**Comment by nicoduj** [comment]
No problem ! #261 : 2 issues :)
