### ISSUE TITLE
[BUG] "publishHomeControlsAsIndividualAccessories" does not show any accessories

### ISSUE THREAD

**Issue by beyerjp** [nicoduj/homebridge-harmony#264]
I am unable to get any home devices (or any devices in general) to appear despite numerous attempts at configuration. Harmony Hub, node, Homebridge, and Harmony plugin are all fresh installs to remove any variability. I am not using any secondary authentication (e.g. Facebook, Google) to login to my account. Harmony hub is responding, and when I create an activity with just one light in it (either Z-wave through Hub Extender or Hue light native to base hub), it will turn the device on, but not off. When I do not have any activities associated with devices, no devices appear in Homebridge or HomeKit. Homebridge is functioning for other plugins as expected.

**To reproduce** 
Use below configuration (or an array which codes appropriately in Homebridge GUI); no devices appear, both Z-wave or Hue for home devices, or entertainment devices.

**System versions**

iOS:
- Version: 13.4.1
- Device: iPhone 11 Pro

Homebridge 
 - Version: 1.0.4

macOS:
- Version 10.15.4

**Logs**
Your log in debug mode (-D option)

In the below configuration:

        {
            "name": "Harmony",
            "hubName": "Harmony",
            "switchAccessories": true,
            "publishHomeControlsAsIndividualAccessories": true,
            "platform": "HarmonyHubWebSocket"
        }

[log.txt](https://github.com/nicoduj/homebridge-harmony/files/4631135/log.txt)

**Comment by beyerjp** [comment]
I have been reading further and it seems this post may have something to do with this:
https://github.com/nicoduj/homebridge-harmony/issues/118#issuecomment-477455911
It appears in the last post, you added the option select the devices you want to expose. Is this the only option? I am still confused since I have added the devices I would like in HomeKit to an array and they still do not show as switches in HomeKit. Of note, the Watch TV switch does appear and seems to be behaving appropriately.

        {
            "name": "Harmony",
            "hubName": "Harmony",
            "TVAccessory": true,
            "mainActivity": "Watch TV",
            "switchAccessories": true,
            "publishSwitchActivitiesAsIndividualAccessories": true,
            "homeControlsToPublishAsAccessoriesSwitch": [
                "Office Floor Lamp",
                "Bathroom Vanity",
                "Left Nightstand",
                "Right Nightstand"
            ],
            "publishHomeControlsAsIndividualAccessories": true,
            "platform": "HarmonyHubWebSocket"
        }

Below are my devices in the Harmony app:
![IMG_26CDB7B1D4ED-1](https://user-images.githubusercontent.com/65371849/82065175-62ca3780-9693-11ea-9404-4eba4b858da7.jpeg)

Thank you for any help you can provide!! 

[log.txt](https://github.com/nicoduj/homebridge-harmony/files/4635103/log.txt)

**Comment by nicoduj** [comment]
Hi, 

the plugin is focused on activities, not device, so with your config you will have a tv accesory with each activity as an input, and a switch for each activity in harmony app.  You can expose "normal" device with some commands (like your LG or yamaha), but for home controls basically it will only expose what you have on the physical buttons on your remote, not devices themselves since they are noly g-handled by the app itself, not the hub.

To have names of your home controls, I suggest you use debug mode in homebridge without the following option homeControlsToPublishAsAccessoriesSwitch

You will see logs if everything is ok like this : 'INFO - got Home Control  which will tell you the names you can use in homeControlsToPublishAsAccessoriesSwitch ..

**Comment by beyerjp** [comment]
Thank you for the reply! Would this be a possible enhancement, or is it not technically possible at all? Would a workaround be creating individual activities for each home control device? Based on that previous post, the poster's Caseta and Hue devices all were exposed so unsure what configuration caused that but that is what I am looking for. Thanks!

**Comment by nicoduj** [comment]
As far as I know the commands to hue and other home accessories are sent from the app directly and not exposed by the bridge.

My remote does not have home buttons,so I can tell more but users for whom I implemented the feature shared their config and I was only able to implement a binding to physical remote commands button that are understandable by the hub . 

I don’t know if you can add home device to activities, if yes you can try the plugin should send to the hub an on / off command for each activity exposed

**Comment by nicoduj** [comment]
`Based on that previous post, the poster's Caseta and Hue devices all were exposed so unsure what configuration caused that but that is what I am looking for`

Could you explain what you mean, I am not sur I understood after all.
