### ISSUE TITLE
Unable to Add Air Conditioner

### ISSUE THREAD

**Issue by SSutherland94** [nicoduj/homebridge-harmony#265]
I'm not entirely sure if this is a bug or a feature request, but I seem to be having some trouble adding my Air Conditioner into the plugin. It shows up just fine in my Harmony App, but when I try to add it into the plugin, I don't get a tile for it in my Home app. My two soundbars however, show up just fine. Maybe I'm missing something? Any guidance would be greatly appreciated!

**Comment by SSutherland94** [comment]
Apologies. Had to add the Power toggle manually for some reason. Would be cool if Soundbars and Air Conditioners could have actual remote interfaces someday if that's a possibility, instead of a cluster of switches!

**Comment by nicoduj** [comment]
Hi, only activities are added automatically , not devices . Concerning a remote for a device, thinking of it but right now need to be sure that multiple remotes works well again in latest homebridge .

**Comment by SSutherland94** [comment]
Sounds good to me! I just got a bit confused when the soundbar power toggles popped up, but not the AC. Great to know that remotes are a thought! Hope you can make it happen somewhere down the line! Until then, I have some very organized clusters of switches for my devices. Thank you!

**Comment by SSutherland94** [comment]
Sorry, I hate double posting, but what you said just registered differently to me today. If you're referring to multiple remotes working in the Remote Control Center shortcut, I thought I should mention I have two TV's and two Xbox One X's showing up in there, and seemingly functional so far. Latest everything running on FreeNAS.

**Comment by nicoduj** [comment]
Hi, are they all exposed from the same hombridge instance , and what is the version of homebridge ? What plugin do you use, harmony for all of them ? Like I said it should work and was working really fine if this is the case due to use of external accessories , but many users are reporting it does not anymore or at least is not reliable (some times you see it but they do not respond ) since homebridge 1.x

**Comment by SSutherland94** [comment]
Apologies, I have separate plugins for my Samsung and Sony TV's and Xbox One. But they are all on the same Homebridge instance
