### ISSUE TITLE
WARNING - socket closed

### ISSUE THREAD

**Issue by Christian-CFP** [nicoduj/homebridge-harmony#266]
What does this mean?

After this warning this happens...
`WARNING - socket closed
ERROR (2)- refreshCurrentActivity TimeoutError: Can't open WebSocket within allowed timeout: 10000 ms. - Stack : TimeoutError: Can't open WebSocket within allowed timeout: 10000 ms.
    at PromiseController._handleTimeout (/home/hoobs/.hoobs/node_modules/promise-controller/src/index.js:172:19)
    at Timeout.<anonymous> (/home/hoobs/.hoobs/node_modules/promise-controller/src/index.js:178:43)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)`
`INFO - Loading activities...
Error - Error retrieving info from hub : Error: connect EHOSTUNREACH xxx.xxx.xxx.xxx:8088-(445)`

The hub and the remote works just fine even with this message. Only homebridge is affected and I don't know why.

After this the connection is gone and restart the service does not work. I have to disconnect the Hub to get it work again.

**Comment by nicoduj** [comment]
Hi, could you sahre your config ? Are you on fix IP or autodiscovery of the hub ? It seems the hub becomes unreachable, maybe in case of IP change.

**Comment by Christian-CFP** [comment]
No, its a fixed IP. And like i mentioned, the hub works. I can even control it via my phone.

 "platform": "HarmonyHubWebSocket",
            "plugin_map": {
                "plugin_name": "homebridge-harmony"
            },
            "name": "TV",
            "hubIP": "192.168.100.221",
            "cleanCache": false,
            "mainActivity": "Fernseher",
            "playPauseBehavior": true,
            "publishHomeControlsAsIndividualAccessories": true,
            "publishDevicesAsIndividualAccessories": true,
            "switchAccessories": true,
            "showTurnOffActivity": "false",
            "TVAccessory": true,
            "publishSequencesAsIndividualAccessories": true,
            "publishSwitchActivitiesAsIndividualAccessories": true,
            "publishGeneralMuteSwitch": false,
            "showCommandsAtStartup": false,
            "publishHomeControlButtons": true,
            "addAllActivitiesToSkippedIfSameStateActivitiesList": true,
            "publishGeneralVolumeSlider": false,
            "linkVolumeControlToTV": true

**Comment by nicoduj** [comment]
Are you on hoobs ? It is clearly a network problem, double check IP on harmony app / network, firewall and so on ... It can't reach your hub on 8088 port, on the given address

**Comment by Christian-CFP** [comment]
Yes, I am on hoobs and I checked everything. Seems ok. But from time to time this happens... and I do not know why. Before 1.3.7 or before hoobs 3.2.4 it works just fine.

Or before nodes 12.16.3...

**Comment by nicoduj** [comment]
I can’t be sure everything works correctly on hoobs sorry, they are doing some stuff out of the my control and I only use legitimate homebridge install sorry !

**Comment by Christian-CFP** [comment]
No problem, thank you.

**Comment by Christian-CFP** [comment]
Further research...
This is a issue with my WiFi Mesh. If the Hub changes WiFi hub/router, ports will not assume.
Already reported this to the manufacturer.

**Comment by nicoduj** [comment]
What router are you using ? Orbi ? 

If yes (or maybe you can check options), check this thread : https://github.com/nicoduj/homebridge-harmony/issues/240#issuecomment-615557487

**Comment by Christian-CFP** [comment]
No, it is a common one here in germany. FritzBox from AVM.

**Comment by Corvetteguy19** [comment]
Not sure if you guys are still looking at this, but I’m having a similar problem with my hubs and my mesh network.  I have four harmony hubs, an xfinity xFi router and pods, and HOOBS keeps crashing when trying to connect to my hubs.  I’m connecting via hub name, but for some strange reason I keep getting a very similar error.  Now my hubs aren’t showing up properly in homekit.  Is this a common problem with mesh networks?  Any ideas on a fix?

**Comment by nicoduj** [comment]
I use mesh router and it works fine. (NEtgear one). some users reported that it works better with 20/40mhz coexistence disabled however (I am running those settings) - see previous comment.

However, it seems that there are more affected users with hoobs, don't really know what they do behind the scene.
