### ISSUE TITLE
[BUG] After 1.3.8 update, devicesToPublishAsAccessoriesSwitch not working

### ISSUE THREAD

**Issue by atonaltensor** [nicoduj/homebridge-harmony#269]
**Describe the bug**
After upgrading to 1.3.8, none of the devices listed under `devicesToPublishAsAccessoriesSwitches` are responsive. They appear in the iOS Home app correctly, but pressing the buttons does not do anything. (I've tried removing and re-adding the entire Homebridge Bridge from the iOS Home app, but the issue continues.) The same issue is true of the generalized mute switch under 'publishGeneralMuteSwitch: true'

**To Reproduce**
Add this to the config file:
```
"devicesToPublishAsAccessoriesSwitch": [
                "Vizio TV|TV Volume Up;VolumeUp|100;VolumeUp|100;VolumeUp",
                "Vizio TV|TV Volume Down;VolumeDown|100;VolumeDown|100;VolumeDown",
                "Xfinity Box|Watch CNN;Number8|100;Number1|100;Number7|100;Select",
                "Xfinity Box|Watch MSNBC;Number8|100;Number1|100;Number8|100;Select"]
```

**Expected behavior**
When pushing the "Watch CNN" activity tile in iOS Home app, the programmed sequence of button commands should be sent to Harmony Hub. 
(Note: I've double-checked to make sure that the name of the devices are exactly as it appears in Harmony Hub. Also, this was working fine before the update and I have not changed any settings.)

**Screenshots**
When launching Homebridge, the following error message shows up in the log:
 https://ibb.co/Hd4q1pc
```

(node:395) UnhandledPromiseRejectionWarning: Error: Cannot add a Service with the same UUID '0 00000DA-0000-1000-8000-0026BB765291' as another Service in this Accessory without also definin g a unique 'subtype' property. 

at Accessory._this.addService (/usr/local/lib/node_modules/homebridge/node_modules/hap-nod ejs/src/lib/Accessory.ts:276:17) 

at PlatformAccessory.addService (/usr/local/lib/node_modules/homebridge/src/platformAccess ory.ts:92:41) 

at HarmonySubPlatform.readTVAccessories (/homebridge/node_modules/homebridge-harmony/harmo nySubPlatform.js:298:24) 

at HarmonySubPlatform.readAccessories (/homebridge/node_modules/homebridge-harmony/harmony SubPlatform.js:158:58) 

at /homebridge/nodemodules/homebridge-harmony/harmonyBase. is: 93:27 

(node:395) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originate d either by throwing inside of an async function without a catch block, or by rejecting a prom ise which was not handled with .catch(). (rejection id: 1) 

(node:395) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the f uture, promise rejections that are not handled will terminate the Node.js process with a non-z ero exit code. 

```

**IOS (please complete the following information):**
- iOS Version 13.4.1
- Device: iPad Pro (2018)
- Homebridge Version: 1.1.0
- Homebridge Harmony Version: 1.3.8

**Comment by nicoduj** [comment]
Hi, which version did you upgrade from ? And are you exposing a tv accessory ? I am interested  in Your full config

**Comment by DMBlakeley** [comment]
Observing the same /similar issue on start of Homebridge:

`[5/21/2020, 3:03:42 PM] [Spectrum] (Spectrum)INFO - configuring Main TV Service
[5/21/2020, 3:03:42 PM] [Spectrum] (Spectrum)INFO - Configuring Main Activity Watch TV
(node:68748) UnhandledPromiseRejectionWarning: Error: Cannot add a Service with the same UUID '000000DA-0000-1000-8000-0026BB765291' as another Service in this Accessory without also defining a unique 'subtype' property.
    at Accessory._this.addService (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:276:17)
    at PlatformAccessory.addService (/usr/local/lib/node_modules/homebridge/src/platformAccessory.ts:92:41)
    at HarmonySubPlatform.readTVAccessories (/usr/local/lib/node_modules/homebridge-harmony/harmonySubPlatform.js:298:24)
    at HarmonySubPlatform.readAccessories (/usr/local/lib/node_modules/homebridge-harmony/harmonySubPlatform.js:158:58)
    at /usr/local/lib/node_modules/homebridge-harmony/harmonyBase.js:93:27
(node:68748) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:68748) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

**Comment by nicoduj** [comment]
Ok, sorry guys will try to reproduce with a similar config new services for access control must collide with others . Can you confirm you are exposing a tv service ? Like I said I would appreciate full config

**Comment by atonaltensor** [comment]
> Hi, which version did you upgrade from ? And are you exposing a tv accessory ? I am interested in Your full config

I upgraded Homebridge Harmony from 1.2.6 to 1.3.8. I also upgraded Homebridge itself from 0.4.53 to 1.1.0. 

I should add that all other aspects of Homebridge Harmony is working CORRECTLY, including switching inputs in Homekit, etc.  (Note the general mute switch is also not working).


Here is my full config: (hope it helps)

```
{
    "bridge": {
        "name": "Homebridge CD15",
        "username": [REDACTED],
        "port": [REDACTED],
        "pin": [REDACTED]"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Nest",
            "googleAuth": {
                "issueToken": [REDACTED],
                "cookies": [REDACTED],
                "apiKey": [REDACTED]
            },
            "platform": "Nest"
        },
        {
            "name": "Harmony Hub",
            "hubIP": [REDACTED],
            "TVAccessory": true,
            "mainActivity": "Watch TV",
            "numberOfCommandsSentForVolumeControl": 3,
            "switchAccessories": false,
            "showTurnOffActivity": "false",
            "publishGeneralMuteSwitch": true,
            "devicesToPublishAsAccessoriesSwitch": [
                "Vizio TV|TV Volume Up;VolumeUp|100;VolumeUp|100;VolumeUp",
                "Vizio TV|TV Volume Down;VolumeDown|100;VolumeDown|100;VolumeDown",
                "Xfinity Box|Watch CNN;Number8|100;Number1|100;Number7|100;Select",
                "Xfinity Box|Watch MSNBC;Number8|100;Number1|100;Number8|100;Select",
                "Xfinity Box|Watch Weather Channel;Number8|100;Number1|100;Number5|100;Select",
                "Xfinity Box|Watch Food Network;Number8|100;Number3|100;Number9|100;Select",
                "Xfinity Box|Watch PBS;Number2|100;Number2|100;Select",
                "Xfinity Box|Watch ESPN;Number8|100;Number5|100;Number0|100;Select",
                "Xfinity Box|Watch ESPN2;Number8|100;Number5|100;Number1|100;Select"
            ],
            "showCommandsAtStartup": true,
            "platform": "HarmonyHubWebSocket"
        }
    ]
}
```

**Comment by BigKrisch** [comment]
Hello,

I get the same error when starting the Homebridge:

> [2020-5-21 21:10:50] [Wohnzimmer Sony Bravia KDL-55W905A] (Wohnzimmer Sony Bravia KDL-55W905A)INFO - configuring Main TV Service
[2020-5-21 21:10:51] [Wohnzimmer Sony Bravia KDL-55W905A] (Wohnzimmer Sony Bravia KDL-55W905A)INFO - Configuring Main Activity Fernsehen
(node:623) UnhandledPromiseRejectionWarning: Error: Cannot add a Service with the same UUID '000000DA-0000-1000-8000-0026BB765291' as another Service in this Accessory without also defining a unique 'subtype' property.
    at Accessory._this.addService (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:276:17)
    at PlatformAccessory.addService (/usr/local/lib/node_modules/homebridge/src/platformAccessory.ts:92:41)
    at HarmonySubPlatform.readTVAccessories (/usr/local/lib/node_modules/homebridge-harmony/harmonySubPlatform.js:298:24)
    at HarmonySubPlatform.readAccessories (/usr/local/lib/node_modules/homebridge-harmony/harmonySubPlatform.js:158:58)
    at /usr/local/lib/node_modules/homebridge-harmony/harmonyBase.js:93:27
(node:623) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:623) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.


Enclosed my config.json:

> {
            "name": "Wohnzimmer Sony Bravia KDL-55W905A",
            "hubIP": "192.168.XXX.XXX",
            "hubName": "Wohnzimmer Harmony Hub",
            "cleanCache": false,
            "TVAccessory": true,
            "mainActivity": "Fernsehen",
            "addAllActivitiesToSkippedIfSameStateActivitiesList": true,
            "sequencesToPublishAsAccessoriesSwitch": [
                "Sky PIN"
            ],
            "showCommandsAtStartup": false,
            "platform": "HarmonyHubWebSocket"
        }

**Comment by DMBlakeley** [comment]
Here is my redacted config.json file:

{
    "bridge": {
        "name": "Homebridge C2B9",
        "username": "[REDACTED]",
        "port": [REDACTED],
        "pin": "[REDACTED]"
    },
    "accessories": [
        {
            "name": "Garage Door",
            "username": "[REDACTED]",
            "password": "[REDACTED]",
            "deviceId": "[REDACTED]",
            "accessory": "[REDACTED]"
        },
        {
            "name": "MyAwair",
            "token": "[REDACTED]",
            "devType": "awair-r2",
            "devId": [REDACTED],
            "model": "Awair 2nd Edition",
            "serial": "[REDACTED]",
            "carbonDioxideThreshold": 1000,
            "carbonDioxideThresholdOff": 600,
            "air_quality_method": "awair-score",
            "endpoint": "5-min-avg",
            "polling": 600,
            "userType": "users/self",
            "limit": 12,
            "logging": true,
            "accessory": "Awair"
        }
    ],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "f",
            "lang": "auto",
            "platform": "config"
        },
        {
            "name": "Nest",
            "access_token": "[REDACTED]",
            "options": [
                "Thermostat.SeparateBuiltInHumiditySensor.Enable",
                "HomeAway.Disable",
                "Debug.Verbose"
            ],
            "platform": "Nest"
        },
        {
            "name": "Spectrum",
            "hubIP": "10.0.1.27",
            "hubName": "Harmony Hub",
            "TVAccessory": true,
            "mainActivity": "Watch TV",
            "publishGeneralVolumeSlider": false,
            "platform": "HarmonyHubWebSocket"
        },
        {
            "refreshToken": "[REDACTED]",
            "platform": "Ring"
        },
        {
            "name": "Security System",
            "username": "[REDACTED]",
            "password": "[REDACTED]",
            "logLevel": 3,
            "pollTimeoutSeconds": 90,
            "armingModes": {
                "away": {
                    "noEntryDelay": false,
                    "silentArming": false
                },
                "night": {
                    "noEntryDelay": false,
                    "silentArming": false
                },
                "stay": {
                    "noEntryDelay": false,
                    "silentArming": false
                }
            },
            "platform": "Alarmdotcom"
        }
    ]
}

**Comment by nicoduj** [comment]
Thank you. Can you all tell me from which version you upgraded from ? (Harmony and maybe homebridge if you did)

**Comment by BigKrisch** [comment]
Update from 1.3.7 to 1.3.8
Homebridge: 1.1.0
Node.js 12.16.3

But before the bug, I only updated the plugin. Homebridge was already running on this version for a few days.

**Comment by DMBlakeley** [comment]
Updated from harmony 1.3.7. Other details:

node.js: v12.16.3
npm: v6.14.5
homebridge: 1.1.0

**Comment by nicoduj** [comment]
Ok, one last question : did it happen after a restart ?

**Comment by BigKrisch** [comment]
The same error message:

> [2020-5-21 21:50:09] [Wohnzimmer Sony Bravia KDL-55W905A] (Wohnzimmer Sony Bravia KDL-55W905A)INFO - configuring Main TV Service
[2020-5-21 21:50:10] [Wohnzimmer Sony Bravia KDL-55W905A] (Wohnzimmer Sony Bravia KDL-55W905A)INFO - Configuring Main Activity Fernsehen
(node:480) UnhandledPromiseRejectionWarning: Error: Cannot add a Service with the same UUID '000000DA-0000-1000-8000-0026BB765291' as another Service in this Accessory without also defining a unique 'subtype' property.
    at Accessory._this.addService (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:276:17)
    at PlatformAccessory.addService (/usr/local/lib/node_modules/homebridge/src/platformAccessory.ts:92:41)
    at HarmonySubPlatform.readTVAccessories (/usr/local/lib/node_modules/homebridge-harmony/harmonySubPlatform.js:298:24)
    at HarmonySubPlatform.readAccessories (/usr/local/lib/node_modules/homebridge-harmony/harmonySubPlatform.js:158:58)
    at /usr/local/lib/node_modules/homebridge-harmony/harmonyBase.js:93:27
(node:480) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:480) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by BigKrisch** [comment]
Yes, I restarted the Raspberry and since then I get this error message.

**Comment by DMBlakeley** [comment]
Yes, on restart of Homebridge. Downgraded to 1.3.7 and error was not present.

**Comment by atonaltensor** [comment]
My version information is with my config.json above. And as for me, this started happening after restarting all of Homebridge. 

FYI, I am running homebridge in a docker container, if it matters.

**Comment by nicoduj** [comment]
I can reproduce, working on it

**Comment by nicoduj** [comment]
1.3.9 on its way, sorry :) You might need to restart twice, Ithe plugin should dleete the faulting service at first start, and will create it again at second start

**Comment by BigKrisch** [comment]
Perfect. It's working perfectly again.
Thanks for the quick help! 👍

**Comment by DMBlakeley** [comment]
Also working again for me. Is there a way to reduce the volume control sensitivity? When I set to 1 (default) the volume increases/decreases quite a bit. I have a Bose system for audio for all devices (TV, Apple TV, DVD).

**Comment by nicoduj** [comment]
> Is there a way to reduce the volume control sensitivity? 

@DMBlakeley You have an option for the number of commands to send called `numberOfCommandsSentForVolumeControl` but it defaults to 1, So if 1 command is to much I can't do anything :) So Putting it to 5 for example will send 5 commands (UP/Down, each time), but can't send less than 1.
