### ISSUE TITLE
Update 1.3.9 no iOS Remote[BUG]

### ISSUE THREAD

**Issue by bananajoe86** [nicoduj/homebridge-harmony#271]
With 1.3.7 the iOS included Remote works. After installing 1.3.9 the Harmony is shown but all buttons without work. Downgrade to 1.3.7 and the Remote works again. 
Using Config:
{
            "platform": "HarmonyHubWebSocket",
            "name": "Harmony",
            "hubIP": "192.168.178.52",
            "publishGeneralVolumeSlider": true,
            "linkVolumeControlToTV": true,
            "mainActivity": "Fernsehen",
            "sequencesToPublishAsAccessoriesSwitch": [
                "RTL"
            ],
            "showCommandsAtStartup": true,
            "devicesToPublishAsAccessoriesSwitch": [
                "Samsung TV|HDMI;InputHdmi1"
            ]
        }
    ],

**Comment by nicoduj** [comment]
Hi,

Can you check access permissions in your home app and tell me what the settings are ?

**Comment by bananajoe86** [comment]
You mean the "control devices remotely" and "add or edit devices"? Everything is activated.
For me from the version 1.3.8 doesn´t work. With 1.3.7 it´s fine. 1.3.8 and 1.3.9 it´s not good for my remote.

**Comment by Hatika78** [comment]
Hi, 
Same problem here.
I think the mapping doesn't work. I've sold the problem withe the "remoteOverrideCommandsList"

**Comment by nicoduj** [comment]
Hi there, I can confirm that volume is still working with physical buttons, but not the commands themselves. 
@Hatika78 you were on 1.3.7 before and you did not have to override commands ? 
@bananajoe86  : I a ma tlaking about the setting in home app (uper lefet icon on home tab, access control option - everyone , everyone on the same network or those who share your home)

Will investigate

**Comment by Hatika78** [comment]
Yes I was on 1.3.7 before and all is working without the override commands. I was just used it for Information Button.

**Comment by nicoduj** [comment]
will be fixed in 1.3.10

**Comment by Hatika78** [comment]
Thank you very much. Et Bravo très bon travail 😉

**Comment by bananajoe86** [comment]
Perfekt work....thx a lot
