### ISSUE TITLE
[BUG] Devices To Publish As Accessories Switch Switcher always switch back to Off

### ISSUE THREAD

**Issue by pascal0906** [nicoduj/homebridge-harmony#272]
Hi 
if i choose a dDevice from my Harmony hub in [] the device‘s name is on my Home App, everytime i hit the Switch on the App the Device starts, but the Switcher switches back to Status Off?! Any Solutions for that?

**Comment by nicoduj** [comment]
Hi, device switch are stateless since there is no way to know if a device is on or off through harmony hub. Only activities switch have a status retrieved from the hub.

**Comment by pascal0906** [comment]
wow thanks for the fast reply ;) okay this make sense :)
