### ISSUE TITLE
HOOBS - No switches for Activities for second Harmony Hub

### ISSUE THREAD

**Issue by OrigReckit** [nicoduj/homebridge-harmony#273]
**Describe the bug**
I have two Harmony Hubs connected to my Homekit using the HOOBS certified Harmony plugin. The first hub will show up as a device and two switches (for the activities) the second hub will only show up as a device. I've tried everything to expose the activities as switches for the second hub. Any help would be appreciated

**To Reproduce**
Switching between hubs confirms that switches will only appear for the first harmony hub 

**Expected behavior**
Switches for activities should appear for all harmony hubs

**Screenshots**

**IOS 13.5:**
- Version 
- Device:  iPhone XS & iPad Pro 

**Logs**
[Living Room] HarmonyPlatform Init
26/05/2020, 09:09:48 [Living Room] DidFinishLaunching
26/05/2020, 09:09:48 [Living Room] (Living Room)INFO - Loading activities...
26/05/2020, 09:09:48 [Living Room] (Bedroom)INFO - Loading activities...
26/05/2020, 09:09:49 [Living Room] (Bedroom)INFO - configuring Main TV Service
26/05/2020, 09:09:49 [Living Room] (Bedroom)INFO - Configuring Main Activity Watch TV
26/05/2020, 09:09:49 [Living Room] (Living Room)INFO - configuring Main TV Service
26/05/2020, 09:09:49 [Living Room] (Living Room)WARNING - No main Activity that match config file found, default to first one
26/05/2020, 09:09:49 [Living Room] (Living Room)INFO - Configuring Main Activity Watch TV
26/05/2020, 09:09:49 [Living Room] (Living Room)INFO - Discovered Activity : Watch TV
26/05/2020, 09:09:49 [Living Room] (Living Room)INFO - Discovered Activity : Watch Apple TV

**Config**
 {
            "platform": "HarmonyHubWebSocket",
            "name": "Living Room",
            "hubIP": "192.168.0.5",
            "otherPlatforms": [
                {
                    "name": "Bedroom",
                    "hubIP": "192.168.0.84",
                    "mainActivity": "Watch TV"
                }
            ],
            "switchAccessories": true,
            "activitiesToPublishAsInputForTVMode": [],
            "remoteOverrideCommandsList": [],
            "activitiesToPublishAsAccessoriesSwitch": [],
            "skippedIfSameStateActivities": [],
            "devicesToPublishAsAccessoriesSwitch": [],
            "sequencesToPublishAsAccessoriesSwitch": [],
            "homeControlsToPublishAsAccessoriesSwitch": []
        }
**Additional context**

**Comment by nicoduj** [comment]
Hi, I think your config should be like this to achieve what you want :

```json
{
"platform": "HarmonyHubWebSocket",
"name": "Living Room",
"hubIP": "192.168.0.5",
"otherPlatforms": [
{
"name": "Bedroom",
"hubIP": "192.168.0.84",
"mainActivity": "Watch TV",
"switchAccessories": true
}
],
"switchAccessories": true,
"activitiesToPublishAsInputForTVMode": [],
"remoteOverrideCommandsList": [],
"activitiesToPublishAsAccessoriesSwitch": [],
"skippedIfSameStateActivities": [],
"devicesToPublishAsAccessoriesSwitch": [],
"sequencesToPublishAsAccessoriesSwitch": [],
"homeControlsToPublishAsAccessoriesSwitch": []
}
```

**Comment by OrigReckit** [comment]
Thank you so much that fixed my problem
