### ISSUE TITLE
[FEATURE] Sleep timer

### ISSUE THREAD

**Issue by inspectorgadjet7** [nicoduj/homebridge-harmony#276]
Enable the Harmony sleep timer 

Is there any way to set a sleep timer? Using the remote or app you can set a sleep timer to turn off your activity after set intervals, and you can also ask Alexa to set a sleep timer for a specific amount of time. E.g. 23 minutes if you wanted to.

I’d like to either have a switch that sets a predefined sleep timer or the ability to set the sleep timer in the device in HomeKit if it’s possible.

BTW - Thanks for a great plugin.

**Comment by nicoduj** [comment]
Hi, I am not aware of such a feature . Could you point me to online doc or explain how to set up ? I fear it is not hub based but I can take a look.

However you can still achieve this with shortcut I think

**Comment by inspectorgadjet7** [comment]
Hi. Does this help? https://support.myharmony.com/en-us/setting-an-activity-sleep-timer

**Comment by nicoduj** [comment]
Yes, so it is a remote / app function and not a hub config based , so I can’t mimic it in the plugin easily (need to reproduce the dev inside the plugin ) . I would suggest to try with shortcut app and an automation

**Comment by nicoduj** [comment]
Hi, there is nothing I can do there, sorry.
