### ISSUE TITLE
Wrong input when starting

### ISSUE THREAD

**Issue by yaccy123** [nicoduj/homebridge-harmony#278]
When starting an activity (from off) via home(this plugin) it always starting the false activity/input. It seems like there is a default activity/input which always starts when activating it. When i start a scene with input x it doesnt work.

Thanks :)

**Comment by nicoduj** [comment]
Hi, did you configure main activity ?

Also, please note that from home app there is no way to start on an input, it will always start on the default one. You can however do this via shortcut

**Comment by yaccy123** [comment]
Hey how do i configure a main activity? :)
So that means there isnt a chance to start in a special input?

Thanks :)

**Comment by nicoduj** [comment]
Check readme, option is documented ;)

And like I said, you can through shortcut but not directly through home app (it is a missing feature there that was possible ont in first beta of ios12) .

**Comment by yaccy123** [comment]
Ahh okay yes i tried with shortcut on iphone but anyway after a few seconds it changes back to „main input“ 🤷🏾‍♂️. That is the Problem.

**Comment by nicoduj** [comment]
Can you share config and log in debug mode please ?

**Comment by yaccy123** [comment]
Thats the config

**Comment by nicoduj** [comment]
You Missed a copy paste or file attachement

**Comment by yaccy123** [comment]
Ohh sorry now ?!

**Comment by yaccy123** [comment]
![D978ECB2-C278-47F8-9359-64D9063BFA1A](https://user-images.githubusercontent.com/65060351/83657066-a9d78880-a5c0-11ea-9b1a-0ce7d2b0f6ca.png)
Now

**Comment by nicoduj** [comment]
Hi, I need your logs to investigate on this .
