### ISSUE TITLE
[BUG] Cannot add a  Sequence as a bridged Accessory

### ISSUE THREAD

**Issue by surrogatextrakt** [nicoduj/homebridge-harmony#279]
My config:
Homebridge: 1.1.0
homebridge-denon-heos v2.8.4
Harmony Hub with a sequence called "Sound umschalten"
iOS: 13.4.1 (iPad / iPhone 11)

If I make the config without the sequences to publish as a accessory switch all works fine.

```
{
            "name": "Harmony",
            "hubIP": "192.168.178.16",
            "hubName": "Harmony Hub",
            "publishGeneralMuteSwitch": true,
            "platform": "HarmonyHubWebSocket"
        },
```

After configure the sequence as a accessory the config entry looks like this:
```
{
            "name": "Harmony",
            "hubIP": "192.168.178.16",
            "hubName": "Harmony Hub",
            "publishGeneralMuteSwitch": true,
            "sequencesToPublishAsAccessoriesSwitch": [
                "Sound umschalten"
            ],
            "platform": "HarmonyHubWebSocket"
        },
```

the following output comes on start up of homebridge:

_(Harmony)INFO - Loading sequences...
(Harmony)INFO - Discovered sequence : Sound umschalten
(Harmony)INFO - Adding Accessory : Harmony-Sound umschalten
(Harmony)INFO - Creating Switch Service Sound umschalten/Sound umschalten-Sequence
(Harmony)INFO - Discovered sequence : Sound umschalten
(Harmony)INFO - Adding Accessory : Harmony-Sound umschalten
(Harmony)INFO - Creating Switch Service Sound umschalten/Sound umschalten-Sequence
(Harmony)INFO - Discovered sequence : Sound umschalten
(Harmony)INFO - Adding Accessory : Harmony-Sound umschalten
(Harmony)INFO - Creating Switch Service Sound umschalten/Sound umschalten-Sequence
(Harmony)INFO - Discovered sequence : Sound umschalten
(Harmony)INFO - Adding Accessory : Harmony-Sound umschalten
(Harmony)INFO - Creating Switch Service Sound umschalten/Sound umschalten-Sequence
(node:8982) UnhandledPromiseRejectionWarning: Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: ..._

The sequence is loaded multiple times and this causes an error. At the first restart of homebridge the error ist in the output but the homebridge works fine. If you are restart the homebridge a sencond time this error causes to stop the bridge on startup.

If you cut out the the following part from the config and clear the accessory cache all works fine again:

```
            "sequencesToPublishAsAccessoriesSwitch": [
                "Sound umschalten"
            ],
```

**Comment by nicoduj** [comment]
Hi, will try to reproduce thanks for reporting.

**Comment by nicoduj** [comment]
Hi, I can not reproduce, do you have any activity / command that would have the same name as your sequence ? Could you post your full hub config ?

**Comment by nicoduj** [comment]
Need more info to investigate, please check your sequence is only defined Once in hamrony and does not collide with any other device. Closing, feel free to reopen if you can give more info
