### ISSUE TITLE
New option accessories 

### ISSUE THREAD

**Issue by det-box** [nicoduj/homebridge-harmony#28]
How should the entry for the folder (/var/homebridge-harmony/accessories/) in the config.json be?

`[2019-1-27 15:02:32] [Harmony Ultimate] Initializing platform accessory 'Blu-ray wiedergeben'...
/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:266
      throw new Error("Cannot add a bridged Accessory with the same UUID as another bridged Accessory: " + existing.UUID);
            ^
Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 18cb95b1-a0e6-49c2-80ba-52b714c28019
    at Bridge.Accessory.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:266:13)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:399:24)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:16:19
    at that.wsp.onUnpackedMessage.addListener.data (/usr/local/lib/node_modules/homebridge-harmony/index.js:208:17)
    at Timeout.apply [as _onTimeout] (/usr/local/lib/node_modules/homebridge-harmony/node_modules/websocket-as-promised/dist/webpack:/WebSocketAsPromised/node_modules/chnl/es5/channel.js:230:1)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
homebridge-harmony.service: Main process exited, code=exited, status=1/FAILURE
homebridge-harmony.service: Unit entered failed state.
homebridge-harmony.service: Failed with result 'exit-code'.
Stopped Node.js HomeKit homebridge-harmony.`

(Im down to 0.0.9)

Thanks

**Comment by nicoduj** [comment]
Hi,

Do you have multiple hubs ? Could you post your config ? Did you try latest (0.1.2) ?

**Comment by nicoduj** [comment]
Definitely a bug since 0.1.0 . Will try to fix asap, stay on 0.0.9 until then

**Comment by nicoduj** [comment]
I tried something quickly to fix this try to update manually to see if ot helps I will release if so

**Comment by det-box** [comment]
I tested version 1.2.0, unfortunately it does not work. I use again Version 0.0.9

**Comment by nicoduj** [comment]
Ok thanks. The fix i hope will work is not released through npm for now so you have to replace index.js manually with the one in the github repository on master branch

**Comment by det-box** [comment]
Hello, 
I have updated the update to version 1.2 .0 and replaced the index.js manually. 
This starts the plugin without errors. 
Now every action of the Harmony is a separate device in the HomeKit. 

Thanks for the fix
