### ISSUE TITLE
iOS 14 TV Accessory

### ISSUE THREAD

**Issue by pascal0906** [nicoduj/homebridge-harmony#282]
is there any possibility to get my TV‘s get to work with newest iOS 14? at the moment they‘re just home Symbols and i cant trigger the with any shortcut. 

![DFAA2ED1-B4A1-460B-91BB-C3FC5B606AB2](https://user-images.githubusercontent.com/65828547/85402889-c0885400-b55c-11ea-8dc6-c8a3ccaecabf.jpeg)

![A5CEAAA9-89E6-4A20-A242-AB0865C07409](https://user-images.githubusercontent.com/65828547/85403323-6fc52b00-b55d-11ea-8159-5809df7ac387.jpeg)

**Comment by dkrizic** [comment]
I observed the same: 
![image](https://user-images.githubusercontent.com/1181349/85405795-342c6000-b561-11ea-97c0-0442c32c2598.png)

But I would stay cool, this is the very first beta, many to come.

**Comment by nicoduj** [comment]
Hi , first beta was released yesterday evening , so I had no chance to check for the moment !. From my setup, the icon seems broken but the inputs are still listed and services reported. I will check ASAP, but can you confirm it does not work at all or only a display issue ?

**Comment by pascal0906** [comment]
for me it workes when i push the button in home app, but when i put some devices in a shortcut, i choose the tv but, shortcuts does not recognize it as a tv accessory

**Comment by nicoduj** [comment]
I have checked, as far as I can tell commands including remote are working on IOS 14, only the icon is not good. When setup it sees it is a TV and asks to rename inputs. but like you said, they are not visible in shortcut app. I think the type is not ok, don't know if it is homebridge / hap related or IOS 14 (probably IOS14 !)

**Comment by nicoduj** [comment]
Ok, it seems IOS 14 does not like anymore Tv that are bridged. you have to publish them as externalAccessories with this option : publishAllTVAsExternalAccessory

**Comment by pascal0906** [comment]
i try this but for me it looks like that in homekit:

![image](https://user-images.githubusercontent.com/65828547/85436527-7ec1d280-b589-11ea-91c3-ffe8561a0ac8.jpeg)


 ![image](https://user-images.githubusercontent.com/65828547/85436509-78335b00-b589-11ea-8c76-fe049f25d1f9.png)

any ideas?

**Comment by nicoduj** [comment]
You have to remove the old cached accessory (through config UI), and then publish the nnew one as external, and add it manually (not added with the bridge) - same code.

**Comment by pascal0906** [comment]
got the right icons back, bit in iOS 14 beta 1 still not possible to integrate these TV accessories in shortcuts! thanks for your help :)

**Comment by AdlerCentauri** [comment]
@horst69 was ist das für eine App? Wo Du da alles einstellst.

**Comment by pascal0906** [comment]
das is die App hier: 

https://apps.apple.com/de/app/homemanager-f%C3%BCr-homebridge/id1440396849

kostet zwar, aber ist auf jedenfall hilfreich

**Comment by AdlerCentauri** [comment]
Dankeschön @horst69

**Comment by nicoduj** [comment]
Seems ok in beta 2 of iOS 14, and integration in shortcut seems possible again

**Comment by nicoduj** [comment]
Seems ok for me in beta4

**Comment by genfersee** [comment]
Hello, just updated from iOS13.7 to iOS14 this morning and I have the issue. Small house icon is displayed for my main Harmony Hub.

**Comment by nicoduj** [comment]
You have to publish as external accessory, they reverted the changes in final version, nothing I can do about

**Comment by genfersee** [comment]
Hi Nico,
do you mean as "otherPlatforms"?

 "platforms": [
        {
            "platform": "HarmonyHubWebSocket",
            "name": "Harmony",
            "hubIP": "XXX",
            "TVPlatformMode": true,
            "mainActivity": "Apple TV Salon",
            "switchAccessories": false,
            "devicesToPublishAsAccessoriesSwitch": [
                "Apple TV|PlayPause;Play"
            ],
            "publishGeneralMuteSwitch": true,
            "activitiesToPublishAsInputForTVMode": [
                "Cable Salon",
                "Apple TV Salon",
                "PS3 Salon",
                "Airplay Salon"
            ],
            "otherPlatforms": [
                {
                    "name": "Harmony_Chambre",
                    "hubIP": XXX,
                    "TVPlatformMode": true,
                    "mainActivity": "Apple TV Chambre",
                    "switchAccessories": false,
                    "activitiesToPublishAsInputForTVMode": [
                        "Cable Chambre",
                        "Apple TV Chambre",
                        "PS3 Chambre"
                    ]
                }
            ]

**Comment by nicoduj** [comment]
Every tv published through a bridge won’t have the correct icon. You must use publishaszxternalacczssories option

**Comment by genfersee** [comment]
Now working, many thanks Nico!
