### ISSUE TITLE
[BUG] Mute button missing and home button ideas.

### ISSUE THREAD

**Issue by joerexlo** [nicoduj/homebridge-harmony#283]
i am sorry id this is not a bug. i tried discord but no help. Everything is working fine. but i have 2 issues.

1. mute button missing
2. how do i get home button.

So i have harmony hub connected to old IR bose receiver, LG webos TV and nvidia shield. everything is working in the remote app of ios except the above issue. not sure why this is happening.

**Comment by joerexlo** [comment]
any help?

**Comment by nicoduj** [comment]
Hi,

there is no mute button as far as I know. You can create one through a switch config. 
Concerning home button, It is not in IOS remote either.

**Comment by joerexlo** [comment]
Hey thanks for the reply. There is a i button. Is there a way to override that as home?

**Comment by joerexlo** [comment]
@nicoduj can the override help?

**Comment by joerexlo** [comment]
I was able to fix this by override the information icon in the ios TV widget. thanks
