### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory[BUG]

### ISSUE THREAD

**Issue by SSutherland94** [nicoduj/homebridge-harmony#284]
**Describe the bug**
I recently began to migrate my Homebridge setup from being split across FreeNAS/macOS to a unified Raspberry Pi setup with the Homebridge image. On FreeNAS, this config was 100% functional. Naturally, I copied the contents of the Harmony config, as-is, onto my Raspberry Pi, and removed the FreeNAS instance of Homebridge, where the Harmony plugin initially resided. Now, I receive the below error no matter what I do. This is the ideal config, but it is worth noting that I have the same issue, even after I purge the config.

**To Reproduce**
1) Install plugin
2) Begin config
3) Restart service

**Expected behavior**
I expected the plug-in to load error-free. I know this can be misconstrued as snooty, but I promise it's not. I'm just filling in as many blanks as I can here.

**Logs**
`(node:988) UnhandledPromiseRejectionWarning: Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 1bcae207-8d90-454f-a83f-71e2c652ea86
    at Bridge.Accessory._this.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:414:15)
    at Bridge.Accessory._this.addBridgedAccessories (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:448:12)
    at Server.handleRegisterPlatformAccessories (/usr/local/lib/node_modules/homebridge/src/server.ts:528:17)
    at HomebridgeAPI.emit (events.js:315:20)
    at HomebridgeAPI.registerPlatformAccessories (/usr/local/lib/node_modules/homebridge/src/api.ts:316:10)
    at HarmonyBase.addAccessories (/usr/local/lib/node_modules/homebridge-harmony/harmonyBase.js:1236:25)
    at HarmonyBase.getDevicesAccessories (/usr/local/lib/node_modules/homebridge-harmony/harmonyBase.js:1132:12)
    at HarmonyBase.setupFoundAccessories (/usr/local/lib/node_modules/homebridge-harmony/harmonyBase.js:341:10)
    at HarmonySubPlatform.readAccessories (/usr/local/lib/node_modules/homebridge-harmony/harmonySubPlatform.js:163:22)
    at /usr/local/lib/node_modules/homebridge-harmony/harmonyBase.js:93:27
(node:988) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:988) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Config**
```
            "name": "Harmony",
            "hubIP": "xxx.xxx.x.xx",
            "hubName": "Harmony Hub",
            "cleanCache": false,
            "TVAccessory": false,
            "numberOfCommandsSentForVolumeControl": 1,
            "switchAccessories": true,
            "showTurnOffActivity": "stateless",
            "publishGeneralVolumeSlider": false,
            "linkVolumeControlToTV": false,
            "publishSwitchActivitiesAsIndividualAccessories": true,
            "devicesToPublishAsAccessoriesSwitch": [
                "Soundbar",
                "Soundbar|SB Vol Down;VolumeDown",
                "Soundbar|SB Vol Up;VolumeUp",
                "Soundbar|SB Sub Down;SubwooferDown",
                "Soundbar|SB Sub Up;SubwooferUp",
                "Soundbar|SB PS4;InputLine1",
                "Soundbar|SB Xbox;InputDigital1",
                "Soundplate",
                "Soundplate|SP Vol Up;VolumeUp",
                "Soundplate|SP Vol Down;VolumeDown",
                "Air",
                "Air|AC;PowerToggle",
                "Air|AC Mode;Mode",
                "Air|AC Fan Speed;FanSpeed",
                "Air|AC Cooler;TempCooler",
                "Air|AC Warmer;TempHotter",
                "Monitor|Monitor;PowerToggle",
                "Monitor|MP Source;Source",
                "Monitor|MP Menu;Menu",
                "Monitor|MP Up;DirectionUp",
                "Monitor|MP Down;DirectionDown",
                "Monitor|MP Right;DirectionRight",
                "Monitor|MP Left;DirectionLeft",
                "Monitor|MP Select;Select",
                "Monitor|MP Xbox;Source;DirectionUp;DirectionUp;Select",
                "Monitor|MP PS4;Source;DirectionUp;DirectionUp;DirectionUp;Select",
                "Monitor|Mac from Xbox;Source;DirectionUp;DirectionUp;DirectionUp;Select",
                "Monitor|Mac from PS4;Source;DirectionUp;DirectionUp;Select",
                "Surround Sound|SS Apple TV;InputMediaBox",
                "Surround Sound|SS Xbox;InputBd/Dvd",
                "Surround Sound|SS PS4;InputSat/Catv",
                "Surround Sound|SS Switch;InputGame",
                "Surround Sound|SS Volume Up;VolumeUp",
                "Surround Sound|SS Volume Down;VolumeDown",
                "Surround Sound|SS Pure Direct;PureDirect",
                "Surround Sound|SS AFD;2Ch/Multi"
            ],
            "publishDevicesAsIndividualAccessories": true,
            "publishHomeControlsAsIndividualAccessories": true,
            "showCommandsAtStartup": false,
            "platform": "HarmonyHubWebSocket"
        },
```

**Comment by nicoduj** [comment]
Hi, this error is happening because a device is added twice . Did you move the cache between installs and rename something meanwhile ? You can try to clean the cached accessories either through plugin option or configui-x .

**Comment by SSutherland94** [comment]
Yeah I went through it all, and it seems that the issue was that although I had switches with different names, the command sequences were the same, which although it worked fine on FreeNAS somehow, it seems to not be working on the Raspberry Pi, so I've mitigated the issue in the last hour or so by altering the command sequences for the two conflicting switches. So it seems that even if the names are different, identical command strings will set off a panic of sorts.

**Comment by nicoduj** [comment]
Maybe it is a case sensitive issues depending on the OS. Or maybe some functions where not found on some macro, then triggering a duplicate.
