### ISSUE TITLE
Harmony activities as scènes in Homekit

### ISSUE THREAD

**Issue by clintbillton** [nicoduj/homebridge-harmony#287]
Hi guys,
Is there a way the activities on the Harmony Hub can be published to Homekit as scènes?
I'm able to create scènes manually but I'm getting conflicts because I want them to have the same name in Homekit as they are named on the Hub.
Thanks

**Comment by nicoduj** [comment]
Hi,

I don't think it can be done plugin side but you can always rename inputs in the device and then create scenes I think with the names .
