### ISSUE TITLE
[FEATURE] remoteOverrideCommandsList allow command sequence

### ISSUE THREAD

**Issue by maisun** [nicoduj/homebridge-harmony#288]
**Is your feature request related to a problem? Please describe.**
I'd like to request the possibility to define a command sequence for remoteOverrideCommandsList
The intention behind it is when switch internet radio channels, I need to press up/down and then select. It would be nice just to click up/down

**Describe the solution you'd like**
Instead of only one command, define a sequence of commands 

**Describe alternatives you've considered**
No other alternative.

**Additional context**
N/A

**Comment by nicoduj** [comment]
Hi, Noticed, I am putting this in the backlog !

**Comment by maisun** [comment]
Thank you!
