### ISSUE TITLE
[BUG] Main Activity not found

### ISSUE THREAD

**Issue by abb0r** [nicoduj/homebridge-harmony#289]
**Describe the bug**
I set my mainActivity to the activity which starts my Nvidia Shield. But the plugin switches to my "Fernsehen" activity when it starts.

**Expected behavior**
When activating my device with Siri or the Home App it should start my "SHIELD TV" activity and not my "Fernsehen" activity.

**Screenshots**

**IOS (please complete the following information):**
- Version iOS 14 beta 4
- Device: iPhone X

**Logs**
[8/12/2020, 03:01:36] [Harmony] (Harmony)INFO - configuring Main TV Service
[8/12/2020, 03:01:36] [Harmony] (Harmony)WARNING - No main Activity that match config file found, default to first one
[8/12/2020, 03:01:36] [Harmony] (Harmony)INFO - Configuring Main Activity Fernsehen

**Config**
        {
            "name": "Harmony",
            "hubIP": "192.168.178.36",
            "platform": "HarmonyHubWebSocket",
            "mainActivity": "SHIELD TV"
        },

**Additional context**

**Comment by nicoduj** [comment]
Hi, the nap is probably incorrect . Be careful il is case sensitive. Double check the log that create the input

**Comment by abb0r** [comment]
Ok, I somehow fixed the problem. I had to change the name of my "SHIELD TV" activity to "Shield TV" and cleaned the cached accessories. But still doesn't know why I didn't work in the first place. The name of the activity and the created input were the same, maybe it had something to do with the name beeing all in uppercase.

**Comment by nicoduj** [comment]
Yes, like I said you must respect upper / lower cases letters .
