### ISSUE TITLE
npm install throwing EHOSTUNREACH 

### ISSUE THREAD

**Issue by ViGuru** [nicoduj/homebridge-harmony#290]
**Describe the bug**
I was trying to deploy my project using Dockerfile.When I am running my dockerfile,it is failing while trying to run npm install.
It shows Connect:EHOSTUNREACH with a ip

**To Reproduce**
To reproduce needs to add following commands in Docker file
FROM Node:12.18.2
WORKDIR src/app
COPY package*.json ./
RUN node -v
RUN npm -v
RUN npm install

**Expected behavior**
It should install the all the dependencies.I also have package.json present.

**Screenshots**
![image](https://user-images.githubusercontent.com/69675299/90242039-e5f15a00-de49-11ea-9508-7c10b0e7a867.png)

**Additional context**
It is also showing same error when I am trying to do npm install for angular cli.I also verifed the node and npm version that is showing version correctly.

**Comment by nicoduj** [comment]
This issue is not plugin related, from the error I see npm registry is not reachable

**Comment by ViGuru** [comment]
Thanks,but when I pinged the registry separately.It is sending and receiving packets and doesn't have any issue of unreachability.
While running npm install only it is failing.

Is there any other way to do node install through Dockerfile in centos?

**Comment by nicoduj** [comment]
Did you try to ping inside your docker file ?

**Comment by ViGuru** [comment]
No
