### ISSUE TITLE
Main hub missing from control center remote

### ISSUE THREAD

**Issue by zelik888** [nicoduj/homebridge-harmony#292]
I have two hubs and both their activities work and can be started/stopped from Home app. The problem is, I can only see one remote in control center, the second one listed in my config. Is there something I should try? I’ve deleted the platform and reinstalled it but same situation.

**Comment by nicoduj** [comment]
Hi, can you share your config ? Did you had them both as external accessories ? Some network / homebridge configurations seems to have problems for tv accessory discovery through bonjour protocol . Hope next version of homebridge will fix that, not on the plugin side unfortunately

**Comment by zelik888** [comment]
Here's the harmony part:
```
{
            "name": "Living Room",
            "hubIP": "192.168.0.107",
            "hubName": "Veree Living Room",
            "cleanCache": false,
            "publishAllTVAsExternalAccessory": false,
            "TVAccessory": true,
            "mainActivity": "Watch AppleTV",
            "numberOfCommandsSentForVolumeControl": 1,
            "switchAccessories": false,
            "showTurnOffActivity": "true",
            "publishGeneralMuteSwitch": false,
            "publishGeneralVolumeSlider": false,
            "linkVolumeControlToTV": true,
            "otherPlatforms": [
                {
                    "name": "3rd Floor Theater",
                    "hubIP": "192.168.0.225",
                    "hubName": "3F",
                    "TVAccessory": true,
                    "mainActivity": "Watch Apple TV",
                    "linkVolumeControlToTV": true
                }
            ],
            "platform": "HarmonyHubWebSocket"
        },
```
Looking at doc again, am I not supposed to have both hubname and hubIP?

**Comment by nicoduj** [comment]
No, specify hub name for autodiscovery or hupip (preferable) if you have fixed ip . Are you wifi device on the same subnet ?

**Comment by zelik888** [comment]
yes same. The thing is, both hubs can be controlled via Home app. They both can start activities. BUT only the second hub shows up in the remote from control center. This is the part I can't figure out

**Comment by nicoduj** [comment]
Like I said, remote in control center does not use Homekit for discovery but bonjour protocol. You would have to use some wireshark on your network to see if it is correctly advertised at first, but I fear that there are some issues with homebridge on some network on thie part.

You can try by setting publishAllTVAsExternalAccessory at true, and see if it hemps, but you will have to add both remote manually.

**Comment by zelik888** [comment]
I understand and will do wireshark soon. 

What I wanted to clarify that boggles my mind is if I swap the order of the two hubs via config-ui, the situation reverses, now missing hub shows and the one that used to show becomes missing. Still trying to debug this. I’ve also deleted the plugin and also cleared cache etc

**Comment by zelik888** [comment]
I understand and will do wireshark soon. 

What I wanted to clarify that boggles my mind is if I swap the order of the two hubs via config-ui, the situation reverses, now missing hub shows and the one that used to show becomes missing. Still trying to debug this. I’ve also deleted the plugin and also cleared cache etc

**Comment by nicoduj** [comment]
Any news on this especially with homebridge 1.2 and external accessories ?

**Comment by zelik888** [comment]
My issue has been resolved but not sure of why. I created a new secondary homebridge instance and moved my harmony there but at the same time I also upgraded to IOS14. Thank you for this plugin!
