### ISSUE TITLE
Hub intermittent not responding

### ISSUE THREAD

**Issue by wratran** [nicoduj/homebridge-harmony#293]
here is the log:

[8/31/2020, 9:44:06 AM] [harmony hub] (harmony hub)INFO - Loading activities...
[8/31/2020, 9:44:09 AM] [harmony hub] (harmony hub)Error - Error retrieving info from hub : Error: connect EHOSTUNREACH 192.168.86.59:8088-(50)

Its not responding from homekit from time to time

**Comment by nicoduj** [comment]
Hi, could you share your config ? Seems like a network issue, does your hub light changes to red sometime ? Prefer using static I'm from both your router and plugin config to limit such issues.

**Comment by wratran** [comment]
"name": "harmony hub",
            "hubIP": "192.168.86.59",
            "hubName": "harmony hub",
            "TVAccessory": false,
            "switchAccessories": true,
            "publishGeneralMuteSwitch": false,
            "publishSwitchActivitiesAsIndividualAccessories": true,
            "otherPlatforms": [
                {
                    "name": "harmony hub 2",
                    "hubIP": "192.168.86.68",
                    "hubName": "harmony hub 2",
                    "switchAccessories": true,
                    "publishSwitchActivitiesAsIndividualAccessories": true
                }
            ],
            "platform": "HarmonyHubWebSocket"

**Comment by SSutherland94** [comment]
I've been having this issue all day today. Worked just fine yesterday though
`        {
            "name": "Harmony",
            "hubIP": "192.168.1.10",
            "hubName": "Harmony Hub",
            "cleanCache": false,
            "TVAccessory": false,
            "switchAccessories": true,
            "showTurnOffActivity": "true",
            "publishSwitchActivitiesAsIndividualAccessories": true,
            "devicesToPublishAsAccessoriesSwitch": [
                "Air|AC;PowerToggle;Mode",
                "Air|AC Cooler;TempCooler",
                "Air|AC Warmer;TempHotter",
                "Air|AC Energy Saver;PowerToggle",
                "Soundbar",
                "Soundbar|SB Vol Down;VolumeDown",
                "Soundbar|SB Vol Up;VolumeUp",
                "Soundbar|SB Sub Down;SubwooferDown",
                "Soundbar|SB Sub Up;SubwooferUp",
                "Soundplate",
                "Soundplate|SP Vol Up;VolumeUp",
                "Soundplate|SP Vol Down;VolumeDown",
                "Surround Sound|SS Apple TV;InputMediaBox",
                "Surround Sound|SS Xbox;InputBd/Dvd",
                "Surround Sound|SS PS4;InputSat/Catv",
                "Surround Sound|SS Switch;InputGame",
                "Surround Sound|SS Volume Up;VolumeUp",
                "Surround Sound|SS Volume Down;VolumeDown",
                "Surround Sound|SS Pure Direct;PureDirect",
                "Surround Sound|SS AFD;2Ch/Multi",
                "Monitor|Monitor;PowerToggle",
                "Monitor|MP Source;Source",
                "Monitor|MP Menu;Menu",
                "Monitor|MP Up;DirectionUp",
                "Monitor|MP Down;DirectionDown",
                "Monitor|MP Right;DirectionRight",
                "Monitor|MP Left;DirectionLeft",
                "Monitor|MP Select;Select"
            ],
            "showCommandsAtStartup": false,
            "platform": "HarmonyHubWebSocket"
        },`
Light is consistently green

**Comment by nicoduj** [comment]
Hi, did something update at all ? Like homebridge (or hoobs ?) . Can you check network connectivity with a ping inside the docker / homebridge env ? Can you give me the exact log?

**Comment by nicoduj** [comment]
Closing , feel free to reopen if you have more info
