### ISSUE TITLE
Option devicesToPublishAsAccessoriesSwitch - The plugin doesn't detect PowerOn/PowerOff

### ISSUE THREAD

**Issue by maisun** [nicoduj/homebridge-harmony#294]
Hi,
I'm trying to map the LED candles as a device to HomeKit. It's been added to Harmony with PowerOn and PowerOff commands working perfectly fine.
I read the description of **devicesToPublishAsAccessoriesSwitch** says:
If you do not specify any specific command, the plugin will add either powerToggle if found in Power command group, or PowerOn and/or PowerOff if there is no powerToggle feature.
But it doesn't seem to work (please see the log below):

.[37m[9/10/2020, 8:36:19 PM] .[39m.[36m[Logitech Harmony] .[39m(Logitech Harmony)INFO - Command : PowerOff discovered for device : LED Candles
.[37m[9/10/2020, 8:36:19 PM] .[39m.[36m[Logitech Harmony] .[39m(Logitech Harmony)INFO - Command : PowerOn discovered for device : LED Candles
.......
.[37m[9/10/2020, 8:36:19 PM] .[39m.[36m[Logitech Harmony] .[39m(Logitech Harmony)INFO - Discovered Device : LED Candles
.[37m[9/10/2020, 8:36:19 PM] .[39m.[36m[Logitech Harmony] .[39m(Logitech Harmony)Error - No function found for LED Candles

My configuration is as follows:
      "devicesToPublishAsAccessoriesSwitch": [
                "Light Controller;Red",
                **"LED Candles"**
        ]

Not sure if it's a bug or something that I misunderstand from the instructions. Basically I'd like to have a switch in HomeKit to turn on and off the LED candles. Any suggestion is appreciated!

**Comment by nicoduj** [comment]
Hi, i think your commands are not in the power control section of the device in harmony (since probably you learned them ?) could you try setting them explicitly ?

**Comment by maisun** [comment]
> Hi, i think your commands are not in the power control section of the device in harmony (since probably you learned them ?) could you try setting them explicitly ?

Hi, thanks for replying! You’re right the device is not in harmony database so it learned the commands from the original remote. I just tried to add the command PowerOn to configuration and it works. However I’d like the switch to send PowerOff when it’s tuned off. Is there a way to allow that?

**Comment by nicoduj** [comment]
You must use 2 switches to do that. Harmony hub does not handle device state, so I can't make a reliable on / off switch. If you have a device with power  On / Off "real" commands (not powerToggle), it will also publish two switch. In other words, device switches are always stateless.

**Comment by maisun** [comment]
> You must use 2 switches to do that. Harmony hub does not handle device state, so I can't make a reliable on / off switch. If you have a device with power On / Off "real" commands (not powerToggle), it will also publish two switch. In other words, device switches are always stateless.

Hi Nico, would it be possible to trigger PowerOn when the switch is turned on in HomeKit and PowerOff when the switch is turned off in HomeKit? I know it's difficult to sync state but the logic described above doesn't require to keep track of the state (I believe HomeKit will callback if the action is on or off). And for devices with separate poweron/poweroff buttons, it is definitely Ok to send the same command multiple times.

**Comment by nicoduj** [comment]
in this case sometimes you would have to power off then power on (if the device is allready off and the switch not in sync).
Will think of this however if this drawback is acceptable, but I fear to hae a lot of issues from users who will sync it should be in sync ...

**Comment by maisun** [comment]
> in this case sometimes you would have to power off then power on (if the device is allready off and the switch not in sync).
> Will think of this however if this drawback is acceptable, but I fear to hae a lot of issues from users who will sync it should be in sync ...

Hi Nico,

Thank you for considering it! I agree the best way would be to configure the device in Harmony with PowerOn/Off so that Harmony keeps the state of the device. Do you know if there is a way to add the self-learned commands to the power control section? I have downloaded MyHarmony desktop and there is a setting for the custom device to choose between:
1. I press the same button for on and for off
2. I press two different buttons for on and for off
Which the 2nd option is selected. And the next screen shows both PowerOn command and PowerOff command are configured correctly. But those commands are still not recognised by the plugin, so something must be wrong in my setup.

**Comment by nicoduj** [comment]
> Do you know if there is a way to add the self-learned commands to the power control section?

No, sorry, don't think it is possible. You can post your hub config (in debug mode) if you want me to take a look however, like I said, it will produce 2 buttons so not the behavior you want.

**Comment by maisun** [comment]
> > Do you know if there is a way to add the self-learned commands to the power control section?
> 
> No, sorry, don't think it is possible. You can post your hub config (in debug mode) if you want me to take a look however, like I said, it will produce 2 buttons so not the behavior you want.

Hi Nico, ok understood. Strange Logitech doesn't allow custom devices to be powered on/off standard way.
Any chance to include a configuration to allow PowerOn PowerOff commands being sent depending on the state in HomeKit? I know if won't be in sync with Harmony but at least I can toggle on/off multiple times to make them in sync, and for users who only use Harmony it's easier. To make the change backward compatible it could perhaps be added as another configuration item, where users can specify what command to send when the switch is turned on and/or off. Maybe something like the following:
 "commandsToPublishAsAccessoriesSwitch": [
        "LED Candles"  : [
                "On": "LED Candles;PowerOn",
                "Off": "LED Candles;PowerOff"
         ],
        ..................
   ]

**Comment by nicoduj** [comment]
Hi, can think of it, but just to be sure, can you post your hub config ?  (running homebridge in debug mode) ?

**Comment by maisun** [comment]
Hi @nicoduj , please see the hub config that contains the section for "LED Candles" below:
      {
        "label": "LED Candles",
        "deviceAddedDate": "/Date(1599764487467+0000)/",
        "ControlPort": 7,
        "contentProfileKey": 71258615,
        "deviceProfileUri": "svcs.myharmony.com/res/device/71258615-P49rBjSd2JaZaotQ3AvALxT7R/BOoCPyHfckqLa+3E0=",
        "manufacturer": "Lights4fun",
        "icon": "24",
        "Capabilities": [
          501
        ],
        "deviceTypeDisplayName": "LightController",
        "powerFeatures": {
          "PowerOffActions": [
            {
              "__type": "IRPressAction",
              "IRCommandName": "PowerOff",
              "Order": 0,
              "Duration": 0,
              "ActionId": 0
            }
          ],
          "PowerOnActions": [
            {
              "__type": "IRPressAction",
              "IRCommandName": "PowerOn",
              "Order": 0,
              "Duration": 0,
              "ActionId": 0
            }
          ]
        },
        "isManualPower": "false",
        "controlGroup": [
          {
            "name": "Home",
            "function": [
              {
                "action": "{\"command\":\"PowerOff\",\"type\":\"IRCommand\",\"deviceId\":\"71258615\"}",
                "name": "PowerOff",
                "label": "Power Off"
              },
              {
                "action": "{\"command\":\"PowerOn\",\"type\":\"IRCommand\",\"deviceId\":\"71258615\"}",
                "name": "PowerOn",
                "label": "Power On"
              }
            ]
          },
          {
            "name": "Miscellaneous",
            "function": [
              {
                "action": "{\"command\":\"Blue\",\"type\":\"IRCommand\",\"deviceId\":\"71258615\"}",
                "name": "Blue",
                "label": "Blue"
              },
              {
                "action": "{\"command\":\"Bright\",\"type\":\"IRCommand\",\"deviceId\":\"71258615\"}",
                "name": "Bright",
                "label": "Bright"
              },
              {
                "action": "{\"command\":\"Dim\",\"type\":\"IRCommand\",\"deviceId\":\"71258615\"}",
                "name": "Dim",
                "label": "Dim"
              },
              {
                "action": "{\"command\":\"Fade\",\"type\":\"IRCommand\",\"deviceId\":\"71258615\"}",
                "name": "Fade",
                "label": "Fade"
              },
              {
                "action": "{\"command\":\"Flash\",\"type\":\"IRCommand\",\"deviceId\":\"71258615\"}",
                "name": "Flash",
                "label": "Flash"
              },
              {
                "action": "{\"command\":\"Green\",\"type\":\"IRCommand\",\"deviceId\":\"71258615\"}",
                "name": "Green",
                "label": "Green"
              },
              {
                "action": "{\"command\":\"Light1\",\"type\":\"IRCommand\",\"deviceId\":\"71258615\"}",
                "name": "Light1",
                "label": "Light1"
              },
              {
                "action": "{\"command\":\"Light10\",\"type\":\"IRCommand\",\"deviceId\":\"71258615\"}",
                "name": "Light10",
                "label": "Light10"
              },
              {
                "action": "{\"command\":\"Light11\",\"type\":\"IRCommand\",\"deviceId\":\"71258615\"}",
                "name": "Light11",
                "label": "Light11"
              },
              {
                "action": "{\"command\":\"Light12\",\"type\":\"IRCommand\",\"deviceId\":\"71258615\"}",
                "name": "Light12",
                "label": "Light12"
              },
              {
                "action": "{\"command\":\"Light13\",\"type\":\"IRCommand\",\"deviceId\":\"71258615\"}",
                "name": "Light13",
                "label": "Light13"
              },
              {
                "action": "{\"command\":\"Light14\",\"type\":\"IRCommand\",\"deviceId\":\"71258615\"}",
                "name": "Light14",
                "label": "Light14"
              },
              {
                "action": "{\"command\":\"Light15\",\"type\":\"IRCommand\",\"deviceId\":\"71258615\"}",
                "name": "Light15",
                "label": "Light15"
              },
              {
                "action": "{\"command\":\"Light16\",\"type\":\"IRCommand\",\"deviceId\":\"71258615\"}",
                "name": "Light16",
                "label": "Light16"
              },
              {
                "action": "{\"command\":\"Light2\",\"type\":\"IRCommand\",\"deviceId\":\"71258615\"}",
                "name": "Light2",
                "label": "Light2"
              },
              {
                "action": "{\"command\":\"Light3\",\"type\":\"IRCommand\",\"deviceId\":\"71258615\"}",
                "name": "Light3",
                "label": "Light3"
              },
              {
                "action": "{\"command\":\"Light4\",\"type\":\"IRCommand\",\"deviceId\":\"71258615\"}",
                "name": "Light4",
                "label": "Light4"
              },
              {
                "action": "{\"command\":\"Light5\",\"type\":\"IRCommand\",\"deviceId\":\"71258615\"}",
                "name": "Light5",
                "label": "Light5"
              },
              {
                "action": "{\"command\":\"Light6\",\"type\":\"IRCommand\",\"deviceId\":\"71258615\"}",
                "name": "Light6",
                "label": "Light6"
              },
              {
                "action": "{\"command\":\"Light7\",\"type\":\"IRCommand\",\"deviceId\":\"71258615\"}",
                "name": "Light7",
                "label": "Light7"
              },
              {
                "action": "{\"command\":\"Light8\",\"type\":\"IRCommand\",\"deviceId\":\"71258615\"}",
                "name": "Light8",
                "label": "Light8"
              },
              {
                "action": "{\"command\":\"Light9\",\"type\":\"IRCommand\",\"deviceId\":\"71258615\"}",
                "name": "Light9",
                "label": "Light9"
              },
              {
                "action": "{\"command\":\"Red\",\"type\":\"IRCommand\",\"deviceId\":\"71258615\"}",
                "name": "Red",
                "label": "Red"
              },
              {
                "action": "{\"command\":\"Smooth\",\"type\":\"IRCommand\",\"deviceId\":\"71258615\"}",
                "name": "Smooth",
                "label": "Smooth"
              },
              {
                "action": "{\"command\":\"Strobe\",\"type\":\"IRCommand\",\"deviceId\":\"71258615\"}",
                "name": "Strobe",
                "label": "Strobe"
              },
              {
                "action": "{\"command\":\"Timer\",\"type\":\"IRCommand\",\"deviceId\":\"71258615\"}",
                "name": "Timer",
                "label": "Timer"
              },
              {
                "action": "{\"command\":\"White\",\"type\":\"IRCommand\",\"deviceId\":\"71258615\"}",
                "name": "White",
                "label": "White"
              }
            ]
          }
        ],
        "model": "LED Candles",
        "IsKeyboardAssociated": false,
        "DongleRFID": 0,
        "id": "71258615",
        "type": "LightController",
        "suggestedDisplay": "DEFAULT",
        "Transport": 1
      }

**Comment by maisun** [comment]
The whole config json is also attached below:
[hubconfig.log](https://github.com/nicoduj/homebridge-harmony/files/5243999/hubconfig.log)

**Comment by nicoduj** [comment]
Thnak you, so power on / off function are on 3Home" group in harmony config, that is why it does not work. will think of being less "strict" on the group in a next version.

**Comment by maisun** [comment]
> Thnak you, so power on / off function are on 3Home" group in harmony config, that is why it does not work. will think of being less "strict" on the group in a next version.

Hi Nico, thank you very much for looking into it! Look forward to version 1.4!

**Comment by maisun** [comment]
Hi Nico, thank you for the new version 1.4. I can confirm it now detects PowerOn/Off commands:
.[37m[10/4/2020, 9:44:25 AM] .[39m.[36m[Logitech Harmony] .[39m(Logitech Harmony)INFO - Adding Accessory : Logitech Harmony-LED Candles-PowerOff
.[37m[10/4/2020, 9:44:25 AM] .[39m.[36m[Logitech Harmony] .[39m(Logitech Harmony)INFO - Creating Switch Service LED Candles/LED Candles-PowerOff
.[37m[10/4/2020, 9:44:25 AM] .[39m.[36m[Logitech Harmony] .[39m(Logitech Harmony)INFO - Adding Accessory : Logitech Harmony-LED Candles-PowerOn
.[37m[10/4/2020, 9:44:25 AM] .[39m.[36m[Logitech Harmony] .[39m(Logitech Harmony)INFO - Creating Switch Service LED Candles/LED Candles-PowerOn

However it still creates two switches, one for PowerOn and the other for PowerOff. So my feature request remains: can we optionally allow one single switch sending On/Off command based on the user action? 
I have a scene which turns off all lights, but the scene will be deactivated when the PowerOff switch is turned off after a few seconds.
Appreciate your consideration of the enhancement!

**Comment by nicoduj** [comment]
Hi, indeed I agreed only at first for detecting outside of power functions :) 

The other request is more complicated and involves potential out of sync issues ... I a m stll thinking of it but please fill another feature request.

**Comment by maisun** [comment]
> Hi, indeed I agreed only at first for detecting outside of power functions :)
> 
> The other request is more complicated and involves potential out of sync issues ... I a m stll thinking of it but please fill another feature request.

Sure thanks! Will create a new feature request.
