### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by h0mesmart** [nicoduj/homebridge-harmony#295]
**Describe the bug**
Since iOS 14, the icon for the TV is set to a  generic Home icon instead of a TV icon. It looks like that the harmony plugin do not specify the category so HomeKit could not recognise it as TV

**To Reproduce**
Update iOS to version 14

**Expected behavior**
A TV icon for the TV accessory.

**IOS (please complete the following information):**
- Version 14
- Device: iPhone X

**Config**
{
            "platform": "HarmonyHubWebSocket",
            "name": "Salon TV",
            "hubIP": "10.0.0.119",
            "TVPlatformMode": true,
            "mainActivity": "Regarder la TV",
            "devicesToPublishAsAccessoriesSwitch": [
                "Sony Mini System"
            ],
            "activitiesToPublishAsInputForTVMode": [
                "Regarder Apple TV",
                "Regarder la TV",
                "M6",
                "TF1",
                "TFX",
                "6TER",
                "FR4",
                "FR3"
            ],
            "activitiesToPublishAsAccessoriesSwitch": [
                "Credence Sunset"
            ]
        }

Thanks for any help

**Comment by nicoduj** [comment]
Category is specified (will double check but quite sure) but if it is bridged it does not work . You have to publish as external accessory . During the beta it w s not working , then worked again, and sees to be broken un final ...

**Comment by h0mesmart** [comment]
Do you mean I have to change my config ? FIY other plugin : https://github.com/homebridge/homebridge/issues/2683#issuecomment-694142561 did have the same issue but they sorted out and now everything is back to normal. May be it's help

**Comment by nicoduj** [comment]
Like I said my plugin already use the correct way for external accessories . Like they said on the other post, accessories exposed through the bridge does not use the type . You have to publish as external accessory in your config if you want the icon to be set . The behavior has changed one way and another during the beta (see #282 ) so I will wait for 14.1 and decide if I go to default publishing all as external or not

**Comment by h0mesmart** [comment]
gotcha! thank you
