### ISSUE TITLE
[FEATURE] General Volume Up and Down Accessories

### ISSUE THREAD

**Issue by jplwoodward** [nicoduj/homebridge-harmony#296]
The GeneralVolumeControl is buggy.  If you leave the number of commands to send blank, it defaults to -26, not 1 as stated in the plugin.  Furthermore, it is difficult to control how much the volume goes up or down given the slider.  I always turn it up too much and then down too much to compensate.

It would be great to have the option for individual general VolumeUp and VolumeDown accessory switches.

I know that individual accessories for specific devices can be added, but I could not find a way to do this for the current activity.

**Comment by nicoduj** [comment]
First of all, "**Hello**" ...

Secondly, sharing your config and logs in debug would be a good way to start if you seek any help and see if there is a bug for your config there.

Finall, Adding a switch for up / down would not be really usable since it would involve some delay for the switch to go back off before behing pushed again. 

I encourage you to use TV accessory with remote control and physical buttons.

**Comment by jplwoodward** [comment]
Hi!  Thanks for your prompt reply.  Oddly, I cannot repeat the -26 behavior, though it happened once in each of my 2 Homebridge instances.  However, both instances were upgraded between the -26 going into the config and my trying to repeat it.  On the subject of the Volume Up/Down accessories, I guess my experience is different that yours.  I created individual accessories for my Receiver:

"AV Receiver-Family Room|X1 Volume Up;VolumeUp",
"AV Receiver-Family Room|X1 Volume Down;VolumeDown”

and they work great…I just wanted the option to have that as a general volume control.  Here is a movie showing 3 volume up presses, a pause, and 3 volume down presses, to show you how quickly the accessory resets for me.:

http://thewoodwards.us/3Up3Down.mov

 Thanks for your consideration.  - John

**Comment by jplwoodward** [comment]
You code was so very clear that I was to easily add an option for general volume up/down switches.  Here is a link to the 4 files that I changed:

http://thewoodwards.us/WoodwardChanges.zip

Here is a summary of the changes I mde:

harmonyBase.js:
Added getGeneralVolumeSwitchesAccessories, which checks publishGeneralVolumeSwitches in the config
Added code in setSwitchOnCharacteristic that performs the volume up/down sending the number of command specified in numberOfCommandsSentForVolumeControl
harmonConst.js, added:

GENERALVOLUMEUP_TYPE = 'VOLUMEUP';
GENERALVOLUMEDOWN_TYPE = 'VOLUMEDOWN';

harmonySubPlatform.js:
added publishGeneralVolumeSwitches
added support for GENERALVOLUMEUP_TYPE and GENERALVOLUMEDOWN_TYPE in checkOn

config.schema.json:

added publishGeneralVolumeSwitches

Feel free to use any of this in your project.

- John

**Comment by nicoduj** [comment]
Thank you, will add this in a next release (maybe with some changes !)

**Comment by jplwoodward** [comment]
Thank you!
