### ISSUE TITLE
IOS 14 Tile image issue

### ISSUE THREAD

**Issue by adavison007** [nicoduj/homebridge-harmony#297]
Hi, since updating to IOS 14, the TV picture on the tile has gone and now shows as a house? the functionality still works though, is this an issue with the code?

![IMG_2524](https://user-images.githubusercontent.com/47482260/93529194-69173b80-f933-11ea-8e5a-717c4ced60e3.jpeg)

**Comment by iandronowicz** [comment]
Exactly same problem here, one out of three shows up with that house image instead the tv one
![0C0363A3-9F44-4426-979F-77A423A599CE](https://user-images.githubusercontent.com/250746/93544311-21dd7a80-f934-11ea-9b24-999a105f97ff.jpeg)

**Comment by nicoduj** [comment]
See #298

**Comment by adavison007** [comment]
Thanks, sorted, I had to clear the cache manually to remove the original accessories, but then it worked, thanks.

Adam Davison
adavison@me.com <mailto:adavison@me.com>
01276 63145
07748 761448

On 18 Sep 2020, at 06:27, Nicolas Dujardin <notifications@github.com> wrote:


See #298 <https://github.com/nicoduj/homebridge-harmony/issues/298>
