### ISSUE TITLE
IOS 14 - notice about TV Icon

### ISSUE THREAD

**Issue by nicoduj** [nicoduj/homebridge-harmony#298]
Hi all, 

Since GM / Final of IOS 14, it seems that **first** TV accessory does not have a TV icon anymore, if it is published through the bridge and **not** as an external accessory.

The beahvior changed during the beta one way and another, so I **won't do anything until 14.1 at least** .

Meanwhile, if you really want the icon, you can publish all TV accessories as external accessories (use corresponding option `publishAllTVAsExternalAccessory ` .

Support of bridged TV accessories has never been really official, and it has at least never been really supported for control center widget (that is why the second hub is published as an external accessory).
I might move to a default behavior of publishing all TV Accessories as external (I did not do that at first since it needs one more steps to add - and remove -  them in home app but thinking of it).

#297  - #295  - #282

**Comment by leoneleone** [comment]
@nicoduj 
iOS 14 has a new “Set Top Box” accessory category, which might be useful for the plug-in.

https://appleinsider.com/articles/20/09/16/apple-quietly-adds-new-streaming-device-categories-to-homekit-in-ios-14

**Comment by jplwoodward** [comment]
This issue is still there in IOS 14.2 Beta.

**Comment by raygan** [comment]
Thanks, glad to have my icon back. If this situation doesn't change it might be nice for this information to be spelled out in the Config UI X settings screen for the plugin.

**Comment by sxc731** [comment]
> This issue is still there in IOS 14.2 Beta.

In my case (homebridge-harmony v1.4.1 and iOS 14.2), I had to add: `"publishAllTVAsExternalAccessory": true` to my HB `config.json` (this can also be accomplished from the WebUI under "General").  The documentation suggests this defaults to true but it doesn't appear to be the case.  After doing this, I had to re-add the TV accessory to HomeKit and the "TV" icon is back.

**Comment by nicoduj** [comment]
Hi, It defaults to true for new installs. Existing install which have a cached accessory will still retrieve it from cache . If you remove it from cache, at next start it will publish as an external accessory

**Comment by DaveM8686** [comment]
This actually doesn’t seem to work for me. If I delete the plug-in and then reinstall with the publish as external set to true, the tv just doesn’t appear.

**Comment by nicoduj** [comment]
> This actually doesn’t seem to work for me. If I delete the plug-in and then reinstall with the publish as external set to true, the tv just doesn’t appear. 

You have to add it manually it won't' be linked to the hub

**Comment by DaveM8686** [comment]
> 
> 
> > This actually doesn’t seem to work for me. If I delete the plug-in and then reinstall with the publish as external set to true, the tv just doesn’t appear.
> 
> You have to add it manually it won't' be linked to the hub

Oh, I see.  That worked now, thank you!  Sorry about that.

**Comment by generator85** [comment]
@nicoduj What do you mean by "You have to add it manually it won't' be linked to the hub". I can't get the TV to show up at all, only the separate switches.
