### ISSUE TITLE
HomeKit TV Profile Support

### ISSUE THREAD

**Issue by VeniceNerd** [nicoduj/homebridge-harmony#30]
Hey, how realistic is it that you could get this plugin working with TV profile support? I know Khoas Tian has updated hap-nodejs and homebridge to  support them:

https://twitter.com/KhaosT/status/1088678984970162176

But not sure how trivial that would be on your end to integrate. Obviously would be awesome to have a “proper” TV device that supports volume and direction keypads instead of multiple switches.

**Comment by dp917** [comment]
That’d be great if possible. The TV power could be the main power for harmony (on starts last activity or set what to use), TV inputs be harmony activities...all in one accessory instead of multiple switches.

**Comment by nicoduj** [comment]
Hi, I have plans to dig into this. However I am not sure of the best way to do it : either have one tv device per harmony activity with start / stop function on the main switch, volume control of the activity and other functions binded as possible to the one on the physical remote or like you said using harmony activities as tv inputs (in this case the switch could be linked to the main activity) ! Suggestions / comments are welcomed !

**Comment by VeniceNerd** [comment]
I would certainly suggest to treat each Harmony Remote as one TV device with each activity being an input. It would clean up the entire experience and you should therotiecly be able to use the Apple Remote app to control volume and direction keypad for all activities as well. 

Hopefully it won’t be too time consuming on your end to implement this. This will be really sweet!

**Comment by VeniceNerd** [comment]
Yes. Perhaps even give users an option in the config if “power on” should default to a certain activity or last used activity.

**Comment by VeniceNerd** [comment]
Also, looks like someone already did this:
https://www.npmjs.com/package/homebridge-harmony-tv-smockle-temp

Haven’t installed to verify it actually works but maybe have a look to see how they did it?

**Comment by BetoRn** [comment]
I agree treating  activities as inputs would be super clean!

**Comment by nicoduj** [comment]
Ok, thanks for feedback, I will try to update this way

**Comment by nicoduj** [comment]
For those who likes risks in life, you can check the branch, it is beginning to work !

**Comment by nicoduj** [comment]
https://twitter.com/dujnic/status/1091094270814109696?s=21 For video preview

**Comment by krazyflipj** [comment]
Can't wait to try this. Currently running 12.2 beta

**Comment by krazyflipj** [comment]
sorry for the noob question but how would one try the beta version? I installed via git url. What do i need to add to config file?

**Comment by nicoduj** [comment]
If you already. Have installed through the branch, you have to use those 2 settings in your config :

TVPlatformMode : true
mainActivity : name of the activity you want to use on the main switch.

All activities will be associated to an input if everything is ok. Keys and sound is also beginning to work but it reliably for now.

I will maintain both versions for your information so you can always switch back by setting tvplatform mode to false (having two platforms with each configuration might also work).

Please note that some options are ignored  in tv platform mode (like an activity per accessory which has no sense anymore) but you can let them if you want to switch back.

**Comment by krazyflipj** [comment]
So this is what i put in my config file and it's still showing the normal mode. I am running IOS 12.2 

`"platform": "HarmonyHubWebSocket",
            "name": "Harmony",
            "hubIP": "123.123.123",
            "showTurnOffActivity": true,
            "TVPlatformMode": true,
            "mainActivity": "Watch Apple TV",
            "refreshTimer": 30,`

**Comment by nicoduj** [comment]
Could you check the files you get ? You should have 3 js files instead of only index.js

**Comment by nicoduj** [comment]
You can also post your log at startup so that I can check you should see a dedicated log saying which mode your are on

**Comment by Krocko** [comment]
How to install this version?

**Comment by krazyflipj** [comment]
I was finally able to install. The issue was I was installing the master and not the 12.2 branch. Inputs show but I don't have the volume controls and other buttons shown in your video. I like how clean the inputs are. Only issue is that you can't automate activities anymore (ex listen to music activity turns off lights) you are only limited to tv on or off. This is probably a limitation with 12.2 beta

**Comment by aschzero** [comment]
@nicoduj Thank you so much for your hard work on this, it's been running perfectly for me!

**Comment by nicoduj** [comment]
Sound is beginning to work with iPhone / iPad physical buttons.
You also have some keys of the activity (arrows, select, menu...) that are mapped to the remote in control center if you choose your HomeKit device instead of an Apple TV if you have one (on the top of the screen it took me some time to discover)

**Comment by krazyflipj** [comment]
Any way to activate an input (activity) with an automation? For example, I want input "Listen to music" activated when I hit "Im Home" automation. Currently, it turns on my main activity even though I have harmony button activated to listen to music in automation

**Comment by petschni** [comment]
I see the following in the log

```[2/1/2019, 7:07:11 PM] [HarmonyHub] Creating Main TV Service                                                                                                                                               
Uncaught exception error:  TypeError: Service.Television is not a constructor                                                                                                                              
    at that.wsp.onUnpackedMessage.addListener.data (/usr/local/lib/node_modules/homebridge-harmony/harmonyAsTVPlatform.js:178:35)                                                                          
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-harmony/node_modules/websocket-as-promised/dist/index.js:2:4404)                                                                         
    at ontimeout (timers.js:425:11)                                                                                                                                                                        
    at tryOnTimeout (timers.js:289:5)                                                                                                                                                                      
    at listOnTimeout (timers.js:252:5)                                                                                                                                                                     
    at Timer.processTimers (timers.js:212:10)           ```

with the following config:

```{
		"platform": "HarmonyHubWebSocket",
		"name": "HarmonyHub",
		"hubIP": "192.168.xx.xx",
		"showTurnOffActivity": true,
		"TVPlatformMode": true,
		"mainActivity": "TV",
		"refreshTimer": 30
	  }
```
Am I missing something?

**Comment by nicoduj** [comment]
Hi all .
0.2.0 is out for test purpose through NPM.
@petschni I think you don't run the latest version of homebridge (0.0.46)

**Comment by nicoduj** [comment]
@krazyflipj : yes i think you just have to set up an automation in home app, and while selecting your tv device in the accessory list, long press the device and select the input you want (it will say its name below the name of the device)

**Comment by krazyflipj** [comment]
@nicoduj I did that but when I test the automation it goes to the main activity I setup in the config file

**Comment by zackwag** [comment]
I just installed the plug-in and on/off works and the settings view can see the inputs (the activities), but when I long press and click "Input" I can't pick any activities.

My configuration is:

```
{
   "platform":"HarmonyHubWebSocket",
   "name":"TV",
   "hubIP":"10.0.0.143",
   "TVPlatformMode":true,
   "mainActivity":"Watch TV"
}
```

**Comment by nicoduj** [comment]
@krazyflipj : noted I will test probably something to do by my side. i fear it will however launch the main activity and then switch to the input but still I will try to find a way !

@zackwag : could you post your logs in debug while homebridge launches ? When you press inputs on the bottom left, nothing is listed or it doesn’t respond to any slection ?

**Comment by zackwag** [comment]
@nicoduj Very strange. I couldn't pick any input. I restarted and now it's working. It could because I'm using the Homebridge UI plugin and recently restarted and to enable logging I had to make some changes to make sure it was reading the logs from systemd.

Thank you though!

**Comment by krazyflipj** [comment]
Anyone have any issues with the directional vtouch controls? My Harmony controls my apple tv and when I hit any direction, it moves cursor to the end of the page

**Comment by sefki21** [comment]
Great Work! Do see all activities as input and they turn on correctly - but if i want to use the remote to control, it jumps to the main „activity / input“. 

Am I missing some configuration to fix this to use the remote with different activites?

**Comment by nicoduj** [comment]
Since the beta is out, now referencing bugs as individual  items and closing this one

**Comment by krazyflipj** [comment]
FYI. Still works with 12.2 beta 2

**Comment by nicoduj** [comment]
Saw that :) i have some issue with background refresh without timer, let me know if you have them (and which version you use if thie is the case)

**Comment by krazyflipj** [comment]
Would that show in the log? I personally don't notice any issues with using the Harmony plugin
