### ISSUE TITLE
Socket Loss/Close

### ISSUE THREAD

**Issue by Christian-CFP** [nicoduj/homebridge-harmony#303]
`[TV] (TV)ERROR (1)- refreshCurrentActivity TimeoutError: Can't open WebSocket within allowed timeout: 10000 ms. - Stack : TimeoutError: Can't open WebSocket within allowed timeout: 10000 ms.
    at PromiseController._handleTimeout (/home/hoobs/.hoobs/node_modules/promise-controller/src/index.js:172:19)
    at Timeout.<anonymous> (/home/hoobs/.hoobs/node_modules/promise-controller/src/index.js:178:43)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)`

This happens at least once a day. The only thing that helps is to cut off power from the Logitech hub and reconnect.

**Comment by Christian-CFP** [comment]
EDIT:
`[TV] (TV)WARNING - refreshCurrentActivity : NO refresh done since too much socket errors - will retry later
30.9.2020, 13:22:53 [TV] (TV)WARNING - refreshCurrentActivity : Resetting counter after network loss, trying to refresh
30.9.2020, 13:23:03 [TV] (TV)ERROR (1)- refreshCurrentActivity TimeoutError: Can't open WebSocket within allowed timeout: 10000 ms. - Stack : TimeoutError: Can't open WebSocket within allowed timeout: 10000 ms.
    at PromiseController._handleTimeout (/home/hoobs/.hoobs/node_modules/promise-controller/src/index.js:172:19)
    at Timeout.<anonymous> (/home/hoobs/.hoobs/node_modules/promise-controller/src/index.js:178:43)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) `

**Comment by nicoduj** [comment]
Hello,

can you share your config please ? I see you are on hoobs, there might be some conflicts there also, did you check with hoobs suppor tfirst ?

**Comment by Christian-CFP** [comment]
I did, but they have no clue. Here my config.

`{
            "platform": "HarmonyHubWebSocket",
            "plugin_map": {
                "plugin_name": "homebridge-harmony"
            },
            "name": "TV",
            "hubName": "Harmony Hub",
            "hubIP": "192.168.100.221",
            "cleanCache": false,
            "mainActivity": "Fernseher",
            "playPauseBehavior": true,
            "publishHomeControlsAsIndividualAccessories": true,
            "publishDevicesAsIndividualAccessories": true,
            "switchAccessories": true,
            "showTurnOffActivity": "false",
            "TVAccessory": true,
            "publishSequencesAsIndividualAccessories": true,
            "publishSwitchActivitiesAsIndividualAccessories": true,
            "publishGeneralMuteSwitch": false,
            "showCommandsAtStartup": false,
            "publishHomeControlButtons": true,
            "addAllActivitiesToSkippedIfSameStateActivitiesList": true,
            "publishGeneralVolumeSlider": false,
            "linkVolumeControlToTV": true
        }`

**Comment by nicoduj** [comment]
Are you sure your hub is on a fixed IP by your network ?

**Comment by Christian-CFP** [comment]
Yes.

**Comment by Christian-CFP** [comment]
Something new?

**Comment by nicoduj** [comment]
Hi, like I said I can't reproduce and fear it is hoobs related / or network related . When it happens, what color is the hub ? Does the harmony app works ? Could you try without hoobs ?

**Comment by Christian-CFP** [comment]
On the Harmony site everything works normal Remote & App. Color green.
Cant try without hoobs. Sry.

**Comment by Christian-CFP** [comment]
This is what I get:

[TV] (TV)INFO - Loading activities...
8.10.2020, 16:06:16 [TV] (TV)Error - Error retrieving info from hub : network timeout at: http://192.168.100.221:8088/-(470)

It seems that the port 8088 is closed like the log tells me with Socket closed.

**Comment by Christian-CFP** [comment]
But the hub works just fine

**Comment by Christian-CFP** [comment]
In this case I have to disconnect the hub from power and reconnect. Than HB gets the activities...

**Comment by nicoduj** [comment]
If you restart hoobs without restarting the hub ?

**Comment by Christian-CFP** [comment]
No, I have to disconnect the hub.

**Comment by Christian-CFP** [comment]
This is what I mentioned:

9.10.2020, 12:58:33 [TV] (TV)WARNING - socket closed
9.10.2020, 12:58:53 [TV] (TV)ERROR (1)- refreshCurrentActivity TimeoutError: Can't open WebSocket within allowed timeout: 10000 ms. - Stack : TimeoutError: Can't open WebSocket within allowed timeout: 10000 ms.
    at PromiseController._handleTimeout (/home/hoobs/.hoobs/node_modules/promise-controller/src/index.js:172:19)
    at Timeout.<anonymous> (/home/hoobs/.hoobs/node_modules/promise-controller/src/index.js:178:43)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)


9.10.2020, 13:44:03 [TV] (TV)WARNING - refreshCurrentActivity : NO refresh done since too much socket errors - will retry later

**Comment by nicoduj** [comment]
As I said the error is not in the plugin but on the socket lib, can't do anything about it without installing hoobs to debug (which I won't do since Indo not officially support this environment). Moreover it might be related to your config since there is not much report of such a problem....

**Comment by Christian-CFP** [comment]
Of cause you do not debug :) I will include the hoobs guys in this case. TX a lot! @BobbySlope

**Comment by BobbySlope** [comment]
Thanks for tagging, this will be solved in the next update of hoobs.

**Comment by Christian-CFP** [comment]
Awesome, thank you! Cant wait...
