### ISSUE TITLE
[BUG] Failed to install on RPi3+

### ISSUE THREAD

**Issue by stavrop** [nicoduj/homebridge-harmony#305]
Trying to install with 
`npm install -g homebridge-harmony`

Getting error:
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported

> bufferutil@4.0.1 install /usr/local/lib/node_modules/homebridge-harmony/node_modules/bufferutil
> node-gyp-build

gyp WARN EACCES current user ("nobody") does not have permission to access the dev dir "/root/.cache/node-gyp/14.13.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/homebridge-harmony/node_modules/bufferutil/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/homebridge-harmony/node_modules/bufferutil/.node-gyp'
gyp ERR! System Linux 5.4.51-v7+
gyp ERR! command "/usr/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/homebridge-harmony/node_modules/bufferutil
gyp ERR! node -v v14.13.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bufferutil@4.0.1 install: `node-gyp-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bufferutil@4.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-10-02T08_32_17_357Z-debug.log

Full log file:
[dbg.log](https://github.com/nicoduj/homebridge-harmony/files/5316807/dbg.log)
(2500+ lines...)

Read about deleting ~/.node-gyp directory or ~/.npmrc file but i have neither.

Any ideas?

Thanks!

**Comment by nicoduj** [comment]
Hi,

Maybe see : https://stackoverflow.com/questions/44633419/no-access-permission-error-with-npm-global-install-on-docker-image and https://github.com/npm/npm/issues/3849.

Maybe try setting npm user to anything else (maybe not root however) : 

`npm -g config set user root`

**Comment by Kohle81** [comment]
I had the same problem, see here #309 

https://github.com/nicoduj/homebridge-harmony/issues/309

**Comment by stavrop** [comment]
> I had the same problem, see here #309
> 
> #309

Worked just fine!
Thanks a lot!
