### ISSUE TITLE
[FEATURE] devicesToPublishAsAccessoriesSwitch allow single switch to control devices with only PowerOn/PowerOff commands

### ISSUE THREAD

**Issue by maisun** [nicoduj/homebridge-harmony#308]
**Is your feature request related to a problem? Please describe.**
Currently for devices with only PowerOn/PowerOff commands, the option devicesToPublishAsAccessoriesSwitch will create two separate switches, one for PowerOn and the other for PowerOff. This can break scenes relying on the status of switches. For example a scene used to turn off all lights need to set the PowerOff switch On, but after timeout the PowerOff switch is off again and the scene is deactivated.

**Describe the solution you'd like**
Optionally allow a single switch to control both PowerOn and PowerOff commands. When the switch is turned on, it sends PowerOn, and when the switch is turned off it sends PowerOff.

**Describe alternatives you've considered**
No real alternatives that I can think of

**Additional context**
The option allowing a single switch to send PowerOn/PowerOff commands can potentially break the synchronisation of device status. A few considerations:
1) Is it possible to sync device status by Harmony API so if the device is turned on by Harmony remote, the on status can be sync to HomeKit? This would be the best option if possible.
2) The sync will not be a problem if we only use HomeKit Harmony plugin to control the device. If we can persist the On/Off status it will even survive the restart 
3) If the device is out of sync it's not the end of the world - when the switch is toggled it just does nothing but to sync the state. For example when the device is On but HomeKit thinks it's Off, when I toggle in HomeKit it sends PowerOn and set the state On. Now the state is in sync.

**Comment by nicoduj** [comment]
Hi, Like you said the main issue with this kind of behavior is the out of sync possibility. Harmony does not handled device state in API (only activities).
I have multiple request of such a feature, but still considering to do or not because of this sync issue (and potential feedback from users who do not understand)

**Comment by maisun** [comment]
Hi @nicoduj , thank you for your reply! I think IR is not meant for synchronisation anyways, and even with Harmony app sometimes some devices can be out of sync. Can this be implemented as non-default option (maybe with disclaimer) for ones who need it like my use-case?

**Comment by nicoduj** [comment]
Yes, I am considering it as an option indeed. but need to find some time to do this, and I have other more "urgent" problems to handle (bugs ;p, especially with external accessories )

**Comment by maisun** [comment]
> Yes, I am considering it as an option indeed. but need to find some time to do this, and I have other more "urgent" problems to handle (bugs ;p, especially with external accessories )

Sure, thanks for considering it!

**Comment by Nastras** [comment]
Hello @nicoduj  is this option now possible? Can not find anything about it?
