### ISSUE TITLE
Activities still showing in Home.app after removal from Harmony

### ISSUE THREAD

**Issue by bverkron** [nicoduj/homebridge-harmony#31]
Activities that previously existed but have been deleted in the Harmony app and thus from the hub are still showing in HomeKit. This may or may not be a problem with homebridge-harmony directly. 

I have of course restarted home bridge, rebooted the server (Pi), upgraded both Homebridge and this plugin.

Looking for a troubleshooting path to follow. I am unable to find any config settings related to this. Please advise.

**Comment by bverkron** [comment]
Seems the issue resolved itself after the latest update / restart. For future reference are there any configs, caches, logs, etc that might show the activities pulled from the harmony?

**Comment by nicoduj** [comment]
Hi,

For now this platform plugin is not dynamic, it means that you indeed need to restart the homebridge if you have updated your activities. What is unclear is why they didn’t disappear after your first restart. Maybe you renamed them in HomeKit ? It must create then an entry in accessory folder I think, I’ll try to reproduce .

**Comment by bverkron** [comment]
Rebooted the entire Pi several times over the past few weeks for other reasons but they remained. Must have been related to the Homebridge / homebridge-harmony updates I did today. Finally flushed them out even though it didn't appear to at first.

**Comment by NoTrace-Kai** [comment]
Perhaps it would help if you delete the cachedAccessories?
~/.homebridge/accessories/cachedAccessories

**Comment by nicoduj** [comment]
If so it means cached accessory were not added by my plugin since it is not a dynamic platform, but some people had this issue because they were using another plugon before !

**Comment by nicoduj** [comment]
Not reproduced
