### ISSUE TITLE
[FIX?] Is the TV ICON fix in 1.4.0?

### ISSUE THREAD

**Issue by m4d-maNu** [nicoduj/homebridge-harmony#310]
Hello,
I see the same threads are closed and the last one indicated milestone 1.4.0.

Has the problem now been resolved or were only preparations for fixxen built in with 1.4.0?

**Comment by nicoduj** [comment]
the problem cannot be resolved, but 1.4 defaults to external accessory which is ok : IOS 1.4.0 does not support icons on bridged TV .
