### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by tooh** [nicoduj/homebridge-harmony#311]
**Describe the bug**
Possibly missing mainActivity option in settings page
**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**
Expected entry field for setting mainActivity.

Adding it manually in config works.

**Screenshots**

**IOS (please complete the following information):**

**Logs**
Your log in debug mode (-D option)

**Config**
Your config section of platform. Please do not post your whole config and especially with logins / passwords !

**Additional context**

**Comment by nicoduj** [comment]
Hi, Can you elaborate please ? 

![Capture d’écran 2020-11-01 à 12 23 47](https://user-images.githubusercontent.com/19813688/97801444-1a043c00-1c3d-11eb-946e-136352b5b1d1.png)

**Comment by nicoduj** [comment]
No new information and can't reproduce, please feel free to reopen if you have steps to reproduce.
