### ISSUE TITLE
Error retrieving info from hub

### ISSUE THREAD

**Issue by Jbb08** [nicoduj/homebridge-harmony#312]
Ever since the last update I seem to be getting this error? I do not think it affects my home app, but odd that it appears, any way to fix it?

[Harmony Hub] (Harmony Hub)Error - Error retrieving info from hub : request to http://10.0.1.3:8088/ failed, reason: connect ENETUNREACH 10.0.1.3:8088 - Local (0.0.0.0:0)-(1)

My config

"platforms": [
        {
            "platform": "HarmonyHubWebSocket",
            "plugin_map": {
                "plugin_name": "homebridge-harmony"
            },
            "hubIP": "10.0.1.3",
            "hubName": "Harmony Hub",
            "name": "Harmony Hub",
            "cleanCache": false,
            "publishAllTVAsExternalAccessory": true,
            "mainActivity": "Watch Virgin Media",
            "linkVolumeControlToTV": true,
            "switchAccessories": false,
            "TVAccessory": true,
            "activitiesToPublishAsInputForTVMode": [],
            "remoteOverrideCommandsList": [],
            "activitiesToPublishAsAccessoriesSwitch": [],
            "skippedIfSameStateActivities": [],
            "devicesToPublishAsAccessoriesSwitch": [],
            "sequencesToPublishAsAccessoriesSwitch": [],
            "homeControlsToPublishAsAccessoriesSwitch": [],
            "otherPlatforms": []

**Comment by nicoduj** [comment]
Seems to be network related on discoveryhowever, I suggest you remove hubName in your config since you seem to have a fixed IP

**Comment by nicoduj** [comment]
Closing since I have no news, feel free to reopen if you have more information / if fixed ip do not work.

**Comment by imroue** [comment]
Hi @nicoduj ,
I seem to have the same issue and I also removed the hubName:

Error - Error retrieving info from hub : request to http://192.168.0.120:8088/ failed, reason: connect EHOSTUNREACH 192.168.0.120:8088-

{
            "name": "MroueHarmony",
            "hubIP": "192.168.0.120",
            "cleanCache": false,
            "TVAccessory": false,
            "configureAccesscontrol": false,
            "playPauseBehavior": true,
            "numberOfCommandsSentForVolumeControl": 15,
            "switchAccessories": true,
            "publishGeneralMuteSwitch": true,
            "publishGeneralVolumeSlider": false,
            "publishGeneralVolumeSwitches": true,
            "linkVolumeControlToTV": false,
            "showCommandsAtStartup": true,
            "platform": "HarmonyHubWebSocket"
        }

**Comment by nicoduj** [comment]
Is the IP the correct one ? Please verify on your network, not in harmony app it is not always up to date. You need to have a fixed IP for the hub
