### ISSUE TITLE
[BUG] - Renaming mute/volumeup/volumedown does not persist even if not linked to tv accessory

### ISSUE THREAD

**Issue by RockerKadi** [nicoduj/homebridge-harmony#313]
Hi..I brought this issue to your attention yesterday.  Basically I am having an issue with the General mute/volumeup/volumedown switches.  Every time I rename  them  in HomeKit to a custom name,  they always go back to default names when Homebridge restarts.

**Comment by nicoduj** [comment]
Can you just try with linkVolumeControlToTV set to false please ? 
Might be linked to the fact thatif you link them to an external accessory, they are not persisted in cache so renamed each time they are exposed.

**Comment by RockerKadi** [comment]
> Can you just try with linkVolumeControlToTV set to false please ?
> Might be linked to the fact thatif you link them to an external accessory, they are not persisted in cache so renamed each time they are exposed.

Setting  linkVolumeControlToTV To false  stopped the switches from reverting to default names when Homebridge restarts.

But now every time I leave the Home app and come back,the volume switches are shown as being On, and you have to press on them once before they start working properly...is this normal?
