### ISSUE TITLE
[BUG] Accessories get re-added on every Homebridge start

### ISSUE THREAD

**Issue by MirkoKas** [nicoduj/homebridge-harmony#314]
**Describe the bug**
I have some automations that trigger the General Mute Switch in HomeKit. Today I noticed that this switch gets removed from my automations on ever restart of Homebridge. Therefore my automations show no devices configured in the Home app. The only thing I changed lately was activating the publishAllTVAsExternalAccessory and therefore deleting the cache. After that I deactivated the clean cache option again. The log shows on every restart of homebridge that it’s creating all devices/activities. 
I‘m running all the latest versions (iOS, homebridge, plugin)

I can reproduce the behavior when disabling the publishAllTVAsExternalAccessory and running the plugin in bridge mode. Then everything works as expected again and my automations keep the way they should. 

**Expected behavior**
The automations with Harmony devices shouldn’t change on the restart of Homebridge. 

**IOS (please complete the following information):**
- Version 14.1
- Device: iPhone 11 Pro

**Config**

"name": "MirkoHarmonyHub",
            "hubIP": "192.168.99.13",
            "publishAllTVAsExternalAccessory": true,
            "mainActivity": "Entertain",
            "publishGeneralMuteSwitch": true,
            "publishGeneralVolumeSlider": true,
            "publishGeneralVolumeSwitches": false,
            "linkVolumeControlToTV": true,
            "showCommandsAtStartup": false,
            "platform": "HarmonyHubWebSocket"

**Comment by nicoduj** [comment]
Hi, I think it has the same cause than #313 : those are services of the accessory which is external so not cached. Will try to see if it can ba handled but meanwhile you can unlink them from tvaccessory by setting option linkVolumeControlToTV to false

**Comment by MirkoKas** [comment]
Thanks for the heads up. For the time being I turned the publishAllTVAsExternalAccessory option off again and I'm working with the bridged devices. Is the icon really the only difference from an user perspective?

Will be happy if you find a way to handle the "not caching"

**Comment by nicoduj** [comment]
As far as I know, yes. Some users are also reporting better discovery of remote app while in external accessory.

**Comment by Phoenix-DH** [comment]
Hey,

I was just right now experiencing the same behaviour:
I only have general Mute/Volume swirtch enabled.

Each restart will rename the devices back to default in home app.
And in the accessories page of config-ui-x they will be recreated as it seems.
Because when I move them to a different room, they are back in the default room after restart.

If I got it right, I got also this config:
```
            "linkVolumeControlToTV": true,
            "publishAllTVAsExternalAccessory": true,
```

Set them to false will fix it?

But I see that this is already added as milestone. I will not loose the TV icon ;)

**Comment by MirkoKas** [comment]
You only have to set "publishAllTVAsExternalAccessory": false.

Maybe you have to clean the cache once, but besides that this works very well for me.

**Comment by Phoenix-DH** [comment]
I tried, yes you are right, but I lost the icon.
Better have the icon, because the other things In only would realize when having a look to the webpage.

**Comment by MirkoKas** [comment]
Yeah, you loose the icon as @nicoduj stated. For me it’s still the better solution as I have automations that silent the the TV when I get a call on my telephone. These automations won’t work when the Mute button resets itself on every restart.

**Comment by MirkoKas** [comment]
So with the new release I wanted to go back to enable publishAllTVAsExternalAccessory to get my TV icon back, but I'm unable to achieve that.
I just switched the publishAllTVAsExternalAccessory to true in my config an then cleared the cache of the plugin and also from homebridge itself. In the log it's also showing my that it created the accessory.

But when I try to add the accessory in the home app with the code it won't find it...

What am I doing wrong @nicoduj ?

Heres the part of the log from the startup:

[2020-11-15 0:14:29] [MirkoHarmonyHub] (MirkoHarmonyHub)INFO - Adding Accessory : MirkoHarmonyHub-TV
[2020-11-15 0:14:29] [MirkoHarmonyHub] (MirkoHarmonyHub)INFO - configuring Main TV Service
[2020-11-15 0:14:29] [MirkoHarmonyHub] (MirkoHarmonyHub)INFO - Creating TV Service
[2020-11-15 0:14:29] [MirkoHarmonyHub] (MirkoHarmonyHub)INFO - Creating Input Service - AppleTV
[2020-11-15 0:14:29] [MirkoHarmonyHub] (MirkoHarmonyHub)INFO - Creating Input Service - Playstation 4
[2020-11-15 0:14:29] [MirkoHarmonyHub] (MirkoHarmonyHub)INFO - Configuring Main Activity Entertain
[2020-11-15 0:14:29] [MirkoHarmonyHub] (MirkoHarmonyHub)INFO - Creating TV Speaker Service
[2020-11-15 0:14:29] [MirkoHarmonyHub] (MirkoHarmonyHub)INFO - Creating Input Service - Entertain
[2020-11-15 0:14:29] [MirkoHarmonyHub] (MirkoHarmonyHub)INFO - Creating Input Service - Nintendo Switch
[2020-11-15 0:14:29] [MirkoHarmonyHub] (MirkoHarmonyHub)INFO - Loading general mute Switch...
[2020-11-15 0:14:29] [MirkoHarmonyHub] (MirkoHarmonyHub)INFO - Creating Switch Service GeneralMuteSwitch/GeneralMuteSwitch
HAP Warning: Characteristic 000000E3-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000049-0000-1000-8000-0026BB765291. Adding anyway.
[2020-11-15 0:14:29] [MirkoHarmonyHub] (MirkoHarmonyHub)INFO - Loading general volume Slider...
[2020-11-15 0:14:29] [MirkoHarmonyHub] (MirkoHarmonyHub)INFO - Creating Slider Service GeneralVolumeSlider/GeneralVolumeSlider
HAP Warning: Characteristic 000000E3-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000043-0000-1000-8000-0026BB765291. Adding anyway.
[2020-11-15 0:14:29] [MirkoHarmonyHub] (MirkoHarmonyHub)INFO - setupFoundAccessories - TV accessory added as external accessory
[2020-11-15 0:14:29] MirkoHarmonyHub-TV 159D is running on port 43057.
[2020-11-15 0:14:29] Please add [MirkoHarmonyHub-TV 159D] manually in Home app. Setup Code: xxx-xx-xxx

**Comment by nicoduj** [comment]
@MirkoKas since you probably add it before and deleted it in home app, you won't be able to add it again if you don't delete it in homebridge . It is not cached since it is external, but there is a dedicated file in persist folder for each external accessory.

Best way is to use config ui I think to delete it and then restart homebridge, and add it again in home app

![image](https://user-images.githubusercontent.com/19813688/99179531-1aadcf80-271f-11eb-95a4-b037aea41f05.png)
![image](https://user-images.githubusercontent.com/19813688/99179533-1da8c000-271f-11eb-9954-dec32c0118e9.png)

**Comment by MirkoKas** [comment]
OMG - thx. It was probably to late yesterday. I was looking for that option but couldn't find it.
No it works as an accessory again (with the right icon) and also my problem with reconfiguring the devices on startup is fixed. 
Thx!
