### ISSUE TITLE
devicesToPublishAsAccessoriesSwitch not working as expected

### ISSUE THREAD

**Issue by tooh** [nicoduj/homebridge-harmony#317]
**Describe the bug**

I get two switch buttons. Both default in state Powered Off.

One of them can only power off and the other can only power on.

Both have the same description (the correct name of the device).

State of the switch is not persisted.

**To Reproduce**
Steps to reproduce the behavior
"devicesToPublishAsAccessoriesSwitch": [
                "Harman Kardon AV-ontvanger"
            ],
**Expected behavior**

I expected  toggle On/Off switch or two switches with the correct description.

**Screenshots**

![afbeelding](https://user-images.githubusercontent.com/429386/98822904-ae3a8400-2431-11eb-870b-5cf08869ca23.png)

**IOS (please complete the following information):**
- Version  1.4.1
- Device: 

**Logs**
Your log in debug mode (-D option)

**Config**
Your config section of platform. Please do not post your whole config and especially with logins / passwords !

"devicesToPublishAsAccessoriesSwitch": [
                "Harman Kardon AV-ontvanger"
            ],
**Additional context**

Possibly related to #308

**Comment by nicoduj** [comment]
Please could you be more explicit and fill in correctly the bug report template ? I d'ont understand what is the problem there

**Comment by tooh** [comment]
@nicoduj I tried to clarify the description and added screen dump. Hope this helps.
I use your plugin for some time in basic config and I'm now trying some of the advanced features.
I apologize if I'm misunderstanding the feature.

**Comment by nicoduj** [comment]
Device switches are always stateless, since harmony does not provide device state.  I t will publish a powertoggle or poweron / off switches depending of the device in harmony app.
The fact that you have 2 switches with same name suggest your config is exposing 2 powertoggle, would need your whole harmony setting (launch in debug and retrieve the json) to investigate.

**Comment by nicoduj** [comment]
Did you manage to check / get your hub config please ?

**Comment by tooh** [comment]
I manually updated the labels of the buttons , so now it is clear what the button does.

The AV device has a PowerOn and PowerOff but not a PowerToggle.

It would help if the plugin can differentiate so that the generated buttons have dfiferent labels.

I understand that Harmony does not provide state.

Buttons are working as labeled.


![afbeelding](https://user-images.githubusercontent.com/429386/99039521-c4f2ef00-2587-11eb-9912-429d37811d88.png)

**Comment by nicoduj** [comment]
thank, that was what was expected but there must be a bug there, will check. But at first you had allready renamed them no ? 

they did not have Harman Kardon in their name, they should at least take the name of the device ...

**Comment by tooh** [comment]
I only added Aan and out.

I notice that in the tiles on the home screen Harmon Kardon is in the name and in the Room this is missing.

When I click on the tile to look at the details in both home and room Harman Kardon is missing. Strange.

**Comment by nicoduj** [comment]
Will try to reproduce, not really sure what happened there.

**Comment by nicoduj** [comment]
can't reproduce, not sure to have the whole info however. Having harmony hub config would help to understand the devices / controls since I d'ont really understand the names provided (seems to be 2 different deivces/ or maybe renamed in home app)
