### ISSUE TITLE
The plugin stopped working

### ISSUE THREAD

**Issue by adrianguanipa** [nicoduj/homebridge-harmony#318]
I'm getting this error, already tried uninstalling and installing it again:

`(HarmonyHub)Error - Error retrieving info from hub : request to http://192.168.1.17:8088/ failed, reason: connect ECONNREFUSED 192.168.1.17:8088-(25)`

Also tried restarting my Harmony Hub, but no luck. The hub and remote are working with no issues.

**Comment by nicoduj** [comment]
Hi, it is a network error . 

Did you change anything (upgrade of homebridge, network ..) ? What platform are you on ? What version of homebridge ? Did you update to big sur if you are on a mac ? 
Did you put a fixed IP on your hub ? Is it still the same on the network ?

Please provide some background :) However, like I said, it is a network error : homebridge plugin from its location can't connect to the hub on port 8088 (IP not reachable probably).

**Comment by adrianguanipa** [comment]
Hi @nicoduj ,

Thanks for your reply, I found the problem, the harmony mobile app says the hub's IP address is .17 but that changed to .25, as it is not fixed, found it on my router' list of wifi clients.

All good now, thanks again.
