### ISSUE TITLE
[BUG] Activtities don't react after some time

### ISSUE THREAD

**Issue by carsten19** [nicoduj/homebridge-harmony#320]
I have connected one Harmony Hub and control it via the Google Home homebridge plugin.
This works without an issue after the start of homebridge. After some time (hours, sometimes days) the activities are triggered according to the plugin (I can see in the homebridge UI that the device is switched on) but the hub doesn't do anything. The activity is not marked as started in the hub remote control and I can start it as usual with the remote control.
When I restart homebridge (or the plugin) it works again. Homebridge runs in a docker container in case that is related.

**Comment by nicoduj** [comment]
Hi, could you provide some logs ? In debug mode if possible. Your config would be helpfull also to try to help.

**Comment by carsten19** [comment]
OK, I have enabled debug mode and will come back when the error happens again.
Here is the config:

`        {
            "platform": "HarmonyHubWebSocket",
            "name": "Wohnzimmer",
            "hubName": "Wohnzimmer",
            "TVAccessory": false,
            "switchAccessories": true
        }`

**Comment by carsten19** [comment]
I had to wait a few days and then the problem surfaced again. I wanted to switch on the device via Google and nothing happened. I had a look at the log in debug mode and nothing was logged at all. Then I tried to switch the devices via Homebridge UI and it the same story: nothing in the log.
I see a report being send to Google but no reaction whatsoever from the Harmony plugin.
The device config looks like this:
![Bildschirmfoto 2020-12-03 um 20 44 05](https://user-images.githubusercontent.com/839480/101080339-f8ce9c80-35a8-11eb-8689-a7f6486ee354.png)

I could imagine that the plugin looses the connection to Harmony. Anything I can help with?

**Comment by nicoduj** [comment]
Hi, don't you have any error in homebridge logs like connection lost ? Did you try with a fixed il instead of network discovery ?

**Comment by carsten19** [comment]
I don't know if there was an error when the connection was lost as the log was already rotated due to many debug messages. At least from what I could see for the past hours there was no log entry from harmony at all.
I will try with a fixed IP.
I also noticed that the harmony-websocket dependency has an updated version (1.5.3) which has a timeout fix. Maybe related?

**Comment by nicoduj** [comment]
Hi, do you have any news ? You can still update dep to see if it helps .

**Comment by carsten19** [comment]
I had to restart homebridge a few times so it is not completely representative but it looks like the IP works better. I will still watch it over the next days.

**Comment by nicoduj** [comment]
Closing, since it seems to be solved. Feel free to reopen if you have any new information / issue
