### ISSUE TITLE
[BUG]on fresh install of plugin/manual device addon will not show. 

### ISSUE THREAD

**Issue by patrickhere** [nicoduj/homebridge-harmony#321]
On a fresh install of the plugin, the log tells me to manually add the device. It does not show up and even when using the manual mode it never finds the TV to add. 

1. Install the plugin. 
2. Attempt to find TV according to log. 
3. Unable to find it. 

I expected to find the TV on search.

- Version [IOS 14.3 Beta 2]
- Device: [iPhone XR]

 {
            "name": "....",
            "hubIP": "....",
            "hubName": "....",
            "TVAccessory": true,
            "platform": "...."
        }

Also, a fresh invite for discord would be awesome! thank you. 
![harmonyhub-log-11-28](https://user-images.githubusercontent.com/75187477/100528428-760da200-31a2-11eb-88ed-bfe13b075e0d.PNG)

**Comment by nicoduj** [comment]
Hi, di you try in home app, going to add an accessory (top right), "don't have a code or can't scan it" ? It should show there.
If not, either you are not on the same network, either it was previously added. If so, remove the accessory from homebridge (inside config UI X, the easiest way, in Homebrdige Settings / unpair hub,cameras,tvs,external accessories) and try again.

**Comment by patrickhere** [comment]
it seems it was messing up due to the accessories still being in the homebridge UI. I removed it and was able to rediscover my TV. thank you!
