### ISSUE TITLE
[BUG] 1.4.1 Install Issue

### ISSUE THREAD

**Issue by donavanbecker** [nicoduj/homebridge-harmony#322]
**Describe the bug**
When installing 1.4.1, I get the following error:
```
npm ERR! code ENOTEMPTY
npm ERR! syscall rmdir
npm ERR! path /homebridge/node_modules/homebridge-harmony/node_modules/bufferutil/prebuilds/linux-x64
npm ERR! errno -39
npm ERR! ENOTEMPTY: directory not empty, rmdir '/homebridge/node_modules/homebridge-harmony/node_modules/bufferutil/prebuilds/linux-x64'

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-12-08T04_43_04_685Z-debug.log

Command failed. Please review log for details.
```

**To Reproduce**
Try install 1.4.1 from 1.4.0

**Expected behavior**
Update to 1.4.1

**Screenshots**

**IOS (please complete the following information):**
- Version: 14.0
- Device: iPhone Xr

Installed on Docker for Unraid.

**Comment by nicoduj** [comment]
Hi, sorry can't reproduce. Seems more a npm problem to me, what version of npm are you using ?
