### ISSUE TITLE
Help needed....

### ISSUE THREAD

**Issue by barronhough** [nicoduj/homebridge-harmony#324]
Hi Guys 

Sorry I am very new to this, and slowly getting there... but need some advice please.

I have installed this plugin and got it to work in a very basic way using HomeBridge.

I have 2x Harmony Hubs that obviously service 2x rooms.. Bedroom and Living room. I have got the TVs to show up and turn on and off in both rooms... But I am struggling to get anymore functionality.. Such as select, next channel, etc etc any advice would be hugely appreciated 

I know this is basic stuff, but its driving me crazy

**Comment by nicoduj** [comment]
You can only expose commands through switches, or use control center widget in ios . But definitely, it won't replace a full remote :) See Readme, let me know if you want further info.

**Comment by nicoduj** [comment]
Did you try the remote widget ?

**Comment by barronhough** [comment]
Hi Nicolas

I did but there is such limited functionality

Best

**Comment by nicoduj** [comment]
Can't do anything on that by my side. on the plugin side you can add one switch per command (or a sequence if you want), but you will end up with a lot of switch.

**Comment by barronhough** [comment]
Thank you so much for your support and guidance

Now trying to figure out lightwave plugin 🤦🏻‍♂️

Alex Barron-Hough
m. (+44) (0) 7752-167-861  e. barronhough@me.com
w. www.barronhough.com
