### ISSUE TITLE
Does not see my 3rd hub via Hoobs [BUG]

### ISSUE THREAD

**Issue by mwhaley99** [nicoduj/homebridge-harmony#325]
{
            "platform": "HarmonyHubWebSocket",
            "plugin_map": {
                "plugin_name": "homebridge-harmony"
            },
            "name": "Harmony LR",
            "hubName": "Harmony LV",
            "otherPlatforms": [
                {
                    "name": "Harmony OFF",
                    "hubName": "Harmony Office",
                    "otherPlatforms": [
                        {
                            "name": "Harmony GB",
                            "hubName": "Harmony GB"
                        }
                    ]
                }

**Comment by nicoduj** [comment]
Should be like this :

{
"platform": "HarmonyHubWebSocket",
"plugin_map": {
"plugin_name": "homebridge-harmony"
},
"name": "Harmony LR",
"hubName": "Harmony LV",
"otherPlatforms": [
{
"name": "Harmony OFF",
"hubName": "Harmony Office",
},
{
"name": "Harmony GB",
"hubName": "Harmony GB"
}
]

**Comment by mwhaley99** [comment]
That fixed it, many thanks.
