### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by scottsimon1979** [nicoduj/homebridge-harmony#326]
**Describe the bug**
Having an issue with second hub.  I am sure its got something to do with how I am putting in the config file, but I've tried several different ways and still have the same issue.  The issue is that the first hub (The Skylark Living Room) shows up fine just as I want it and works great! The  second hub (Harmony Hub 3) does show up in Homekit, but without the volume and mute controls of the first one.  It does allow me to turn on and off the activities and switch between them, but not any volume controls.

**To Reproduce**
N/A

**Expected behavior**
I was wanting it to show with volume up and down as well as mute controls.  Its like the first "TV" setup adhered to all the options I chose in the configuration, but the second device/platform just shows basic controls.  I tried to copy the section below the "Other Platforms" and paste it in with the name of the second hub to see if that would work, but it didn't.

**Screenshots**

**IOS (please complete the following information):**
- Version [ios 14.2.1, Logitech Harmony Version 5.7.7, Hub  Version 4.15.280]
- Device: [iPhone 12 Pro]

**Logs**
Your log in debug mode (-D option)

**Config**
{
            "platform": "HarmonyHubWebSocket",
            "plugin_map": {
                "plugin_name": "homebridge-harmony"
            },
            "hubIP": "192.168.1.22",
            "name": "Skylark Living Room",
            "otherPlatforms": [
                {
                    "name": "Harmony Hub 3",
                    "hubIP": "192.168.1.14"
                }
            ],
            "hubName": "Harmony Hub 3",
            "cleanCache": false,
            "publishAllTVAsExternalAccessory": true,
            "TVAccessory": true,
            "mainActivity": "Watch Apple TV",
            "playPauseBehavior": true,
            "publishGeneralMuteSwitch": true,
            "publishGeneralVolumeSlider": true,
            "publishGeneralVolumeSwitches": false,
            "linkVolumeControlToTV": true,
            "activitiesToPublishAsInputForTVMode": [],
            "remoteOverrideCommandsList": [],
            "activitiesToPublishAsAccessoriesSwitch": [],
            "skippedIfSameStateActivities": [],
            "devicesToPublishAsAccessoriesSwitch": [],
            "sequencesToPublishAsAccessoriesSwitch": [],
            "homeControlsToPublishAsAccessoriesSwitch": []
        }
    ]
}

**Additional context**

**Comment by nicoduj** [comment]
try this :  

{
"platform": "HarmonyHubWebSocket",
"plugin_map": {
"plugin_name": "homebridge-harmony"
},
"hubIP": "192.168.1.22",
"name": "Skylark Living Room",
"otherPlatforms": [
{
"name": "Harmony Hub 3",
"hubIP": "192.168.1.14",
"playPauseBehavior": true,
"publishGeneralMuteSwitch": true,
"publishGeneralVolumeSlider": true,
"linkVolumeControlToTV": true
}
],
"cleanCache": false,
"publishAllTVAsExternalAccessory": true,
"TVAccessory": true,
"mainActivity": "Watch Apple TV",
"playPauseBehavior": true,
"publishGeneralMuteSwitch": true,
"publishGeneralVolumeSlider": true,
"publishGeneralVolumeSwitches": false,
"linkVolumeControlToTV": true
}
]
}

**Comment by scottsimon1979** [comment]
> try this :
> 
> {
> "platform": "HarmonyHubWebSocket",
> "plugin_map": {
> "plugin_name": "homebridge-harmony"
> },
> "hubIP": "192.168.1.22",
> "name": "Skylark Living Room",
> "otherPlatforms": [
> {
> "name": "Harmony Hub 3",
> "hubIP": "192.168.1.14",
> "playPauseBehavior": true,
> "publishGeneralMuteSwitch": true,
> "publishGeneralVolumeSlider": true,
> "linkVolumeControlToTV": true
> }
> ],
> "cleanCache": false,
> "publishAllTVAsExternalAccessory": true,
> "TVAccessory": true,
> "mainActivity": "Watch Apple TV",
> "playPauseBehavior": true,
> "publishGeneralMuteSwitch": true,
> "publishGeneralVolumeSlider": true,
> "publishGeneralVolumeSwitches": false,
> "linkVolumeControlToTV": true
> }
> ]
> }

Thank you so much;  that worked perfectly.   Loving the plugin - thanks again!!
