### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by scottsimon1979** [nicoduj/homebridge-harmony#327]
**Is your feature request related to a problem? Please describe.**
Adding a second or third hub

**Describe the solution you'd like**
Was wondering if there was a way to use an "Add Accessory" button in HOOBS or Homebridge UI like some other plugins I've seen, rather than having to add the other platforms manually.  I think it would greatly enhance and simplify that process.

**Describe alternatives you've considered**
N/A

**Additional context**
Either way, this project is awesome - please dont view my suggestion as critique!

**Comment by nicoduj** [comment]
TV are external accessories, it is not possible if I correctly understand. But through configUI in homebridge you can add other platforms in the config.
