### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by clipse2004** [nicoduj/homebridge-harmony#328]
**Describe the bug**
Sometimes after restarting Homebrige (to install Updates) i get this error:

(Harmony Hub 1)Error - Error retrieving info from hub : WebSocket closed with reason: Socket Error: read ECONNRESET (1006).-(1)
[20.12.2020, 22:47:39] [Harmony Hub 1] (Harmony Hub 1)WARNING - socket closed

**To Reproduce**
Only When i restart HomeBridge with Configurator-zu-x. After i got this Error, i have to restart my Pi and then it works.
Ah i forgot I have to restart my hub also.
But note it is not on every restart.

**IOS : 14.3
- Version [14.3]
- Device: iPhone 12Pro

**Config**
        {
     "name": "Harmony Hub 1",
    "hubIP": "192.168.xx.xxx",
    "hubName": "HarmonyHUB-Wohnzimmer",
    "publishAllTVAsExternalAccessory": true,
    "TVAccessory": true,
    "mainActivity": "Kabel TV",            "addAllActivitiesToSkippedIfSameStateActivitiesList": true,
    "otherPlatforms": [{
    "name": "Harmony Hub 2",
    "hubIP": "192.168.xx.xxx", 
"hubName": "HarmonyHUB-Schlafzimmer",
    "TVAccessory": true,
    "mainActivity": "Kabel TV",                   "addAllActivitiesToSkippedIfSameStateActivitiesList": true  }],
        "platform": "HarmonyHubWebSocket"
    }

**Additional context**
-

**Comment by nicoduj** [comment]
Hi, It is a network error. I would suggest you check the following : 
- IP are fixed on your router
- remove hubName (it is used only in case of auto discovery without fixed ips)

Are you on regular homebridge or hoobs ?
