### ISSUE TITLE
“Stateful” Accessory Switches 

### ISSUE THREAD

**Issue by b3nnyk22** [nicoduj/homebridge-harmony#331]
Hello 

I’m not sure if what I want to achieve is already possible but I use my Harmony Hub to control my Media Centre with a couple of activities which is working in HomeKit as expected.

I also use the Harmony Hub to control a “Dumb” Fan which just has a power toggle. Currently I have an Accessory Switch which toggles the power when the switch is turned on in HomeKit. I would love for this switch to be “Stateful” (Stays on until switched off and sends the power toggle command again once switch off) so I can utilise this switch in Automations. Is this possible? 

Cheers.

**Comment by nicoduj** [comment]
hi,

no it is not, device switches are stateless since there is no way to retrieve the state of a device in the harmony hub (only activities). I did not implement that since it will lead to out of sync states and could be a problem mostly. But it is a question that is asked very often ;)
