### ISSUE TITLE
Other accesories in Rooms

### ISSUE THREAD

**Issue by jplwoodward** [nicoduj/homebridge-harmony#334]
Homekit allows accessories to be assigned to rooms other than "Default Room", and you can also specify whether the accessory should be included in Favorites and Status.  Can there be a way--when specifying an accessory in you configuration--to specify the room and whether to include in favorites and status?

Maybe something like:

Device|Name;Commands|Room|Favorites or NoFavorites|Status or NoStatus

**Comment by nicoduj** [comment]
Hi,
as far as I known, there is not but I might be mistaken. this is handled while adding accessories in home app, but since this plugin is a bridged one, it only happens when adding the bridge OR the TV accessory (which is an external accessory).
