### ISSUE TITLE
Errors in log 

### ISSUE THREAD

**Issue by skir0cket** [nicoduj/homebridge-harmony#335]
Hi seem to be getting constant errors in log ( Received warning for the plugin 'homebridge-harmony' from the characteristic 'Active Identifier': characteristic was supplied illegal value: string instead of number. Supplying illegal values will throw errors in the future!)

using the latest release plus beta 1.30 42 homebridge. 
any ideas?

**Comment by nicoduj** [comment]
Hi, known potential issue, linked to #315
