### ISSUE TITLE
Controlling Insteon ISY Devices or at least Homekit Scenes with Companion Remote?

### ISSUE THREAD

**Issue by TechRemarker** [nicoduj/homebridge-harmony#336]
This plugin appears to expose Harmony activities in Homekit, but is it able to do the reverse?

That is on the Harmony Remote there are light switch buttons, outlet buttons and a dimmer toggle. When using the actual Insteon Hub it natively integrates with Insteon which would be amazing, except that when I used that years ago it was horrible and had 1 star reviews, and seems the company abandoned their homekit hub 3 years ago. So I switched to ISY which works great but no Insteon and Harmony integration.

So trying to figure out how to control my insteon lights with the harmony remote. Does this plugin or another allow one to control Insteon lights/outlets with the buttons on the remotes? I use ISY homebridge plugin so all my Insteon is in Homekit. So thinking I can assign one of those buttons to a homekit scene that will control the lights (though dimmer feature probably won't work then). Before I start experimenting too much wanted to see if this was the right plugin for that or if there is another meant to syncing those yellow buttons with homekit?

**Comment by nicoduj** [comment]
Hi,

not  it is not. If I correctly understand, you want to use a physical harmony remote to handle some homekit exposed devices ? D'ont know if it is possible at all, maybe IFTTT ?
