### ISSUE TITLE
iOS 14.4 TV remote through AppleTV Remote "pane"

### ISSUE THREAD

**Issue by acresp** [nicoduj/homebridge-harmony#337]
Hello,

First of all: thanks a lot for your great job ! This is an awesome plugin!

I don't know if it's a bug or something new in iOS 14.4, but since the last update I can't control my harmony scene through the Remote panel in the control center. I only see my Apple TV. I don't use it often, but it was very useful sometimes 🙂 

Before the update i was seeing my Apple TV "Salon" and also my "Salon TV" (the harmony hub by homebridge) and the Panasonic TV of my bedroom "TV Chambre". Since the update i only see the Apple TV.

Kind regards

**Comment by nicoduj** [comment]
Hi, it happens sometimes, more an issue with iOS . Did you add it as an external accessory ? Since you closed it solved by itself ?

**Comment by acresp** [comment]
I wanted to edit my post with some screenshot, because I checked on my wife's iPhone (she didn't updated) and everything was ok on it. Then I took my phone (iOS 14.4) and now I can control everything ! 

Totally crazy because since few days I don't see anything more than the Apple TV in the remote panel x)

Thanks for your help 🙂
