### ISSUE TITLE
[FEATURE] polling interval

### ISSUE THREAD

**Issue by brummbaer** [nicoduj/homebridge-harmony#339]
Problem:
We use a switchable socket to deactivate our TV setup. Homebridge throws an error every few seconds when the "Harmony Bridge" is switched off.

Solution:
It would be great if Homebridge did not poll the "Harmony Hub" so often when it goes offline. Only poll again when it goes online.

**Comment by nicoduj** [comment]
Hi, can you share your config ? If you are in discovery mode / name mode did you try with a fixed ip ?

**Comment by nicoduj** [comment]
the polling intervall is 10 seconds . Will add some setting to override it.

**Comment by TheEngineerGuy** [comment]
Hi @nicoduj, Which config parameter should I use for Polling interval adjustment? I found 3 intervals on home page, but none on them suggest polling interval adjustments.

Please advise when you have a minute.
