### ISSUE TITLE
Need some help on how to identify root cause of a strange issue 

### ISSUE THREAD

**Issue by maisun** [nicoduj/homebridge-harmony#342]
Hi,
In my current setup from time to time I experience “no response” from all TV accessories including Harmony. It’s less likely an issue with Harmony plugin but I’d like to get some advice on how to find the root cause. I currently have 3 TV accessories exposed via HomeBridge, 2 of them are external accessories (HomeBridge-Harmony, homebridge-samsung-tizen) and one internal (homebridge-bravia-tvos).
Below are my observations:
1) Occasionally all 3 TV accessories show “no response” in Home app. So either they all work, or none of them works.
2) I verified there is no problem with network connection. I can still use Harmony app to control the device. 
3) It seems only affect TV accessory, I also have some Harmony switches and they all work fine when the TV accessories don’t work.
4) I have restarted all my network components, Apple TV (HomeKit hub) and client devices without help.
5) There is no trace in log file, no error or disconnect events.
Any suggestion where to look next? Thanks in advance!

**Comment by nicoduj** [comment]
Hi, 
Did you try setting "ports" in homebridge config, to define the port rzange for external accessories ?

**Comment by maisun** [comment]
Not yet, will give a try, thanks for the hint!

**Comment by nicoduj** [comment]
closed since I have no news, feel free to reopen
