### ISSUE TITLE
[BUG] "name"-tag conflicts with Child Bridge name on Homebridge 1.3.0

### ISSUE THREAD

**Issue by m-a-r-c-u-s** [nicoduj/homebridge-harmony#347]
**Describe the bug**
When running more than one HarmonyHub the "name" tag conflicts with the Child Bridge name. Multiple gateways/hubs with the same name show up in "add new" in Homekit.

![IMG_FD73D70AFC4C-1](https://user-images.githubusercontent.com/68680472/108620977-0836e680-7430-11eb-8cd2-e66f067bdfbf.jpeg)

**To Reproduce**
Add more than one HamonyHub in settings when running plugin in child bridge mode on Homebridge 1.3.0.

My settings:
        {
            "name": "Livingroom Harmonyhub",
            "hubIP": "10.0.20.5",
            "hubName": "Vardagsrum",
            "cleanCache": true,
            "TVAccessory": true,
            "mainActivity": "TV",
            "switchAccessories": false,
            "activitiesToPublishAsAccessoriesSwitch": [],
            "publishGeneralMuteSwitch": false,
            "publishGeneralVolumeSlider": false,
            "publishGeneralVolumeSwitches": false,
            "linkVolumeControlToTV": false,
            "publishSwitchActivitiesAsIndividualAccessories": false,
            "otherPlatforms": [
                {
                    "name": "Mediaroom HarmonyHub",
                    "hubIP": "10.0.20.6",
                    "hubName": "Mediarum",
                    "TVAccessory": true,
                    "mainActivity": "SHIELD TV",
                    "activitiesToPublishAsInputForTVMode": [
                        "TV",
                        "SHIELD TV",
                        "PS4"
                    ],
                    "switchAccessories": false,
                    "activitiesToPublishAsAccessoriesSwitch": [],
                    "publishGeneralMuteSwitch": false,
                    "publishGeneralVolumeSlider": false,
                    "linkVolumeControlToTV": false
                }

**EDIT:** Added my plugin settings

**Comment by nicoduj** [comment]
Hi,

First of all, I suggest you modify your config . 
-cleancache should not be let to true
-if you use hubIP (meaning you have fixed IP), you should not use hubName (use only in discovery mode)

Then, you have to add each TV device separately. 

What you see I think  is the homebridge platform itself (no TV icon) and The TV device I think . (+ 2 others homekit device that seems not related). Did you have this screen after scanning the QR code or is it a "I don't have code screen" ?
I would need english translation to be sure which screen it is :)

**Comment by m-a-r-c-u-s** [comment]
> Hi,
> 
> First of all, I suggest you modify your config .
> -cleancache should not be let to true
**Now set to false.** 

> -if you use hubIP (meaning you have fixed IP), you should not use hubName (use only in discovery mode)
> Then, you have to add each TV device separately.
**They are fixed IPs. I removed the "hubName" on both of the Harmony hubs.**

> What you see I think is the homebridge platform itself (no TV icon) and The TV device I think . (+ 2 others homekit device that seems not related). Did you have this screen after scanning the QR code or is it a "I don't have code screen" ?
> I would need english translation to be sure which screen it is :)
**This is the "I do not have a code" screen. The other two devices are my luminarie plugins.**

After these mods of the config the add screen looks like this:
![IMG_3A5C7BB329F8-1](https://user-images.githubusercontent.com/68680472/108621891-cad55780-7435-11eb-9812-7557a52ffd7a.jpeg)

Adding the Harmony Child Brigde (device with 3 green dots) to homekit doesn't add the HarmonyHubs as accessories. I have to add these separatly. It would be great if: 
A.) Only the Child Bridge is exposed to Homekit and when added all Harmonyhubs are added as accessories
B.) Since adding the Child Bridge to Homekit doesn't do anything only expose the HarmonyHubs to Homekit.


**My new config settings:**

       {
            "name": "Vardagsrum Harmonyhub",
            "hubIP": "10.0.20.5",
            "cleanCache": false,
            "TVAccessory": true,
            "mainActivity": "TV",
            "switchAccessories": false,
            "publishGeneralMuteSwitch": false,
            "publishGeneralVolumeSlider": false,
            "publishGeneralVolumeSwitches": false,
            "linkVolumeControlToTV": false,
            "publishSwitchActivitiesAsIndividualAccessories": false,
            "otherPlatforms": [
                {
                    "name": "Mediarum HarmonyHub",
                    "hubIP": "10.0.20.6",
                    "TVAccessory": true,
                    "mainActivity": "SHIELD TV",
                    "activitiesToPublishAsInputForTVMode": [
                        "TV",
                        "SHIELD TV",
                        "PS4"
                    ],
                    "switchAccessories": false,
                    "publishGeneralMuteSwitch": false,
                    "publishGeneralVolumeSlider": false,
                    "linkVolumeControlToTV": false
                }

**Comment by nicoduj** [comment]
Thank you, that is what I thought.
TV devices are not birdged accessories, so they have ot be added separately and can't be with the hub : can't be added with the bridged accessory.
Will check for the bridge Accessory, indeed since you don't have any switch exposed (which handle them), exposing it is useless (but not sure I can prevent this, will check).

**Comment by nicoduj** [comment]
Hi juste tried to reproduce, and can't. Are you sure it is not the homebridge hub itself ? Or that at any point you did not have some cached accesory ? What does configUI-X show in cached and external accessories ?

**Comment by m-a-r-c-u-s** [comment]
These are my cached bridges and TVs. As you see "Vardagsrum HarmonyHub" is exposed as both TV and Bridge when I run the plugin as "Child Bridge".

![Linked](https://user-images.githubusercontent.com/68680472/108624344-a92f9c80-7444-11eb-814e-189e10d89c7e.png)

**Comment by m-a-r-c-u-s** [comment]
Noticed that I'd left out the Child Bridge part of the previously posted configs. Don't know if it's of any help but here it is at the bottom:

        {
            "name": "Vardagsrum HarmonyHub",
            "hubIP": "10.0.20.5",
            "cleanCache": false,
            "TVAccessory": true,
            "mainActivity": "TV",
            "switchAccessories": false,
            "publishGeneralMuteSwitch": false,
            "publishGeneralVolumeSlider": false,
            "publishGeneralVolumeSwitches": false,
            "linkVolumeControlToTV": false,
            "publishSwitchActivitiesAsIndividualAccessories": false,
            "otherPlatforms": [
                {
                    "name": "Mediarum HarmonyHub",
                    "hubIP": "10.0.20.6",
                    "TVAccessory": true,
                    "mainActivity": "SHIELD TV",
                    "activitiesToPublishAsInputForTVMode": [
                        "TV",
                        "SHIELD TV",
                        "PS4"
                    ],
                    "switchAccessories": false,
                    "publishGeneralMuteSwitch": false,
                    "publishGeneralVolumeSlider": false,
                    "linkVolumeControlToTV": false
                }
            ],
            "platform": "HarmonyHubWebSocket",
            "_bridge": {
                "username": "0E:25:6E:80:A3:81",
                "port": 51202
            }

**Comment by nicoduj** [comment]
Hum are you talking about this new option of homebridge that can isolate each platform as a bridge ? If yes I think you don't have to do that if you only expose tv accessories since they are external one and not bridge . This I think it is not really my plugin that is exposing this but homebridge itself .

**Comment by m-a-r-c-u-s** [comment]
Yes it's caused by isolating the plugin as "child bridge" in Homebridge 1.3.0. I'll just run the plugin without isolation for the time being. It might help others if you mention not to run the plugin as a "child bridge" under Homebridge 1.3.0 in the readme file.

**Comment by nicoduj** [comment]
Ok, thx. I think running as an isolated one might still make sense if you expose switches , but indeed with only a tv accessory it does not make sense

**Comment by nicoduj** [comment]
will be added in the readme :)
