### ISSUE TITLE
[How-To] devicesToPublishAsAccessoriesSwitch with seperate On Off

### ISSUE THREAD

**Issue by Phoenix-DH** [nicoduj/homebridge-harmony#348]
Hey,

I like the new behaviour of devicesToPublishAsAccessoriesSwitch when there is a combined OnOff Button, because you now see the real state.

Is something also possible for example for a light bar behind a TV which I added in Harmony and has a spererate
PowerOn and PowerOff switch?

Actually I got it in this way, means 2 buttons in Home where you cannot see the actual state because toggle is always off:
```
"devicesToPublishAsAccessoriesSwitch": [
                "Beleuchtung TV;PowerOn",
                "Beleuchtung TV;PowerOff",
                "Beleuchtung Theke;/"
```
                
As mentioned... last one working great with new visible toggle state.

Thanks!

**Comment by nicoduj** [comment]
Hi,

Try "Beleuchtung TV;/"

It should combine in one switch power on and off if found.

Beleuchtung "TV;PowerOn/PowerOff" should also work

**Comment by Phoenix-DH** [comment]
Can you give me a recommendation how to do it ;)
I already tried.
I removed the single one for PowerOff and changed the one for on with
`"Beleuchtung TV;/",`

Result:
```
"devicesToPublishAsAccessoriesSwitch": [
                "Beleuchtung TV;/",
                "Beleuchtung Theke;/"
```

The result was that the homebridge won't come up anymore.
Message was something related to a duplicated UUID.

I also tried to set the cleancache, but no change.
Did a restore of the PI and all good.

**Comment by nicoduj** [comment]
hum, did you update to 1.5.1 ? I need the full log in debug mode if possible. Did you try this also with the same result ? : 
```json
"devicesToPublishAsAccessoriesSwitch": [
                "Beleuchtung TV;PowerOn/PowerOff",
                "Beleuchtung Theke;/"
```

**Comment by Phoenix-DH** [comment]
Yes, I got already 1.5.1
As mentioned, only tried the / only.

Will try your proposal without cleaning the cache ...

Will let you know. But first this afternoon after work, if I have to reset again, because I was not able to solve it without restore of a valid backup.

**Comment by nicoduj** [comment]
You can still use config ui to clear the cached accessory and change the conf , no need to reset

**Comment by Phoenix-DH** [comment]
Yes I know, but this had no effect.

**Comment by Phoenix-DH** [comment]
Strange....

Now it is working.... did nearly the same than yesterday....
Removed one "Beleuchtung TV" line and changed the other now to
`"Beleuchtung TV;PowerOn/PowerOff",`

instead of

`"Beleuchtung TV;/",`

... working.

Thank you.

**Comment by nicoduj** [comment]
Would you mind removing the line, restart, and then add it like you did with ;/ ? Should do the same .

**Comment by Phoenix-DH** [comment]
Will give it a try later on.
