### ISSUE TITLE
[FEATURE] Set Harmony Activities into different tiles in Home App

### ISSUE THREAD

**Issue by freemanuk** [nicoduj/homebridge-harmony#349]
Hi, I have installed the Harmony plugin v1.5.1 and I realised that now the activities are grouped into a single tile called Harmony Hub. Is there a way to separate the Harmony Activities into different tiles in Home App like before. That will be helpful, as I have set automation based on different activities. Thank you.

**Comment by nicoduj** [comment]
It is a feature into home app : you can ask it to separate services (properties of the accessory)

**Comment by freemanuk** [comment]
Not sure what have I missed out, I can only choose to include or exclude the inputs.

![Screenshot 2021-02-25 at 1 49 01 PM](https://user-images.githubusercontent.com/75915816/109109452-53befc80-7770-11eb-87f3-7ea1593ee75f.png)

**Comment by freemanuk** [comment]
Managed to solve it by setting "Switches accessories in homekit" to Yes.

**Comment by nicoduj** [comment]
> Managed to solve it by setting "Switches accessories in homekit" to Yes.

I though you were already publishing it as switches. The default behaviour is a TV accessory that publish eacu activity as an input. Yu can use both modes if you want.
