### ISSUE TITLE
[BUG] the plugin slows down Homebridge

### ISSUE THREAD

**Issue by JacVid** [nicoduj/homebridge-harmony#351]
**Describe the bug**
[06/03/2021, 16:53:49] [homebridge-harmony] This plugin slows down Homebridge. The read handler for the characteristic 'On' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.

**Config**
        {
            "platform": "HarmonyHubWebSocket",
            "name": "Harmony",
            "hubIP": "10.0.1.120",
            "cleanCache": false,
            "publishSwitchActivitiesAsIndividualAccessories": false,
            "activitiesToPublishAsAccessoriesSwitch": [
                "Regarder CanalSat",
                "Regarder Apple TV"
            ],
            "switchAccessories": true,
            "TVAccessory": false,
            "showTurnOffActivity": "inverted",
            "activitiesToPublishAsInputForTVMode": [],
            "remoteOverrideCommandsList": [],
            "skippedIfSameStateActivities": [],
            "devicesToPublishAsAccessoriesSwitch": [],
            "sequencesToPublishAsAccessoriesSwitch": [],
            "homeControlsToPublishAsAccessoriesSwitch": [],
            "otherPlatforms": []
        },

**Additional context**
Homebridge v1.3.2

Any idea of the problem which occur randomly.

**Comment by nicoduj** [comment]
It means that some updates takes time and did not respond in the allowed time . Might be linked to your other issue, probably network related.

**Comment by JacVid** [comment]
Hello Nicoduj, I still get some red alert in Homebridge logs.

_[21/03/2021, 08:14:29] [homebridge-harmony] This plugin slows down Homebridge. The read handler for the characteristic 'On' was slow to respond! See https://git.io/JtMGR for more info.
[21/03/2021, 08:14:35] [homebridge-harmony] This plugin slows down Homebridge. The read handler for the characteristic 'On' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info._

Do you think it still normal ?
