### ISSUE TITLE
[PROBLEM] An action works no more

### ISSUE THREAD

**Issue by MikeDeltaHH** [nicoduj/homebridge-harmony#353]
**Describe the problem**
I have a problem with the plugin since yesterday.... have configured 3 actions on my Harmony:

1. cinema - turns on a media player, A/V receiver & TV.
2. Netflix - turns on the TV and launches the Netflix app.
3. eintertain - turns on the TV & Telekom Receiver

Since yesterday action 3 does not work reliably - when I start this action on the Harmony remote control the message appears that the action is started but very often only the TV is switched on - when ending the action the same, sometimes only the TV is switched off! I have tested extensively and the Telekom receiver is mostly only at the 2nd or 3rd execute the action on or off!

If I start the action on the Harmony remote everything works - both devices are switched on and when switching off the same! 

Actions 1+2 work fine - I have powered down the receiver & Harmony Hub and restarted Homebridge with no success! Since this has never happened since I use the plugin and also only one action is affected by it, I'm pretty clueless what the reason can be...

**To Reproduce**
I switched on Entertain and the TV manually, activated the Homebridge Debug Log and switched off action 3 - works, the Telekom receiver and the TV are switched off! Then I turned on action 3 - only the TV is turned on, the telecom receiver remains off.

**IOS (please complete the following information):**
- Version 14.4
- Device: iPhone 12 Pro Max

**Logs**
[homebridge.log.txt](https://github.com/nicoduj/homebridge-harmony/files/6097173/homebridge.log.txt)

**Config**

{
    "name": "Harmony",
    "hubIP": "192.168.2.34",
    "publishAllTVAsExternalAccessory": true,
    "TVAccessory": true,
    "mainActivity": "Fernsehen",
    "playPauseBehavior": true,
    "switchAccessories": true,
    "showTurnOffActivity": "true",
    "addAllActivitiesToSkippedIfSameStateActivitiesList": true,
    "platform": "HarmonyHubWebSocket",
    "_bridge": {
        "username": "xxx",
        "port": 46696
    }
}

**Comment by nicoduj** [comment]
Hi,

Did you change anything in your conf ? harmony plugin only send the activity command to the hub, t is the hub itself which launch each action. Are you sure there is no IR issue between the hub and the device that not always works ? Depending on your remote, it could be sent by it so it won't have the same behavior I think. Try with harmony app on your phone you should have the same erratic behavior .

**Comment by MikeDeltaHH** [comment]
Hi Nico!

I have not changed anything in the configuration for ages! Have just tested both with the original remote control of the Telekom receiver, the Harmony Elite remote control and the app on my iPhone several times and each time works the action on or off! About the plugin it now unfortunately no longer works, it is only the TV switched but no longer the Telekom receiver!

**Comment by nicoduj** [comment]
You are using an harmony activity right, not a custom sequence or something like that ?

**Comment by MikeDeltaHH** [comment]
Yes, right!

**Comment by nicoduj** [comment]
sl like I said it is very strange, since the plugin only activate the activity (not what is inside). Could you run in debug and post any log when activating / turning off ? Did you try with switches (instead of input of TV accessory) or vice-versa ?

**Comment by MikeDeltaHH** [comment]
The logs i‘ve uploaded in my first post have the needed turn off / activate action with the nom working power on! I use it as switches... indeed, very strange- works perfect in the last years...

**Comment by nicoduj** [comment]
Sorry, missed the logs . However everything seems fine : [3/7/2021, 2:20:42 PM] [Harmony] (Harmony)INFO : SET on an activty in skippedIfsameState list Entertain
[3/7/2021, 2:20:42 PM] [Harmony] (Harmony)INFO : Activty Entertain is false, wants to set to true
[3/7/2021, 2:20:42 PM] [Harmony] (Harmony)INFO : Activty Entertain will be sent command 29968007
[3/7/2021, 2:20:42 PM] [Harmony] (Harmony)INFO - activityCommand : Returned from hub {"cmd":"harmony.activityengine?runactivity","code":200,"id":"0.12144464999462112","msg":"OK"}

Did you try setting a new activity with this device ?

**Comment by MikeDeltaHH** [comment]
I have three activities on the Harmony hub, the other both are working perfect! Do you mean to delete the activity on the harmony and create a new one with the same settings? I can try this tomorrow when i‘m back home! 
And thanks for your help!

**Comment by MikeDeltaHH** [comment]
Hi @nicoduj 
I recreated the action on the hub, uninstalled the plugin, deleted the child bridge and reinstalled the plugin and turned on debug mode! Have then run the action several times, the Telekom receiver has not responded once - I hope you find something in the logs...

[homebridge.log.txt](https://github.com/nicoduj/homebridge-harmony/files/6099784/homebridge.log.txt)

**Comment by nicoduj** [comment]
Hi, did not see anything in the plogs. One idea however : If you have renamed your activties in home app, maybe you can try to delete the file named harmonyPluginNames_XXX in the root directory of your homebridge folder. 

Have no other idea for the moment, the activity is fine through harmony app ?

**Comment by nicoduj** [comment]
Closing since I have no update on this.
