### ISSUE TITLE
[BUG] homebridge v1.3.2 causes warning in logging about Password Setting set to null

### ISSUE THREAD

**Issue by madcat-nl** [nicoduj/homebridge-harmony#355]
When updating to homebridge v1.3.2  with homebridge-harmony v1.5.1 it creates the following error in the log:

[homebridge-harmony] This plugin generated a warning from the characteristic 'Password Setting': characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics. See https://git.io/JtMGR for more info.

i have not configured any password in the configuration

**Comment by nicoduj** [comment]
Hi, can you share your config please ?

**Comment by madcat-nl** [comment]
{
            "name": "Beamer",
            "hubIP": "hubip",
            "cleanCache": false,
            "publishAllTVAsExternalAccessory": false,
            "TVAccessory": true,
            "mainActivity": "Film",
            "activitiesToPublishAsInputForTVMode": [
                "Muziek",
                "Film",
                "Playstation"
            ],
            "playPauseBehavior": true,
            "numberOfCommandsSentForVolumeControl": 2,
            "remoteOverrideCommandsList": [
                {
                    "ActivityName": "Film",
                    "CommandsList": [
                        {
                            "CommandName": "INFORMATION",
                            "NewCommand": "Marantz;Info"
                        },
                        {
                            "CommandName": "ARROW_RIGHT",
                            "NewCommand": "IMAC;ScanPrev"
                        },
                        {
                            "CommandName": "ARROW_LEFT",
                            "NewCommand": "IMAC;ScanNext"
                        },
                        {
                            "CommandName": "SELECT",
                            "NewCommand": "IMAC;Stop"
                        },
                        {
                            "CommandName": "PLAY",
                            "NewCommand": "IMAC;Play"
                        },
                        {
                            "CommandName": "VOLUME_UP",
                            "NewCommand": "Marantz;VolumeUp"
                        },
                        {
                            "CommandName": "VOLUME_DOWN",
                            "NewCommand": "Marantz;VolumeDown"
                        },
                        {
                            "CommandName": "MUTE",
                            "NewCommand": "Marantz;Mute"
                        },
                        {
                            "CommandName": "BACK",
                            "NewCommand": "IMAC;Enter"
                        }
                    ]
                },
                {
                    "ActivityName": "Muziek",
                    "CommandsList": [
                        {
                            "CommandName": "PLAY",
                            "NewCommand": "IMAC;Play"
                        },
                        {
                            "CommandName": "PAUSE",
                            "NewCommand": "IMAC;Play"
                        },
                        {
                            "CommandName": "MUTE",
                            "NewCommand": "Marantz;Mute"
                        },
                        {
                            "CommandName": "VOLUME_UP",
                            "NewCommand": "Marantz;VolumeUp"
                        },
                        {
                            "CommandName": "VOLUME_DOWN",
                            "NewCommand": "Marantz;VolumeDown"
                        }
                    ]
                }
            ],
            "switchAccessories": false,
            "publishGeneralMuteSwitch": false,
            "publishGeneralVolumeSlider": true,
            "linkVolumeControlToTV": true,
            "publishSwitchActivitiesAsIndividualAccessories": false,
            "showCommandsAtStartup": false,
            "platform": "HarmonyHubWebSocket"
        }

ps: just updated to 1.3.3 and still have this issue

**Comment by madcat-nl** [comment]
anything else you need to look into it?

**Comment by nicoduj** [comment]
Are you using home sharing in home app ? Might be related , will check did not have the time yet sorry

**Comment by madcat-nl** [comment]
yes i do have home sharing enabled, if you need any help just ask

**Comment by nicoduj** [comment]
Could you please share the conf of your home sharing in home app ? Same network ? users who shares home ? 

Did you by any chance ever set this option to true : configureAccesscontrol ?

**Comment by nicoduj** [comment]
Closing since I have no update on this.
