### ISSUE TITLE
Log says "add TV manually" even if it is already added?

### ISSUE THREAD

**Issue by mensa84** [nicoduj/homebridge-harmony#356]
Hello,

is it normal, that the logfile of homebridge says at every start, that one should add the TVs manually, altough they are already added working and can't be added twice??

```
Mar 16 18:26:51 Server homebridge[26699]: Preparing Advertiser for 'Schlafzimmer Fernseher-TV 8AC1' using bonjour-hap backend!
Mar 16 18:26:51 Server homebridge[26699]: Starting to advertise 'Schlafzimmer Fernseher-TV 8AC1' using bonjour-hap backend!
Mar 16 18:26:51 Server homebridge[26699]: [3/16/2021, 6:26:51 PM] Schlafzimmer Fernseher-TV 8AC1 is running on port 35403.
Mar 16 18:26:51 Server homebridge[26699]: [3/16/2021, 6:26:51 PM] Please add [Schlafzimmer Fernseher-TV 8AC1] manually in Home app. Setup Code: 031-45-154
```

Or is that normal and just impossible to hide that message?

**Comment by nicoduj** [comment]
Hi, Tv  are external accessories, that are retrieved from cache and are published by the plugin at each launch. I can easily change the message, but since there might be added to different home app not sure I can have knowledge it was already added. It is the same as the homebridge itself :)

**Comment by mensa84** [comment]
Ok, when I know that this is the normal behavior, it's fine. Thx.
