### ISSUE TITLE
Activity Switch resets to Default room and automations disappear [BUG]

### ISSUE THREAD

**Issue by danielepenguin** [nicoduj/homebridge-harmony#359]
I am running HOOBS in Docker.
Every time the docker image gets updated, the Harmony activity switches defined in "Activities To Publish As Accessories Switch", get reset to the default Home room and all related automations disappear. It looks like the switch gets deleted and re-added, and Homekit does not recognise it's the same switch. 
The TV accessory and all other plugins do not show this behaviour.

**Comment by nicoduj** [comment]
Hi,

seems you have clean cache option set to true -> set it to false.

**Comment by danielepenguin** [comment]
Yes, it was set to true.
Thanks
