### ISSUE TITLE
Accessoires not showing up

### ISSUE THREAD

**Issue by Grubi93** [nicoduj/homebridge-harmony#360]
I have an issue with publishing my accessories in the Homebridge app, respectively in the  Home App. 
The connection between Homebridge and  Home is working - I am using the Hue plugin and some other features, all are showing up. 

I have tried reinstalled the Harmony plugin, cleared the cache, tried several different settings, changed the IP address of the hub and updated every software. The issue still persists. 
If I display the full log when restarting home bridge, all my activities and accessories are shown and loaded from my Hub, but nothing is showing up in  home. 

I am using Homebridge v 1.3.4 and Harmony plugin 1.5.1. Node.js v 14.16.0 / Npm v6.14.11

do you have an idea, what could be the root cause or what I can try to fix the issue?
It has worked properly for some time but since a few weeks, it is not working anymore. 

Thanks in advance. 
Best regards, Nico

**Comment by nicoduj** [comment]
Hi, can you share your conf ? Mostly, if you are using basic behavior (tv accessory), it is because you must add it manually in home app with the code provided in the log : it is not a bridged accessory

**Comment by Grubi93** [comment]
Hello,
please check the attached log and config files for your reference. It is recognizing all my activities and accessories, but they are not showing up in  Home. The Accessories, added with the Hue plugin, or WoL, are showing up.
The general mute switch, volume switches and power off button are showing up as well

Thanks in advance for your support.

[config-2.pdf](https://github.com/nicoduj/homebridge-harmony/files/6308424/config-2.pdf)
[Homebridge Log 20210414.pdf](https://github.com/nicoduj/homebridge-harmony/files/6308425/Homebridge.Log.20210414.pdf)

**Comment by nicoduj** [comment]
Hi, like I said you have to add the tv accessory manually (using plus button in home app, don't have a code ...) . Tv accessory is not bridge like the switch are and must be added by itself (like you added the homebridge bridge )

**Comment by Grubi93** [comment]
Hi, okay I will do that. It's strange, because it was working since long with this configuration and all accessories were shown - seems that it has changed.
I will let you know, if it has worked - thanks a lot.

**Comment by nicoduj** [comment]
I was supporting bridged mode for tv at the beginning but since iOS 14 change their are defaulted to external otherwise there are some bugs with remote controls . You can still force the first one as bridge accessory, see readme there is an option for that if you want to try .
