### ISSUE TITLE
Some Harmony Activities are not "Discovered"

### ISSUE THREAD

**Issue by jplwoodward** [nicoduj/homebridge-harmony#365]
When homebridge loads, only 3 of my six Harmony activities are discovered, e.g.:
[5/19/2021, 12:45:15 PM] [Family Room] (Family Room)INFO - Discovered Activity : Watch X1

Why wouldn't all six be discovered?

**Comment by nicoduj** [comment]
Hi (first things first), 

Can you share your conf please and full log ? Did you rename some activities inside harmony after adding the plugin / device in home app ?

**Comment by jplwoodward** [comment]
I was publishing only 3 of my original 6 activities.  Then I deleted one of them which was not published  then I added one with a different name.  Then I added this new activity (“Listen to Music”) to be published  but only the original 3 that I published are discovered.  Here is my current config:

{
            "name": "Family Room",
            "hubIP": "192.168.1.18",
            "hubName": "Family Room",
            "DELAY_BEFORE_RETRY_AFTER_NETWORK_LOSS": 60000,
            "HUB_CONNECT_TIMEOUT": 10000,
            "HUB_SEND_TIMEOUT": 30000,
            "TVAccessory": true,
            "mainActivity": "Watch X1",
            "activitiesToPublishAsInputForTVMode": [
                "Watch Kitchen",
                "Watch Fire TV",
                "Watch X1",
                "Listen to Music"
            ],
            "numberOfCommandsSentForVolumeControl": 4,
            "switchAccessories": true,
            "activitiesToPublishAsAccessoriesSwitch": [
                "Watch X1",
                "Watch Kitchen",
                "Watch Fire TV",
                "Listen To Music"
            ],
            "publishGeneralMuteSwitch": true,
            "publishGeneralVolumeSlider": false,
            "publishGeneralVolumeSwitches": true,
            "linkVolumeControlToTV": false,
            "publishSwitchActivitiesAsIndividualAccessories": true,
            "devicesToPublishAsAccessoriesSwitch": [
                "Xfinity DVR|Channel 4;Number4;Select",
                "Xfinity DVR|Channel 5;Number5;Select",
                "Xfinity DVR|Channel 7;Number7;Select",
                "Xfinity DVR|Channel 10;Number1;Number0;Select",
                "Xfinity DVR|Channel 14;Number1;Number4;Select",
                "Xfinity DVR|Channel 32;Number3;Number2;Select",
                "Xfinity DVR|HGTV;Number8;Number3;Number2;Select",
                "Xfinity DVR|Fox;Number8;Number0;Number6;Select",
                "Xfinity DVR|TBS;Number8;Number3;Number1;Select",
                "Xfinity DVR|USA;Number8;Number3;Number5;Select",
                "Xfinity DVR|Lifetime;Number8;Number3;Number6;Select",
                "Xfinity DVR|ESPN;Number8;Number4;Number9;Select",
                "Xfinity DVR|ESPN2;Number8;Number5;Number0;Select",
                "Xfinity DVR|SYFY;Number8;Number6;Number2;Select",
                "Xfinity DVR|CBS Sports;Number8;Number5;Number6;Select",
                "Xfinity DVR|NESN;Number8;Number5;Number1;Select",
                "Xfinity DVR|NESN Plus;Number8;Number9;Number4;Select",
                "Xfinity DVR|X1 Pause;Pause",
                "Xfinity DVR|X1 Rewind;Rewind",
                "Xfinity DVR|X1 Fast Forward;FastForward",
                "Xfinity DVR|X1 Menu;Menu",
                "Xfinity DVR|X1 Down;DirectionDown",
                "Xfinity DVR|X1 Up;DirectionUp",
                "Xfinity DVR|X1 Left;DirectionLeft",
                "Xfinity DVR|X1 Right;DirectionRight",
                "Xfinity DVR|X1 Select;Select",
                "Xfinity DVR|X1 Guide;Guide",
                "Xfinity DVR|X1 Exit;Exit",
                "Xfinity DVR|X1 Page Down;PageDown",
                "Xfinity DVR|X1 Page Up;PageUp",
                "Xfinity DVR|X1 Previous Channel;PrevChannel",
                "Xfinity DVR|X1 Channel Up;ChannelUp",
                "Xfinity DVR|X1 Channel Down;ChannelDown",
                "Xfinity DVR|X1 Record;Record",
                "Amazon Fire TV Stick|Fire Select;Select",
                "Amazon Fire TV Stick|Fire Pause;Pause",
                "Amazon Fire TV Stick|Fire Home;Home",
                "Amazon Fire TV Stick|Fire Rewind;Rewind",
                "Amazon Fire TV Stick|Fire Fast Forward;FastForward",
                "Amazon Fire TV Stick|Fire Menu;Menu",
                "Amazon Fire TV Stick|Fire Down;DirectionDown",
                "Amazon Fire TV Stick|Fire Up;DirectionUp",
                "Amazon Fire TV Stick|Fire Left;DirectionLeft",
                "Amazon Fire TV Stick|Fire Right;DirectionRight",
                "Amazon Fire TV Stick|Fire Back;Back",
                "Amazon Fire TV Stick|Fire TV Stop;Stop",
                "LG TV|Kitchen TV On;PowerOn",
                "LG TV|Kitchen TV Off;PowerOff",
                "Sharp TV|FR TV On;PowerOn",
                "Sharp TV|FR TV Off;PowerOff",
                "Sharp TV|FR TV Display;Display",
                "Yamaha V485 Receiver|Audio FM;InputFm",
                "Yamaha V485 Receiver|Audio Bluetooth;InputBluetooth",
                "Yamaha V485 Receiver|Audio Music;SceneRadio",
                "Yamaha V485 Receiver|Audio Setup;Menu",
                "Yamaha V485 Receiver|Audio Option;Option",
                "Yamaha V485 Receiver|Audio Return;Exit",
                "Yamaha V485 Receiver|Audio Next Preset;NextPreset",
                "Yamaha V485 Receiver|Audio Prev Preset;PrevPreset",
                "Yamaha V485 Receiver|Audio Enhance;Enhancer",
                "Yamaha V485 Receiver|Audio Pgm Up;ProgramUp",
                "Yamaha V485 Receiver|Audio Pgm Down;ProgramDown",
                "Yamaha V485 Receiver|Audio Bass;Bass"
            ],
            "publishDevicesAsIndividualAccessories": true,
            "showCommandsAtStartup": false,
            "platform": "HarmonyHubWebSocket"
        }

**Comment by nicoduj** [comment]
Hi, maybe there is some cache issue or the name of the activity is not the right one (it is case sensitiv).

You can try to clean the cache, and/or removing any activity filtering (activitiesToPublishAsAccessoriesSwitch) .

**Comment by nicoduj** [comment]
Closing since I had no update on this.
