### ISSUE TITLE
Expose long press action as a switch

### ISSUE THREAD

**Issue by njuart** [nicoduj/homebridge-harmony#369]
Hi @nicoduj First of all thx for this amazing plugin!

So I have an interesting question, maybe you can assist me with it. As you might know Apple TV can be added to Harmony Hub via bluetooth to expose "real" Home button functionality (like it described [here](https://medium.com/@squarefrog/pairing-a-logitech-harmony-hub-with-apple-tv-4-4k-using-bluetooth-57942f62b1db) for example). As you might also know when you long press Home button it opens Apple TV control center (where you can switch user, check audio settings etc.). So my question here, is it possible to expose exactly long press action of Home button as separate switch in Homekit (same as usual single press)? Thx in advance

**Comment by nicoduj** [comment]
Hi, unfortunatley never found a way to do that. Double press is ok, but long press, if possible never found how !

**Comment by njuart** [comment]
> Hi, unfortunatley never found a way to do that. Double press is ok, but long press, if possible never found how !

Thx, anyway 👍
