### ISSUE TITLE
12.2 beta features not working?

### ISSUE THREAD

**Issue by seannymurrs** [nicoduj/homebridge-harmony#37]
I installed the plugin, and added the two additional parameters to my config file, but I’m still just getting a normal switch for my activity in the Home app. I’m running the 12.2 beta and the latest version of homebridge (46). Any suggestions on what to check to further diagnose?

**Comment by nicoduj** [comment]
As Insaid on reddit, I think your are on the Npm version that is not on the work in progress branch on github but on the master. You have to install the branch manually for now.

**Comment by seannymurrs** [comment]
Thanks. I posted here before posting to Reddit. Sorry for the duplicate.

--
Sean Murray

**Comment by nicoduj** [comment]
Not a problem ;) enjoy alpha testing !
