### ISSUE TITLE
Warning message

### ISSUE THREAD

**Issue by Christian-CFP** [nicoduj/homebridge-harmony#371]
Hey I get this WARNING Message:

29.7.2021, 21:22:21HOME BridgeSamsung(Samsung)INFO - Loading activities...
29.7.2021, 21:22:21HOME BridgeFEHLER(node:16104) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 state.change listeners added to [Device]. Use emitter.setMaxListeners() to increase limit
29.7.2021, 21:22:21HOME BridgeFEHLER(Use `node --trace-warnings ...` to show where the warning was created)

**Comment by nicoduj** [comment]
Hi, could you tell me more about your homebridge config (config file, host, versions ???) ?
Do you have a lot of disconnection also ?

**Comment by Christian-CFP** [comment]
This is my config for hb-harmony:
{
            "TVAccessory": true,
            "showTurnOffActivity": false,
            "publishSequencesAsIndividualAccessories": true,
            "publishSwitchActivitiesAsIndividualAccessories": true,
            "linkVolumeControlToTV": true,
            "publishDevicesAsIndividualAccessories": true,
            "name": "Samsung",
            "showCommandsAtStartup": false,
            "hubName": "Harmony Hub",
            "publishGeneralVolumeSlider": false,
            "switchAccessories": true,
            "publishGeneralMuteSwitch": false,
            "configureAccesscontrol": false,
            "platform": "HarmonyHubWebSocket",
            "publishAllTVAsExternalAccessory": true,
            "hubIP": "192.168.xxx.xxx",
            "publishGeneralVolumeSwitches": false,
            "cleanCache": false,
            "playPauseBehavior": true,
            "publishHomeControlsAsIndividualAccessories": true,
            "mainActivity": "Fernseher",
            "addAllActivitiesToSkippedIfSameStateActivitiesList": true,
            "publishHomeControlButtons": true
        }

Versions:
Harmony 1.5.3
Node 14.17.4
Homebridge 1.3.4
need more?

This Warning does not seem to affect anything (I guess / hope). So far it runs (besides this issue #372) and I can control everything.

**Comment by Christian-CFP** [comment]
Here the log:
31.7.2021, 14:08:09HOME BridgeSamsung(Samsung)INFO - Loading activities...
31.7.2021, 14:08:09HOME BridgeFEHLER(node:32097) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 state.change listeners added to [Device]. Use emitter.setMaxListeners() to increase limit
31.7.2021, 14:08:09HOME BridgeFEHLER(Use `node --trace-warnings ...` to show where the warning was created)
31.7.2021, 14:08:10HOME BridgeSamsung(Samsung)INFO - Adding Accessory : Samsung-TV
31.7.2021, 14:08:10HOME BridgeSamsung(Samsung)INFO - configuring Main TV Service
31.7.2021, 14:08:10HOME BridgeSamsung(Samsung)INFO - Creating TV Service
31.7.2021, 14:08:10HOME BridgeSamsung(Samsung)INFO - Creating Input Service - BluRay
31.7.2021, 14:08:10HOME BridgeSamsung(Samsung)INFO - Configuring Main Activity Fernseher
31.7.2021, 14:08:10HOME BridgeSamsung(Samsung)INFO - Creating TV Speaker Service
31.7.2021, 14:08:10HOME BridgeSamsung(Samsung)INFO - Creating Input Service - Fernseher
31.7.2021, 14:08:10HOME BridgeSamsung(Samsung)INFO - Creating Input Service - Apple TV
31.7.2021, 14:08:10HOME BridgeSamsung(Samsung)INFO - Discovered Activity : BluRay
31.7.2021, 14:08:10HOME BridgeSamsung(Samsung)INFO - Discovered Activity : Fernseher
31.7.2021, 14:08:10HOME BridgeSamsung(Samsung)INFO - Discovered Activity : Apple TV
31.7.2021, 14:08:10HOME BridgeSamsung(Samsung)INFO - setupFoundAccessories - TV accessory added as external accessory
31.7.2021, 14:08:10HOME BridgeSamsung-TV 5636 is running on port 34999.

**Comment by Christian-CFP** [comment]
I guess it is maybe the Samsung Tizen Plugin. In debug mode the Tizen plugin is loading before the Warning.
So I guess its related to that plugin not to yours ;)

31.7.2021, 14:20:26HOME BridgePreparing Advertiser for 'Fernseher 1B13' using bonjour-hap backend!
31.7.2021, 14:20:26HOME BridgeWARNING<(node:507) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 state.change listeners added to [Device]. Use emitter.setMaxListeners() to increase limit
31.7.2021, 14:20:26HOME BridgeWARNING(Use node --trace-warnings ... to show where the warning was created)
31.7.2021, 14:20:26HOME BridgeStarting to advertise 'Fernseher 1B13' using bonjour-hap backend!
31.7.2021, 14:20:26HOME BridgeFernseher 1B13 is running on port 34065.
