### ISSUE TITLE
"Random" Issue

### ISSUE THREAD

**Issue by Christian-CFP** [nicoduj/homebridge-harmony#372]
If the Hub connect to a better WIFI mesh station the connection gets lost and homebridge does not reconnect.
It tries but get only error messages.

**Comment by nicoduj** [comment]
Hi, could you provide conf and logs please ? Are you using a static IP for the hub or auto discovery ?

**Comment by Christian-CFP** [comment]
This is my config for hb-harmony:
{
"TVAccessory": true,
"showTurnOffActivity": false,
"publishSequencesAsIndividualAccessories": true,
"publishSwitchActivitiesAsIndividualAccessories": true,
"linkVolumeControlToTV": true,
"publishDevicesAsIndividualAccessories": true,
"name": "Samsung",
"showCommandsAtStartup": false,
"hubName": "Harmony Hub",
"publishGeneralVolumeSlider": false,
"switchAccessories": true,
"publishGeneralMuteSwitch": false,
"configureAccesscontrol": false,
"platform": "HarmonyHubWebSocket",
"publishAllTVAsExternalAccessory": true,
"hubIP": "192.168.xxx.xxx",
"publishGeneralVolumeSwitches": false,
"cleanCache": false,
"playPauseBehavior": true,
"publishHomeControlsAsIndividualAccessories": true,
"mainActivity": "Fernseher",
"addAllActivitiesToSkippedIfSameStateActivitiesList": true,
"publishHomeControlButtons": true
}

Versions:
Harmony 1.5.3
Node 14.17.4
Homebridge 1.3.4
need more?

Logs I have to wait until it switches from one WIFI station to another to provide you some.

**Comment by Christian-CFP** [comment]
Now I switched the Stations manually to provide you some logs, but it seems doing well. So its not the WiFi Mesh.
If it appears ones again I will post the logs here!
