### ISSUE TITLE
Error: Cannot Bridge more than 149 Accessories

### ISSUE THREAD

**Issue by e1l52** [nicoduj/homebridge-harmony#373]
My HomeBridge Installation didn't show up Harmony Switches after last reboot, which worked like a charm for month.

I see this error message :
UnhandledPromiseRejectionWarning: Error: Cannot Bridge more than 149 Accessories

Any idea how to fix that ?

**Comment by nicoduj** [comment]
It seems your bridge has too many devices . You will have to expose another homebridge or if you use homebridge 1.3 to use separate bridge for some plugins (like harmony) . If you switch to a dedicated bridge please note that all accessories will be seen as new ones (and you will loose related automations )

**Comment by e1l52** [comment]
Thanks a lot for your fast reply. I didn't know that there is a limit for devices.
Will try to fix that with a second bridge.
