### ISSUE TITLE
creating two unique device control switches?

### ISSUE THREAD

**Issue by dfizzo** [nicoduj/homebridge-harmony#374]
Hi @nicoduj! 

Is it possible to create two separate device accessory switches with two unique sets of device commands (in my case, (1) for all volume controls and (2) another for all device input selection? I was able to accomplish this by creating two instances of Homebridge-harmony plugins in the config, but seems that ability been deprecated and will be deleted in next version (and also not ideal solution). 

Appreciate any guidance!

Thanks,
@dfizzo

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by nicoduj** [comment]
Hi,

not possible at the moment, either each switch is an individual accessory or one global accessory (which trigeer the group beahvior of home app).two instance of the plugin will still be possible with latest homebridge version if you publish them in separate hubs.
