### ISSUE TITLE
[FEATURE] update the discord invite uri 😬 

### ISSUE THREAD

**Issue by emory** [nicoduj/homebridge-harmony#377]
**Is your feature request related to a problem? Please describe.**

If someone wants to slap my keyboard about this, I'll understand. On the npmjs listing for this plugin it reads:

> You can discuss this plugin on Discord in #harmony channel

But the link to the Discord instance has expired or otherwise isn't available anymore.  That's all.

**Describe the solution you'd like**

To be teleported to a bunch of other geeks with this infernal remote control trying to make it more useful.

**Describe alternatives you've considered**
 
lmgtfy 

**Additional context**

Again, sorry, at least I didn't call it a bug? 😬

**Comment by cereyanli** [comment]
Any update on this one

**Comment by nicoduj** [comment]
should be ok I think (not a "pro" on discord :p )
