### ISSUE TITLE
How to get volume to work?

### ISSUE THREAD

**Issue by monsieurlatte** [nicoduj/homebridge-harmony#378]
Read through the instructions but I'm not clear as to how it works.  Does anyone have a walkthrough explanation on how to get it to work/show up in homekit?

**Comment by nicoduj** [comment]
volume is only available through remote app in ios or through sliders / switch in home app (but not reallu compatible with a siri command).

Use these options : 

`publishGeneralMuteSwitch` publish a mute switch, stateless, that will send a mute command to current activity.

`publishGeneralVolumeSlider` publish a volume slider, stateless, that will send a volume commands to current activity. Approximativley, it will send an Up / Down Volume command each 5%. It can be combined with numberOfCommandsSentForVolumeControl option to multiply the number of up / down commands sent.

`publishGeneralVolumeSwitches` publish switches, stateless, for volume up / down on TV Accessory. It can be combined with numberOfCommandsSentForVolumeControl option to multiply the number of up / down commands sent.

`linkVolumeControlToTVlinks` mute / volume switch to TV accessory if present
