### ISSUE TITLE
Impossible to update homebridge-harmony@latest

### ISSUE THREAD

**Issue by bobybob69** [nicoduj/homebridge-harmony#38]
Hi guys 

I'm trying to update the package using commande 
sudo npm install homebridge-harmony@latest 

However I got an error and I don't understand how to fix it (see bellow) 

I also attached the log file for the error 

Thanks in advance for your support, I notice you fix the latest issue I've open 👍 🤘 you rock ! 

[2019-02-01T18_42_46_073Z-debug.log](https://github.com/nicoduj/homebridge-harmony/files/2822894/2019-02-01T18_42_46_073Z-debug.log)

**Comment by bobybob69** [comment]
serveur:~ loris$ sudo npm install homebridge-harmony@latest
npm WARN tar EISDIR: illegal operation on a directory, open '/Users/loris/node_modules/.staging/chnl-e6ba2fdd/es5'
npm WARN tar EISDIR: illegal operation on a directory, open '/Users/loris/node_modules/.staging/har-schema-1411984e/lib'
npm WARN tar EISDIR: illegal operation on a directory, open '/Users/loris/node_modules/.staging/has-c09b9c62/src'
npm WARN tar EISDIR: illegal operation on a directory, open '/Users/loris/node_modules/.staging/performance-now-2431b5a3/lib'
npm WARN tar EISDIR: illegal operation on a directory, open '/Users/loris/node_modules/.staging/promise-controller-4fe76d90/lib'
npm WARN tar EISDIR: illegal operation on a directory, open '/Users/loris/node_modules/.staging/har-validator-605891bd/lib'
npm WARN tar EISDIR: illegal operation on a directory, open '/Users/loris/node_modules/.staging/flat-options-cb8429bb/lib'
npm WARN tar EISDIR: illegal operation on a directory, open '/Users/loris/node_modules/.staging/delayed-stream-1e0b70ef/lib'
npm WARN tar EISDIR: illegal operation on a directory, open '/Users/loris/node_modules/.staging/tough-cookie-351286e2/lib'
npm WARN tar EISDIR: illegal operation on a directory, open '/Users/loris/node_modules/.staging/has-c09b9c62/test'
npm WARN tar EISDIR: illegal operation on a directory, open '/Users/loris/node_modules/.staging/json-schema-traverse-7899032d/spec'
npm WARN tar EISDIR: illegal operation on a directory, open '/Users/loris/node_modules/.staging/typedarray-to-buffer-b985416f/test'
npm WARN tar EISDIR: illegal operation on a directory, open '/Users/loris/node_modules/.staging/combined-stream-20d0bafc/lib'
npm WARN tar EISDIR: illegal operation on a directory, open '/Users/loris/node_modules/.staging/fast-json-stable-stringify-0271a217/benchmark'
npm WARN tar EISDIR: illegal operation on a directory, open '/Users/loris/node_modules/.staging/json-stringify-safe-e93c4c4b/test'
npm WARN tar EISDIR: illegal operation on a directory, open '/Users/loris/node_modules/.staging/promise-controller-4fe76d90/scripts'
npm WARN tar EISDIR: illegal operation on a directory, open '/Users/loris/node_modules/.staging/asynckit-7100a7bb/lib'
npm WARN tar EISDIR: illegal operation on a directory, open '/Users/loris/node_modules/.staging/ajv-c1cd4f60/dist'
npm WARN tar EISDIR: illegal operation on a directory, open '/Users/loris/node_modules/.staging/yaeti-291b3705/lib'
npm WARN tar EISDIR: illegal operation on a directory, open '/Users/loris/node_modules/.staging/has-symbols-1645e662/test'
npm WARN tar EISDIR: illegal operation on a directory, open '/Users/loris/node_modules/.staging/json-schema-traverse-7899032d/spec/fixtures'
npm WARN tar EISDIR: illegal operation on a directory, open '/Users/loris/node_modules/.staging/performance-now-2431b5a3/src'
npm WARN tar EISDIR: illegal operation on a directory, open '/Users/loris/node_modules/.staging/function-bind-cef2eba5/test'
npm WARN tar EISDIR: illegal operation on a directory, open '/Users/loris/node_modules/.staging/define-properties-156eb3fe/test'
npm WARN tar EISDIR: illegal operation on a directory, open '/Users/loris/node_modules/.staging/promise-controller-4fe76d90/src'
npm WARN tar EISDIR: illegal operation on a directory, open '/Users/loris/node_modules/.staging/qs-b60ae602/dist'
npm WARN tar EISDIR: illegal operation on a directory, open '/Users/loris/node_modules/.staging/object-keys-d9663346/test'
npm WARN tar EISDIR: illegal operation on a directory, open '/Users/loris/node_modules/.staging/chnl-e6ba2fdd/src'
npm WARN tar EISDIR: illegal operation on a directory, open '/Users/loris/node_modules/.staging/fast-json-stable-stringify-0271a217/example'
npm WARN tar EISDIR: illegal operation on a directory, open '/Users/loris/node_modules/.staging/has-symbols-1645e662/test/shams'
npm WARN tar EISDIR: illegal operation on a directory, open '/Users/loris/node_modules/.staging/is-symbol-ecad6a70/test'
npm WARN tar EISDIR: illegal operation on a directory, open '/Users/loris/node_modules/.staging/form-data-a61299ff/lib'
npm WARN tar EISDIR: illegal operation on a directory, open '/Users/loris/node_modules/.staging/websocket-429502a3/lib'
npm WARN tar EISDIR: illegal operation on a directory, open '/Users/loris/node_modules/.staging/performance-now-2431b5a3/test'
npm WARN tar EISDIR: illegal operation on a directory, open '/Users/loris/node_modules/.staging/qs-b60ae602/lib'
npm WARN tar EISDIR: illegal operation on a directory, open '/Users/loris/node_modules/.staging/promise-controller-4fe76d90/test'
npm WARN tar EISDIR: illegal operation on a directory, open '/Users/loris/node_modules/.staging/promise.prototype.finally-8ea89141/test'
npm WARN tar EISDIR: illegal operation on a directory, open '/Users/loris/node_modules/.staging/uri-js-d79124fd/dist/es5'
npm WARN tar EISDIR: illegal operation on a directory, open '/Users/loris/node_modules/.staging/uuid-50435e86/bin'
npm WARN tar EISDIR: illegal operation on a directory, open '/Users/loris/node_modules/.staging/es-to-primitive-c8d94d2b/helpers'
npm WARN tar EISDIR: illegal operation on a directory, open '/Users/loris/node_modules/.staging/performance-now-2431b5a3/test/scripts'
npm WARN tar EISDIR: illegal operation on a directory, open '/Users/loris/node_modules/.staging/promise-controller-4fe76d90/test/specs'
npm WARN tar EISDIR: illegal operation on a directory, open '/Users/loris/node_modules/.staging/request-93d731e3/lib'
npm WARN tar EISDIR: illegal operation on a directory, open '/Users/loris/node_modules/.staging/fast-json-stable-stringify-0271a217/test'
npm WARN tar EISDIR: illegal operation on a directory, open '/Users/loris/node_modules/.staging/psl-9bb3f3cc/data'
npm WARN tar EISDIR: illegal operation on a directory, open '/Users/loris/node_modules/.staging/uuid-50435e86/lib'
npm WARN tar EISDIR: illegal operation on a directory, open '/Users/loris/node_modules/.staging/websocket-as-promised-5413c381/dist'
npm WARN tar EISDIR: illegal operation on a directory, open '/Users/loris/node_modules/.staging/es-to-primitive-c8d94d2b/test'
npm WARN tar EISDIR: illegal operation on a directory, open '/Users/loris/node_modules/.staging/chnl-e6ba2fdd/types'
npm WARN tar EISDIR: illegal operation on a directory, open '/Users/loris/node_modules/.staging/es-abstract-7dfdd777/helpers'
npm WARN tar EISDIR: illegal operation on a directory, open '/Users/loris/node_modules/.staging/psl-9bb3f3cc/dist'
npm WARN tar EISDIR: illegal operation on a directory, open '/Users/loris/node_modules/.staging/qs-b60ae602/test'
npm WARN tar EISDIR: illegal operation on a directory, open '/Users/loris/node_modules/.staging/ajv-c1cd4f60/lib'
npm WARN tar EISDIR: illegal operation on a directory, open '/Users/loris/node_modules/.staging/es-abstract-7dfdd777/operations'
npm WARN tar EISDIR: illegal operation on a directory, open '/Users/loris/node_modules/.staging/websocket-as-promised-5413c381/scripts'
npm WARN tar EISDIR: illegal operation on a directory, open '/Users/loris/node_modules/.staging/websocket-as-promised-5413c381/src'
npm WARN tar EISDIR: illegal operation on a directory, open '/Users/loris/node_modules/.staging/ajv-c1cd4f60/lib/compile'
npm WARN tar EISDIR: illegal operation on a directory, open '/Users/loris/node_modules/.staging/websocket-429502a3/src'
npm WARN tar EISDIR: illegal operation on a directory, open '/Users/loris/node_modules/.staging/uri-js-d79124fd/dist/esnext'
npm WARN tar EISDIR: illegal operation on a directory, open '/Users/loris/node_modules/.staging/websocket-as-promised-5413c381/test'
npm WARN tar EISDIR: illegal operation on a directory, open '/Users/loris/node_modules/.staging/websocket-429502a3/vendor'
npm WARN tar EISDIR: illegal operation on a directory, open '/Users/loris/node_modules/.staging/es-abstract-7dfdd777/test'
npm WARN tar EISDIR: illegal operation on a directory, open '/Users/loris/node_modules/.staging/websocket-as-promised-5413c381/test/specs'
npm WARN tar EISDIR: illegal operation on a directory, open '/Users/loris/node_modules/.staging/nan-24786827/doc'
npm WARN tar EISDIR: illegal operation on a directory, open '/Users/loris/node_modules/.staging/ajv-c1cd4f60/lib/dot'
npm WARN tar EISDIR: illegal operation on a directory, open '/Users/loris/node_modules/.staging/uri-js-d79124fd/dist/esnext/schemes'
npm WARN tar EISDIR: illegal operation on a directory, open '/Users/loris/node_modules/.staging/es-abstract-7dfdd777/test/helpers'
npm WARN tar EISDIR: illegal operation on a directory, open '/Users/loris/node_modules/.staging/websocket-as-promised-5413c381/types'
npm WARN tar EISDIR: illegal operation on a directory, open '/Users/loris/node_modules/.staging/nan-24786827/tools'
npm WARN tar EISDIR: illegal operation on a directory, open '/Users/loris/node_modules/.staging/uri-js-d79124fd/src'
npm WARN tar EISDIR: illegal operation on a directory, open '/Users/loris/node_modules/.staging/uri-js-d79124fd/src/schemes'
npm WARN tar EISDIR: illegal operation on a directory, open '/Users/loris/node_modules/.staging/ajv-c1cd4f60/lib/dotjs'
npm WARN tar EISDIR: illegal operation on a directory, open '/Users/loris/node_modules/.staging/uri-js-d79124fd/tests'
npm WARN tar EISDIR: illegal operation on a directory, open '/Users/loris/node_modules/.staging/ajv-c1cd4f60/lib/refs'
npm WARN tar EISDIR: illegal operation on a directory, open '/Users/loris/node_modules/.staging/ajv-c1cd4f60/scripts'
npm WARN enoent ENOENT: no such file or directory, open '/Users/loris/package.json'
npm WARN loris No description
npm WARN loris No repository field.
npm WARN loris No README data
npm WARN loris No license field.

npm ERR! path /Users/loris/node_modules/request/node_modules/sshpk/bin/sshpk-conv
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/loris/node_modules/request/node_modules/sshpk/bin/sshpk-conv'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:

**Comment by nicoduj** [comment]
don't really know what happens there. I have jsut published through npm 0.2.0 with beta tv platform support

**Comment by bobybob69** [comment]
update to latest 0.2.0 fix the issue 
Closed
