### ISSUE TITLE
[BUG] Perhaps question: HarmonyHub general device not visible in Eve App

### ISSUE THREAD

**Issue by CHTHSCH** [nicoduj/homebridge-harmony#381]
**Describe the bug**
First: All elements, that I configured are correctly displayed in the Home App and functioning as specified and desired. This also includes the general HarmonyHub device with its characteristics/switches (volume, mute etc.)

Second: I am using the Eve App. The general HarmonyHub device is not displayed at all. All other elements are visible as expected. How can the general HarmonyHub device made visible in the Eve App?

**To Reproduce**
n/a

**Expected behavior**
The general HarmonyHub device with its characteristics/switches is also visible in the Eve App.

**Screenshots**
n/a

**IOS (please complete the following information):**
- Version [15.1]
- Device: [iPhone XS and iPad Air 2]

**Logs**
n/a

**Config**
n/a

**Additional context**
n/a

**Comment by nicoduj** [comment]
Hi, If you are talking about the TV device (the one with inputs), it won't be visible in any third party app like EVE : those devices are not exposed to them by apple, nothing I can do about it.
Switches however will be (but not switches linked to tv accessory)

**Comment by CHTHSCH** [comment]
Understood.

Thanks for the response. Yes, I meant the Tv device.
I like your plugin, works well! Perhaps some more examples would be very usefull for people with limited technical capabilities.

**Comment by nicoduj** [comment]
Agree with that for the sample, since the plugin evolved a lot with a lot of options through time. Any contribution to the readme is welcome, I unfortunately don't have a lot of time to work on this those days.
