### ISSUE TITLE
Getting a lot of No response from HomeKit app

### ISSUE THREAD

**Issue by SilentRage47** [nicoduj/homebridge-harmony#385]
Hello,
i configured the plugin with no problem.
In my Home app I have all my activities but they are usually in a 'No Response' state when opening the app, they acctualy start to work after a couple of minutes. This seems to happens everytime I close and re-open the app.

Homebridge log's shows this warning:
`This plugin slows down Homebridge. The read handler for the characteristic 'On' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.`

This is my config:

> {
            "name": "Harmony",
            "hubIP": "192.168.47.23",
            "hubName": "Media room",
            "DELAY_BEFORE_RETRY_AFTER_NETWORK_LOSS": 60000,
            "HUB_CONNECT_TIMEOUT": 10000,
            "HUB_SEND_TIMEOUT": 30000,
            "TVAccessory": true,
            "mainActivity": "SHIELD TV",
            "activitiesToPublishAsInputForTVMode": [
                "SHIELD TV"
            ],
            "switchAccessories": true,
            "activitiesToPublishAsAccessoriesSwitch": [
                "PC",
                "Guarda un film"
            ],
            "showTurnOffActivity": "stateless",
            "linkVolumeControlToTV": false,
            "publishSwitchActivitiesAsIndividualAccessories": true,
            "platform": "HarmonyHubWebSocket"
        }

Thank you

**Comment by nicoduj** [comment]
Hi, generally speaking, this kind of error is due to slow network connection between your homebridge and the harmony hub. Do you have a lot of accessories / devices in your harmony conf ?

**Comment by SilentRage47** [comment]
I have 8 devices and 6 activity. Is that a lot ?

**Comment by nicoduj** [comment]
It is not a lot. what kind of network are you using ? IS this a mesh wifi where your hub might switch from one to another access point ? What are the settings of your wifi connection ?

**Comment by nicoduj** [comment]
#387 for merging this issue
