### ISSUE TITLE
Question: Is there a way to expose a light to HomeKit not as a simple switch

### ISSUE THREAD

**Issue by onelight17** [nicoduj/homebridge-harmony#389]
Hi, sorry if this isn't the right place for this question but wanted to know if there was a way to control a RGB light in HomeKit as a light. Currently it's just a switch that can turn on and off but Harmony can do other things such as brightness and colors. Has any one tried that?

**Comment by nicoduj** [comment]
Hi,
no, hermony controls of lights / home accessories is not exposed through the remote functions, it is coded inside app itself.
