### ISSUE TITLE
Two Hubs - One Disappeared

### ISSUE THREAD

**Issue by tjbx** [nicoduj/homebridge-harmony#390]
I have two hubs configured with static IPs and a simple config (like the multiple hub example) and one disappeared from HomeKit in the last couple of days. I can't seem to get it back. I've restarted homebridge multiple times, tried downgrading homebridge-harmony (and upgrading it back to the latest) but nothing has worked. I can see normal log files about the missing hub and it appears and works in the homebridge UI, but it doesn't appear in the home app anymore. I have a lot of scenes tied each hub so I'd prefer a solution that would get the missing one back as opposed to nuking all hubs and recreating them if possible. Any clues appreciated.

**Comment by nicoduj** [comment]
Hi,
was harmony plugin on a dedicated bridge or the main bridge ? When you say it disapeared from homekit, You mean from home app right ?
What was published  ? only a tv accessory or also switches ? If it is the tv accessory that disapeared, di you try adding it back with its id (external accessory) ?

**Comment by tjbx** [comment]
I had tried to add it back but it didn't appear. Your answer prompted me to look around more in homebridge and using the "Unpair Bridges/Cameras/TVs/External Accessories" to unpair the problem HarmonyHub allowed me to re-add it. Thanks.
