### ISSUE TITLE
Support Sleep - [FEATURE]

### ISSUE THREAD

**Issue by scottleestrange** [nicoduj/homebridge-harmony#391]
Most harmony remote support sleep timer which will turn off all running activities, choice of 15, 30,60, 90 and 120 minutes

Can this be added?

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by nicoduj** [comment]
Hi, 
You can use shortcut / automation for that I think, will be far more powerfull . The timer is handled as far as I know by the harmony app, not the hub itself.
