### ISSUE TITLE
[BUG] Harmony activities revert back to 'default room'

### ISSUE THREAD

**Issue by Coder84619** [nicoduj/homebridge-harmony#393]
**Describe the bug**
In Homekit the Harmony activities keep reverting back to being in the 'default room', after I assign each activity to a specific rooom.

**To Reproduce**
Move Harmony activities into a specific room in the Home app. Wait a few days, and see that the activities ALL get moved back into the 'default room'.

**Expected behavior**
Harmony activities should stay in their assigned room.

**Screenshots**

**IOS (please complete the following information):**
- Version 15.3
- Device: iPhone 13 Pro

**Logs**
Your log in debug mode (-D option)

**Config**
Your config section of platform. Please do not post your whole config and especially with logins / passwords !

**Additional context**

**Comment by nicoduj** [comment]
Hi,

you probably have an incorrect config file with option cleanCache set to true, which re-create all accessories when hub restarts. 

If not, it can also be due to some old ipad in old ios version in your home (and can't do anything about that).

**Comment by nicoduj** [comment]
Closing this one, please feel free to reopen if you have more info / need more help
