### ISSUE TITLE
2nd Hub activities only show up as a Multi Switch, not individual switches like the 1st Hub

### ISSUE THREAD

**Issue by iBaird44** [nicoduj/homebridge-harmony#394]
<img width="375" alt="image" src="https://user-images.githubusercontent.com/97559981/152562207-8a76140d-1ba2-4e0b-a4c2-f01c153ebc9c.png">

It also strangely always starts on the Third item on the list when powered on, not the first

**Comment by nicoduj** [comment]
Hi, please share your conf. It seems your second hub does not have any switch configured, and is an external TV Accessory (default).

**Comment by nicoduj** [comment]
I am closing this one, please feel free to reopen if you want more help
