### ISSUE TITLE
mainActivity with "Apple TV" or "AppleTV" fails with WARNING

### ISSUE THREAD

**Issue by jvaleski** [nicoduj/homebridge-harmony#396]
configuring mainActivity to "Apple TV" or "AppleTV" fails with the following warning during plugin startup.

`No main Activity that match config file found, default to first one`

workaround is to set said activity in Harmony to some other string (e.g. "abc"), and then set the plugin's mainActivity to that.

**Comment by nicoduj** [comment]
Hi, double check the log and the name of the activity, it is case sensitive

**Comment by jvaleski** [comment]
I double checked many times to no avail. I just used the activity rename workaround and it worked. something about "Apple*" doesn't work.

**Comment by nicoduj** [comment]
Hi, it seems strange. Are you tlaking about the name inside harmony app, or Home app ? The name in the plugin config should be the one in Harmony app. You can rename in home app, but config must remains on harmony settings.

Please post startup logs if you want me to check further.

**Comment by scottleestrange** [comment]
Strange. I have 4 hubs with the main activity “Watch AppleTV” and no issues.  However I did see this error once.  It went away after I simply refreshed the config and restarted the bridge.  But defiantly something
