### ISSUE TITLE
Switching to activities bevor powering on

### ISSUE THREAD

**Issue by beatpaul** [nicoduj/homebridge-harmony#397]
**Is your feature request related to a problem? Please describe.**

I would like to choose the activity BEFORE powering it on  with HarmonyPlugin/Home app. Its because i do have some Activities without Screen --> (like "Music") but in Home app i have to poweron first and then change the Activity so some components like the TV has to be swiched on always.

**Describe the solution you'd like**

In Home App it would be great to be abel to choose the Activity first before powering on (I remember that worked in an earlier version)

**Describe alternatives you've considered**

Creating an Empty Activity as a first "Startup activity where no Hifi Components were switched on

**Additional context**

**Comment by nicoduj** [comment]
Hi,

unfortunately, it is a limitation of home app . It was possible in the early beginnings, but they removed this possibility to select an input and thus power on on this input.

the only way to do so now is with a switch per input, not through the TV accessory.
