### ISSUE TITLE
Channels direct Buttons like on the Harmony remote control

### ISSUE THREAD

**Issue by mrxxxxxx** [nicoduj/homebridge-harmony#399]
Hello,

I would like to have buttons in the home app with which I can switch the TV channels (for TV Device) e.g. Eurosport with Button 1 (Channel 1); MTV with Button 2 (Chanel 2) etc........
How can I realize this?
Thank you very much.

**Comment by nicoduj** [comment]
Hi,
I think you could always define switches with custom commands (number of the channel itself) with devicesToPublishAsAccessoriesSwitch . Use a sequence with a small delay for channels numbers > 9 .
