### ISSUE TITLE
Installation hangs

### ISSUE THREAD

**Issue by JotWee** [nicoduj/homebridge-harmony#4]
Install hangs at
`[..................] | fetchMetadata: sill resolveWithNewModule punycode@2.1.1 checking installable status`

**Comment by nicoduj** [comment]
Hi,

Strange have no clue why it does that. Are you installing through configUi ? What are your npm version / which OS are you on ? (Other plugins install are ok ?)

**Comment by JotWee** [comment]
repeated about ten times, at some point it worked. maybe just some hiccup.
