### ISSUE TITLE
Individual control

### ISSUE THREAD

**Issue by Gotcha182** [nicoduj/homebridge-harmony#400]
I currently have the tv activity set up with all of my scenes from harmony working well. I cannot seem to get individual control of certain devices like being able to have my fireplace turn in or off while my watch tv activity is on and not including that fireplace. 

Is this a possibility? If so what is needed as I would love to have some extra controls

**Comment by nicoduj** [comment]
Hi,

you can always use shortcut or automation to do that. You will have to expose a switch for your fireplace, and then a shortcut (or automation).
