### ISSUE TITLE
1.6 Still getting socket closed errors [BUG]

### ISSUE THREAD

**Issue by schlotz** [nicoduj/homebridge-harmony#401]
Not as many by far, but usually 2-3 per day.  Is this considered normal?

**Comment by nicoduj** [comment]
Hi,

The error is network related, can't do anything about that . What I tried to resolve in latest update was the fact that it might not reconnect and some slow response time warning on homebridge side .

**Comment by schlotz** [comment]
Gotta ya, then no worries.  Thanks!
