### ISSUE TITLE
No Response  when added as "TV"

### ISSUE THREAD

**Issue by alegend2k** [nicoduj/homebridge-harmony#408]
Hey there...
I was using the plugin for nearly 2 years now  -  I added it "normal" just as HUB via the homebridge scan.
Recently I saw the log in homebridge that there is the option to add it as "TV" device....
I did this and it first worked but now very often this added device does show "no response" mostly this happens after some hours or maybe 1 day...
Any clue why this is?

**Comment by nicoduj** [comment]
Hi, can you share your config and log please ? Can be due to auto discovery, I would recommend to stick on fixed IP config .

**Comment by nicoduj** [comment]
please open again if it is still an issue
