### ISSUE TITLE
[BUG] TV-Smybol in Home App

### ISSUE THREAD

**Issue by dibimuc** [nicoduj/homebridge-harmony#409]
![992D6925-C63D-4A0E-B706-E62D9A898C6D](https://user-images.githubusercontent.com/61652682/185736858-5ffbfd77-f350-479c-8687-2515275defba.jpeg)
![7350EFBC-3730-4254-9EF6-1D178163A2AC](https://user-images.githubusercontent.com/61652682/185736859-c886e597-419f-4e83-bd94-288912b5f2d0.jpeg)
**Describe the bug**
The Harmony Plug-In ist very good and reliable. However, the symbol in the Home App changed from the TV-Smybol into the orange Home symbol. Do you know how to change this icon again into the TV symbol in the Home App? It’s not possible to change the icon in the Home App itself.

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**

**Screenshots**

**IOS (please complete the following information):**

**Logs**
Your log in debug mode (-D option)

**Config**

            "switchAccessories": false,
            "showCommandsAtStartup": true,
            "cleanCache": false,
            "publishAllTVAsExternalAccessory": false,
            "platform": "HarmonyHubWebSocket",
            "TVAccessory": true,
            "name": "Harmony Hub",
            "DELAY_BEFORE_RETRY_AFTER_NETWORK_LOSS": 60000,
            "HUB_CONNECT_TIMEOUT": 10000,
            "HUB_SEND_TIMEOUT": 30000,
            "sortInput": 0,
            "hubIP": "xxx.xxx.xxx.xx",
            "hubName": "Harmony Hub"

**Additional context**

**Comment by nicoduj** [comment]
Hi, which iOS version are you using ?

**Comment by dibimuc** [comment]
> Hi, which iOS version are you using ?

15.6.1

**Comment by nicoduj** [comment]
Hum, can't reproduce, I have the correct icon by my side .
Do you have an older device in your home ? Maybe try to remove and add it again but not sure at all. Is it the case on all your devices ?

**Comment by dibimuc** [comment]
Yes, it’s on all my devices (I have the latest Apple stack). I will close the ticket then and wait for iOS 16 since this is not the highest priority.
