### ISSUE TITLE
Can't add Harmony TV manually in Home app

### ISSUE THREAD

**Issue by cl4udiu5** [nicoduj/homebridge-harmony#413]
**Describe the bug**
I had to delete Homebridge from Home app because all devices didn't respond anymore.
Main problem was, that after homebridge restart all homebridge devices didn't respond any more. I think this I maybe an iOS 16 problem. Restarting homebridge didn't make any problems in Home app in the past.

Reconnected homebridge in Home app again and then added the devices in Home app. 
In Harmony Hub I have three activities (see my screenshot), they are also back in Home app as switches. 
Harmony-TV A2D1 I have to add manually in Home app and this devices I can't see when trying to add it manually.
Didn't change my config for years now.

My Samsung TV for example was no problem to add manually.

Homebridge: 1.5.0
homebridge-harmony: 1.6.1

**Screenshots**
<img width="742" alt="Bildschirmfoto 2022-10-14 um 10 04 55" src="https://user-images.githubusercontent.com/74124378/195795410-43a14a64-7f74-49d2-9960-a0c14ccf8667.png">

**iOS (please complete the following information):**
- 16.0.3
- iPhone 14 Pro

**Config**
            "platform": "HarmonyHubWebSocket",
            "name": "Harmony",
            "hubIP": "192.168.0.251",
            "DELAY_BEFORE_RETRY_AFTER_NETWORK_LOSS": 60000,
            "HUB_CONNECT_TIMEOUT": 10000,
            "HUB_SEND_TIMEOUT": 30000,
            "cleanCache": false,
            "TVAccessory": true,
            "sortInput": 2,
            "switchAccessories": true,
            "mainActivity": "Watch TV"

**Comment by cl4udiu5** [comment]
After deleting all cached devices in Homebridge UI and restarting Homebridge, I was able to connect Harmony TV and all other devices again.

**Comment by nicoduj** [comment]
I think that in this case you indeed have to delete the dedicated external device for the tv accessory in homebridge cache.
