### ISSUE TITLE
Experiencing Homebridge crashing

### ISSUE THREAD

**Issue by basemodel72** [nicoduj/homebridge-harmony#414]
**Describe the bug**
I am experiencing repeated issues where the harmony plug-in has a failure that leads to the rest of homebridge shutting down and needing a full restart to function again.

**To Reproduce**
it seems that every 20min or so this issue will occur following a full restart

**Expected behavior**
For Homebridge to have 100% uptime with desired features (control of harmony remote from HomeKit) in place

**Screenshots**
![Screen Shot 2022-10-16 at 6 33 58 PM](https://user-images.githubusercontent.com/103601071/196074691-f0de5686-fece-485e-b864-359d5638af72.png)
![Screen Shot 2022-10-16 at 10 03 01 PM](https://user-images.githubusercontent.com/103601071/196074696-5f8158b2-ed26-4229-bb5d-00e722a00f20.png)

**IOS (please complete the following information):**
- Version: hb 1.5 / harmony plug-in: 1.6.1 / node.js: 16.18.0
- Device: Mac mini os10.15.7

**Logs**
as soon as I capture events in full logging mode I will add/update

**Additional context**
issue only began occurring when harmony plug in was installed... harmony remote will continue to function as normal even when homebridge/plug in is not

**Comment by basemodel72** [comment]
here are the logs from the last hours
[homebridge.log](https://github.com/nicoduj/homebridge-harmony/files/9800043/homebridge.log)

**Comment by nicoduj** [comment]
Hi,
can you share your config, and/or check what kind of ip config you have ? Did you set a static ip to your hub through your network ? 
The network range seems a bit strange to me, even if it should not be a problem. 
However it is a network issue, maybe since you are on a mac it goes into some network sleep mode ?

**Comment by basemodel72** [comment]
Hub set to DHCP but I have my router giving it a fixed address thru DHCP reservation...
Mac could be the issue but this problem only started after I installed the harmony plug in

**Comment by basemodel72** [comment]
![Screen Shot 2022-10-17 at 6 43 23 PM](https://user-images.githubusercontent.com/103601071/196297790-54c5bf8b-24d6-4e13-84ae-557d63c19c6d.png)

**Comment by nicoduj** [comment]
Hum, ok, please remove other platform section, might be related (see #410)
