### ISSUE TITLE
Change heading level h6 to h5

### ISSUE THREAD

**Issue by lisanet** [nicoduj/homebridge-harmony#418]
In config UI heading levels on subsections (e.g. 'Devices to publish as accessories switch' in 'Other Accessories') are very small. This makes it difficult to recognize a new subsection and to distinguish between heading and text.

IMO setting heading levels to h5 might offer some better readability.

I've just made a PR #417 with h5. I'd be glad, if it would be accepted.

**Comment by nicoduj** [comment]
Merged it, thx . Will be included in next release.
