### ISSUE TITLE
Help to start

### ISSUE THREAD

**Issue by Letrakeur** [nicoduj/homebridge-harmony#421]
Hi, 
I am a new user of homebridge.
I set some plugin but I have some problem with Harmony.
I see my activity on Homebridge but not in HomeKit.
Somebody could help me?
Thanks

**Comment by nicoduj** [comment]
Hi,

You have to add in home app your device manually . (Add device, enter code which is presented in the log )

**Comment by Letrakeur** [comment]
Ok Thanks
