### ISSUE TITLE
[FEATURE] - More Accessory types, choosable separately for each device, e.g. "window blinds" for IR-controlled projector screens or window blinds 

### ISSUE THREAD

**Issue by knikkabokka** [nicoduj/homebridge-harmony#422]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I must tell Siri to "turn on" the IR-controlled window blinds or the IR-controlled projector screen.

**Describe the solution you'd like**
It would be nice, if I could say "Hey Siri, window blinds down / up" or "Hey Siri, screen up / down" or "Hey Siri, window blinds 50%" and so on) - That would be possible, I guess, if I could only chose accessory type "window blinds" for the affected devices ...

**Describe alternatives you've considered**
It would be nice, if accessory type could be set freely and separately for any of the devices that the harmony hub offers, to any accessory type HomeKit offers for IR-controlled devices on the market.

(As are: 
Lights (This is already implemented and choosable in HomeKit ✅)
Switches (This is already implemented and choosable in HomeKit ✅)
Outlets (There are IR controlled devices on the market)
Thermostats (I guess not necessary, as I've seen no such IR-controlled devices on the market)
Window Blinds (There are IR controlled devices on the market)
Fans (This is already implemented and choosable in HomeKit ✅)
Air Conditioners (There are IR controlled devices on the market)
Humidifiers (There are IR controlled devices on the market)
Air Purifiers (There are IR controlled devices on the market)
Sensors (I guess not necessary, as I've seen no such IR-controlled devices on the market)
Locks (I guess not necessary, as I've seen no such IR-controlled devices on the market)
Cameras (I guess not necessary, as I've seen no such IR-controlled devices on the market)
Doorbells (I guess not necessary, as I've seen no such IR-controlled devices on the market)
Garage Doors (There are IR controlled devices on the market)
Sprinklers (Don't know if there exists any IR-controlled devices)
Speakers (Don't know if there exists any IR-controlled devices)
Routers (I guess not necessary, as I've seen no such IR-controlled devices on the market)
TVs (There are IR controlled devices on the market)) 

**Additional context**
The ability to chose accessory type would also be handy for IR-controlled air conditioners, humidifiers, garage doors, etc. pp. ...

This would be a great improvement! ;-)

**Comment by nicoduj** [comment]
Hi,
i suggest you use shortcut app to do so, creating a shortcut with homekit accessory should work. The structure of the plugin, which is quite difficult to maintain (would need a full rework but I d'ont have time to do so), would make such a thing not impossible but difficult, since each type of accessory needs custom events handling / properties to set.
