### ISSUE TITLE
[solved] Returns "Error retrieving info from hub .... connect EHOSTUNREACH" but IP is correct

### ISSUE THREAD

**Issue by oscarabilleira** [nicoduj/homebridge-harmony#424]
Hello,

I have installed this plugin  (homebridge-harmony v1.6.3)  in "homebridge" in a new QNPA, I have been using this plugin without problems in "previous QNAP", but this time returns this error "- Error retrieving info from hub....  failed, reason: connect EHOSTUNREACH".
I have checked and the IP is correct and also fixed.

Any Idea about was happening? 

Thanks in advance

![Captura de pantalla 2023-05-10 a las 5 58 22](https://github.com/nicoduj/homebridge-harmony/assets/89222826/f4b78879-cadd-4823-9726-f48615f977db)

This is another "error", but I don't know if it's relevant with this issue, and how to solve it?

![Captura de pantalla 2023-05-10 a las 7 58 41](https://github.com/nicoduj/homebridge-harmony/assets/89222826/91e7ced4-5093-4ae6-bb3f-405259328a09)

Here is the config.
```
{
    "name": "Harmony Hub",
    "hubIP": "192.168.1.102",
    "hubName": "Harmony Hub",
    "DELAY_BEFORE_RETRY_AFTER_NETWORK_LOSS": 60000,


    "HUB_CONNECT_TIMEOUT": 10000,
    "HUB_SEND_TIMEOUT": 30000,
    "publishAllTVAsExternalAccessory": false,
    "TVAccessory": false,
    "sortInput": 0,


    "switchAccessories": true,
    "publishSwitchActivitiesAsIndividualAccessories": false,
    "showCommandsAtStartup": false,
    "otherPlatforms": [
        {
            "TVAccessory": false,
            "sortInput": 0
        }
    ],
    "platform": "HarmonyHubWebSocket"
}
```

**Comment by oscarabilleira** [comment]
Finally It was a problem of HomeBridge instalation... it was not posible to make a ping from the docker to any IP... I reinstall homebridge again and all works like a charm

**Comment by jerome71** [comment]
Had the same issue.
I think I started the server when the Harmony hub was offline (because the router was restarting).
Solved by restarting the server (which is way better than re-installing Homebridge! 😀)

**Comment by nicoduj** [comment]
Sorry for not reading that earlier. Glad it is solved. By the way, you can remove otherplatform section if you have only 1 hub.
