### ISSUE TITLE
Don't see devices in HomeKit App [BUG]

### ISSUE THREAD

**Issue by peterno3** [nicoduj/homebridge-harmony#429]
I'm able to add my Harmony child bridge to my HomeKit app, but the app doesn't seem to see any of the actual Harmony accessories. The accessories do show correctly in the HomeBridge panel, but the app doesn't show them. It used to work perfectly, but it stopped working a few months back. I've tried removing and reinstalling the plugin, switching between a child bridge and the main bridge, and messing with a bunch of the configurations, to no avail. Any other suggestions? Below is my configuration

`{
    "name": "Harmony",
    "hubIP": "192.168.0.106",
    "hubName": "Harmony Hub",
    "DELAY_BEFORE_RETRY_AFTER_NETWORK_LOSS": 60000,
    "HUB_CONNECT_TIMEOUT": 10000,
    "HUB_SEND_TIMEOUT": 30000,
    "TVAccessory": true,
    "sortInput": 0,
    "otherPlatforms": [
        {
            "TVAccessory": false,
            "sortInput": 0
        }
    ],
    "platform": "HarmonyHubWebSocket",
    "_bridge": {
        "username": "0E:2D:9D:48:25:D3",
        "port": 54566
    }
}`

**Comment by peterno3** [comment]
As a note, on bridge startup i do see the message "[04/07/2023, 12:01:41] Harmony-TV A2D1 is running on port 44785.
[04/07/2023, 12:01:41] Please add [Harmony-TV A2D1] manually in Home app. Setup Code: 327-21-234", but nothing appears in the HomeKit app when i try to add it

**Comment by AxelDoerr** [comment]
I have exactly the same issue. The TV accessories shows up in home bridge just fine, so i tried to add the TV accessory with the setup code in the home app. Unfortunately i can't enter this code in the described form (mine is 731-68-566). When i try to enter the code in the home app it automatically gets changed to 7316-8566 by the home app and nothing happens.

**Comment by nicoduj** [comment]
You have 2 platforms . The first one is a tv device. The second one is declared with the switches. I suggest you remove the other platforms entry, it should be better .

**Comment by AxelDoerr** [comment]
I tried that already but the same issue. I can‘t enter the code in the home app in the Schema 731-68-566. I guess that is the issue as the accessory appears in the bridge just fine.

**Comment by nicoduj** [comment]
Use this conf : { "name": "Harmony", "hubIP": "192.168.0.106", "hubName": "Harmony Hub", "DELAY_BEFORE_RETRY_AFTER_NETWORK_LOSS": 60000, "HUB_CONNECT_TIMEOUT": 10000, "HUB_SEND_TIMEOUT": 30000, "TVAccessory": true, "sortInput": 0, "platform": "HarmonyHubWebSocket", "_bridge": { "username": "0E:2D:9D:48:25:D3", "port": 54566 } }

And in home app do the following : 
- add new accessory (+ icon top left)
- more options (link on the top of the camera window)
- it should find the bridge if not already added , and you wille have to enter the code

If it does not appear, you have to clear the accessory from the cache in homebridge configuration.
