### ISSUE TITLE
Guide for using Siri with this plugin, especially with switching Activities?

### ISSUE THREAD

**Issue by chrismanderson** [nicoduj/homebridge-harmony#430]
Hello - I looked for documentation and through the other issues but didn't find a definitive list - how can I use Siri to control Activities set up with this plugin?

I have the plugin configured to expose Activities as a TV Accessory in Homekit. Say the hub is named 'Harmony' - I see a TV device named Harmony in my Home app, with the activities listed as input.

I can successfully say 'Turn on Harmony' and 'Turn off Harmony'. 

I'm unable though to switch inputs via Siri no matter what command I try to give. Say I have 'Play Playstation' and 'Watch Apple TV' - no combination of 'Play Playstation on Harmony' or 'Play Playstation on Harmony TV' will work.

I'm assuming I'm missing something here, so any guidance would be appreciated - can turn that around into a PR to improve the documentation as well.

**Comment by PrplHaz4** [comment]
I've created homeassistant scenes for the activities I want to do - then trigger the scenes (which are exposed by the hass app) via the Apple Shortcuts app.  It's not elegant, and requires a fiddling to get right but it's pretty reliable.  I would love to see a more straightforward solution.

**Comment by nicoduj** [comment]
Hi, I think the easy way is through shortcut app . I never found any reliable direct siri commands for input switching, volume control .... Only on / off works also for me "natively".
