### ISSUE TITLE
[BUG] EHOSTUNREACH error

### ISSUE THREAD

**Issue by manicmouse86** [nicoduj/homebridge-harmony#431]
**Describe the bug**
Cannot connect to Harmony Hub - repeatedly gives message:

[30/09/2023, 19:42:07] [HarmonyHub] (HarmonyHub)INFO - Loading activities...
[30/09/2023, 19:42:10] [HarmonyHub] (HarmonyHub)Error - Error retrieving info from hub : request to http://192.168.68.250:8088/ failed, reason: connect EHOSTUNREACH 192.168.68.250:8088-(79)

Raspbian GNU/Linux Bullseye (11)
 Homebridge v1.6.1 
Node v 18.16.0
npm 9.5.1

**Logs**
Your log in debug mode (-D option)

**Config**
{
    "name": "Harmony Hub",
    "hubIP": "192.168.68.250",
    "hubName": "HarmonyHub",
    "DELAY_BEFORE_RETRY_AFTER_NETWORK_LOSS": 60000,
    "HUB_CONNECT_TIMEOUT": 10000,
    "HUB_SEND_TIMEOUT": 30000,
    "TVAccessory": true,
    "sortInput": 0,
    "otherPlatforms": [
        {
            "TVAccessory": false,
            "sortInput": 0
        }
    ],
    "platform": "HarmonyHubWebSocket",
    "_bridge": {
        "username": "0E:36:98:6A:53:6B",
        "port": 57345
    }
}

**Additional context**

**Comment by nicoduj** [comment]
Hi, it seems your homebridge device can't reach the network / your hub . Double check that your hub has a static ip, that is reachable from your homebridge device.
