### ISSUE TITLE
Homebridge not showing accessories from additional Hub

### ISSUE THREAD

**Issue by TheJewce72** [nicoduj/homebridge-harmony#440]
I added a second hub per the instructions, but nothing new shows up in Accessories. Here is the JSON:

{
    "name": "Master Bedroom",
    "hubIP": "192.168.1.31",
    "hubName": "Master Bedroom",
    "DELAY_BEFORE_RETRY_AFTER_NETWORK_LOSS": 60000,
    "HUB_CONNECT_TIMEOUT": 10000,
    "HUB_SEND_TIMEOUT": 30000,
    "TVAccessory": true,
    "sortInput": 0,
    "otherPlatforms": [
        {
            "name": "Family Room",
            "hubIP": "192.168.1.47",
            "hubName": "Family Room",
            "TVAccessory": false,
            "sortInput": 0
        }
    ],
    "platform": "HarmonyHubWebSocket"
}

**Comment by nicoduj** [comment]
You have to add it manualy from Home app, as a new accessory. It won't be added automatically.
