### ISSUE TITLE
[BUG] Update version displaying incorrectly under Homebridge UI

### ISSUE THREAD

**Issue by AntlerDM** [nicoduj/homebridge-harmony#441]
**Describe the bug**
Whenever there is an update to the plugin, the plugin (or Hombridge UI) displays the incorrect version. It usually looks like a downgrade.

**To Reproduce**
Select the Plugin Update button when an update is available.

**Expected behavior**
Version information should display the current version and the available update version.

**Screenshots**
![Screenshot 2024-06-29 at 10 49 36 AM](https://github.com/nicoduj/homebridge-harmony/assets/29990136/4c358a8c-019e-4b10-8c44-6173ae0f7a31)

**Logs**
[6/29/2024, 10:49:45 AM] [Homebridge UI] Running Command: sudo -E -n npm install -g homebridge-denon-tv@4.13.20
NOTE: The version information in the log is completely different than either of the versions displayed in the UI (see screenshot).

**Config**
I can post this if it is relevant.

**Additional context**
This has been happening since version 4.12.x (possibly earlier).

**Comment by nicoduj** [comment]
I think this is the wrong plugin, you are talking about https://github.com/grzegorz914/homebridge-denon-tv
