### ISSUE TITLE
tv mode - automation  goes to the main activity even if another is set up

### ISSUE THREAD

**Issue by nicoduj** [nicoduj/homebridge-harmony#45]
@nicoduj I did that but when I test the automation it goes to the main activity I setup in the config file

_Originally posted by @krazyflipj in https://github.com/nicoduj/homebridge-harmony/issues/30#issuecomment-459858476_

**Comment by krazyflipj** [comment]
This is still an issue. Set "Listen to music" input in Im Home automation and it went to main activity

**Comment by krazyflipj** [comment]
It actually worked today. Will do further testing

**Comment by nicoduj** [comment]
I had the problem once today, seems that automation sent 0 to the input value, and so I default to main activity . Might be related to input sometimes not shown after homebridge startup / maybe a ios 12.2 bug not sure for now. Will keep an eye on this.
