### ISSUE TITLE
Add an option to expose devices as individual tv platform accessories

### ISSUE THREAD

**Issue by nicoduj** [nicoduj/homebridge-harmony#53]
For tv platform mode - equivalent to #15 
On/off, keys and volume if available
The goal of this fetaure would be to match all device individualy to a remote, with inputs if avaliable and other commands that could be mapped the same way it is for activities, but at a device level

You can vote if you want it :)

**Comment by nicoduj** [comment]
put on hold since TV platform mode doesn't seems to support multiple devices exposed from same huh, which would not be so great for this use case.

**Comment by nicoduj** [comment]
Limitation of ios prevents this to be done

**Comment by nicoduj** [comment]
On the road again thanks to @KhaosT https://github.com/nfarina/homebridge/issues/2184

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Krocko** [comment]
I would like this feature too!
Is it possible to have the TV as TVplatform with the HDMI and AV inputs? Like it is now with the activities?

**Comment by nicoduj** [comment]
> I would like this feature too!
> Is it possible to have the TV as TVplatform with the HDMI and AV inputs? Like it is now with the activities?

that would be the goal of this new feature indeed.It involves a bit of work however, but will put it in the pipeline :)

**Comment by nicoduj** [comment]
Ok, i begun to work on this but it involves more work than I expected . There is also the problem of device state which will not be easy to handle since I have to cross some manual state change triggers and activities triggered that involves devices (the hub does not give states on devices themselves). Moreover , on / off function are not always separate so this could lead to some out of sync issues if triggered outside HomeKit and harmony ... Need to think a bit longer also about the plugin structure to do this the right way ... especially since I am not satisfied yet about the structure :) 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nicoduj** [comment]
After some testing, the lack of device state makes this unreliable . So I won't consider this anymore.
