### ISSUE TITLE
Multiple hubs not populating Apple TV Control Centre menu

### ISSUE THREAD

**Issue by durosity** [nicoduj/homebridge-harmony#54]
Using the new TV Mode I've added two hubs (Lounge and Master Bedroom) to my config and they both show up in Home correctly and work flawlessly pretty much.  But only one is showing up when I go into the control centre option for AppleTV.  If I remove the one that is showing from the config.json the other one will replace it, but if I add it back in again it won't re-appear.  I'm currently running 10.15.1 of nodeJS, Homebridge 0.4.46, and 0.2.7 of this plugin.  I've got this setup as it's own separate Homebridge server so I've tried removing the bridge from Home, purging the cached and accessories folder and setting it up from scratch a few times.  Any ideas?

(also side question.. does this mode support tv volume yet?  If so where do I find it?)

**Comment by nicoduj** [comment]
Hi, I will check why but since I have only one hub might be difficult to reproduce ! Did you have different names in the config file ?

Concerning volume it works using physical buttons of your iPhone / iPad while the remote from control center is ipen

**Comment by durosity** [comment]
Yep different names, one called Master Bedroom TV and the other, surprising, called Lounge TV.  Now I don’t know if this is related or not but volume controls don’t work for either.  I’ll try stripping out one tonight and see if it works when only one configuration is specified.  

Of course I suppose it could be a bug in iOS 12.2..

**Comment by nicoduj** [comment]
Could also be a bug by my part, but sound control works here (with one hub) and have reports of it working by other one. Feel free to post your config / log so that I can take a look

**Comment by sefki21** [comment]
same behaviour with my 2 hubs

**Comment by nicoduj** [comment]
I can reproduce by adding twice my hub, but really don't see what's happening there. @nfarina / @KhaosT, maybe you have an idea on this ?

**Comment by durosity** [comment]
Well just tried it again and volume is working so must’ve been a red herring!

Config file as requested.  Nothing exciting.. pretty generic actually:

{
    "bridge": {
        "name": "Homebridge",
        "username": "DD:22:3D:E3:CE:30",
        "port": 51999,
        "pin": "031-45-154"
    },
    
    "description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",


	"platforms": [
		 {
   			  "platform": "HarmonyHubWebSocket",
  			  "name": "Lounge TV",
  			  "hubIP": "192.168.1.70",
 			  "TVPlatformMode" : true,
  			  "mainActivity" : "Watch Apple TV"
  		  },
		  {
   			 "platform": "HarmonyHubWebSocket",
  			  "name": "Master Bedroom TV",
  			  "hubIP": "192.168.1.80",
 			  "TVPlatformMode" : true,
  			  "mainActivity" : "Watch Apple TV"
		  },
		  {
    	 	 "platform": "config",
    	  	 "name": "Config",
  		     "port": 8082,
  	         "sudo": false
 	     }
	]
}


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nicoduj** [comment]
I thnik there is an issue either with ios 12.2 and / or homebridge / hap server on this. the 2 TV platform are visible in home app, but not in the remote control from control center. If I have Two homebridge instance, it is fine. But with one homebridge / 2 platforms, it is not. Maybe because my platform is not dynamic but really don't know what is happening behind the scene there.

**Comment by durosity** [comment]
theres another HB plug-in that uses the tvmode functionality but works by sending device commands rather than activities (activists being the more sensible option IMO) so I might try playing with that just to see if I get the same behaviour.

**Comment by nicoduj** [comment]
@durosity Did you have any chance to make this work with another plugin to help me understand ? I Tried different things with no luck so far ...

**Comment by durosity** [comment]
Not yet, I’d planned to have a look at the weekend but life had other plans.  I’ll try to do it in the next couple of days and see what behaviour I get.  

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nicoduj** [comment]
Seems that Other plugins are affected might be linked to beta status : 
https://github.com/KhaosT/HAP-NodeJS/issues/641

**Comment by durosity** [comment]
Aha perfect timing, I was about to start looking into that.  Not a surprise, my gut feeling it was iOS rather than your implementation.  I’ll keep this topic updated as further iOS betas appear

**Comment by krazyflipj** [comment]
Seems like you can only have 2 remotes at one time. Currently, I have apple tv, Harmony, and Roku alpha plugin installed but only Harmony and apple tv remotes are listed. If I remove the harmony from my config, the Roku and apple tv show.

**Comment by nicoduj** [comment]
Hi, I think you can only have One remote per homebridge hub in fact. If I run 2 homebridge with each one an harmony, I will have them both + my apple TV.

I opened a bug report and a question on apple dev forum, but I think it is beacuse of the way the remote app discovers the accessory through bonjour prootcol and homebreidge instance exposure.

**Comment by durosity** [comment]
Ah that does seem plausible.  I’ve not tried it with multiple instances of homebridge yet but certainly worth trying.  FYI no change in behaviour in beta 3.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nicoduj** [comment]
For information. I just had a request of syslog on this issue on the bug report, will keep you updated 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nicoduj** [comment]
Seems to still be a limitation in stable release . See workaround here : https://github.com/bschlenk/homebridge-roku/issues/65

**Comment by nicoduj** [comment]
In the road again thanks to @KhaosT https://github.com/nfarina/homebridge/issues/2184

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by durosity** [comment]
Oh fab, I was about to go setup a VM to work around it but stuff it I’ll wait for this :)

**Comment by nicoduj** [comment]
Needs dynamic platform, moved to Milestone 1.0.0

**Comment by nicoduj** [comment]
for a quick demo https://twitter.com/dujnic/status/1110644949027041282
