### ISSUE TITLE
Can't move accessories from two hubs into two different rooms

### ISSUE THREAD

**Issue by DavidJHiebert** [nicoduj/homebridge-harmony#6]
I have two harmony hubs which i use in two different rooms. However, all the activities appear in one room on my iPhone. When I move one activity from one room, it moves them all leaving no Harmony activities in the original room. Any ideas how to fix?

Thanks in advance!

- David

**Comment by nicoduj** [comment]
Did you check the name you set ? I lll try to make some changes on the serial number of the accessory / platform properties and will keep you informed .

**Comment by nicoduj** [comment]
Hi again, I checked and by declaring a config like the following, I can have on platform (with all activities) in one room and another one in another. 

    "platforms": [
        {
            "platform": "HarmonyHubWebSocket",
            "name": "Nico HarmonyHub Salon DEV",
            "hubIP": "192.168.1.42",
            "showTurnOffActivity" : true,
            "TurnOffActivityName" : "HC Off",
            "DEVMODE" : true

        },
        {
            "platform": "HarmonyHubWebSocket",
            "name": "Nico HarmonyHub Salon DEV 2",
            "hubIP": "192.168.1.42",
            "showTurnOffActivity" : true,
            "TurnOffActivityName" : "HC Off",
            "DEVMODE" : true

        }
    ]

**Comment by DavidJHiebert** [comment]
That seems to have fixed it, which is wild because my original set up
wasn't that different from yours. The new working platform settings are is
as follows:

"platforms": [

    {

        "platform": "HarmonyHub",

        "name": "BedRoomHarmonyHub",

        "hubIP": "192.168.1.77",

        "showTurnOffActivity" : true,

        "TurnOffActivityName" : "HC Off",

        "DEVMODE" : true


    },

    {

        "platform": "HarmonyHub",

        "name": "LivingRoomHarmonyHub",

        "hubIP": "192.168.1.83",

        "showTurnOffActivity" : true,

        "TurnOffActivityName" : "HC Off",

        "DEVMODE" : true

    }

]


My original configuration that wasn't working as follows:


"platforms": [

    {

        "platform": "HarmonyHub",

        "name": "BedRoomHarmonyHub",

        "hubIP": "192.168.1.77"

    },

    {

        "platform": "HarmonyHub",

        "name": "LivingRoomHarmonyHub",

        "hubIP": "192.168.1.83"

    }


]

FYI, I am not running the latest Harmony Hub firmware--I'm on 4.15.206 on
my living room hub and I'm too lazy to check my bedroom hub, but its
probably that version or older.

Thanks for your help! I will play around with it and let you know how I
make out!

- David

**Comment by nicoduj** [comment]
Hi, be aware that devmode will rename your activities , prefixing them with « DEV ». I had this hidden switch to run a dev homebridge server for debugging purpose and don’t mix my activities with my « production » server. You should  set it to false if you want to have the real name of your activities (even if you can rename them in home app)

**Comment by DavidJHiebert** [comment]
Thanks for the advice! I'll do that!

- David
