### ISSUE TITLE
Error code 128 Cant install plug in

### ISSUE THREAD

**Issue by felkahlout** [nicoduj/homebridge-harmony#60]
npm ERR! code 128
npm ERR! Command failed: /usr/bin/git clone --depth=1 -q -b master git://github.com/nicoduj/harmony-websocket.git /root/.npm/_cacache/tmp/git-clone-5236a626
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-5236a626': Permission denied
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-02-12T18_56_29_734Z-debug.log

**Comment by nicoduj** [comment]
Hi,

It is a git issue . On latest version I had to reference a fork of a lib. I made a pull request but still not accepted f I’m the maintainer.

You can try this meanwhile : https://gist.github.com/taoyuan/bfa3ff87e4b5611b5cbe

**Comment by felkahlout** [comment]
https://gist.github.com/taoyuan/bfa3ff87e4b5611b5cbe did not work as well :(

**Comment by nicoduj** [comment]
And with something like : sudo npm install -g --unsafe-perm homebridge-harmony ?

**Comment by Krocko** [comment]
`sudo chown -R $USER /usr/local && npm install -g homebridge-harmony`

**Comment by rogatec** [comment]
For me this worked:

1. `sudo  /usr/bin/git clone --depth=1 -q -b master git://github.com/nicoduj/harmony-websocket.git /home/homebridge/.npm/_cacache/tmp/git-clone-342321d7`

2. `cd /usr/lib/node_modules`

3. `sudo -E -n npm --no-update-notifier install --unsafe-perm homebridge-harmony@latest`

**Comment by felkahlout** [comment]
> For me this worked:
> 
> 1. `sudo  /usr/bin/git clone --depth=1 -q -b master git://github.com/nicoduj/harmony-websocket.git /home/homebridge/.npm/_cacache/tmp/git-clone-342321d7`
> 2. `cd /usr/lib/node_modules`
> 3. `sudo -E -n npm --no-update-notifier install --unsafe-perm homebridge-harmony@latest`

Thanks a lot it worked for me too

**Comment by roberkane212** [comment]
none of this sis working for me at all

**Comment by nicoduj** [comment]
Back to official dependency in 0.3.91 so it should solve this issue
