### ISSUE TITLE
Error retrieving info from hub

### ISSUE THREAD

**Issue by mrdavidsilva** [nicoduj/homebridge-harmony#61]
Getting this error after about 24 hours of up time.  A restart solves the issue, but then comes back.

**Comment by nicoduj** [comment]
Hi,

Can I ask which version you are using / what config you have ?
Can you post a complete log (in debug) ? 

It is strange since this error is intended to be set only at launch of homebridge / intial config of accessories

**Comment by nicoduj** [comment]
Hi,

I am closing this since I didn't see it happen in latest version. Feel free to open again and give me a bit more of information if it happens again !
