### ISSUE TITLE
error when installation

### ISSUE THREAD

**Issue by forte17hl** [nicoduj/homebridge-harmony#62]
got an error while to try install it .
<img width="498" alt="bildschirmfoto 2019-02-14 um 21 38 14" src="https://user-images.githubusercontent.com/47644802/52816124-df412580-30a0-11e9-9d3a-86a215c7f3f6.png">

**Comment by nicoduj** [comment]
Hi, some possible solution there to wait for the integration of my  pull request on a lib : 
https://github.com/nicoduj/homebridge-harmony/issues/60

**Comment by forte17hl** [comment]
> Hi, some possible solution there to wait for the integration of my pull request on a lib :
> #60

dont work for me
<img width="489" alt="bildschirmfoto 2019-02-14 um 22 02 14" src="https://user-images.githubusercontent.com/47644802/52817487-42808700-30a4-11e9-8e5b-159e290aaf8d.png">

**Comment by ryanchucks** [comment]
Try:

sudo sudo npm install -g --unsafe-perm homebridge-harmony

**Comment by nicoduj** [comment]
Back to official dependency in 0.3.91 so it should solve this issue
