### ISSUE TITLE
[Enhacement] Macro - Command Sequence of AccessoriesSwitch

### ISSUE THREAD

**Issue by DJay-X** [nicoduj/homebridge-harmony#63]
@nicoduj The "devicesToPublishAsAccessoriesSwitch" works great. Thanks for this. Although, finding the possible command can be tricky in debug mode (-D) hub config output . ;) 

Is there any chance to have like a Macro feature to use some of the devicesToPublishAsAccessoriesSwitch to get a sequence of commands, like "DirectionDown, DirectionLeft, DirectionLeft, DirectionDown, DirectionLeft, Enter".
To publish one Switch with the sequence behind?
Thanks for maybe considering this enhancement and for your great ongoing work and sharing with us.
👍

**Comment by nicoduj** [comment]
Hi, it is possible but I fear that it might be more complicated especially if we need to handle delay between commands ... definitely for power users but will think of it :) could you tell me more on the use case ?

Concerning the command list yep I was thinking of some other way to display them :)

**Comment by DJay-X** [comment]
Thanks. The use case would be for example to switch between Audio Language on Netflix.
Watching some Series and Movies in english, other in german. So there is always the manual effort like "DirectionDown, DirectionLeft, DirectionLeft, DirectionDown, DirectionLeft, Enter". for German. Another sequence would be for english.
Could be something to control in an automated sequence via Siri a little easier. :)
Thanks again.

**Comment by nicoduj** [comment]
Ok I see . Will check after restoring with latest firmware revision !

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nicoduj** [comment]
@DJay-X : Let me know if latest version suits your needs !

**Comment by DJay-X** [comment]
Wahoo... Sequences of commands. :) 👍 
I appreciate your work a lot and I hope I'm not the only one you did this for. ;) You are incredibly fast. 

Not sure what it is, maybe the delay not long enough, but sometimes Apple TV misses a command and of course is then a completely different menu. 

For example
```
"devicesToPublishAsAccessoriesSwitch": [
                "Apple TV 4K;Menu",
                "Apple TV 4K;DirectionDown;DirectionRight;DirectionRight;DirectionDown;DirectionLeft;Select",
                "Apple TV 4K;DirectionDown;DirectionRight;DirectionRight;DirectionDown;DirectionLeft;DirectionDown,Select"
            ],
```

The first sequence is Audio German, the second sequence is Audio English.
It works sometimes. But sometimes it misses one of the DirectionRight commands and ends in the Subtitle Menu not in the Audio Menu. 
Could it be the delay of 250ms?

**Comment by nicoduj** [comment]
Yes, definitely the delay can be an issue . Will have to fine tune this :)

**Comment by DJay-X** [comment]
350ms didn't change it for me. :( But maybe we should wait until other people trying to use the sequence feature and point to something. My case shouldn't be the only case. ;) 
Because the longer the sequence, the higher the chance for a problem with this method I think.
But anyway, I think the sequence feature can be helpful.

**Comment by nicoduj** [comment]
Interesting ... I will release a version where you can set the timing between each command in the sequence and will test yours by the way (I have only tested with ir controls, Apple TV is Bluetooth so maybe it needs some other tricks to work !) 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Nastras** [comment]
Hello @nicoduj, 
it is not possible to display the sequences that can be programmed in the Harmony software as switches in HomeKit. There is also the possibility to install delays and many more. 

If it is possible then I think it would be the better and more extensive option to include sequences in HomeKit than to set this up in the plugin.

https://support.myharmony.com/en-us/creating-button-sequences

**Comment by krazyflipj** [comment]
Interesting. Here is something similar if you want to have certain commands open certain apps https://www.reddit.com/r/amazonecho/comments/5admcw/launching_netflix_appletv_v4_harmony/

**Comment by nicoduj** [comment]
Hi, it is interesting indeed . Will check if it is available for all harmony (and not only the one with a touch screen). I also have to check if the sequence is handle by the hub or by the client app that sends them ! 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by krazyflipj** [comment]
I should add that link I provided is for apple tv

**Comment by nicoduj** [comment]
>I should add that link I provided is for apple tv

@krazyflipj yep, I saw that . Will check that 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nicoduj** [comment]
So I pushed a new version where you can specify a delay between actions. Seems to work for the sample @DJay-X gave to me with this (might try lower)  : "Apple TV Gen 4;DirectionDown|1500;DirectionRight|1500;DirectionRight|1500;DirectionDown|1500;DirectionLeft|1500;Select"

I will try to configure sequences in harmony and see if it can be also handle, new feature for that.

**Comment by DJay-X** [comment]
Now, works like charm. 👍 I love this feature. And to me its an easy and convenient way to quickly setup or adjust a sequence to run. Thanks for this @nicoduj 
By the way, did I miss a Button on the main page here for PayPal spending a beer or coffee? 😉

**Comment by nicoduj** [comment]
Nice to hear it works . I accept the virtual beer :) will think of something but maybe a bit different than a paypal button :)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nicoduj** [comment]
paypal button has been added :)
