### ISSUE TITLE
Possibility to replace Hub with no need to re-configure everything? (UUID in cachedAceessories)

### ISSUE THREAD

**Issue by mensa84** [nicoduj/homebridge-harmony#65]
Hello,

my Harmony Hub in the living room got defect and I want to go to replace it with a new one. Using the MyHarmony software it will be easy to restore the Logitech Harmony configuration on the hub.

But for the homebridge-harmony plugin the new hub will show up with a new UUID.

Which steps would be necessary to make homebridge-harmony plugin think, that the new hub is the same one as the old and so that I don't have to reconfigure everything in Homekit?

Would following be enough?
- stop homebridge
- replace old UUId in file "cachedAccessories" with UUID of the new Hub
- start homebridge

I currently don't have received the new hub, therefore I can't test it.
I would thank you very much, if you could help me!

**Comment by nicoduj** [comment]
Hi, this plugin is a static platform with no cached accessory in homebridge itself.

From what I know, the uuid of the devices is built by a combination of homebridge uuid, and name of the service which is itself constructed from the name of the hub/ ip / name of the activity / inputs  (and devices). 

Everything is built at startup so if you replace with the exact same config the hub it should be ok , but never really tried so no guarantee :) 

This 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
