### ISSUE TITLE
Tv mode not working anymore since 0.4.2

### ISSUE THREAD

**Issue by nicoduj** [nicoduj/homebridge-harmony#66]
Have to fix error in latest update

**Comment by nicoduj** [comment]
Updated in source on github will release tomorrow

**Comment by Krocko** [comment]
After update to iOS 12.2 Beta 3 there are only 3 buttons in the platform mode (with beta 2 there are 4 buttons) and the button in the middle don't work anymore.

![img_3345](https://user-images.githubusercontent.com/29394115/53193014-33538900-3610-11e9-8449-319a211b32b4.png)
