### ISSUE TITLE
Error Unexpected token

### ISSUE THREAD

**Issue by suxus-zz** [nicoduj/homebridge-harmony#70]
Hello, my Harmony Hub has Firmware 4.15.250 and today i want install the new 0.4.4 Version, but after install the plugin does not start my homebridge anymore and I have the following error in the log.

Feb 21 17:18:14 raspberrypi homebridge[616]: [2019-2-21 17:18:14] ERROR LOADING PLUGIN homebridge-harmony:
Feb 21 17:18:14 raspberrypi homebridge[616]: [2019-2-21 17:18:14] /usr/local/lib/node_modules/homebridge-harmony/harmonyBase.js:494
Feb 21 17:18:14 raspberrypi homebridge[616]: async function processCommands(hb, platform, commands) {
Feb 21 17:18:14 raspberrypi homebridge[616]:       ^^^^^^^^
Feb 21 17:18:14 raspberrypi homebridge[616]: SyntaxError: Unexpected token function
Feb 21 17:18:14 raspberrypi homebridge[616]:     at createScript (vm.js:56:10)
Feb 21 17:18:14 raspberrypi homebridge[616]:     at Object.runInThisContext (vm.js:97:10)
Feb 21 17:18:14 raspberrypi homebridge[616]:     at Module._compile (module.js:542:28)
Feb 21 17:18:14 raspberrypi homebridge[616]:     at Object.Module._extensions..js (module.js:579:10)
Feb 21 17:18:14 raspberrypi homebridge[616]:     at Module.load (module.js:487:32)
Feb 21 17:18:14 raspberrypi homebridge[616]:     at tryModuleLoad (module.js:446:12)
Feb 21 17:18:14 raspberrypi homebridge[616]:     at Function.Module._load (module.js:438:3)
Feb 21 17:18:14 raspberrypi homebridge[616]:     at Module.require (module.js:497:17)
Feb 21 17:18:14 raspberrypi homebridge[616]:     at require (internal/module.js:20:19)
Feb 21 17:18:14 raspberrypi homebridge[616]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-harmony/harmonyAsSwitches.js:2:45)
...

When i go back to the 0.4.1 Version, then it's okay and my homebridge works.

Have you a idea what's the problem?

regards

That's my Config

{
   "platform": "HarmonyHubWebSocket",
   "name": "HarmonyHub",
   "hubIP": "192.168.98.20",
   "showTurnOffActivity": true,
   "refreshTimer": 30,
   "publishActivitiesAsIndividualAccessories": false,
   "skipedIfSameStateActivities": [
      "PowerOff",
      "TV schauen",
      "Apple TV"
   ]
},

node --version
v6.11.0

**Comment by nicoduj** [comment]
I think you should update your node version. I introduced a sync functions a bit so node 7.6 at least is needed I think. Will update dependencies if the package in the next release .

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by suxus-zz** [comment]
Thank you, then i will look how can update my node version and hope then it's okay.
