### ISSUE TITLE
After update to iOS 12.2 Beta 3 button in the middle don't work anymore.

### ISSUE THREAD

**Issue by nicoduj** [nicoduj/homebridge-harmony#71]
After update to iOS 12.2 Beta 3 there are only 3 buttons in the platform mode (with beta 2 there are 4 buttons) and the button in the middle don't work anymore.

![img_3345](https://user-images.githubusercontent.com/29394115/53193014-33538900-3610-11e9-8449-319a211b32b4.png)

_Originally posted by @Krocko in https://github.com/nicoduj/homebridge-harmony/issues/66#issuecomment-466115352_

**Comment by nicoduj** [comment]
And volume seems to work when he wants too :)

**Comment by gitgayhub** [comment]
Yes I can confirm that. Back button doesn't work on iOS 12.2 beta 3, and the "i"" button which stands for "info" I think sends an exit command.

What I need is a "Menu" button to full control my TV

**Comment by nicoduj** [comment]
>Yes I can confirm that. Back button doesn't work on iOS 12.2 beta 3, and the "i"" button which stands for "info" I think sends an exit command. ...

@gitgayhub that was the behavior in beta 1/2  but while revamping the remote app they removed a button ([twitter post](https://twitter.com/dujnic/status/1091094270814109696?s=21) and messed up a bit the reference. Will check when beta 3 is up 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nicoduj** [comment]
Seems to be fixed in beta4 !
