### ISSUE TITLE
Volume control 

### ISSUE THREAD

**Issue by overflywingo** [nicoduj/homebridge-harmony#72]
> Buttons on the remote app and volume controls will be binded to the one defined in the activity (if so). VOLUME IS BIND TO PHYSICAL BUTTONS WHEN REMOTE FROM CONTROL CENTER IS SHOWN

Hello, not sure to understand this sentence ! Sorry.  
I'm using the TV mode and would like to be able also to control the volume up/down from the home app. Is it possible  and if so, how ?   Tks

**Comment by nicoduj** [comment]
Hi. In the tv mode the volume control is accessible through the physical buttons of your  IPhone / iPad when and only when the remote app is displayed (and not the home app). The remote app can be launched through control center (see screen below) . However it seems that it doesn’t always work in latest beta (was fine in beta 2, in beta 3 they broke some things while revamping the remote app) . 
![GitHawk Upload by nicoduj](https://i.imgur.com/NKHWQa9.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nicoduj** [comment]
In beta 3 of ios 12.2, If you switch the widget to your AppleTV and then back to the _Television_ service, the volume works.

**Comment by gitgayhub** [comment]
> In beta 3 of ios 12.2, If you switch the widget to your AppleTV and then back to the _Television_ service, the volume works.

Can't get it work on my iOS 12.2 beta 3, physical button can only control volume of the iPhone itself

**Comment by nicoduj** [comment]
Hi, it is buggy but I managed to make it works on my iPad if :
- I launch the remote app in control center
- I select the harmony device on the top
- I select back the Apple TV
- I select harmony again and then it is ok

It is a bug in beta 3 we’ll see in beta 4 :)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by gitgayhub** [comment]
> Hi, it is buggy but I managed to make it works on my iPad if :
> 
> * I launch the remote app in control center
> * I select the harmony device on the top
> * I select back the Apple TV
> * I select harmony again and then it is ok
> 
> It is a bug in beta 3 we’ll see in beta 4 :)
> 
> Sent with [GitHawk](http://githawk.com)

I don't have an Apple TV, there's only the Hamony device for me to select, so I still can't get the volume control working. I will try to simulate two harmony tv devices to try again

**Comment by gitgayhub** [comment]
> I don't have an Apple TV, there's only the Hamony device for me to select, so I still can't get the volume control working. I will try to simulate two harmony tv devices to try again

I managed to add 2 harmony tv devices to homebridge, both shown and working in the Home App, but only the 1st one can be shown in the remote control. Don't know if it is a bug or just that I can't set two simulated  tv

**Comment by nicoduj** [comment]
>> I don't have an Apple TV, there's only the Hamony device for me to select, so I still can't get the volume control working. I will try to simulate two harmony tv devices to try again ...

@gitgayhub it is a limitation right now if remote app also , see #54

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by gitgayhub** [comment]
> it is a limitation right now if remote app also , see #54

Thanks, I saw your reply in that issue and run two homebridge instance, now the second harmony TV can be shown on my iPhone's remote screen, and I can control the volume using the method you mentioned above

thanks for helping

**Comment by Midifreakz** [comment]
Hi @nicoduj this workaround also seems to work on my iPhone XR.

I would like to say to you you did an amazing job to implement this functionality at such short notice! 
I will try to give you regular updates on my experiences with this plugin. keep up the good work!

**Comment by nicoduj** [comment]
>Hi @nicoduj this workaround also seems to work on my iPhone XR. ...

@Midifreakz thank you :) 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nicoduj** [comment]
Seems to be fixed in beta4 !
