### ISSUE TITLE
Platform plugin blocks the whole homebridge at start if no connection to the hub

### ISSUE THREAD

**Issue by gutaker** [nicoduj/homebridge-harmony#73]
Hi,

today for some reason the homebridge stopped working while I was out of home. A friend of mine, living in the same area, told me we're having a power blockout. When got back home, I checked the logs and found that my Harmony Hub Ultimate was having trouble to go back online (it's pretty far from wifi router), then I realized that Your plugin is trying to connect to the hub over and over again, and is blocking the homebridge from starting.

Wouldn't it be great to use some promise or something like that to let other platforms and accessories start, and in the end when the hub finally gets online, connect it?

I have Philips Hub bridge with IKEA tradfri bulbs paired, so it's more important for me to have homebridge-hue working than homebridge-harmony.

Please see the closed homebridge issue [https://github.com/nfarina/homebridge/issues/948](url)

**Comment by rcbooth14** [comment]
You're more than welcome to use another plugin.

**Comment by nicoduj** [comment]
@rcbooth14 why being so rude ?

**Comment by nicoduj** [comment]
@gutaker I understand, I will try to handle this more cleanly ! The connection error was happening at the start of the homebridge instance while discovering device that’s it ?

**Comment by gutaker** [comment]
Hi, I didn't meant to be rude. The situation has been described what is more important for me. I do really love the @nicoduj plugin and that's why I'm posting an issue. If it were worth nothing to me I would obviously switch to another one @rcbooth14 

Keep up the magnificent work @nicoduj !

**Comment by gutaker** [comment]
I've just found a nice workaround: following the steps here [https://www.reddit.com/r/homebridge/comments/759ip9/multiple_instances_of_homebridge_on_rpi/do4k4rk](url), I just ran another instance of `homebridge` for your plugin only.

Everything works independently now!

**Comment by nicoduj** [comment]
>Hi, I didn't meant to be rude. 

@gutaker that was not for you, I appreciate the feedback of course . That was for @rcbooth14 , I don’t really know why he answered to you this way, I make my best effort to answer all issues there as far as I can !

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nicoduj** [comment]
>I've just found a nice workaround.

@gutaker  nice workaround I should have suggest that at first ;) But I will work on your issue since it is definitely one !

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nicoduj** [comment]
For the moment, I made a change where if the plugin can't connect to the hub at homebridge start, it will throw an error and stop homebridge for starting. I Think it is better than letting it check and check again, and blocking the whole platform.

Still planned to be working on moving to a dynamic platform to handle this better with cached accessories (but I need to find a way to remove them also if activities are changed an d so on, so it is a bit more work to do)

**Comment by nicoduj** [comment]
Hi everyone.

I have a branch for a dynamic platform. If anyone can test it, it could be great since it involves a lot of changes !

**Comment by Krocko** [comment]
> Hi everyone.
> 
> I have a branch for a dynamic platform. If anyone can test it, it could be great since it involves a lot of changes !
> 
> https://github.com/nicoduj/homebridge-harmony/tree/Dynamic-Platform

How we can test this branch?
There are changes in the config.json?

**Comment by nicoduj** [comment]
thanks to @Krocko and first feedbacks (on slack :) ), I have published a beta for those who wants to try :

```bash
npm install -g homebridge-harmony@beta
```
It should not be visible in homebridge-config-ui-x update pannel, so you have to install it through terminal if you want.

**Comment by gitgayhub** [comment]
updated to 1.0 beta 3 and iOS 12.2 beta 6

everything works fine so far

thanks nico

**Comment by nicoduj** [comment]
Bêta updated , config changed ne careful, should support multiple hubs or same hub declared multiple times 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
