### ISSUE TITLE
Not see the commands in the log

### ISSUE THREAD

**Issue by suxus-zz** [nicoduj/homebridge-harmony#74]
Hello

I have also completely rewritten my Raspberry and now Homebridge 0.4.46 is active and from the Harmony plugin 0.4.6 and the config looks like this.

        {
            "platform": "HarmonyHubWebSocket",
            "name": "HarmonyHub",
            "hubIP": "192.168.98.20",
            "showTurnOffActivity": true,
            "refreshTimer": 30,
            "publishActivitiesAsIndividualAccessories": false,
            "publishDevicesAsIndividualAccessories": true,
            "addAllActivitiesToSkipedIfSameStateActivitiesList": false,
            "devicesToPublishAsAccessoriesSwitch": [],
            "skipedIfSameStateActivities": [
                "PowerOff",
                "TV schauen",
                "Apple TV"
            ]
        },

Would not I have to see the possible Harmony commands in the log to use them with the tag "devicesToPublishAsAccessoriesSwitch"?

Many Thanks
Greeting

**Comment by nicoduj** [comment]
Hi, you have to add at least one device to the list from what I remember 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by suxus-zz** [comment]
Hello, you mean in the devicesToPublishAsAccessoriesSwitch Tag i must add one of my devices like this. And the i will see all commands from this device in the log?

"devicesToPublishAsAccessoriesSwitch": [
 "Apple TV 4K;Menu"
 ],

And the device name is the exact name from the Harmony Hub?

Greeting

**Comment by nicoduj** [comment]
Yes, From what I remember :)it will print for all your devices , and you can only add the name of the device without any command like « Apple TV 4K ».  not at home so I can check later if you want .

**Comment by suxus-zz** [comment]
Great thank you very much, if you can check this later

**Comment by nicoduj** [comment]
OK, so just add something like : 
            "devicesToPublishAsAccessoriesSwitch" : ["LIST"]

Tou will see all the commands per device at startup.
