### ISSUE TITLE
Problem in remote widget with devices that need seperate IR commands  for Play/Pause 

### ISSUE THREAD

**Issue by Midifreakz** [nicoduj/homebridge-harmony#75]
Hi @nicoduj , 

I have tested some of the features on ios 12.2 Public Beta 3. And in addition to the volume control bug and the 'back' button bug, I have discovered that the Play button does not work across all activities. 

- My Apple TV activity utilizes the play button (in ios remote widget) as expected. 
- My Set-Top-TV-Decoder  activity does not play/pause at al (in ios remote widget), however the LED on the Harmony hub flashes so it sends a command, just not the correct one I presume.

In The harmony app, both activities have the play button mapped to the correct remote buttons.
Also when I press the play button (on physical remote) it just works as expected.

_ _ _ _ _ _

If you can give me some kind of list or explanation on how the mapping of buttons work (which physical remote button are mapped to which buttons on the ioswidget. I can make a graphic representation of a physical remote and the ios widget side by side. (I am a graphic designer), pointing out how to map your remote for optimal compatibility. 

- For instance, I can't figure it out how to send the "mute" command héhé.

Perhaps this graphic  wil be convenient to post in the "tutorial section". Let me know if you are interested ;).

**Comment by nicoduj** [comment]
Hi, you can check in debug mode ( -D) which command it sends for which action. If you want you can also post to me your hub config that will be displayed at homebridge startup in debug mode . 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Midifreakz** [comment]
I tried to figure out what command is being sent but I think the code is to complicated for a mere enthousiast as myself. Can you give it a quick look? the DIGIBOX activity is the one where the play button in the widget does not respond.

https://pastebin.com/mQ5Kw6wZ

**Comment by nicoduj** [comment]
Will take a look this evening !

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nicoduj** [comment]
I took a look, the log says you are mapping play command of digibox activity to the play button in remote control app, seems good at first.

I see that your homebridge gets an error at startup are you sure your node version is ok ? 

Moreover could you check the command that is sent in the log when you trigger the play button ? (In debug mode)

**Comment by Midifreakz** [comment]
My node version is v8.15.0

According to a quick online search the error(s) displayed at the bottom should be because I have another instance of homebridge running on startup, in the background using 'screen'.

However, I seem to be unable to get a realtime trigger-log from the application so I can't tell you what action takes place when pressing the play button for this activity. 

If you have any idea's let me know! Enjoy your weekend!

**Comment by nicoduj** [comment]
Hi, checked again and can’t see what is going on. Could you launch your main homebridge instance in debug mode ? I think this way you can have the log of the command sent while using the play button in ios remote app. The one you launched gave the config but since it crashes you can’t get event while using the device / remote

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Midifreakz** [comment]
Hi, I did some more research on getting into a proper debug mode, showing me the eventlog. 

I managed to do that and here is a new log file where you can see me activating the Apple TV activity first, Then press the play button a couple of times in the widget, then switch to the Digibox activity, then press play a couple of times there. 

I noticed that on my physical remote, play & pause requires the use of both buttons accordingly. so pause button for pause, play button to resume playing. 

I don't know if this problem could be overcome due to limitations of the remote widget interface?

Log: https://pastebin.com/4wJz790D

**Comment by gitgayhub** [comment]
Does the Harmony app on your iPhone work properly? If you can’t use the play/pause button within the activity tab either, it’s probably you didn’t set the correct device to control after starting an activity, it can only set in the myharmony Windows software, there’s the setting “which device to change channels” in the activity settings

**Comment by nicoduj** [comment]
Hi, from the log the command are the one defined in your activity and sent correctly with an OK from the hub. As @gitgayhub said, please checked they are correctly mapped in harmony app.

Currently I only send the play button, no matter there is or not a pause button. From my experience, lots of devices handle play while playing as pause. I could send alternatively, but if I can't be sure to be in sync if you sometimes use the physical remote or harmony app, that is why I didn't.

**Comment by Midifreakz** [comment]
Hi guys, I did some more checking and in fact, this specific device needs 2 different IR commands. one for play and one for pause... When I pause with the remote, I can resume play with the widget. As you said, this is unusual for most devices.

I understand why it would be hard to implement this to just one button in the widget. not worth the effort. 

I noticed my TVSP  just released a new set-top-box where play/pause is one button on their standard remote. So for me, i'll just fix it by getting the newest set-top-box.

Changed the name of this issue so that people with the same issue can find it more easily.

This issue can be closed.

**Comment by nicoduj** [comment]
@Midifreakz : Could you just check what happens if you send pause while in pause ? I can definitely add an option, the only drawback would be that if it was not set in pause or play by the remote app, you could have to send the command twice. What do you think ?

**Comment by Midifreakz** [comment]
I just checked,  

for both play and pause nothing happens when pressing the respective button on the remote twice. So what you are suggesting (2presses in widget) could be a good fallback for people with devices that act like this. always better something works on the second press then not working at al offcourse.

**Comment by nicoduj** [comment]
Will see 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nicoduj** [comment]
will be done in #76
