### ISSUE TITLE
Add option to TVMode for play / pause command

### ISSUE THREAD

**Issue by nicoduj** [nicoduj/homebridge-harmony#76]
Add an option to handle play / pause command on TV mode if activities have both  commands

**Comment by Midifreakz** [comment]
Hi @nicoduj 

I've just tried installing the update you made this weekend. 
I've also made sure to set the option playpause to true in the config file.

The play/pause command on the widget is still not doing anything on my 'Digicorder'.
- I see a command being received by the harmonyhub on every press  (green LED blinks) 
- Also, the 'i' button on the widget used to bring up a settings-pane on the digibox. After this update    the hub does not receive a command anymore for this 'i' button.'

**Comment by nicoduj** [comment]
Hi, thank you for feedback ! Is it possible to get the log in debug mode and your config file ? Concerning the « I » button I don’t remember changing something , did you change some configuration in harmony app ? Your log could also help !

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Midifreakz** [comment]
Hi, Here's the debug file (only last couple of lines) I pressed the play/pause button a few times in the widget but it seems that still only the 'play' command gets send. Perhaps something I overlooked in the config file? 

The ' I ' button started working again for the 'Digibox' since Beta 4 (Just installed it).. really weird. 
It used to work on Beta 3 too at first. 

_Extra info unrelated to this issue:_
For me, the 'back' button in the widget also started working in Beta 4, never worked for me in beta 3.

I haven't changed any of the buttons in the harmony app and won't do so in the future. The default mapping seems to do most of the trick anyway.


Debug Log:  https://pastebin.com/WBURqX9m
ConfigFile: https://pastebin.com/u8LSYuvK

**Comment by nicoduj** [comment]
Hi, it indeed sends play always !  Can you check at the beginning of the log if a pause command is discovered for this activity ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nicoduj** [comment]
I have deleted your message please delete your config file with your secret where you put it ... 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Midifreakz** [comment]
Whoa! totally overlooked that. thanks for covering my back.

Here's a complete log, new session.
https://pastebin.com/RSHa5b77

If i'm not mistaking, the pause command is mapped as should. just not executed.

**Comment by nicoduj** [comment]
I need your log in debug again (not your config :) ) .

You should see a line saying the status after each press like  : INFO - current play status is ...

Check again maybe the parameter in the config : playPauseBehavior

**Comment by Midifreakz** [comment]
I think we just crossfired a message? is the link I sent in the previous post okay?

**Comment by nicoduj** [comment]
indeed. Yes it is, but I don't see the log in question which make me feel like the version is not ok ... I will check .

**Comment by nicoduj** [comment]
Ok ,are you sure you are in 0.4.7 ? I realized I published it only through NPM. Can you check the file harmonyAsTVPlatform.js -> should have 

              case newValue === Characteristic.RemoteKey.PLAY_PAUSE:
                this.log.debug(
                  'INFO - current play status is : ' +
                    this.playStatus[this._currentInputService.id]
                );

in it.

**Comment by Midifreakz** [comment]
Hi @nicoduj 

Yes definitely on 0.4.7  I always install through NPM
`pi@raspberrypi:~ $ sudo npm view homebridge-harmony version
0.4.7`

The harmonyAsTVPlatform.js file has the code you specified in it.
I have noticed that there are a few entries 'undefined' but i'm to much a n00b to know what it means.

`case newValue === Characteristic.RemoteKey.PLAY_PAUSE:
                this.log.debug(
                  'INFO - current play status is : ' +
                    this.playStatus[this._currentInputService.id]
                );

                if (
                  !this.playPauseBehavior ||
                  this._currentInputService.PauseCommand === undefined ||
                  this.playStatus[this._currentInputService.id] === 'PAUSED' ||
                  this.playStatus[this._currentInputService.id] === undefined
                ) {
                  this.log.debug('INFO - sending PlayCommand for PLAY_PAUSE');
                  this.harmonyBase.sendCommand(
                    this,
                    this._currentInputService.PlayCommand
                  );
                  this.playStatus[this._currentInputService.id] = '';
                } else {
                  this.log.debug('INFO - sending PauseCommand for PLAY_PAUSE');
                  this.harmonyBase.sendCommand(
                    this,
                    this._currentInputService.PauseCommand
                  );
                  this.playStatus[this._currentInputService.id] = 'PAUSED';
                }`

**Comment by nicoduj** [comment]
OK, I really don't see what is happening there and why you don't get the log. Must be big but I don't see the whale ! Will try to put more logs on next version, sorry for that.

you could try to simplify your conf if you have time (removing sequences especially, just a basic one with this option only)

**Comment by nicoduj** [comment]
@Midifreakz I finally found the problem, sorry for this, it was a really bad mistake by my side :( Will publish a new version soon, but since I have made a lot of refactoring I will do more tests before.
