### ISSUE TITLE
Updating homebridge-harmony breaks the remote widget functionality

### ISSUE THREAD

**Issue by Midifreakz** [nicoduj/homebridge-harmony#79]
After updating this plugin, the remote-widget functionality seems to get broken, no 'TV' device in the list of available remotes (everything in homekit-app works fine).

It shows up again if you remove the homebridge-hub accessory and re-add it to homekit. bit of a hassle. Perhaps something worth fixing in the future for reliability.

**Comment by nicoduj** [comment]
Hi, I didn’t have this problem as far as I checked . Did you change the name of the hub / or activities ? Did your device in home app reset to default room ?

if they are exposed and working well in home app without any visible change I think it is more a problem of iOS beta than in the plugin (nothing special is done to expose in remote widget ) . Did you try rebooting your iOS device before removing the hub ? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Midifreakz** [comment]
Hi, I always do a full 'reboot cycle' whenever I start testing stuf. (So I reboot Pi,ATV,iDevices & router).

Upgraded from beta3 to beta4 now so I'll notify you here if this problem persists when I update to a newer version of your plugin. perhaps this is/was also an AppleDev problem rather than one of the plugin.

**Comment by nicoduj** [comment]
@Midifreakz Hi, could you check with latest version ? Thanks !

**Comment by Midifreakz** [comment]
Hi @nicoduj 

Installed it straight away! ;) This time the update went very smoothly. 

- - - -

Off Topic but just letting you know: Yesterday and the day before my girlfriend was watching tv and used the Harmony Remote to start the activity. While watching a movie, the TV (only the actual television, not the activity) just powered off out of itself. When I wanted to check the state of the harmony activity in homekit I noticed the remote widget did not show the TV device from homekit. This only happened this one time. Have you ever experienced such an issue in the past? even without using homekit? It's naggin' me hehe...

I guess this has probably something to do with Harmony and not with your plugin.

**Comment by nicoduj** [comment]
I am closing, let me know if it appears again.
