### ISSUE TITLE
Add option to TVMode for channel +  / channel -  command

### ISSUE THREAD

**Issue by overflywingo** [nicoduj/homebridge-harmony#80]

**Comment by nicoduj** [comment]
Hi, how do you expect them to be added? there is no way from what I see in TV remote widget. Or do you expect them to be bound to up / down arrow ?

**Comment by overflywingo** [comment]
It's possible to change channels with Apple Remote App (IOS 12.2b4) so this request is irrelevant.

**Comment by nicoduj** [comment]
Hi, thanks for feedback . How do you change channel in b4 ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by overflywingo** [comment]
Hi
By just selecting the up down arrows





Le 5 mars 2019 à 11:55:38, Nicolas Dujardin (notifications@github.com) a
écrit:

**Comment by nicoduj** [comment]
Ok, so it is probably because your activity and up/ down commands are mapped to this (there is no command explicitly for channel up / down in HomeKit)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
