### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by tooh** [nicoduj/homebridge-harmony#90]
sudo npm install -g homebridge-harmony

> websocket@1.0.28 install /usr/lib/node_modules/homebridge-harmony/node_modules/harmony-websocket/node_modules/websocket
> (node-gyp rebuild 2> builderror.log) || (exit 0)

sh: 1: cannot create builderror.log: Permission denied

> websocket@1.0.28 install /usr/lib/node_modules/homebridge-harmony/node_modules/websocket
> (node-gyp rebuild 2> builderror.log) || (exit 0)

sh: 1: cannot create builderror.log: Permission denied
+ homebridge-harmony@0.4.8
added 80 packages from 88 contributors in 11.496s

**Comment by nicoduj** [comment]
Hi, seems to be a permisison issues on your conf. Try maybe to not sudo .

**Comment by nicoduj** [comment]
I googled a bit on your issue . Might find a solution there : https://github.com/nodejs/node-gyp/issues/115 but I would try before installing without sudo

**Comment by tooh** [comment]
This worked

sudo npm install homebridge-harmony -g --unsafe-perm
