### ISSUE TITLE
TVMode : no visible inputs in home app at first launch

### ISSUE THREAD

**Issue by nicoduj** [nicoduj/homebridge-harmony#91]
It seems that the first time the plugin is installed and discovered by home app after launching homebridge, inputs are only visible in the configration pane of the TV Device, but not on the lis on the bottom left of the screen.

Restarting homebridge fixes it. No clue why for the moment, might be a bug in homekit / homebridge / hap or something I am doing wrong ...

**Comment by nicoduj** [comment]
seems to be fixed with dynamic platform

**Comment by int3nz0r** [comment]
Nvm, sorry. After a second restart everything is working fine indeed. Thanks, kutgw!

**Comment by nicoduj** [comment]
Glad to ear ! I tried to fix that but with no luck, and didn’t reproduce in 1.0.0 beta (dynamic mode) so I did not try harder :) 


Nicolas
