### ISSUE TITLE
[Request] CHANGELOG.md for use with config-ui-x

### ISSUE THREAD

**Issue by DJay-X** [nicoduj/homebridge-harmony#92]
Just a small note... Would be great to have a CHANGELOG.md so that the release notes come up in config-ui-x when updating the plugin there. :)
Thanks in advance for your time and consideration.

**Comment by nicoduj** [comment]
Gréât suggestion will do ! 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nicoduj** [comment]
done since 0.4.92, thanks for suggestion !
