### ISSUE TITLE
Sequences are gone since 0.4.8

### ISSUE THREAD

**Issue by DeutscheMark** [nicoduj/homebridge-harmony#93]
As the title says, there are no sequences exposed anymore since I think 0.4.8 or 0.4.9.
Had to revert to 0.4.7 to fix.

**Comment by DJay-X** [comment]
Same here 0.4.91
`"sequencesToPublishAsAccessoriesSwitch": [
                "Lauter",
                "Leiser"
            ],`
Both the switches "Lauter" and "Leiser", did not show up anymore in HomeKit.

Full config..

`{
            "platform": "HarmonyHubWebSocket",
            "name": "HarmonyHub",
            "hubIP": "xxx.xxx.xxx.xx",
            "showTurnOffActivity": true,
            "refreshTimer": 30,
            "publishActivitiesAsIndividualAccessories": false,
            "sequencesToPublishAsAccessoriesSwitch": [
                "Lauter",
                "Leiser"
            ],
            "devicesToPublishAsAccessoriesSwitch": [
                "LG-Fernseher;Green",
                "Apple TV 4K;Menu",
                "Apple TV 4K;Home",
                "Apple TV 4K;DirectionDown|600;DirectionRight|600;DirectionRight|600;DirectionDown|600;DirectionLeft|600;Select|600",
                "Apple TV 4K;DirectionDown|600;DirectionRight|600;DirectionRight|600;DirectionDown|600;DirectionLeft|600;DirectionDown|600;Select|600"
            ],
            "skipedIfSameStateActivities": [
                "PowerOff",
                "Apple TV",
                "Live Fernsehen",
                "Smart TV"
            ]
        },`

**Comment by nicoduj** [comment]
Hi, thanks for reporting I will check ASAP sorry for that 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nicoduj** [comment]
0.4.92 should restore it, sorry. Didn't test much however, so I hope everything is ok.
