### ISSUE TITLE
Remote widget lost after x period of time

### ISSUE THREAD

**Issue by Midifreakz** [nicoduj/homebridge-harmony#94]
Hi @nicoduj

After the latest update the 'tv' dissappears from the remote widget...  tried rebooting every device in the chain but only re-adding the homebridge device to the homekit app fixes this.

but it hapens again after a while... which logs do you need?

**Comment by nicoduj** [comment]
Hi, It is lost in the remote app, that's it ? no crash in homebridge ?

**Comment by Midifreakz** [comment]
Indeed, no crash in homebridge, only lost in remote app. I will instal the latest version first and let you know if the problem is stil present.

**Comment by nicoduj** [comment]
ok, I will publish probably a 0.5.0 this evening with new option to Ovverride remote buttons with devices command.

**Comment by Midifreakz** [comment]
Remote in widget came back since I updated to .92. I'll monitor it for a few days

**Comment by nicoduj** [comment]
ok, feel free to reopen. Might have change some things, I also noticed that there might have some issues with Icloud Sync sometimes if some of your devices are not on IOS 12 .
