### ISSUE TITLE
publishSequencesAsIndividualAccessories Not displaying switches in homekit

### ISSUE THREAD

**Issue by Midifreakz** [nicoduj/homebridge-harmony#95]
Latest update broke all custome switches in homekit. 

Sorry for the fast explenation. Got little time now but i'll try to send more detailed information soon!

**Comment by nicoduj** [comment]
Hi, in 0.4.92 ?

**Comment by Midifreakz** [comment]
Hi, sorry did not notice there were new updates.

**Comment by nicoduj** [comment]
no problem, this one should be fixed.
