### ISSUE TITLE
Ability to Publish Activity Switchs AND TVMode

### ISSUE THREAD

**Issue by SafariKC** [nicoduj/homebridge-harmony#97]
I tried to configure for TV Mode and for Activity Switches to show up.  It looks like once you turn on TV Mode  you pretty much don't have the ability to also expose other awesome things that this module can do.   

Am i missing a config or is this the case that it's either one or the other but not both at the same time?

**Comment by nicoduj** [comment]
Hi,

You can combine tv mode and options for sequences / devices in a single platform.

If you want to have both tv mode and activity mode, you can always define 2 platforms section in your config with the same hub as a target (that is what I do :) )

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
